### ISSUE TITLE
sidebar 

### ISSUE THREAD

**Issue by AndrewKa** [vueComponent/ant-design-vue-pro#10]
http://nimb.ws/pdLeK5

**Comment by ZacRenis** [comment]
`I think he ate it. `

**Comment by sendya** [comment]
![20181123195949](https://user-images.githubusercontent.com/5404542/48942428-5b244980-ef5a-11e8-99a6-40cc46183e62.png)

![20181123200357](https://user-images.githubusercontent.com/5404542/48942578-fe755e80-ef5a-11e8-8dd5-e899d10f6ebf.png)


try cleanup `localStorage`

**Comment by AndrewKa** [comment]
pleas test on a different screen resolution. 1060 and less. 
https://imgur.com/a/kyZNN6O

**Comment by sendya** [comment]
针对手机模式 暂不进行支持，等待之后版本。（以后的 issue 请注明环境） 也欢迎 PR

**Comment by sendya** [comment]
closed in #10 https://github.com/sendya/ant-design-pro-vue/commit/2ddf9e9d839c63cdee54d8015ce88fa6533212c5
