### ISSUE TITLE
发布到非根目录怎么配置?

### ISSUE THREAD

**Issue by BrettKang** [vueComponent/ant-design-vue-pro#1001]
**Question （问题描述）**
你好，生产版本发布到网站子目录，怎么配置才能正常访问？
现在如果直接放到子目录，路径是有问题的。
谢谢啦

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://cli.vuejs.org/config/#publicpath

**Comment by jorshen** [comment]
部署到二级目录，router得改为hash模式
