### ISSUE TITLE
组件导出问题

### ISSUE THREAD

**Issue by 240011814** [vueComponent/ant-design-vue-pro#1002]
组件没有写在index.js里面 export ， 直接引用组件报 not found in 文件名

**Comment by sendya** [comment]
请描述清楚

**Comment by 240011814** [comment]
<template>
  <div>test</div>
</template>

<script>
export default {
  name: 'Test',
   data () {
      return { show: true }
    },
    created () {},
    mounted () {},
    methods: {}
}
</script>

<style>

</style>


引用的地方
import { Test } from '@/components/Test/index'
export default {
  name: 'Exception404',
  components: { Error, Test },
  methods: {
    toHome () {
      this.$router.push({ path: '/' })
    }
  }
}

报 "export 'Test' was not found in '@/components/Test/index'

我在其他框架里面这样写没有问题，在这个框架里面需要在index.js在导出一次

**Comment by sendya** [comment]
这是你的问题，跟框架没关系。
你 export 的 default 却不引入 default 的 export 而跑去引入一个不存在的 Test
建议看一下 import export 的语法教程

**Comment by 240011814** [comment]
这里导入的是vue组件，index.js里面都是这样导入的

**Comment by 240011814** [comment]
搞明白了，原来是import default 不加{}
