### ISSUE TITLE
src/config/defaultSetting.js中的primaryColor，生产模式部署到子目录不生效

### ISSUE THREAD

**Issue by BrettKang** [vueComponent/ant-design-vue-pro#1004]
**Question （问题描述）**
一直显示的是系统默认配色（导航栏选中情况白色，主色调蓝色）
在本地开发模式预览没有问题，但在生产环境 （部署在子目录hash模式）不生效

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
生产模式默认不提供主题功能，请直接改 vue.config.js  css 配置。
如有需要生产环境主题功能，请自行查看源码 改动插件配置项  https://github.com/vueComponent/ant-design-vue-pro/blob/master/config/plugin.config.js#L15

**Comment by BrettKang** [comment]
> 生产模式默认不提供主题功能，请直接改 vue.config.js css 配置。
> 如有需要生产环境主题功能，请自行查看源码 改动插件配置项 https://github.com/vueComponent/ant-design-vue-pro/blob/master/config/plugin.config.js#L15

这样，谢谢啦
