### ISSUE TITLE
SettingDrawer生产环境选择主题色不生效

### ISSUE THREAD

**Issue by yxh410** [vueComponent/ant-design-vue-pro#1007]
**Question （问题描述）**
本地环境都正常，生产环境使用SettingDrawer更改主题色不生效，其他设置都正常，唯独主题色无法更改
![image](https://user-images.githubusercontent.com/36829582/96961077-80e76e00-1536-11eb-8ba0-f42afc8a7c34.png)
![image](https://user-images.githubusercontent.com/36829582/96961159-ac6a5880-1536-11eb-9c08-ce94a6c64525.png)

**Comment by sendya** [comment]
生产不提供主题功能
如果实在需要，可以改这里
https://github.com/vueComponent/ant-design-vue-pro/blob/master/vue.config.js#L123-L128

**Comment by gzlboy** [comment]
> 生产不提供主题功能
> 如果实在需要，可以改这里
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/vue.config.js#L123-L128

请教怎么在本地切换好主题之后再上传？线上可以不支持切换
