### ISSUE TITLE
路由切换过渡动画设置无效

### ISSUE THREAD

**Issue by baiwumm** [vueComponent/ant-design-vue-pro#1008]
APP.vue和BasicLayout.vue、所有的<router-view></router-view>都设置了transition，但没切换动画，请问下应该在哪里设置才正确
![image](https://user-images.githubusercontent.com/40554571/97386773-8d414180-190f-11eb-9173-0574564499cd.png)

**Comment by sendya** [comment]
设置在有变化的 router-view 上，具体打开 vue-devtools 看哪层路由在变化
