### ISSUE TITLE
请问下这个主题切换使用的文件怎么设置相对路径

### ISSUE THREAD

**Issue by zxuanhong** [vueComponent/ant-design-vue-pro#1014]
**Describe the bug （描述 Bug）**
1. 为啥主题切换这个文件不能是相对路径，即自动加上部署访问目录，其他都可以。
2. 如果只能这样弄，这也太老火了吧，我部署想换个文件夹都不行，还得重新打包。

**To Reproduce （重现步骤）**

1. 修改vue.config.js文件中vueConfig中变量publicPath为'./'
2. 打包部署在nginx的skillWeb
3. 切换主题
4. 发现只有一个文件为绝对路径，即：theme-colors-dbf14da2.css，其他都会在访问路径上自动加上skillWeb(即相对路径生效)

**Screenshots（截图）**
1. 异常文件显示访问路径(域名下就是css开头没有拼接上访问路径)
![image](https://user-images.githubusercontent.com/62740686/97645329-98b77880-1a87-11eb-82fb-f3e05d901265.png)
2. 正常文件访问路径(自动拼接上skillWeb访问路径)
![image](https://user-images.githubusercontent.com/62740686/97645345-ae2ca280-1a87-11eb-9406-5963e62be47e.png)

**Desktop (please complete the following information):**

 - OS: mac 
 - Browser : chrome
 - Version: pro版本3.0.0

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/config/plugin.config.js#L15

主题功能由于性能问题，不提供生产环境支持。如有需要可自行设计和替换主题更换插件

**Comment by zxuanhong** [comment]
@sendya 已经找到原因，是pro-layout这个地方给干死了
![image](https://user-images.githubusercontent.com/62740686/97652010-6a8e6480-1a98-11eb-9bdd-79013e531936.png)
