### ISSUE TITLE
为什么预览的页面中不能设置暗黑模式？

### ISSUE THREAD

**Issue by jiabochao** [vueComponent/ant-design-vue-pro#1016]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
antdv 尚未提供黑暗模式的支持，无法切换
