### ISSUE TITLE
pro-layout的属性collapsed设置为true初始化无法收回菜单

### ISSUE THREAD

**Issue by NiShuiXingZ** [vueComponent/ant-design-vue-pro#1017]
**pro-layout的属性collapsed设置为true初始化无法收回菜单**

将BasicLayout.vue文件pro-layout的属性collapsed设置为true，菜单页无法收回。
排查了一下原因：
将collapsed设置为true，则初始化时会调用handleCollapse方法，handleCollapse方法的val参数为false，将collapsed又设置回false了。
将collapsed设置为false，则初始化时不会调用handleCollapse方法。

![QQ截图20201103183818](https://user-images.githubusercontent.com/4465323/97975233-c1cb6680-1e03-11eb-8a46-b22647e1b8ca.png)

**Comment by sendya** [comment]
去掉这个

https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/BasicLayout.vue#L139

想要默认收起，就不能开自适应分辨率，否则就跟自适应分辨率冲突了。

**Comment by NiShuiXingZ** [comment]
> 去掉这个
> 
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/BasicLayout.vue#L139
> 
> 想要默认收起，就不能开自适应分辨率，否则就跟自适应分辨率冲突了。

我去除之后也是无法默认收回菜单。当data()中的collapsed：true时，初始化还是会调用handleCollapse这个方法，将this.collapsed=val设置成false，导致菜单无法收回。

**Comment by chenxianfei** [comment]
遇到了同样的问题

**Comment by chenxianfei** [comment]
遇到了同样的问题。我的做法是 页面加载后调用定时器 1秒后再将collapsed 设为false，但是有时候定时器会在handleCollapse 之前执行。定时器时间设置大了。又先显示再隐藏。 所以这个方法不太理想

**Comment by sendya** [comment]
升级到
@ant-design-vue/pro-layout 1.0.4

**Comment by NiShuiXingZ** [comment]
> 升级到
> @ant-design-vue/pro-layout 1.0.4

好的1.0.5，已经解决了这个问题，谢谢
