### ISSUE TITLE
Menu文本被选中后，点击SubMenu选项，文本的选中状态没有改变

### ISSUE THREAD

**Issue by oduoge** [vueComponent/ant-design-vue-pro#1018]
**Describe the bug （描述 Bug）**

Menu文本被选中后，点击SubMenu选项，文本的选中状态没有改变

**To Reproduce （重现步骤）**

1. 打开子菜单选项
2. 鼠标悬停于两个菜单选项之间。
3. 待鼠标由“小手”变成“箭头”之后，长按鼠标左键不放，框选菜单选项，
4. 此时选中的菜单文本处于选中状态，点击鼠标起始位置的子菜单选项，文本选中状态不会消失。

**Expected behavior（你期待的是什么?）**
选中的菜单文本处于选中状态，鼠标点击起始位置的子菜单选项，文本选中状态应该消失。

**Screenshots（截图）**
[![B67VRP.gif](https://s1.ax1x.com/2020/11/04/B67VRP.gif)

**Desktop (please complete the following information):**

windows 7
Chrome
版本 86.0.4240.183（正式版本） （64 位）

**Comment by sendya** [comment]
user-select 无法避免的，如有必要，你可以自己把 user-select 置 none
