### ISSUE TITLE
想实现点击左侧菜单右侧变成iframe的效果，请问有办法实现吗

### ISSUE THREAD

**Issue by lj1002094787** [vueComponent/ant-design-vue-pro#1020]
**Question （问题描述）**
想实现点击左侧菜单右侧变成iframe的效果

**Describe the solution you'd like （你期待的是什么？）**
想知道怎么修改能实现该需求

**Additional context（附加信息）**
无

**Comment by sendya** [comment]
iframe 效果是什么样？

**Comment by lj1002094787** [comment]
> iframe 效果是什么样？

![QQ截图20201105115443](https://user-images.githubusercontent.com/29915753/98195992-03702480-1f5e-11eb-96bd-9bc09ef67473.png)
点首页的时候红框区域配置成iframe，点其他菜单还是正常的路由跳转

**Comment by sendya** [comment]
你可以在 router-view 上做文章。

**Comment by lj1002094787** [comment]
哦哦  明白了   感觉问了个愚蠢的问题   脑子短路
