### ISSUE TITLE
QT框架 C++语言开发windows客户端 打开打包后的url崩溃

### ISSUE THREAD

**Issue by cuteCloud** [vueComponent/ant-design-vue-pro#1022]
直接创建窗口打开https://preview.pro.antdv.com/dashboard/workplace这个页面就崩溃了 用vue-cli3直接创建出来的项目不会崩溃

**Comment by sendya** [comment]
如果浏览器打开正常，则无法为你解答。请使用 webkit 内核 或任意现代浏览器
