### ISSUE TITLE
路由跳转   菜单选中样式不生效的问题

### ISSUE THREAD

**Issue by yunboom** [vueComponent/ant-design-vue-pro#1023]
![}ZW%Z91 TK9%50K$P QT19U](https://user-images.githubusercontent.com/56998421/98322108-9faf2f80-2021-11eb-953b-3fef04c3e2c3.png)

**Comment by sendya** [comment]
无法复现

**Comment by sendya** [comment]
请提供详细信息

**Comment by yunboom** [comment]
> 请提供详细信息
问题找到了
当子路由路径简写时 会发生这种情况
![image](https://user-images.githubusercontent.com/56998421/98323564-071aae80-2025-11eb-8e33-76f8d67a095c.png)

**Comment by Ma-Yun-Peng** [comment]
> 请提供详细信息

![8G98{HJ0(HHN}(HSM N_A1T](https://user-images.githubusercontent.com/56998421/98323580-126dda00-2025-11eb-8e68-4fe393f4635b.png)

**Comment by Ma-Yun-Peng** [comment]
![8G98{HJ0(HHN}(HSM N_A1T](https://user-images.githubusercontent.com/56998421/98323633-32050280-2025-11eb-8c88-6aabd690ecf1.png)

**Comment by sendya** [comment]
请按规定写绝对路径路由
