### ISSUE TITLE
关于设置头部菜单之后 , 页面弹出遮罩 会出现菜单抖动的问题

### ISSUE THREAD

**Issue by see5lt** [vueComponent/ant-design-vue-pro#1026]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
无法处理，各种方案都有问题。
如果你需要不抖动，给页面加 overflow 常驻显示 scroll 即可。但会带来其他问题，比如 内容不够也显示了滚动条，页面很丑
