### ISSUE TITLE
3.0开启multiTab后，切换部分tab标签会刷新页面

### ISSUE THREAD

**Issue by brucethomaswayne6** [vueComponent/ant-design-vue-pro#1027]
按照@xyfy 格式引入后[开启multiTab](https://github.com/vueComponent/ant-design-vue-pro/issues/912#issuecomment-671711002)，根据@raythunder [修改RouteView](https://github.com/vueComponent/ant-design-vue-pro/issues/912#issuecomment-696600204) ，切换部分标签还是会刷新页面

**Comment by ZengJun-cloud** [comment]
` {
    path: '/',
    name: 'index',
    component: BasicLayout,
    meta: { title: '首页' },
    redirect: '/dashboard/workplace',
    children: [
      // dashboard
      {
        path: '/dashboard',
        name: 'dashboard',
        redirect: '/dashboard/workplace',
        component: () => import('@/views/dashboard/Analysis'),
        meta: { title: '仪表盘', keepAlive: true, icon: bxAnaalyse }
      },
      // forms
      {
        path: '/form',
        redirect: '/form/base-form',
        component: RouteView,
        meta: { title: '表单页', icon: 'form', permission: [ 'form' ] },
        children: [
          {
            path: '/form/base-form',
            name: 'BaseForm',
            component: () => import('@/views/form/basicForm'),
            meta: { title: '基础表单', keepAlive: true, permission: [ 'form' ] }
          },
          {
            path: '/form/step-form',
            name: 'StepForm',
            component: () => import('@/views/form/stepForm/StepForm'),
            meta: { title: '分步表单', keepAlive: true, permission: [ 'form' ] }
          },
          {
            path: '/form/advanced-form',
            name: 'AdvanceForm',
            component: () => import('@/views/form/advancedForm/AdvancedForm'),
            meta: { title: '高级表单', keepAlive: true, permission: [ 'form' ] }
          }
        ]
      }
   ]
}
`

**Comment by brucethomaswayne6** [comment]
第一个路由菜单只有1级，后面的有2级菜单，后面的2级菜单切到第一个路由1级菜单，此时切回2级菜单，页面无缓存
![image](https://user-images.githubusercontent.com/52198079/98652191-39564400-2376-11eb-8f5a-33577b2a6031.png)

**Comment by sendya** [comment]
本项目默认不提供 multi-tab 的维护，并且难以维护。 请自行想办法

**Comment by leegedan** [comment]
多页签真是个糟糕的设计
