### ISSUE TITLE
@ant-design/colors 5.0版本不兼容

### ISSUE THREAD

**Issue by onenine-top** [vueComponent/ant-design-vue-pro#1032]
**Describe the bug （描述 Bug）**
@ant-design/colors 5.0版本不兼容

**To Reproduce （重现步骤）**
1、安装
npm install -g npm-check-updates

2、检查
npm-check-updates

3、升级package.json
ncu -u

4、升级模块
npm install

**Expected behavior（你期待的是什么?）**
无缝兼容

**Comment by sendya** [comment]
不支持

@ant-design/colors 不是为 1.x antdv 设计的，请按照本项目锁定的依赖版本使用，使用其他版本请自行处理问题，本项目只负责测试本项目当前依赖项版本
