### ISSUE TITLE
访问后台接口返回404

### ISSUE THREAD

**Issue by Lockhart-beep** [vueComponent/ant-design-vue-pro#1033]
**Question （问题描述）**
已设置devServer
 proxy: {
      '/api': {
        target: 'https://10.6.64.161:8980/js',
        ws: false,
        pathRewrite: { '^/api': '' },
        changeOrigin: true
      }
    }
请求函数为
export function fetch (values) {
  return request({
    url: '/a/iaplat/dami/list',
    method: 'post',
    data: values
  })
}
api应该是写在了baseURL里面
const request = axios.create({
  // API 请求的默认前缀
  baseURL: process.env.VUE_APP_API_BASE_URL,
  timeout: 6000 // 请求超时时间
})
结果如下，地址应该没有错误，但是显示错误404
![image](https://user-images.githubusercontent.com/74491189/99490477-e2b7be00-29a4-11eb-9e6f-d44a8e3208e3.png)
直接网页打开“https://10.6.64.161:8980/js/a/iaplat/dami/list”
显示错误400，请求参数错误，但是地址应该是正确的
是不是有什么地方设置错了

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
devServer 请自行确认能否访问到，代理是否正确等问题。
