### ISSUE TITLE
左侧菜单更换icon的问题

### ISSUE THREAD

**Issue by yuyu19880526** [vueComponent/ant-design-vue-pro#1034]
左侧菜单，使用自定义svg格式的icon，该怎么配置呢？有没有例子，官网说明就一句话，然后配置了半天不出来

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/config/router.config.js#L25

https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/core/icons.js

**Comment by chf-gh** [comment]
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/config/router.config.js#L25
> 
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/core/icons.js

渲染不出来啊？这个是我页面的html，
![image](https://user-images.githubusercontent.com/20312535/138835495-5946b881-37fe-4cfb-848e-99fea7bccb61.png)
我的图标是后台配置的，使用的是PageView组件，我看route.config.js中用的都是RouteView，这俩有啥区别？为啥RouteView中定义的svg能显示？
