### ISSUE TITLE
`elVal` String数据类型判断不对

### ISSUE THREAD

**Issue by zss1004504439** [vueComponent/ant-design-vue-pro#1035]
https://github.com/vueComponent/ant-design-vue-pro/blob/982741b17aa7d0ff94b665b095fa359446af3fdd/src/core/directives/action.js#L22
$route.name 可能是 String 和 Number
meta.permission 也可能是 String 和 Number

`字符串 instanceof String` 值为 false
我用 meta.name 用作权限标识 相近的路由$route.name 会出错

```
const action = Vue.directive('action', {
  inserted: function (el, binding, vnode) {
    const actionName = binding.arg
    const roles = store.getters.roles
    // const elVal = vnode.context.$route.meta.permission
        const elVal = vnode.context.$route.name
    const permissionId = elVal instanceof String && [elVal] || elVal
    roles.permissions.forEach(p => {
      if (!permissionId.includes(p.permissionId)) {
        return
      }
      if (p.actionList && !p.actionList.includes(actionName)) {
        el.parentNode && el.parentNode.removeChild(el) || (el.style.display = 'none')
      }
    })
  }
})
```

**Comment by sendya** [comment]
`name` 只能是 string，可以看 VueRouter 官方类型定义 https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L144
`meta.permission` 在我默认的规范上，也是 string [add, edit, query, delete, import, export]，没有什么问题。

如果你自己数据类型不相同，那么请自行修改。
