### ISSUE TITLE
菜单-外部链接-非https不正常（会拼接当前域名）？

### ISSUE THREAD

**Issue by hsj-xiaokang** [vueComponent/ant-design-vue-pro#1037]
版本：
    "@ant-design-vue/pro-layout": "^0.3.4",
    "ant-design-vue": "^1.6.5"

部分代码：
  // 路由菜单，path外部链接http
......
          {
            path: 'http://192.168.1.105:8080/swagger-ui.html',
            name: 'Monitor',
            meta: { title: 'menu.dashboard.monitor', target: '_blank' }
          },
......

路由hash模式

开发某个界面：http://192.168.1.105:8009/#xxx
菜单查看html部分： href="http://192.168.1.105:8080/swagger-ui.html" target="_blank"
实际鼠标浮在上面可以看到href地址是：http://192.168.1.105:8009/http://192.168.1.105:8080/swagger-ui.html
实际跳转地址：http://192.168.1.105:8009/http://192.168.1.105:8080/swagger-ui.html

如果改成https则正常，开发时候谁搞成https?：
......
          {
            path: 'https://192.168.1.105:8080/swagger-ui.html',
            name: 'Monitor',
            meta: { title: 'menu.dashboard.monitor', target: '_blank' }
          },
......

**Comment by sendya** [comment]
请使用 history 模式

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-layout/releases/tag/1.0.6
