### ISSUE TITLE
侧边导航栏宽度

### ISSUE THREAD

**Issue by haossu** [vueComponent/ant-design-vue-pro#1038]
**Question （问题描述）**
想修改 侧边导航栏宽度 ,f12 调试后 修改 class="ant-layout-sider ant-layout-sider-dark ant-pro-sider-menu-sider ant-pro-sider-menu" 对应的 256px 页面生效,但是在 BasicLayout.less 上添加相应css失败
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
请提供代码

**Comment by haossu** [comment]
menu demo 未做修改 ,less 在最下面添加
.ant-layout-sider{
  flex: 0 0 160; max-width: 160px; min-width: 160px; width: 160px;
}
.ant-layout-sider-dark {
  flex: 0 0 160; max-width: 160px; min-width: 160px; width: 160px;
}
.ant-pro-sider-menu-sider {
  flex: 0 0 160; max-width: 160px; min-width: 160px; width: 160px;
}
.ant-pro-sider-menu {
  flex: 0 0 160; max-width: 160px; min-width: 160px; width: 160px;
}

**Comment by sendya** [comment]
弄确定你的样式能覆盖到吗？样式问题自己想办法覆盖到就行了。再不行就自己改源码

**Comment by haossu** [comment]
尝试添加import 强制不被覆盖 ,siber 宽度减少,但是 collapsed无法缩小, f12 看style 宽度还是250px

**Comment by haossu** [comment]
fix ,看了下代码, BasicLayout.vue 中 prolayout 添加    siderWidth="160px" 即可
感谢支持

**Comment by haossu** [comment]
> fix ,看了下代码, BasicLayout.vue 中 prolayout 添加 siderWidth="160px" 即可
> 感谢支持

:siderWidth="160"
这样就不会有问题了
