### ISSUE TITLE
列表页.查询表格自带的状态前的状态颜色在哪里设置的.

### ISSUE THREAD

**Issue by vvair** [vueComponent/ant-design-vue-pro#1039]
麻烦问下,列表页.查询表格的状态颜色是在哪里设置的.
看起来是过滤器设置的.但是全局过滤器和当前页面src/views/list/TableList.vue 的过滤器 ,都没有找到相关代码. 好像是和statusMap.status,值绑定的,麻烦告知一下.下图这个地方.颜色是在什么地方定制的..

![image](https://user-images.githubusercontent.com/23339449/99954551-e9d43700-2dbd-11eb-8c44-29497bd3379a.png)

`  filters: {
    statusFilter (type) {
      return statusMap[type].text
    },
    statusTypeFilter (type) {
      return statusMap[type].status
    }

const statusMap = {
  0: {
    status: 'default',
    text: '关闭'
  },
  1: {
    status: 'processing',
    text: '运行中'
  },
  2: {
    status: 'success',
    text: '已上线'
  },
  3: {
    status: 'error',
    text: '异常'
  }
}`

**Comment by sendya** [comment]
https://antdv.com/components/tag-cn/

**Comment by vvair** [comment]
> https://antdv.com/components/tag-cn/

你可以看到我发的图吗.这个明显不是一个东西吧.

**Comment by sendya** [comment]
progress
