### ISSUE TITLE
如何在ie打开

### ISSUE THREAD

**Issue by 2964536830** [vueComponent/ant-design-vue-pro#104]
最新版的ie都无法打开,怎么处理兼容性

**Comment by mynuolr** [comment]
#95

**Comment by mynuolr** [comment]
vue-ls.js 插件使用了 ES6 语法。IE 不支持 ES6 语法，你可以 使用polyfill 进行兼容
[https://cli.vuejs.org/zh/guide/browser-compatibility.html#polyfill](https://cli.vuejs.org/zh/guide/browser-compatibility.html#polyfill)

**Comment by 2964536830** [comment]
![image](https://user-images.githubusercontent.com/37103998/53545904-edde1100-3b65-11e9-981a-8f2be9e347bf.png)
都引入了还是报错,哎

**Comment by sendya** [comment]
参考我最新的提交。已经兼容到 IE10 ref https://github.com/sendya/ant-design-pro-vue/commit/e392885985f9745033f95cad381310eca467567b

**Comment by 2964536830** [comment]
好的,十分感谢,膜拜大佬
