### ISSUE TITLE
连接无法访问了

### ISSUE THREAD

**Issue by binvb** [vueComponent/ant-design-vue-pro#1040]
**Describe the bug （描述 Bug）**

Preview: https://preview.pro.antdv.com
Home Page: https://pro.antdv.com
Documentation: https://pro.antdv.com/docs/getting-started
ChangeLog: https://pro.antdv.com/docs/changelog
FAQ: https://pro.antdv.com/docs/faq

这些站点都无法访问了哦

**Comment by sendya** [comment]
没有问题，可以打开，请在试试

**Comment by binvb** [comment]
[还是不行欸，我以为是内网的缘故，用手机流量也访问不到，你可以试试外网吗？


========================
无法访问此网站网址为 https://preview.pro.antdv.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONNECTION_ABORTED

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/100067160-e0f06d80-2e70-11eb-9542-db51e19c3824.png)


请确认你自己的网络情况
