### ISSUE TITLE
如何配置多个不同地址的http请求

### ISSUE THREAD

**Issue by whiteviolin** [vueComponent/ant-design-vue-pro#1044]
**Question （问题描述）**
因为有多个后端地址提供不同类型的数据，request.js里应该怎么写呢？
只有一个的情况下是这样配置
`const request = axios.create({
  // API 请求的默认前缀
  baseURL: 'http://xxxx:xx',
  timeout: xx // 请求超时时间
})`

**Comment by sendya** [comment]
正常情况下，接口应该是走统一网关，不过既然这么问了，那应该就是后端没网关这个东西，这时候就 axios.create 多个即可

**Comment by whiteviolin** [comment]
谢谢，我明白了。（这就让后端改成同一网关……
