### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by chenxianfei** [vueComponent/ant-design-vue-pro#1047]
**Describe the bug （描述 Bug）**
在页面连续刷新，内存一直在增长

**To Reproduce （重现步骤）**
打开任何页面进行连续刷新

**Expected behavior（你期待的是什么?）**
内存能够释放

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/41931336/100702142-1d294e00-33dc-11eb-892c-2234f0a13fe1.png)

**Desktop (please complete the following information):**

 - OS: windows
 - Browser ie chrome
 - Version 所有版本

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
预览环境有提供动态主题的计算，会很占用性能。在生产环境则不会有这种问题。 无需处理

**Comment by chenxianfei** [comment]
这个是在生产环境中 测试发现的

**Comment by chenxianfei** [comment]
如果删掉动态主题计算
