### ISSUE TITLE
yarn run build 生成的chunk-vendors.js 很大 首页加载速度很慢

### ISSUE THREAD

**Issue by piaoshangji** [vueComponent/ant-design-vue-pro#1048]
**Question （问题描述）**
打包后的 chunk-vendors.js 大概有2.3MB 左右 首页首次进入非常慢

**Describe the solution you'd like （你期待的是什么？）**
不知有没有办法将把 此文件 进行分割

**Additional context（附加信息）**
![image](https://user-images.githubusercontent.com/59563688/100707808-3931ed00-33e6-11eb-84b6-1421e1a7c684.png)

**Comment by sendya** [comment]
gzip 之后只有 700~800KB，10M 带宽服务器 按理说 1秒之内就加载完了。如有必要拆分，请自行百度谷歌 或部分库采用 CDN 引入。

**Comment by SAIDAKBAR123** [comment]
Same problem, 

I have a bundle within size 2.3 MB, how to can handle this issue? could someone explain or refer to solution of this problem, it took me hours , please
