### ISSUE TITLE
关于Pro 3.0打开报错

### ISSUE THREAD

**Issue by afr751116** [vueComponent/ant-design-vue-pro#1052]
**Question （问题描述）**
WIN系统，下载了Pro 3 版本的文件，直接安装依赖并运行没问题。
![image](https://user-images.githubusercontent.com/57131579/101243369-c81e6c80-373a-11eb-813c-82f25be1efad.png)
但是用 《Visual Studio Code》打开router.config.js后就报错，还没改，只是空格保存一下，主要编缉器中还没报错，是什么问题呢？
![image](https://user-images.githubusercontent.com/57131579/101243385-df5d5a00-373a-11eb-9943-27d146491ed7.png)
![image](https://user-images.githubusercontent.com/57131579/101243391-e4220e00-373a-11eb-99d4-acf9054c21d3.png)

**Comment by sendya** [comment]
自查 ESLint
