### ISSUE TITLE
不能使用a-space组件

### ISSUE THREAD

**Issue by imic07** [vueComponent/ant-design-vue-pro#1053]
**Describe the bug （描述 Bug）**

不能使用组件a-space.

**To Reproduce （重现步骤）**

1.  ant-design-vue-pro代码中直接使用报错
` <a-space>
        <a>Publish11</a>
        <a>Publish2</a>
        <a>Publish3</a>
      </a-space>
`
2. 在sandbox使用无问题。
a-space已经内置了，可以直接使用
https://codesandbox.io/s/antd-vue-table-expico-forked-0uzd2?file=/src/components/TestExpandedRowRender.vue

**Expected behavior（你期待的是什么?）**
能够直接使用a-space

**Comment by sendya** [comment]
建议看文档

https://pro.antdv.com/docs/faq

![image](https://user-images.githubusercontent.com/5404542/101337494-b530a700-38b6-11eb-81a7-3a6551a29d02.png)

**Comment by imic07** [comment]
@sendya 就是因为在lay_use.js中不能import ASpace from 'ant-design-vue' 才来issues的， 点进去看了下，node_modules/ant-design-vue/types/ant-design-vue.d.ts 中没有注册ASpace。

**Comment by sendya** [comment]
@imic07 import { Space } from 'ant-design-vue'

**Comment by sendya** [comment]
如组件库无 .d.ts 则无法在 ts 中提示使用，请在 ant-design-vue 反馈，谢谢

**Comment by imic07** [comment]
@sendya  import { Space } from 'ant-design-vue' 之前也试过了，不得行!!

ant-design-vue 是内置了的，直接使用<a-space/>标签即可， 不需要 在.d.ts中定义，看上面的沙箱测试！

**Comment by sendya** [comment]
> @sendya  import { Space } from 'ant-design-vue' 之前也试过了，不得行!!
> 
> ant-design-vue 是内置了的，直接使用<a-space/>标签即可， 不需要 在.d.ts中定义，看上面的沙箱测试！

那你倒是更新一下依赖？

**Comment by imic07** [comment]
@sendya 已经最新了，yarn install了的
![image](https://user-images.githubusercontent.com/16321067/101427620-341af380-393a-11eb-8c28-4fe2d2822134.png)
`
  "dependencies": {
    "@ant-design-vue/pro-layout": "^1.0.6",
    "@tinymce/tinymce-vue": "^3.2.6",
    "ant-design-vue": "~1.7.2",
    "axios": "^0.21.0",
    "core-js": "^3.1.2",
    "echarts": "^4.8.0",
    "echarts-liquidfill": "^2.0.6",
    "enquire.js": "^2.1.6",
    "lodash.clonedeep": "^4.5.0",
    "lodash.get": "^4.4.2",
    "lodash.pick": "^4.4.0",
    "md5": "^2.3.0",
    "mockjs2": "1.0.8",
    "moment": "^2.29.1",
    "nprogress": "^0.2.0",
    "store": "^2.0.12",
    "tinymce": "^5.6.1",
    "viser-vue": "^2.4.8",
    "vue": "^2.6.12",
    "vue-clipboard2": "^0.3.1",
    "vue-cropper": "0.5.5",
    "vue-i18n": "^8.22.2",
    "vue-lazyload": "^1.3.3",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "^3.4.9",
    "vue-svg-component-runtime": "^1.0.1",
    "vuex": "^3.6.0",
    "wangeditor": "^3.1.1"
  },
`

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/101428479-c2dc4000-393b-11eb-94bf-37d1851b410f.png)

无任何问题，请自查你安装的版本到底是不是特定版本， 到底有没有引入依赖。

**Comment by imic07** [comment]
@sendya 按需加载的情况下，space组件目前只能在使用的地方这样引用下才能使用，只有通知ant-disign-vue注册下node_modules/ant-design-vue/types/ant-design-vue.d.ts：
`
import ASpace from 'ant-design-vue/lib/space'

import 'ant-design-vue/lib/space/style/index.css'
`

**Comment by sendya** [comment]
@imic07 你没用 Typescript ，尽管直接引入，没有问题可以直接用。

```
import { Space } form 'ant-design-vue';
Vue.use(Space);
```


此话题结束

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/101431471-f621cd80-3941-11eb-82aa-ddabaf14b476.png)
