### ISSUE TITLE
route config "component" for path: index cannot be a string id. Use an actual component instead.

### ISSUE THREAD

**Issue by tomMentor** [vueComponent/ant-design-vue-pro#1056]
你好 请问一下我这个 component还是 报实际的组件代替 错误 ，请问你是怎么解决的呢
[vue-router] route config "component" for path: index cannot be a string id. Use an actual component instead.
![image](https://user-images.githubusercontent.com/45265422/101421803-26607080-3930-11eb-9b4e-8c4637cf3688.png)

**Comment by sendya** [comment]
没遇到过，难道你用的 TS?   JS 是不会检查类型的

**Comment by tomMentor** [comment]
@sendya 用的是JS 哦

**Comment by tomMentor** [comment]
@sendya 已经解决了 这样的写法是正确的，我传值传错了
