### ISSUE TITLE
关于移除了i18n之后部分组件显示英文的情况

### ISSUE THREAD

**Issue by JieAnthony** [vueComponent/ant-design-vue-pro#1066]
**Question （问题描述）**
关于移除了i18n之后组件文字显示英文的情况。
默认直接为中文即可，请问demo中可以显示中文是因为代码里还缺少什么需要配置的地方吗？还需指点一下

**Describe the solution you'd like （你期待的是什么？）**
我期待组件可以自动显示中文
例如 table中需要（没有数据） 而不是 No Data
例如 分页中 显示（条/页） 而不是 （/page）等等

**Comment by sendya** [comment]
组件库需要自行设定语言，请查阅组件库文档

**Comment by JieAnthony** [comment]
已解决 多谢

**Comment by InsHomePgup** [comment]
> 已解决 多谢

怎么解决 的？

**Comment by JieAnthony** [comment]
> > 已解决 多谢
> 
> 怎么解决 的？

@InsHomePgup  https://antdv.com/components/config-provider-cn/
