### ISSUE TITLE
隐藏子孙路由时，点击或者跳转子孙路由，主菜单的状态未保持，如/account

### ISSUE THREAD

**Issue by Wang-Yang** [vueComponent/ant-design-vue-pro#1069]
**Question （问题描述）**
path:/account下，我把二级路由隐藏了，只显示account的主菜单，点击settings里面的几个路由，主菜单account不能保持状态
**Describe the solution you'd like （你期待的是什么？）**
隐藏子孙路由时，点击或者跳转子孙路由，主菜单的状态可以保持，如/account
**Additional context（附加信息）**
`
{
        path: '/account',
        component: RouteView,
        redirect: '/account/settings',
        name: 'account',
        meta: { title: 'menu.account', icon: 'user', keepAlive: true, permission: ['user'] },
        hideChildrenInMenu: true,
        children: [
          {
            path: '/account/settings',
            name: 'settings',
            component: () => import('@/views/account/settings/Index'),
            meta: { title: 'menu.account.settings', hidden: true, hideHeader: true, permission: ['user'] },
            redirect: '/account/settings/base',
            children: [
              {
                path: '/account/settings/base',
                name: 'BaseSettings',
                component: () => import('@/views/account/settings/BaseSetting'),
                meta: { title: '基本设置', hidden: true, permission: ['user'] }
              },
              {
                path: '/account/settings/security',
                name: 'SecuritySettings',
                component: () => import('@/views/account/settings/Security'),
                meta: { title: '安全设置', hidden: true, keepAlive: true, permission: ['user'] }
              },
              {
                path: '/account/settings/custom',
                name: 'CustomSettings',
                component: () => import('@/views/account/settings/Custom'),
                meta: { title: '个性化设置', hidden: true, keepAlive: true, permission: ['user'] }
              }
            ]
          }
        ]
      }
`

**Comment by sendya** [comment]
https://pro.antdv.com/docs/router-and-nav#%E8%B7%AF%E7%94%B1

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/102311672-37505800-3fa8-11eb-84c5-1f7a9b9ba835.png)

**Comment by Wang-Yang** [comment]
![image](https://user-images.githubusercontent.com/25840593/102322577-39bbad80-3fba-11eb-9ceb-2e798cdd4e1b.png)
![Uploading image.png…]()
