### ISSUE TITLE
不同用户的权限问题，a用户应该只能看a权限的内容，b只能看b权限的内容，但现在a能通过直接输入网址的方式看到b用户的内容

### ISSUE THREAD

**Issue by yy-richard** [vueComponent/ant-design-vue-pro#1078]
**Question （问题描述）**
最近在做一个商场后台管理系统，有两个用户角色，管理员和供应商，不同角色进入系统后看到的界面应该不同。现在我是以管理员的身份进入，不应该能看到供应商的界面，供应商给了不同权限（侧边栏菜单显示的是管理员应该看到的界面，这是正确的），可是现在我能通过直接输入网址的方式看到供应商的内容页面，按理说供应商和管理员没有共同权限，不能看到彼此的内容

**Describe the solution you'd like （你期待的是什么？）**
求解路由和权限如何配置，才能不让管理员看到供应商的界面

**Additional context（附加信息）**
无

**Comment by sendya** [comment]
本项目设计的权限基于路由控制，按理说不可能不同权限的可以看页面，因为路由里根本没这个页面。  除非你做了什么改动，导致路由过滤失效了。

**Comment by yy-richard** [comment]
> 本项目设计的权限基于路由控制，按理说不可能不同权限的可以看页面，因为路由里根本没这个页面。 除非你做了什么改动，导致路由过滤失效了。

**Comment by yy-richard** [comment]
路由中，我是把所有路由写好了（包括管理员和供应商），然后根据后端返回的用户角色权限来决定展示哪些页面，即文档中的第一种权限方案。侧边栏菜单路由过滤成功了，只是内容区可以通过直接输入地址显示不属于它权限的内容

**Comment by sendya** [comment]
我已经说过了，按默认的实现 路由里不会存在 没有权限的路由，请检查路由为什么会多出没有权限的那些来。

更多详情可以去查看 Vue Router 官方文档中的 addRouters

**Comment by yy-richard** [comment]
谢谢，问题已解决。按默认的实现路由是没有问题的，该问题原因是因为我同事在router/index.js中将静态路由和动态路由一起添加进路由了，没有和我说，汗，弄得我搞了这么长时间
