### ISSUE TITLE
页面无法热重载

### ISSUE THREAD

**Issue by gouchaowen** [vueComponent/ant-design-vue-pro#108]
## 代码更新后，页面无法热重载

- 系统：macOS Mojave，版本10.14.1（18B75）
- 浏览器：Google Chrome，版本 72.0.3626.119（正式版本） （64 位）
- Pro版本：1.3.1

浏览器打开应用后，如下图，热重载功能启动的：
![image](https://user-images.githubusercontent.com/6114451/53727416-26098a80-3eab-11e9-8f31-bbd8aaaec213.png)

socket链接似乎也是ok的，更改代码保存并重新编译后，能够收到更新推送：
![image](https://user-images.githubusercontent.com/6114451/53729920-74ba2300-3eb1-11e9-8b46-8181c012cfe4.png)

但是页面内容就是不刷新，需要手动刷新才能看到刚才更改的内容。

**Comment by sendya** [comment]
经过测试我这里开发环境运行没这个问题

![gif](https://user-images.githubusercontent.com/5404542/53739249-4564df80-3ecc-11e9-8634-9ffb6e13942b.gif)

不清楚你是否改了什么配置，或者加了什么依赖

**Comment by gouchaowen** [comment]
> 经过测试我这里开发环境运行没这个问题
> 
> ![gif](https://user-images.githubusercontent.com/5404542/53739249-4564df80-3ecc-11e9-8634-9ffb6e13942b.gif)
> 
> 不清楚你是否改了什么配置，或者加了什么依赖

我才试了下，直接从git拉下来，然后`yarn install`、`yarn run serve`，还是这样，另一位同事也有同样问题，搞不懂为啥

**Comment by sendya** [comment]
尝试换个环境在试试， 晚上我到家用 macOS 也测试下

**Comment by gouchaowen** [comment]
嗯，终于解决了，虽然不知道啥原因，重新装了`node`，`npm`，`yarn`还是不行，然后重启了电脑，就好了[捂脸]
