### ISSUE TITLE
我在vue.config.js中配置的devServer不生效怎么办？

### ISSUE THREAD

**Issue by MilanMilanSoloConte** [vueComponent/ant-design-vue-pro#1086]
先声明我是一个新手。我在vue.config.js中配置的devServer如下：
![image](https://user-images.githubusercontent.com/22017194/103198458-54c7df00-4923-11eb-90ce-4589f284789e.png)
但是访问时，却仍在访问8000端口，并且也没把/api过滤掉。如下：
![image](https://user-images.githubusercontent.com/22017194/103198700-edf6f580-4923-11eb-98d9-d255bac1c403.png)
我想问下，如果我在开发时，所有的接口都想访问localhost:80端口，这个该如何配置呢？

**Comment by sendya** [comment]
代理的目的就是把你配置的 80 代理到 8000 下，来防止出现跨域的情况。你现在又将这个问题倒回去了，那配置该功能就没任何意义了。
更多建议看 https://cli.vuejs.org/config/#devserver-proxy 或者 webpack 文档中的 proxyTable，我这边就不做更多基础的解释了

**Comment by MilanMilanSoloConte** [comment]
其实我的需求是这样的：我本地还启动了后台服务器，比如说本地后台启动后的域名是localhost:80。现在又启动了vue的前端，那么我就想在我本地调试的时候，无论前端启动后的端口是什么（antd-pro默认是8000），那么它在请求接口的时候，都请求到localhost:80这个URL上。不知道我这么说表述清楚了没有。

**Comment by sendya** [comment]
看样子我说的也还不够清楚

> 代理的目的就是把你配置的 80 代理到 8000 下，来防止出现跨域的情况。你现在又将这个问题倒回去了，那配置该功能就没任何意义了。

**代理的目的就是把你配置的 80 代理到 8000 下**  
**代理的目的就是把你配置的 80 代理到 8000 下**  
**代理的目的就是把你配置的 80 代理到 8000 下**

先默读三遍，然后去搜索引擎找一下 **CORS** 是什么，为什么会有这个东西，解决这个东西的方案有哪些，各有什么利弊或作用。

**Comment by weixians** [comment]
> 看样子我说的也还不够清楚
> 
> > 代理的目的就是把你配置的 80 代理到 8000 下，来防止出现跨域的情况。你现在又将这个问题倒回去了，那配置该功能就没任何意义了。
> 
> **代理的目的就是把你配置的 80 代理到 8000 下**
> **代理的目的就是把你配置的 80 代理到 8000 下**
> **代理的目的就是把你配置的 80 代理到 8000 下**
> 
> 先默读三遍，然后去搜索引擎找一下 **CORS** 是什么，为什么会有这个东西，解决这个东西的方案有哪些，各有什么利弊或作用。

我觉得你没理解人家问的问题。这个8000仅仅只是启动并动态维护vuejs的端口，并并非访问后台服务的端口。
