### ISSUE TITLE
a标签下载本地的excel表单报错

### ISSUE THREAD

**Issue by goukuDev** [vueComponent/ant-design-vue-pro#1087]
**Question （问题描述）**
a标签下载本地的excel表单报错

**Describe the solution you'd like （你期待的是什么？）**
可以下载本地的excel表单

**Additional context（附加信息）**
![0545617b88f8e236b5bcc41ca33838f](https://user-images.githubusercontent.com/30975895/103206779-92cefe00-4937-11eb-88d1-4ff1e551a5fe.png)
![1d708cb290e4cb5aa11a26441d099bc](https://user-images.githubusercontent.com/30975895/103206785-96fb1b80-4937-11eb-8866-897eae5f4785.png)

当这里引入的是本地图片的时候，不会报错，并且可以下载成功。
如果像这又引入excel,项目直接报错了。
请问这个需要怎么解决

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/103210142-d299e380-493f-11eb-82f1-ca2deb1f2949.png)


没有 loaders 无法直接加载 xls 文件。你可以考虑当作静态文件使用，而不是这样的动态引入。 
这是你的业务逻辑，你可以考虑依靠 搜索相关业务 来完成你的业务

**Comment by goukuDev** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/103210142-d299e380-493f-11eb-82f1-ca2deb1f2949.png)
> 
> 没有 loaders 无法直接加载 xls 文件。你可以考虑当作静态文件使用，而不是这样的动态引入。
> 这是你的业务逻辑，你可以考虑依靠 搜索相关业务 来完成你的业务

谢谢，把模板放在public文件夹内，再当作静态文件引入就可以了。

**Comment by goukuDev** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/103210142-d299e380-493f-11eb-82f1-ca2deb1f2949.png)
> 
> 没有 loaders 无法直接加载 xls 文件。你可以考虑当作静态文件使用，而不是这样的动态引入。
> 这是你的业务逻辑，你可以考虑依靠 搜索相关业务 来完成你的业务

谢谢，把模板放在public文件夹内，再当作静态文件引入就可以了。
