### ISSUE TITLE
RightContent组件中调用api中方法报错Cannot find module './viewsBasicLayout'

### ISSUE THREAD

**Issue by TengChongChong** [vueComponent/ant-design-vue-pro#1091]
**Question （问题描述）**
How to use component `s-table` paging
我在RightContent的methods中调用了api中定义的一个方法
![image](https://user-images.githubusercontent.com/11783658/103396929-dbbdc700-4b70-11eb-9d50-d6e730a93ca5.png)

会报如下错误
![image](https://user-images.githubusercontent.com/11783658/103396903-b3ce6380-4b70-11eb-872b-fab5f7869215.png)
只要methods中写了api中的方法不调用也会报错，后就不报错。api中方法在views中的组件可以正常使用

**Describe the solution you'd like （你期待的是什么？）**
如何在RightContent中使用api中定义方法？

**Comment by sendya** [comment]
提供复现

**Comment by TengChongChong** [comment]
框架的代码我改掉好多，可能是我哪里改出问题了。不知道如何提供复现。
现在的情况是如果在BasicLayout中引入使用request的代码就会导致generator-routers.js中constantRouterComponents的BasicLayout为undefined，移除使用request的代码BasicLayout就会有值

**Comment by TengChongChong** [comment]
应该是加载顺序的问题，不知道是什么导致的。我把BasicLayout引入方式改为以下方式就可以了，不知道有没有其他影响
![image](https://user-images.githubusercontent.com/11783658/103417188-a4790580-4bc4-11eb-93d6-44d138b9204a.png)

**Comment by HANACYGM** [comment]
感谢，我也是这个问题
通过更改 generator-router.js  的 BasicLayout: () => import('@/layouts/BasicLayout') 
解决了

**Comment by sansan-mei** [comment]
感谢，解决了
