### ISSUE TITLE
ant design vue pro中无法使用a-form-model和a-form-model-item

### ISSUE THREAD

**Issue by xue8710** [vueComponent/ant-design-vue-pro#1094]
Unknown custom element: <a-form-model>

**Comment by xue8710** [comment]
ant-design-vue版本^1.7.2

**Comment by xue8710** [comment]
补充：
项目名称：vue-antd-pro
版本：3.0.0
浏览器：chrome 87.0.4280.88
![q2](https://user-images.githubusercontent.com/20987620/103405656-c48fd100-4b92-11eb-9e59-208e8c2a9562.png)

部分代码截图：
![q1](https://user-images.githubusercontent.com/20987620/103405723-0caef380-4b93-11eb-8207-95f8f025a462.png)

**Comment by sendya** [comment]
能麻烦引入一下 FormModel 并 Vue.use 挂给 vue 实例吗

**Comment by hardape** [comment]
> 补充：
> 项目名称：vue-antd-pro
> 版本：3.0.0
> 浏览器：chrome 87.0.4280.88
> ![q2](https://user-images.githubusercontent.com/20987620/103405656-c48fd100-4b92-11eb-9e59-208e8c2a9562.png)
> 
> 部分代码截图：
> ![q1](https://user-images.githubusercontent.com/20987620/103405723-0caef380-4b93-11eb-8207-95f8f025a462.png)

同学解决了吗，我也遇到这个问题

**Comment by OracleGao** [comment]
use.js中
增加import { FormModel } from 'ant-design-vue'和Vue.use(FormModel) 之后问题依旧存在。

**Comment by OracleGao** [comment]
找到原因了，lazy_use.js中没有加载FormModel, 在lazy_use.js的import{}这一坨中增加FormModel，并且在下面一坨的vue.use中增加Vue.use(FormModel)即可。
