### ISSUE TITLE
亲，请问有富文本框组件吗？

### ISSUE THREAD

**Issue by easonjim** [vueComponent/ant-design-vue-pro#1096]
十年不变的大难题，请问有富文本框组件吗？

**Comment by sendya** [comment]
没有

**Comment by easonjim** [comment]
亲，我查了组件库，其实是有的，两个：
WangEditor
QuillEditor
![image](https://user-images.githubusercontent.com/5625433/104420632-200b8700-55b5-11eb-8d75-c90566498358.png)
