### ISSUE TITLE
pro Layout 支持左侧菜单可以一直展开

### ISSUE THREAD

**Issue by owen800q** [vueComponent/ant-design-vue-pro#1102]
**Question （问题描述）**
click子菜单不会自动收缩, 左侧菜单默认展开
Antd 官方已经把这个属性加到pro layout里了 只是目前文档里没有写

**Describe the solution you'd like （你期待的是什么？）**
左侧菜单默认展开， click子菜单不会自动收缩

**Additional context（附加信息）**
![image](https://user-images.githubusercontent.com/19252045/104018088-38b22080-51f4-11eb-84a1-3e029ec6fc5f.png)
官方的直接在defaultSettings.js 加入openKeys=false 就可以
![image](https://user-images.githubusercontent.com/19252045/104018397-a9f1d380-51f4-11eb-89de-ac9532685fda.png)

**Comment by owen800q** [comment]
或者在BasicLayout.vue 可以直接修改RouteMenu的openKeys嗎
如下圖，如果要同時展開兩個菜單的所冇子菜單，直接把要展開的菜單加入openKeys就好了
![image](https://user-images.githubusercontent.com/19252045/104019128-f853a200-51f5-11eb-836f-b87ce16fc982.png)

**Comment by sendya** [comment]
目前不支持，等 pro-layout next
