### ISSUE TITLE
hiddenHeaderContent设置为true，不起作用。面包屑没有隐藏！

### ISSUE THREAD

**Issue by erduoJiang** [vueComponent/ant-design-vue-pro#1103]
**Describe the bug （描述 Bug）**

我要隐藏面包屑，在meat中如下设置：
meta: { title: 'menu.form.basic-form', hiddenHeaderContent: true, keepAlive: true, permission: ['form'] }
刷新页面发现面包屑没有隐藏！
我重新启动项目，还是没有隐藏！

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/33342387/104151509-27495e00-5418-11eb-80c8-9acf420979b8.png)
![image](https://user-images.githubusercontent.com/33342387/104151522-34fee380-5418-11eb-8a93-83b746bccc15.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/104277275-8626da00-54e1-11eb-88c6-6697178f3624.png)

现在都是由你自己渲染 <page-header-wrapper> 组件了，你可以直接在你需要的页面直接控制
详细的 API 可以看这里 https://github.com/vueComponent/pro-layout#pageheaderwrapper

**Comment by a1159717508** [comment]
https://github.com/vueComponent/pro-layout#pageheaderwrapper
也没有详细的API呀
