### ISSUE TITLE
设置 Theme Color 为第一个蓝色，打开页面，主题色没有被勾选住

### ISSUE THREAD

**Issue by wxy1234567890** [vueComponent/ant-design-vue-pro#1120]
![image](https://user-images.githubusercontent.com/24424956/108932910-1d588300-7685-11eb-8f5e-fc3da516b98e.png)

**Comment by wxy1234567890** [comment]
另一个问题，设置为黄色主题后，退出登录，刷新浏览器，页面又变成原始的蓝色，没有保存住设置的黄色主题，怎么解决？

**Comment by sendya** [comment]
主题色只用于预览，编译时 请通过 vue.config.js 内的主题色替换覆盖主题色

**Comment by wxy1234567890** [comment]
需要主题色配置这个功能呢

**Comment by hero8080** [comment]
package.json
下的版本"version": "3.0.0",
3.00版本主题组件放在node_modules，同时给提供了src\components\SettingDrawer本地文件组件需要自己倒腾需要花点时间
