### ISSUE TITLE
ant-design-vue-pro 不再升级vue3了吗？

### ISSUE THREAD

**Issue by BG7ZAG** [vueComponent/ant-design-vue-pro#1121]
![image](https://user-images.githubusercontent.com/16408650/108935120-2565f200-7688-11eb-9349-4bc66fcbc2e2.png)

和 免费开源版(Ant Design Vue Pro) 有什么区别
免费开源版是基于 Vue2 进行开发，并且官方不再进行新功能的增加，只会修复 bug。
商业版基于最新技术栈，持续迭代维护，专有钉钉群、语雀空间

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/issues/982
