### ISSUE TITLE
yarn start 如果路径中有字母“n”开头的文件夹，   src/.umi/core/routes.ts 会报错

### ISSUE THREAD

**Issue by yhfly** [vueComponent/ant-design-vue-pro#1129]
**Describe the bug （描述 Bug）**

yarn start 如果路径中有字母“n”开头的文件夹，   src/.umi/core/routes.ts 会报错

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/6168630/109625378-3b891c00-7b7a-11eb-9ea1-cebccedfef19.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
你来错地方了吧，这里是 vue 版本仓库

**Comment by yhfly** [comment]
抱歉，抱歉， 跑错山头了
