### ISSUE TITLE
左侧导航菜单默认开启了“只展开当前父级菜单”，如何关闭它？

### ISSUE THREAD

**Issue by JunX21194250** [vueComponent/ant-design-vue-pro#1136]
Question （问题描述）
左侧导航菜单默认开启了“只展开当前父级菜单 ”，当点击一个菜单时会让其它菜单组都折叠起来，ProLayout好像没有提供这个功能的开关和相关接口

Describe the solution you'd like （你期待的是什么？）
关闭这个功能或可以配置这个功能

Additional context（附加信息）
https://www.antdv.com/components/menu-cn/#components-menu-demo-open-current-submenu-only

**Comment by sendya** [comment]
不提供

你可以尝试最新的 pro-layout
