### ISSUE TITLE
我想给pro-layout属性collapsed设置一个浏览器记忆功能

### ISSUE THREAD

**Issue by jekip** [vueComponent/ant-design-vue-pro#1141]
**Question （问题描述）**
我想给pro-layout属性collapsed设置一个浏览器记忆功能

**Describe the solution you'd like （你期待的是什么？）**
期望是点击收起之后，不管是刷新浏览器，还是切换其他页面，菜单始终保持收起，如果再次点击展开，始终保持展开

**Additional context（附加信息）**
我已经尝试用localStorage去存储 collapsed 状态，确实可行，但是点击收起之后，如果频繁切换不同路由（缓存路由），和没有设置缓存的路由，菜单收起状态会自动展开，不知道是什么原因

代码如下：
![image](https://user-images.githubusercontent.com/19426584/111724247-df273b80-889f-11eb-8da8-587586d59e39.png)
切换路由的时候，一旦切换到设置了keepAlive 为 true 的路由，在切换其他没设置的路由，此时，BasicLayout 会刷新，变成一个，然后就会导致collapsed重新变成展开状态

![image](https://user-images.githubusercontent.com/19426584/111724270-ec442a80-889f-11eb-8242-3ddfb471b43d.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/111725702-7d1c0580-88a2-11eb-8416-18ec688b522a.png)  你用了两个 BasicLayout ?

**Comment by jekip** [comment]
![image](https://user-images.githubusercontent.com/19426584/111725903-e00d9c80-88a2-11eb-8e6b-0f3394506eca.png)

因为有些路由页面，期望缓存起来，所以在app里面 用 keep-alive 组件包了一个 <router-view /> ，这里我尝试多种写法，目前这种是可以让路由缓存生效，如果去掉这个特性，以上我用localStorage去存储 collapsed 状态，则不会有问题，望大佬帮我看看，怎么优雅的解决，表示真心的谢谢

**Comment by sendya** [comment]
不能缓存 basiclayout， 缓存包装在 basiclayout 的内部才能保证状态，其他的你可以自己想办法
