### ISSUE TITLE
登录页面背景图片被投诉侵犯著作权

### ISSUE THREAD

**Issue by guozqgzq** [vueComponent/ant-design-vue-pro#1142]
**Question （问题描述）**
How to use component `s-table` paging
背景图片是否有知识产权相关法律风险？
**Describe the solution you'd like （你期待的是什么？）**
前几天客户反映，登录页面背景被投诉侵犯著作权，背景图片是否能够继续使用？
**Additional context（附加信息）**

**Comment by sendya** [comment]
背景图是蚂蚁金服所属，请自行更换
