### ISSUE TITLE
s-table 不显示分页器

### ISSUE THREAD

**Issue by zsl1549** [vueComponent/ant-design-vue-pro#1147]
**Describe the bug （描述 Bug）**

pageNo: 1
pageSize: 10
totalCount: 3
这样的返回不显示分页器

**To Reproduce （重现步骤）**

totalCount 小于 pageNo*pageSize 就不显示分页器

**Expected behavior（你期待的是什么?）**
Whether or not to display the pager should have a variable to resolve

**Comment by sendya** [comment]
不大于1页，没有分页器很正常。
如果不符合你的预期，你可以自行修改 s-table 的内部判断逻辑

**Comment by zsl1549** [comment]
希望后期封装s-table 有更多的属性 便利用户使用 @sendya

**Comment by sendya** [comment]
欢迎 PR

**Comment by zsl1549** [comment]
周末加班 辛苦了 开源精神 @sendya
