### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by m-git-hub** [vueComponent/ant-design-vue-pro#1150]
**Describe the bug （描述 Bug）**

Menu 菜单组件打开状态下选中菜单，点击关闭按钮之后，菜单只显示图标，但是没有高亮展示（菜单只有一级的时候有高亮），此时根本不知道哪一个菜单被选中，当鼠标滑过菜单时，高亮才显示，体验极差,还有应该可以控制高亮的颜色，提升体验。
我使用了你们的demo也存在这个问题。跟换浏览器无果。望解决
看了其他版本的ant design 也是一样的效果

**To Reproduce （重现步骤）**
菜单默认打开
选中子菜单
点击关闭菜单按钮
此时左边图标没有高亮

**Expected behavior（你期待的是什么?）**
希望优化此功能，高亮的颜色可以自由设定

**Screenshots（截图）**
*******************************操作一**********************************
![截屏2021-03-28 上午1 04 40](https://user-images.githubusercontent.com/35618634/112728329-a4896700-8f61-11eb-94cd-0789eb04c791.png)
![截屏2021-03-28 上午1 05 35](https://user-images.githubusercontent.com/35618634/112728340-bd921800-8f61-11eb-905d-2b81d1d7444a.png)

*******************************操作二**********************************
![截屏2021-03-28 上午1 11 25](https://user-images.githubusercontent.com/35618634/112728494-8b34ea80-8f62-11eb-9f26-716ee940b8ce.png)
![截屏2021-03-28 上午1 11 51](https://user-images.githubusercontent.com/35618634/112728502-98ea7000-8f62-11eb-93f2-2a0f73bd14d6.png)

*******************************操作三**********************************
![截屏2021-03-28 上午1 13 21](https://user-images.githubusercontent.com/35618634/112728547-d222e000-8f62-11eb-8a40-41b37b0a64bc.png)
![截屏2021-03-28 上午1 14 05](https://user-images.githubusercontent.com/35618634/112728569-e9fa6400-8f62-11eb-94bc-fe4589310d23.png)

*******************************操作四**********************************
![截屏2021-03-28 上午1 21 30](https://user-images.githubusercontent.com/35618634/112728847-34301500-8f64-11eb-9497-536da69cc0b3.png)
![截屏2021-03-28 上午1 21 41](https://user-images.githubusercontent.com/35618634/112728851-3a25f600-8f64-11eb-9695-7f8aa6825ad9.png)
![截屏2021-03-28 上午1 21 57](https://user-images.githubusercontent.com/35618634/112728858-3db97d00-8f64-11eb-9767-762681306701.png)
![截屏2021-03-28 上午1 22 04](https://user-images.githubusercontent.com/35618634/112728862-427e3100-8f64-11eb-95f5-eda634aa591e.png)

vue版本3.0
Ant Design 版本 2.1.0

**Comment by sendya** [comment]
发错地方了？

**Comment by m-git-hub** [comment]
为啥没人响应嘞，难道只有我遇到这个问题么。。。

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/113374452-c2aaf900-939f-11eb-8e19-a6faddfcbe9f.png)

本项目没有支持 Vue3 不知你是否发错地方了。请核查一下

**Comment by m-git-hub** [comment]
这是1.7.3的demo
![截屏2021-04-02 上午11 06 39](https://user-images.githubusercontent.com/35618634/113376255-d8bab880-93a3-11eb-8d4e-bcaca71c4cc2.png)
![截屏2021-04-02 上午11 07 23](https://user-images.githubusercontent.com/35618634/113376260-dd7f6c80-93a3-11eb-8d25-50858b12c446.png)
![截屏2021-04-02 上午11 07 30](https://user-images.githubusercontent.com/35618634/113376380-2800e900-93a4-11eb-85f9-78f1d9499c59.png)


这个是pro的
![截屏2021-04-02 上午11 08 26](https://user-images.githubusercontent.com/35618634/113376296-f25c0000-93a3-11eb-841d-c88795420605.png)
![截屏2021-04-02 上午11 08 39](https://user-images.githubusercontent.com/35618634/113376300-f556f080-93a3-11eb-9c0a-8bf0f845d282.png)
