### ISSUE TITLE
如何修改build后的资源路径

### ISSUE THREAD

**Issue by AmazingDM** [vueComponent/ant-design-vue-pro#116]
RT,现在build后js和css文件夹直接在dist文件夹下，我想让build后的这些文件夹能全部放在/dist/static/中。没有找到网上所说的assetsPublicPath配置。求解谢谢。

**Comment by zkwolf** [comment]
vue.config.js里加上assetsDir: 'static'，js、css和img目录就会放到static下了

**Comment by AmazingDM** [comment]
> vue.config.js里加上assetsDir: 'static'，js、css和img目录就会放到static下了

ok好使了，谢谢！

**Comment by wangshaoan** [comment]
好
