### ISSUE TITLE
动态加载路由无效问题

### ISSUE THREAD

**Issue by SoraYY** [vueComponent/ant-design-vue-pro#1160]
**Question （问题描述）**
我现在已经把整个路由守卫和路由权限那一块改成自己的逻辑了  现在就是想把菜单这一块不用配置文件加载,想改成后端请求返回,也改动了项目提供的/moudules/async.route.js和router/generator-route文件,但就是不走里面的步骤,不知道为啥

**Describe the solution you'd like （你期待的是什么？）**
如何实现动态加载菜单

**Additional context（附加信息）**
我打开store/index.js里面的dynamic router permission control,关闭default模块后,就提示我module if not resolve这个模块打包错误了

**Comment by sendya** [comment]
https://pro.antdv.com/docs/authority-management
