### ISSUE TITLE
请问build以后本地Nginx访问报错的问题

### ISSUE THREAD

**Issue by 0530-Liub** [vueComponent/ant-design-vue-pro#1164]
![image](https://user-images.githubusercontent.com/49514401/115356376-2d589300-a1ee-11eb-8e13-9d16db25c237.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/vue.config.js#L22-L38

检查一下是否通过 cdn 加载了，并且没加载到 vue

**Comment by 0530-Liub** [comment]
vueConfig基本没有修改，只改了打包的静态资源路径

**Comment by 0530-Liub** [comment]
已解决
