### ISSUE TITLE
a-week-picker 汉化之后，moment.updateLocale进行设置dow和doy 无效

### ISSUE THREAD

**Issue by lmd3385** [vueComponent/ant-design-vue-pro#1167]
需求是自行设置一年的第一周，但是
a-week-picker 汉化之后，moment.updateLocale进行设置dow和doy 无效，
   moment.updateLocale("zh-cn", { week: {
        dow: 1, // First day of week is Monday
        doy: 7  // First week of year must contain 1 January (7 + 1 - 1)
      }})
麻烦请问下该如何操作？

**Comment by sendya** [comment]
这个我也不清楚，建议 antdvue 库去问
