### ISSUE TITLE
不错，期待ts版本

### ISSUE THREAD

**Issue by mongofeng** [vueComponent/ant-design-vue-pro#117]
如题

**Comment by sendya** [comment]
vue 没发布 3 之前，应该没打算会出 ts 版。
你可以参考其他 TS 版  https://github.com/vue-alain/vue-alain

同时也欢迎 PR

**Comment by mongofeng** [comment]
> vue 没发布 3 之前，应该没打算会出 ts 版。
> 你可以参考其他 TS 版 https://github.com/vue-alain/vue-alain

好哒，想请问一下，登录有些接口是怎么回事
