### ISSUE TITLE
Source面板下为什么会有webpack://

### ISSUE THREAD

**Issue by zss1004504439** [vueComponent/ant-design-vue-pro#1170]
**Question （问题描述）**
打开 [https://preview.pro.antdv.com/dashboard/workplace](https://preview.pro.antdv.com/dashboard/workplace)
Source面板下为什么会有`webpack://`
![image](https://user-images.githubusercontent.com/24915880/116229266-de2fd680-a788-11eb-8f62-e02f40a264c6.png)

**Describe the solution you'd like （你期待的是什么？）**
打开Source面板不显示`webpack://`

**Additional context（附加信息）**
 productionSourceMap: false, 已设置为false

**Comment by sendya** [comment]
很正常，很多用了 webpack 的网站都有，比如 bilibili.com
