### ISSUE TITLE
动态修改@font-size-base变量,动态字体

### ISSUE THREAD

**Issue by SnowGuest** [vueComponent/ant-design-vue-pro#1171]
**Question （问题描述）**
有大佬做过全局字体font-size动态修改吗？
，less.modifyVars一直不生效

**Describe the solution you'd like （你期待的是什么？）**
默认字体太小了，需求要动态改变大小
**Additional context（附加信息）**

**Comment by SnowGuest** [comment]
问题已解决

**Comment by dmdoit** [comment]
请问你是怎么解决的呢？我跟你有一样的需求

**Comment by SnowGuest** [comment]
> 请问你是怎么解决的呢？我跟你有一样的需求

你好， 可以直接在vue.config.js中配置
css.loaderOptions.less.modifyVars中配置    'font-size-base': '1rem',
然后获取 动态改变html根节点大小即可
但是要注意部分组件字体大小会变的异常
需要手动覆盖错误的样式修复即可

**Comment by dmdoit** [comment]
以为我要做一个系统的字体大小切换，这种方式也支持吗

**Comment by SnowGuest** [comment]
> 以为我要做一个系统的字体大小切换，这种方式也支持吗

我目前就是做一套后台管理系统，用这种方式去配置全局的字体大小的

**Comment by SnowGuest** [comment]
> 以为我要做一个系统的字体大小切换，这种方式也支持吗
``` js
    SetFont (font) {
      const html = document.querySelector('html')
      html.style.fontSize = font + 'px'
      storage.set('Font', font)
    },
```
基本上ant-design所有组件都是用font-size-base这个变量的 初始化为1rem
然后改html 基本没有什么大问题

**Comment by dmdoit** [comment]
" 然后获取 动态改变html根节点大小即可" 这句话是怎么实现的？
我在vue.config.js中写了
```
css: {
    loaderOptions: {
      less: {
        modifyVars: {
          'font-size-base': '20px'
        }
      }
    }
  },
```
需要重新npm run serve 才能起作用

**Comment by SnowGuest** [comment]
> " 然后获取 动态改变html根节点大小即可" 这句话是怎么实现的？
> 我在vue.config.js中写了
> 
> ```
> css: {
>     loaderOptions: {
>       less: {
>         modifyVars: {
>           'font-size-base': '20px'
>         }
>       }
>     }
>   },
> ```
> 
> 需要重新npm run serve 才能起作用

这里需要你改变成
``` js
  css: {
    loaderOptions: {
      less: {
        modifyVars: {
          'font-size-base': '1rem',
        },
        javascriptEnabled: true
      }
    }
  },
```
通过rem单位去改变字体大小，我尝试过，这里使用变量替代但是失效了，只能通过rem去解决

**Comment by dmdoit** [comment]
我先把SetFont按照你的方式放到vuex中去试试，这种方式必须npm run serve 才能起作用吗？有没有按钮切换选择字体大小时直接起作用。
javascriptEnabled: true  我一直都写了，只是刚才没有发出来

**Comment by SnowGuest** [comment]
> 我先把SetFont按照你的方式放到vuex中去试试，这种方式必须npm run serve 才能起作用吗？有没有按钮切换选择字体大小时直接起作用。
> javascriptEnabled: true 我一直都写了，只是刚才没有发出来

这个函数只需要你把字体大小传入这个函数就可以了 比如SetFont(12), SetFont(33)
而且要确保你是
``` js
'font-size-base': '1rem',
```

**Comment by SnowGuest** [comment]
> 我先把SetFont按照你的方式放到vuex中去试试，这种方式必须npm run serve 才能起作用吗？有没有按钮切换选择字体大小时直接起作用。
> javascriptEnabled: true 我一直都写了，只是刚才没有发出来

无论在那里调用都可以

**Comment by dmdoit** [comment]
我明白了，主要是这个'font-size-base': '1rem' 里的“1rem”， 你给了rem， 然后你用
```
SetFont (font) {
  const html = document.querySelector('html')
  html.style.fontSize = font + 'px'
  storage.set('Font', font)
}
```
设置了html的基础字体大小，然后这个1rem读取了html的字体大小，然后从而改变了font-size-base

**Comment by SnowGuest** [comment]
> 我明白了，主要是这个'font-size-base': '1rem' 里的“1rem”， 你给了rem， 然后你用
> 
> ```
> SetFont (font) {
>   const html = document.querySelector('html')
>   html.style.fontSize = font + 'px'
>   storage.set('Font', font)
> }
> ```
> 
> 设置了html的基础字体大小，然后这个1rem读取了html的字体大小，然后从而改变了font-size-base

对滴 用css方案解决 因为是1个rem 所以设置多少字体 全局的字体都是一个html的大小

**Comment by SnowGuest** [comment]
> 我明白了，主要是这个'font-size-base': '1rem' 里的“1rem”， 你给了rem， 然后你用
> 
> ```
> SetFont (font) {
>   const html = document.querySelector('html')
>   html.style.fontSize = font + 'px'
>   storage.set('Font', font)
> }
> ```
> 
> 设置了html的基础字体大小，然后这个1rem读取了html的字体大小，然后从而改变了font-size-base

![kudou-h8u8e](https://user-images.githubusercontent.com/59474029/121325952-a64dae80-c944-11eb-899e-792c273cc3c8.gif)
这是我做好之后的效果

**Comment by dmdoit** [comment]
> > 我明白了，主要是这个'font-size-base': '1rem' 里的“1rem”， 你给了rem， 然后你用
> > ```
> > SetFont (font) {
> >   const html = document.querySelector('html')
> >   html.style.fontSize = font + 'px'
> >   storage.set('Font', font)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 设置了html的基础字体大小，然后这个1rem读取了html的字体大小，然后从而改变了font-size-base
> 
> ![kudou-h8u8e](https://user-images.githubusercontent.com/59474029/121325952-a64dae80-c944-11eb-899e-792c273cc3c8.gif)
> 这是我做好之后的效果

对的，就是这种效果

**Comment by dmdoit** [comment]
加个微信或者QQ吧？有空可以多多交流一下， 微信：dengmin945

**Comment by money-yes** [comment]
请问，改成rem后，less文件里面的的样式计算结果不对，应该怎么解决呢
![微信图片_20231121110751](https://github.com/vueComponent/ant-design-vue-pro/assets/71144588/b5e7b5e2-b00c-4ffd-88af-2c2bf64a90e2)

**Comment by SnowGuest** [comment]
> 请问，改成rem后，less文件里面的的样式计算结果不对，应该怎么解决呢 ![微信图片_20231121110751](https://user-images.githubusercontent.com/71144588/284451544-b5e7b5e2-b00c-4ffd-88af-2c2bf64a90e2.png)

不好意思，我当时没遇到这种情况
