### ISSUE TITLE
菜单menu 如果mode为动态的，自适应屏宽不会折叠

### ISSUE THREAD

**Issue by yiwuyu** [vueComponent/ant-design-vue-pro#1176]
**Describe the bug （描述 Bug）**

ant-design-vue-pro 菜单menu未跟随屏宽缩短而折叠

**To Reproduce （重现步骤）**

1. Go to ['demo'](https://preview.pro.antdv.com/account/settings/basic)
2. 缩小屏幕宽度使 isMobile 为true
3. 可以看到 Menu 并没有将无法显示的 MenuItem 折叠

**Expected behavior（你期待的是什么?）**
![image](https://user-images.githubusercontent.com/25633994/117533198-1dc6b000-b01e-11eb-8ba9-91e4cc09f9a2.png)

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/25633994/117533277-857cfb00-b01e-11eb-8950-8de41bfb8dca.png)

**Desktop (please complete the following information):**

 - OS: Macos BigSur
 - Browser chrome
 - Version 89.0.4389.128

**Additional context（附加信息）**

**Comment by sendya** [comment]
本仓库是开源项目，商业版不在本项目维护范围内。你可以直接找商业版客服对接

**Comment by yiwuyu** [comment]
不是商业版啊
https://preview.pro.antdv.com/account/settings/security

**Comment by yiwuyu** [comment]
> 本仓库是开源项目，商业版不在本项目维护范围内。你可以直接找商业版客服对接

不是商业版
https://preview.pro.antdv.com/account/settings/security
