### ISSUE TITLE
a-table 表格嵌套后 右侧设置为fixed的操作栏 出现错位

### ISSUE THREAD

**Issue by Xponglee** [vueComponent/ant-design-vue-pro#1178]
网络问题 图片无法上传
<table class="ant-table-fixed">
    <colgroup>
     ···
    </colgroup>
    <thead class="ant-table-thead">
    ···
    </thead>
    <tbody class="ant-table-tbody">
    <tr class="ant-table-row ant-table-row-level-0" data-row-key="3" style="height: 54px;">
        ···
    </tr>
    <tr data-row-key="3-extra-row" class="ant-table-expanded-row ant-table-expanded-row-level-1">
        <td colspan="1">&amp;nbsp;</td>
    </tr>
    <tr class="ant-table-row ant-table-row-level-0" data-row-key="1" style="height: 54px;">
        ···
    </tr>
    <tr data-row-key="1-extra-row"
        class="ant-table-expanded-row ant-table-expanded-row-level-1">
        <td colspan="1">&amp;nbsp;</td>
    </tr>
    </tbody>
</table>

上述是生成的页面，data-row-key="1-extra-row"的tr没有跨行的样式 而我嵌套进去的表格有多行，就造成了操作栏和数据是错位的。

有什么地方可以修改 tr的跨行属性么或者多生成几个tr?

下述是我的源代码
<template>
<div>
  
  <ProTable
    ref="indexTable"
    headerTitle="运费模板列表"
    :rowKey="(record) => record.id"
    :columns.sync="columns"
    :data="loadData"
    :alert="{ show: true, clear: true }"
    :showPagination="true"
    :expanded-row-keys.sync="expandedRowKeys"
    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
  >
    <a-table
      slot="expandedRowRender"
      slot-scope="row"
      :rowKey="'inner'+row.id"
      :columns="innerColumns"
      :data-source="innerData[row.id]"
      style="padding-left:5%;"
      :pagination="false" >
      <template slot="first_unit_title">首{{ explainType(row.type) }}</template>
      <template slot="continue_unit_title">继{{ explainType(row.type) }}</template>
    </a-table>
    <template slot="type" slot-scope="type">
      计{{ explainType(type) }}
    </template>
    <template slot="tools" slot-scope="id, row">
      <a v-action:edit @click="handleEdit(row)">{{ $t('edit') }}</a>
      <a-divider type="vertical" />
      <a v-action:delete @click="handleDelete(row)">{{ $t('delete') }}</a>
    </template>
    <template slot="toolbar">
      <a-space>
        <a-button v-action:add type="primary" icon="plus" @click="handleAdd($event)">{{ $t('add') }}</a-button>
      </a-space>
      <template v-if="selectedRows.length">
        <a-space>
          <a-dropdown>
            <a-menu slot="overlay" @click="handleMenuClick($event)">
              <a-menu-item v-action:delete key="remove"><a-icon type="delete" />{{ $t('batch.delete') }}</a-menu-item>
              <a-menu-item
                v-action:enable
                key="enable"
              ><a-icon type="check-circle" />{{ $t('batch.enable') }}</a-menu-item
              >
              <a-menu-item
                v-action:disable
                key="disable"
              ><a-icon type="close-circle" />{{ $t('batch.disable') }}</a-menu-item
              >
            </a-menu>
            <a-button> {{ $t('batch.operation') }} <a-icon type="down" /> </a-button>
          </a-dropdown>
        </a-space>
      </template>
    </template>
  </ProTable>
  
</div>
</template>

<script>
import { ProTable, BadgeStatus } from '@/components'
import { IndexMixin } from '@/mixins/IndexMixin'

export default {
components: {
  ProTable,
  BadgeStatus
},
mixins: [IndexMixin],
filters: {},
data () {
  return {
    apiQueryUrl: '/admin/GoodsFreightTemplate/query', // 要实现列表查询的接口地址
    apiDeleteUrl: '/admin/GoodsFreightTemplate/delete', // 要实现删除功能的接口地址
    innerData: [],
    expandedRowKeys: [],
    // 列表列头
    columns: [
      {
        title: '模板名称',
        key: 'template_name',
        dataIndex: 'template_name',
        width: 300
      },

      {
        title: '计价方式',
        key: 'type',
        dataIndex: 'type',
        width: 120,
        scopedSlots: { customRender: 'type' }
      },

      {
        title: '操作',
        key: 'tools',
        fixed: 'right',
        scopedSlots: { customRender: 'tools' }
      }
    ],
    innerColumns: [
      {
        title: '配送区域',
        dataIndex: 'region',
        width: '30%',
        scopedSlots: { customRender: 'region' }
      },
      {
        dataIndex: 'first_unit',
        width: '15%',
        scopedSlots: { customRender: 'first_unit', title: 'first_unit_title' }
      },
      {
        title: '运费',
        dataIndex: 'first_money',
        width: '20%'
      },
      {
        dataIndex: 'continue_unit',
        width: '15%',
        scopedSlots: { customRender: 'continue_unit', title: 'continue_unit_title' }
      },
      {
        title: '运费',
        dataIndex: 'continue_money',
        width: '20%'
      }
    ]
  }
},
methods: {
  // TODO 删除确认提示信息设置的钩子 可能要重构的！！！
  hookHandleDeleteConfirmTitle (row = {}, isRow = true) {
    return isRow ? '确定要删除这条数据吗?' : '确定要删除已选择的数据吗?'
  },
  // TODO 启用禁用确认提示信息设置的钩子 可能要重构的！！！
  hookHandleStatusConfirmTitle (row = {}, isRow = true, type = 0) {
    const typeMsg = !type ? '禁用' : '启用'
    return isRow ? '确定要' + typeMsg + '这条数据吗?' : '确定要' + typeMsg + '已选择的数据吗?'
  },
  // table 数据回调事件
  onQuery (parameter) {
    return this.apiQuery(Object.assign(parameter, this.queryParam))
    .then(res => {
        res.result.data.map((row) => {
          row.goods_freight_configs.map((row) => {
            row.key = 'inner' + row.id
            console.log(row)
            return row
          })
          this.innerData[row.id] = row.goods_freight_configs
          this.expandedRowKeys.push(row.id)
          return row
        })
        return res.result
    })
  },
  // 新增按钮
  handleAdd (e) {
    this.$router.push({ name: 'AdminGoodsFreightEdit' })
  },
  // 编辑按钮
  handleEdit (row) {
    this.$router.push({ name: 'AdminGoodsFreightEdit', query: { id: row.id } })
  },
  explainType (type) {
    return type === 'number' ? '件' : type === 'weight' ? '重' : '体积'
  }
}
}
</script>

**Comment by sendya** [comment]
能排版一下吗？ 或者提供在线复现

**Comment by Xponglee** [comment]
抱歉，排版后又乱了。
<template>
  <div>
    
    <ProTable
      ref="indexTable"
      headerTitle="运费模板列表"
      :rowKey="(record) => record.id"
      :columns.sync="columns"
      :data="loadData"
      :alert="{ show: true, clear: true }"
      :showPagination="true"
      :expanded-row-keys.sync="expandedRowKeys"
      :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
    >
      <a-table
        slot="expandedRowRender"
        slot-scope="record, index, indent, expanded"
        :columns="[
          { title: 'Date', dataIndex: 'date', key: 'date' },
          { title: 'Name', dataIndex: 'name', key: 'name' },
          { title: 'Status', key: 'state', scopedSlots: { customRender: 'status' } },
          { title: 'Upgrade Status', dataIndex: 'upgradeNum', key: 'upgradeNum' },
          {
            title: 'Action',
            dataIndex: 'operation',
            key: 'operation',
            scopedSlots: { customRender: 'operation' },
          },
        ]"
        :data-source="[{
          key: i,
          date: '2014-12-24 23:12:00',
          name: 'This is production name',
          upgradeNum: 'Upgraded: 56',
        }]"
        style="padding-left:5%;"
        :pagination="false" >
        
        <template slot="status">
          {{ record }}
          {{ index }}
          {{ indent }}
          {{ expanded }}</template> -->
      </a-table>
      <template slot="type" slot-scope="type">
        计{{ explainType(type) }}
      </template>
      <template slot="tools" slot-scope="id, row">
        <a v-action:edit @click="handleEdit(row)">{{ $t('edit') }}</a>
        <a-divider type="vertical" />
        <a v-action:delete @click="handleDelete(row)">{{ $t('delete') }}</a>
      </template>
      <template slot="toolbar">
        <a-space>
          <a-button v-action:add type="primary" icon="plus" @click="handleAdd($event)">{{ $t('add') }}</a-button>
        </a-space>
        <template v-if="selectedRows.length">
          <a-space>
            <a-dropdown>
              <a-menu slot="overlay" @click="handleMenuClick($event)">
                <a-menu-item v-action:delete key="remove"><a-icon type="delete" />{{ $t('batch.delete') }}</a-menu-item>
                <a-menu-item
                  v-action:enable
                  key="enable"
                ><a-icon type="check-circle" />{{ $t('batch.enable') }}</a-menu-item
                >
                <a-menu-item
                  v-action:disable
                  key="disable"
                ><a-icon type="close-circle" />{{ $t('batch.disable') }}</a-menu-item
                >
              </a-menu>
              <a-button> {{ $t('batch.operation') }} <a-icon type="down" /> </a-button>
            </a-dropdown>
          </a-space>
        </template>
      </template>
    </ProTable>
    
  </div>
</template>

<script>
import { ProTable, BadgeStatus } from '@/components'
import { IndexMixin } from '@/mixins/IndexMixin'

export default {
  components: {
    ProTable,
    BadgeStatus
  },
  mixins: [IndexMixin],
  filters: {},
  data () {
    return {
      apiQueryUrl: '/admin/GoodsFreightTemplate/query', // 要实现列表查询的接口地址
      apiDeleteUrl: '/admin/GoodsFreightTemplate/delete', // 要实现删除功能的接口地址
      innerData: [],
      expandedRowKeys: [],
      // 列表列头
      columns: [
        {
          title: '模板名称',
          key: 'template_name',
          dataIndex: 'template_name',
          width: 300
        },

        {
          title: '计价方式',
          key: 'type',
          dataIndex: 'type',
          width: 120,
          scopedSlots: { customRender: 'type' }
        },

        {
          title: '操作',
          key: 'tools',
          fixed: 'right',
          scopedSlots: { customRender: 'tools' }
        }
      ],
      innerColumns: [
        {
          title: '配送区域',
          dataIndex: 'region',
          width: '30%',
          scopedSlots: { customRender: 'region' }
        },
        {
          dataIndex: 'first_unit',
          width: '15%',
          scopedSlots: { customRender: 'first_unit', title: 'first_unit_title' }
        },
        {
          title: '运费',
          dataIndex: 'first_money',
          width: '20%'
        },
        {
          dataIndex: 'continue_unit',
          width: '15%',
          scopedSlots: { customRender: 'continue_unit', title: 'continue_unit_title' }
        },
        {
          title: '运费',
          dataIndex: 'continue_money',
          width: '20%'
        }
      ]
    }
  },
  methods: {
    // TODO 删除确认提示信息设置的钩子 可能要重构的！！！
    hookHandleDeleteConfirmTitle (row = {}, isRow = true) {
      return isRow ? '确定要删除这条数据吗?' : '确定要删除已选择的数据吗?'
    },
    // TODO 启用禁用确认提示信息设置的钩子 可能要重构的！！！
    hookHandleStatusConfirmTitle (row = {}, isRow = true, type = 0) {
      const typeMsg = !type ? '禁用' : '启用'
      return isRow ? '确定要' + typeMsg + '这条数据吗?' : '确定要' + typeMsg + '已选择的数据吗?'
    },
    // table 数据回调事件
    onQuery (parameter) {
      return this.apiQuery(Object.assign(parameter, this.queryParam))
      .then(res => {
          res.result.data.map((row) => {
            row.goods_freight_configs.map((row) => {
              row.key = 'inner' + row.id
              console.log(row)
              return row
            })
            this.innerData[row.id] = row.goods_freight_configs
            this.expandedRowKeys.push(row.id)
            return row
          })
          return res.result
      })
    },
    // 新增按钮
    handleAdd (e) {
      this.$router.push({ name: 'AdminGoodsFreightEdit' })
    },
    // 编辑按钮
    handleEdit (row) {
      this.$router.push({ name: 'AdminGoodsFreightEdit', query: { id: row.id } })
    },
    explainType (type) {
      return type === 'number' ? '件' : type === 'weight' ? '重' : '体积'
    }
  }
}
</script>

**Comment by Xponglee** [comment]
第一次提issues 排版一直乱 复现比较困难 代码放沙盒里了 帮我看看，多谢
https://codesandbox.io/s/brave-bush-3dly7?file=/src/views/admin/goodsFreight/Index.vue

**Comment by Xponglee** [comment]
![image](https://user-images.githubusercontent.com/45960007/118575985-3bcca700-b7ba-11eb-87dd-83854d8a75a5.png)

**Comment by Xponglee** [comment]
![image](https://user-images.githubusercontent.com/45960007/118576268-c6150b00-b7ba-11eb-9edb-7555e8db8a44.png)

**Comment by Xponglee** [comment]
![image](https://user-images.githubusercontent.com/45960007/118576755-be099b00-b7bb-11eb-9ccf-e3ecadcbaa6e.png)

**Comment by Xponglee** [comment]
我把columns里fixed:"right"去掉，不用悬浮就没事
![image](https://user-images.githubusercontent.com/45960007/118577048-47b96880-b7bc-11eb-957b-2978b3d528cc.png)
![image](https://user-images.githubusercontent.com/45960007/118577060-4f790d00-b7bc-11eb-9b98-ffc9f5b50c45.png)
