### ISSUE TITLE
角色列表2显示错误

### ISSUE THREAD

**Issue by spiroo** [vueComponent/ant-design-vue-pro#118]
现象：
![image](https://user-images.githubusercontent.com/7858201/54065345-9cffa400-425a-11e9-91ad-815e53a43cf9.png)

复现方法如下：
![roles](https://user-images.githubusercontent.com/7858201/54065361-c9b3bb80-425a-11e9-8ee2-a85dbf57cb39.gif)

**Comment by kokoroli** [comment]
已修复

**Comment by spiroo** [comment]
本地测试，已解决。
