### ISSUE TITLE
Menu组件在版本2.1.6控制台出现很多警告

### ISSUE THREAD

**Issue by cff-github** [vueComponent/ant-design-vue-pro#1182]
**Describe the bug （描述 Bug）**

Menu组件在版本2.1.6控制台出现很多警告 : reactivity.esm-bundler.js?a1e9:337 Set operation on key "default" failed: target is readonly.

**To Reproduce （重现步骤）**

![image](https://user-images.githubusercontent.com/69131256/119312156-90818d80-bca4-11eb-8e5d-61a62b1efc1a.png)

**Expected behavior（你期待的是什么?）**
清除警告

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/69131256/119312248-b444d380-bca4-11eb-9fcb-cfb43ae40a65.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
等 vue3 库处理，具体可以查 vue3 issues
