### ISSUE TITLE
使用jenkins做持续集成，在jenkins每次打包都会报错

### ISSUE THREAD

**Issue by wou101771** [vueComponent/ant-design-vue-pro#1187]
**Question （问题描述）**
使用jenkins做持续集成，在jenkins服务器上每次打包都会报错，本地打包是没问题的，在服务器手动打包也没问题，请问是什么原因？multiTab组件未做任何修改。

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
![image](https://user-images.githubusercontent.com/52279380/119781295-6ecf1300-befd-11eb-8d4a-5f0db8c8c27d.png)

**Comment by sendya** [comment]
手动打包没问题的情况下，自动就不会有问题，如果有问题一般就是环境不对，请自行检查
