### ISSUE TITLE
VAPTCHA 怎么在 antd里使用？

### ISSUE THREAD

**Issue by timi137137** [vueComponent/ant-design-vue-pro#1188]
**Question （问题描述）**
怎么在 antd中使用 VAPTCHA？ [这里](https://www.vaptcha.com/document/install.html#%E5%AE%8C%E6%95%B4%E5%AE%9E%E4%BE%8B)是VAPTCHA的文档，只给了普通JS的用法，我导入js文件都是在index.html,然后运行起来还没用

**Describe the solution you'd like （你期待的是什么？）**
能够有教程或回复一下如何使用VAPTCHA这种普通js

**Comment by sendya** [comment]
建议联系 vaptcha 提供支持

**Comment by sendya** [comment]
但正常的原生 js  按正常引入， window.xxx调用即可

**Comment by timi137137** [comment]
> 但正常的原生 js  按正常引入， window.xxx调用即可
> 
> 
> 
> 

好的我试试

**Comment by timi137137** [comment]
联系了VAPTCHA那边的支持能用上了，这个VAPTCHA是免费且验证效果不错的，建议如果可以的话内置到demo上是不错的。我现在看看能不能做个package，不行就在这里发个教程图片，做存档

**Comment by sendya** [comment]
你可以写文档，或发 issue 关键字让其他人更好索引，项目中不考虑什么库都引入，那么普通使用者将会安装大量无用库

**Comment by timi137137** [comment]
> 你可以写文档，或发 issue 关键字让其他人更好索引，项目中不考虑什么库都引入，那么普通使用者将会安装大量无用库

这个倒是明白，不然也不会做按需加载了xd，至于VAPTCHA的相关issue真没找到，所以我也打算在这个issue做个教程。给后人填坑。（毕竟不是所有人都用谷歌验证码的）

**Comment by timi137137** [comment]
如何在Vue/Antd(Ant Design) 中使用免费的第三方验证码VAPTCHA

首先肯定需要先去[注册](https://www.vaptcha.com/)并按照指示获取一个自己的VID。然后打开你的项目，如果你想在多个组件使用的请创建一个JS文件，如果只是单个组件使用则将以下代码写入methods(其实完全看自己开心)

``` node
Init: function (cb) {
        let Script = document.getElementById('vaptcha_sdk')
        if (Script) {
          cb()
          return
        }
        Script = document.createElement('script')
        Script.id = 'vaptcha_sdk'
        Script.src = 'https://v.vaptcha.com/v3.js' // 这里随着VAPTCHA更新会更新
        Script.onload = cb
        document.body.appendChild(Script)
      },
      Validate: function (success, scene = 0) {
        this.Init(() => {
          const options = {
            vid: '你的VID',
            type: 'invisible', // 可选值click,invisible,embed
            scene: 0, // 验证单元场景，默认 0
            offline_server: '' // 离线模式地址
          }

          window.vaptcha(options).then((vaptchaObj) => {
            vaptchaObj.listen('pass', () => { success(vaptchaObj.getToken()) }) // 监听如果验证成功则返回Token，详情看VAPTCHA文档
            vaptchaObj.validate() // 弹出验证（如果是隐藏式‘invisible’）
          })
        })
      }
```

以上就简单两个函数，第一个是初始化往当前页面插入VAPTCHA的JS文件。第二个是初始化并监听，然后弹出验证窗口。验证完毕会返回token。

使用方法如下:
``` node
Validate(token => {
        console.log(token) // 这里是验证成功后的逻辑，如提交表单或验证表单什么的。
      })
```

如果是点击式或嵌入式则需要添加``` vaptchaObj.render() ``` 去注入HTML，但是个人推荐能用隐藏式用什么点击式呢(xd
