### ISSUE TITLE
src/views/list/TableList.vue 里面的 step-by-step-modal 组件是干什么的?

### ISSUE THREAD

**Issue by sunshine2face** [vueComponent/ant-design-vue-pro#1189]
大佬你好, 我在src/views/list/TableList.vue 里面看到 step-by-step-modal 这个组件, 但是并没找到从哪里展示出来, 所以想问下 这个组件放置在这里是有什么含义吗?

![微信截图_20210531222538](https://user-images.githubusercontent.com/48798036/120208221-cce25a00-c25f-11eb-97ac-1f7dbb1e7493.png)

**Comment by sunshine2face** [comment]
![Uploading 微信截图_20210531222538.png…]()

**Comment by sunshine2face** [comment]
![微信截图_20210531222538](https://user-images.githubusercontent.com/48798036/120208100-b805c680-c25f-11eb-9764-cce23479a3db.png)

**Comment by sendya** [comment]
this.$refs.modal.edit(record);

以前用来显示例子的

**Comment by sunshine2face** [comment]
好的,  非常感谢解答.
