### ISSUE TITLE
input,cascader

### ISSUE THREAD

**Issue by SXGaoXiaoYan** [vueComponent/ant-design-vue-pro#1194]
**Question （问题描述）**
How to use component `s-table` paging
input,cascader组件设置allowClear可清除属性后,不显示清除时的icon图标;使用this.$message.success图标也不显示,F12调试查看了一下,有i标签的结构,但是里面没有svg的结构
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
请提供复现，谢谢
