### ISSUE TITLE
固定列表格无数据时横向滚动条在上面

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue-pro#1195]
![image](https://user-images.githubusercontent.com/77136306/121140016-fad12b00-c86b-11eb-9e8a-ce82103a45d7.png)

**Comment by sendya** [comment]
这个是基础组件库 Table 组件的遗留问题，在 vue3 版本中的新 Table 已经解决，如果对该组件有疑问，可以到 https://github.com/vueComponent/ant-design-vue 库发 issue
