### ISSUE TITLE
修改动态路由后出错 

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#1200]
**Describe the bug （描述 Bug）**

将动态路由开启后 
![image](https://user-images.githubusercontent.com/20655248/122727340-848bea00-d2a9-11eb-8945-77c5ffc7bc95.png)
终端报错 
![image](https://user-images.githubusercontent.com/20655248/122727408-91a8d900-d2a9-11eb-9070-d6cc0b85930f.png)
 
![image](https://user-images.githubusercontent.com/20655248/122727511-adac7a80-d2a9-11eb-9d94-5492174837c4.png)

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
c55b84479fc857cf44ea95e761d9335366354644
