### ISSUE TITLE
仪表盘

### ISSUE THREAD

**Issue by Fourth-fresh-man** [vueComponent/ant-design-vue-pro#1204]
**Describe the bug （描述 Bug）**

点击仪表盘的监控页导航，会跳转到百度搜索

**To Reproduce （重现步骤）**

1. 打开仪表页
2. 点击监控页导航

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
特意为之，该页面用于演示跳转外部页面
