### ISSUE TITLE
建议vue版本pro-layou组件能够像react版本一样添加如图所示布局

### ISSUE THREAD

**Issue by caolaichao** [vueComponent/ant-design-vue-pro#1207]
![image](https://user-images.githubusercontent.com/44855437/124734636-e43ff180-df47-11eb-8d78-b8a0e44cdeb8.png)

**Comment by caolaichao** [comment]
或者是有什么解决方案的！希望能够提供一下,感谢

**Comment by sendya** [comment]
pro-layout 很早就支持这个布局了，请自行尝试
