### ISSUE TITLE
Account Center 页面报错

### ISSUE THREAD

**Issue by adminAnLin** [vueComponent/ant-design-vue-pro#1208]
**Describe the bug （描述 Bug）**

![image](https://user-images.githubusercontent.com/43719059/124889716-eff3ec80-e009-11eb-9f42-76d7ae5e45b3.png)

**To Reproduce （重现步骤）**

1. Go to 'Account Center'
2. Click on '项目'
3. 打开控制台

**Comment by sendya** [comment]
fixed https://github.com/vueComponent/ant-design-vue-pro/commit/6cd90b1c541a45ffa186cd9535bd7afde97d73ca
