### ISSUE TITLE
个人设置组件Bug

### ISSUE THREAD

**Issue by abersheeran** [vueComponent/ant-design-vue-pro#121]
![image](https://user-images.githubusercontent.com/25364828/54121515-9d07cb80-4435-11e9-9723-27972e62054a.png)

当刷新页面后，手动点击菜单或者右上角菜单跳转到 个人设置，会出现这个Bug。Preview提供的网站也是有这个Bug。

经验证是`import AvatarModal from './AvatarModal'`这个组件的问题，注释掉后即可正常。
并非专业前端，不会修复，只能提ISSUE没办法交PR，望修复。

**Comment by Lninn** [comment]
我也遇到了

**Comment by sendya** [comment]
暂时可以使用全局注册 Vue-Cropper 组件

**Comment by abersheeran** [comment]
感谢回复，但全局注册会不会有副作用？

**Comment by sendya** [comment]
> 感谢回复，但全局注册会不会有副作用？

不会
