### ISSUE TITLE
Display Error after Switch Tabs Serval Times by Using a-tabs and a-card in ANTD.

### ISSUE THREAD

**Issue by EternallyAscend** [vueComponent/ant-design-vue-pro#1210]
**Describe the bug （描述 Bug）**

路由hideChildrenInMenu，并在子页面中使用<a-tabs><a-tab-pane><view></view></a-tab-pane></a-tabs>做Tab分页的情况下，使用BasicList文件中的标准列表部分的<a-card>作为<view>组件的组成部分。初次显示无问题，多次切换标签页后出现页面拉伸情况。

Master branch
Git commit 6cd90b1c541a45ffa186cd9535bd7afde97d73ca
Author: Sendya <18x@loacg.com>
Date:   Fri Jul 9 11:49:17 2021 +0800
fix: avatar-list-item did not register

**To Reproduce （重现步骤）**
1. router.config.js 建立一个新的路径，重定向到子页面，子页面hideChildrenInMenu，并使用<a-tabs><a-tab-pane><view></view></a-tab-pane></a-tabs>的格式实现子页面的子页面，创建多个Tab，对应的view组件使用BasicList文件中标准列表的<a-card>填充。
2. 启动npm run serve
3. 在浏览器中登录，并在路由中选择新创建的路径。
4. 反复切换Tab
5. Tab内显示异常(应该是组件宽度识别到浏览器宽度而不是tab页面宽度了，不清楚原因)

**Expected behavior（你期待的是什么?）**
请求分析错误原因并寻求可能可行的解决方案，以便于解决显示异常的问题。

**Screenshots（截图）**
正常情况
https://ftp.bmp.ovh/imgs/2021/07/65e3eb118700da85.png
多次切换Tab后
https://ftp.bmp.ovh/imgs/2021/07/3485664e22a0295e.png

**Desktop (please complete the following information):**
Chrome & Edge
Chrome： 91.0.4472.124
Edge：91.0.864.37

**Additional context（附加信息）**
Nothing else, thanks.

**Comment by sendya** [comment]
不知道你说的 Tab 是什么，可否提供一个可运行的复现项目

**Comment by EternallyAscend** [comment]
您好，您可以克隆下面的仓库运行查看，存在问题的代码处在`src/views/cc/views/communication`目录下。
https://gitee.com/eternallyascend/issue_example

**Comment by EternallyAscend** [comment]
项目中互动管理、内容发布和内容管理的Tab多次点击后均会出现显示问题。疑似将浏览器宽度视为组件宽度。

**Comment by sendya** [comment]
你自己限定一下宽度把，应该能解决

**Comment by sendya** [comment]
或者向 ant-design-vue 库发 issue,本库只处理 pro 相关问题
