### ISSUE TITLE
如何实现菜单多级化？

### ISSUE THREAD

**Issue by WaitingforPu** [vueComponent/ant-design-vue-pro#1211]
1.登录页面进入以后，默认显示顶部的第一个菜单，侧边栏显示第一个菜单的子路由，默认展示第一个内容

2.希望官方可以给一个思路（万分感谢）

3.[](url)
![微信截图_20210714145101](https://user-images.githubusercontent.com/26001471/125576690-d0b9db0e-a60a-4138-818a-e08bfca3d73b.png)

**Comment by sendya** [comment]
当前版本不支持，也不会提供支持。可以使用 `@ant-design-vue/pro-layout@next`
