### ISSUE TITLE
项目运行后内容区域导航屑重复显示

### ISSUE THREAD

**Issue by youzhajun** [vueComponent/ant-design-vue-pro#1212]
![image](https://user-images.githubusercontent.com/84554002/125593481-863600d7-df9a-4900-9722-75186d34e261.png)

**Comment by youzhajun** [comment]
查看layout与组件源码中也并未显示此部分代码

**Comment by youzhajun** [comment]
查看layout与组件源码中也并未显示此部分代码

**Comment by Dreamerryao** [comment]
/layouts/PageView.vue 中 与对应的router组件内部`page-header-wrapper`重复，导致多重表头，稍后会提一个pr

**Comment by sendya** [comment]
你的用法有问题导致的，不用 page-header 组件的页面请直接使用 https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/RouteView.vue 或者 vue-router 的 router-view 。
而不是用专门给 page 用的 page-view
