### ISSUE TITLE
eslint问题

### ISSUE THREAD

**Issue by BearPessimist** [vueComponent/ant-design-vue-pro#1216]
请问这烦人的eslint语法检查怎么去掉呀，不然总是容易出一些诡异的报错
![image](https://user-images.githubusercontent.com/58261397/126067772-c1dceb62-8aa3-4c4a-8542-4821e3f0ddfc.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/126092481-fa9e7f02-e0c6-4d4f-af2f-52c541f1d6b9.png)
