### ISSUE TITLE
为何菜单修改后不变化？

### ISSUE THREAD

**Issue by irongiants** [vueComponent/ant-design-vue-pro#1219]
按照开发说明文档 https://pro.antdv.com/docs/router-and-nav
所说，增加菜单后，自动编译，但是菜单没有显示出来。
单独增加一个不涉及权限的外部url而已
{
    path: 'https://pro.loacg.com/docs/getting-started',
    name: 'docs',
    meta: {
        title: '文档', 
        target: '_blank' // 打开到新窗口
   }
}
最神的时，我将router.config.js文件里相关菜单路由整个注释掉，编译刷新页面后，菜单还在。
应该不是缓存问题，因为修改title立马生效。

**Comment by sendya** [comment]
不知你说的是动态路由还是？

**Comment by ganyanchuan1989** [comment]
同样问题，menu.js修改后，重启依旧是老名字
```js
export default {
    'menu.welcome': '欢迎',
    'menu.home': '主页',
    'menu.dashboard': '仪表盘',
    'menu.dashboard.analysis': '分析页',
    'menu.dashboard.monitor': '监xxxx', // 修改
```

**Comment by sendya** [comment]
先确定自己是 动态路由 还是静态路由

https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/store/index.js#L7-L12

**Comment by irongiants** [comment]
> 先确定自己是 动态路由 还是静态路由
> 
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/store/index.js#L7-L12

好吧，确实是动态路由，我按上面文档所说改成静态的就可以了。
TKS。
