### ISSUE TITLE
内联编辑表格Bug

### ISSUE THREAD

**Issue by Lninn** [vueComponent/ant-design-vue-pro#122]
![image](https://user-images.githubusercontent.com/23557028/54173554-6b3a4780-44bd-11e9-8c79-ca6f77fb49d4.png)

使用表格的时候出现了这个警告，会影响表格的其他功能吗

**Comment by sendya** [comment]
请自行设置 rowKey 具体可以参见 ant vue 官方文档

**Comment by Lninn** [comment]
> 请自行设置 rowKey 具体可以参见 ant vue 官方文档

谢谢
