### ISSUE TITLE
路由表过滤，router.config.js的asyncRouterMap对象数据被修改了

### ISSUE THREAD

**Issue by cwandev** [vueComponent/ant-design-vue-pro#1220]
**Question （问题描述）**
老师，您好。

我这边遇到这样一个问题，颇为困惑，希望能指点一二。感谢感谢感谢。

我采用的是前端固定路由表，根据后端返回的role，生成权限路由。

我这里有两个角色，管理员和审核员。每个角色有对应的菜单权限。

流程：

我以管理员的身份登录，返回了一个路由表。假如这时候我退出登录，非刷新的方式退出登录。再去登录审核员，
结果返回的菜单是上次管理员登录过滤后的菜单。当然，没有刷新，vuex也还有数据。这个时候我刷新后。审核员的菜单就出来了。

我调试后发现，GenerateRoutes方法下的asyncRouterMap对象被改变了。但是我却没有看到更改的地方。

**Describe the solution you'd like （你期待的是什么？）**

统一管理的路由表只是一个数据对象，希望过滤后，也不会改变config/router.config.js这里面的数据。

**Additional context（附加信息）**

**Comment by sendya** [comment]
deepClone 一下

**Comment by CharleeWa** [comment]
非常感谢，已解决。

**Comment by cwandev** [comment]
> deepClone 一下

非常感谢，已解决。

**Comment by CharleeWa** [comment]
> deepClone 一下

非常感谢，已解决。
