### ISSUE TITLE
@ant-design-vue/pro-layout 声明文件如何编写，尤其是花括号里面的参数(vue3+TS)

### ISSUE THREAD

**Issue by guochendong** [vueComponent/ant-design-vue-pro#1225]
**Question （问题描述）**
我开始引入
main.ts
`import ProLayout, {PageHeaderWrapper }   from '@ant-design-vue/pro-layout';`
然后声明
pro-layout.d.ts
```
declare module '@ant-design-vue/pro-layout' {
    interface ComponentCustomProperties {
        ProLayout:any,
    }
    export default ProLayout ;
}
```

**Describe the solution you'd like （你期待的是什么？）**
声明ProLayout参数可以正常工作，不再报错，然而，{ PageHeaderWrapper } 参数始终报错

**Additional context（附加信息）**
我尝试新建一个声明文件
pro-layouts.d.ts
```
declare module '@ant-design-vue/pro-layout' {
  interface ComponentCustomPropertiess {
      PageHeaderWrapper:any,
  }
   export {
     PageHeaderWrapper
   };
}
```
依旧报错：
`"export 'PageHeaderWrapper' was not found in '@ant-design-vue/pro-layout'`

**Comment by sendya** [comment]
本项目是 Vue2 项目，不包含 Vue3 相关的引入，请自行确认
