### ISSUE TITLE
本地服务, 可以正常登录; yarn run build:preview 打包成dist部署在服务器, 登录后页面空白;最新master分支登录不进去, 拉v3版本的代码才可以进入

### ISSUE THREAD

**Issue by liujun8892** [vueComponent/ant-design-vue-pro#1227]
**Question （问题描述）**
本地服务正常:
![image](https://user-images.githubusercontent.com/62731351/128683558-83d95c10-c931-4806-9f7e-f13f3545ca77.png)
![image](https://user-images.githubusercontent.com/62731351/128683812-32571462-6222-4270-9cd0-391a5223587a.png)
打成预览模式的包, 就会报addRoute不是一个方法
![image](https://user-images.githubusercontent.com/62731351/128683954-bec4f56a-fbff-4ded-9a14-517755b8bfb0.png)
![image](https://user-images.githubusercontent.com/62731351/128684051-62c635de-7f7d-49fe-bbad-7ceb16c67cf7.png)

**Describe the solution you'd like （你期待的是什么？）**
期待在预览模式下也能登录然后进入面板页

**Additional context（附加信息）**
拉的master代码, 使用的yarn install 和 yarn run build:preview 然后部署在宝塔.
不管是在宝塔linux服务器, 还是用 serve -s 运行都会报y.addRoute is not a function
公网预览地址: http://antdpro.liujun1314.online/

**Comment by liujun8892** [comment]
拉v3版本的代码可以
![image](https://user-images.githubusercontent.com/62731351/128691560-569343e2-6477-40de-8c26-cdd5d649d225.png)

**Comment by wien-wyc** [comment]
我也遇到这个问题了，修改src/permission.js文件，把38到40行修改为`router.addRoutes(store.getters.addRouters)`，就可以了。估计是vue-router版本问题，build出来的版本无法使用vue-router新的addRoute方法，改成老的addRoutes就行了。我也是前端小白，希望开发者能找下原因。参考：https://router.vuejs.org/zh/api/#router-addroutes
