### ISSUE TITLE
加载Slider出错Unknown custom element

### ISSUE THREAD

**Issue by ergoulee** [vueComponent/ant-design-vue-pro#1228]
系统信息：macOS Big Sur 11.4
"vue-antd-pro": "3.0.2",
浏览器：Google Chrome 版本 92.0.4515.131（正式版本）
问题：加载Slider出错
错误信息：[Vue warn]: Unknown custom element: <a-slider> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
![image](https://user-images.githubusercontent.com/15899945/128702283-4398a171-eb90-41c9-9601-fd346ea279d5.png)

**Comment by sendya** [comment]
你引入了 a-sider 吗？

**Comment by ergoulee** [comment]
> 你引入了 a-sider 吗？

vue-antd-pro不是在src/core/use.js里全量引入了吗？

**Comment by ergoulee** [comment]
哦，发现了，是在/src/main.js里改，readme里有写。谢谢！

**Comment by ergoulee** [comment]
哦，发现了，是在/src/main.js里改，readme里有写。谢谢！
