### ISSUE TITLE
generator-routers 设计理念是啥？

### ISSUE THREAD

**Issue by ganyanchuan1989** [vueComponent/ant-design-vue-pro#1229]
**Is your feature request related to a problem? Please describe.**
generator-routers 设计理念是什么？一个路由本来配置一个地方就可以了。现在弄的很复杂，需要配置很多地方。如果是基于异步路由，我觉得应该采用webpack的动态加载策略，而不是这种在两个地方去配置，看来起十分奇怪。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sendya** [comment]
不知道你是否有认真看代码，或者有认真去理解这些东西。
就过来发表你的看法，但是希望你能先把你想要提出质疑的东西摸清楚

本项目采用的就是你所说的 webpack的动态加载策略，你可以自己看代码。

https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/router/generator-routers.js#L123-L126


怪不怪就 仁者见仁智者见智了，我提供的是多种解决方案，最终使用哪种方案看使用者，而不是你这样说法一刀切。谢谢
