### ISSUE TITLE
使用了webpack5就运行失败得使用webpack4才能运行

### ISSUE THREAD

**Issue by ljsshuai** [vueComponent/ant-design-vue-pro#1240]
如何使用webpack5也能运行需要升级什么

![36ed5080b5e44cdf05665d1c59e604b](https://user-images.githubusercontent.com/40684836/131821826-6193c522-3311-46af-8c25-9ce7660316d1.png)

**Comment by sendya** [comment]
没测试过，建议不要升级。
如果有发现是什么导致的，可以提供一下
