### ISSUE TITLE
npm run serve 报错

### ISSUE THREAD

**Issue by stevenliu87** [vueComponent/ant-design-vue-pro#1246]
0% compiling ERROR  TypeError: Cannot read property 'get' of undefined

**Comment by stevenliu87** [comment]
fatal: not a git repository (or any of the parent directories): .git
VUE_APP_PREVIEW true
 INFO  Starting development server...
0% compiling ERROR  TypeError: Cannot read property 'get' of undefined

**Comment by sendya** [comment]
使用 `git clone https://github.com/vueComponent/ant-design-vue-pro.git` 拉代码把

**Comment by stevenliu87** [comment]
fatal: unable to access 'https://github.com/vueComponent/ant-design-vue-pro.git/': OpenSSL SSL_read: Connection was reset, errno 10054

**Comment by stevenliu87** [comment]
问题解决了
