### ISSUE TITLE
ChartCard组件的total为什么是string？

### ISSUE THREAD

**Issue by ccb1900** [vueComponent/ant-design-vue-pro#125]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/chart/ChartCard.vue
total应该只会传入number类型的数据吧。
数字还要转换到字符串，感觉很不合理。
还是说有其他方面的考虑？

**Comment by sendya** [comment]
如果传递 `number` 就没办法传递其他符号了。而且绑定 total 必须写成
```diff
- <chart-card :loading="loading" title="总销售额" total="￥126,560">
+ <chart-card :loading="loading" title="总销售额" :total="126560">
```

这个 我后期在优化吧，让传 v-slot

**Comment by ccb1900** [comment]
> 如果传递 `number` 就没办法传递其他符号了。而且绑定 total 必须写成

```
total: {
      type: [String, Number],
      default: ''
    },
```
这样是不是好一点。

**Comment by sendya** [comment]
ref d6b23f39cfbbc7c2ae51a29be64454c23482e682 

已更新 API，其他 chart 内的组件也会在近期重构到跟 react pro 官方 API 一致

**Comment by ulongx** [comment]
@sendya 系统里用的那个<v-chart  是什么组件，怎么找不到引用的地方呀？
```
<v-chart :force-fit="true" :height="height" :data="data" :padding="[36, 5, 18, 5]">
     <v-tooltip />
     <v-bar position="x*y" />
</v-chart>
```
