### ISSUE TITLE
帮帮孩子吧，内网发布，怎么去掉CDN使用本地文件

### ISSUE THREAD

**Issue by KangYuChun** [vueComponent/ant-design-vue-pro#1258]
**Question （问题描述）**
内网发布，怎么去掉CDN使用本地文件

**Describe the solution you'd like （你期待的是什么？）**
内网状态下无网络，如何本地加载 cs、js 文件

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/vue.config.js#L22-L38

详情查询 webpack 或 vue cli 配置
