### ISSUE TITLE
进入基本表单页面后，点击面包屑导航的表单页的时候会出现404

### ISSUE THREAD

**Issue by yunchen1314** [vueComponent/ant-design-vue-pro#1260]
进入基本表单页面后，点击面包屑导航的表单页的时候会出现404，原因是重定向的路径与基本表单配置的路由不一致

**Comment by sendya** [comment]
来个 PR ？

**Comment by yunchen1314** [comment]
文件：mock/services/user.js




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 进入基本表单页面后，点击面包屑导航的表单页的时候会出现404 (Issue #1260)





 
来个 PR ？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
