### ISSUE TITLE
怎么才可以添加React版本里的水印效果呀

### ISSUE THREAD

**Issue by skyworthli** [vueComponent/ant-design-vue-pro#1261]
**Describe the solution you'd like （你期待的是什么？）**
实现React版本里的水印效果

**Comment by sendya** [comment]
vue2 版本不提供，vue3 版有 watermark 可以直接使用

**Comment by skyworthli** [comment]
有具体的链接吗，我下了master分支的Tags是V3.0还有Releases是Pro 3.0.0版本都没看到有水印啊

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/issues/1236
