### ISSUE TITLE
为什么免费版本菜单导航历史功能都不舍得放出来。

### ISSUE THREAD

**Issue by f4762690** [vueComponent/ant-design-vue-pro#1265]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sendya** [comment]
菜单导航历史是什么

**Comment by zhajianjun** [comment]
是呀！只有企业版才有

**Comment by sendya** [comment]
是什么东西？无法理解你说的是什么东西

**Comment by dmdoit** [comment]
> 是什么东西？无法理解你说的是什么东西

我想他说的应该是 MultiTab

**Comment by sendya** [comment]
MultiTab 一直都在源码里，什么叫舍不得放出来？
