### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by TheFirstSunday** [vueComponent/ant-design-vue-pro#1269]
**Question （问题描述）**
admin/admin 不能登录

**Describe the solution you'd like （你期待的是什么？）**
正常登陆

**Additional context（附加信息）**
![image](https://user-images.githubusercontent.com/20334663/141682271-177854a6-fff7-4af7-afdf-6fefc48ddabd.png)

**Comment by sendya** [comment]
默认有提供 mock API 数据，如果你去除了还不提供 API 来服务，是不可能使用的。需要先确定你是否使用了 mock ，或者是否自己提供服务

**Comment by TheFirstSunday** [comment]
> 默认有提供 mock API 数据，如果你去除了还不提供 API 来服务，是不可能使用的。需要先确定你是否使用了 mock ，或者是否自己提供服务

     怎么使用mock数据 yarn -> yarn serve  ?要修改什么配置才会走到mock api？
