### ISSUE TITLE
请问路由隐藏项如何设置菜单父级选中

### ISSUE THREAD

**Issue by doitcore** [vueComponent/ant-design-vue-pro#127]
请问路由隐藏项如何设置菜单父级选中，超过三级菜单如何父级选中

**Comment by sendya** [comment]
如果父菜单属性带有 `hideChildrenInMenu` 那么会自定隐藏子集菜单。并且该父菜单啊会被识别为 `A-Menu-Item` 也就是非 `Sub-Menu`

**Comment by doitcore** [comment]
`{
        path: '/store',
        name: 'store',
        redirect: '/store/store-list',
        component: PageView,
        hideChildrenInMenu: true,
        meta: {
          icon: 'shop',
          permission: 'Pages.Administration.Tenant.Store',
          title: '门店'
        },
        children: [
          {
            path: '/store/store-list',
            name: 'store-list',
            hidden: true,
            meta: {
              icon: 'appstore',
              permission: 'Pages.Administration.Tenant.Store',
              title: '全部门店',
              hiddenHeaderContent: true
            },
            component: _import('store/store')
          },
          {
            path: '/store/store-create',
            name: 'store-create',
            hidden: true,
            meta: {
              icon: 'appstore',
              permission: 'Pages.Administration.Tenant.Store.Create',
              title: '添加门店',
              hiddenHeaderContent: true,
              isActive: true
            },
            component: _import('store/store-create')
          },
          {
            path: '/store/store-edit',
            name: 'store-edit',
            hidden: true,
            meta: {
              icon: 'appstore',
              permission: 'Pages.Administration.Tenant.Store.Edit',
              title: '修改门店',
              hiddenHeaderContent: true,
              isActive: true
            },
            component: _import('store/store-edit')
          }
        ]
      }`
在子路由页面，主路由菜单没有选中

**Comment by sendya** [comment]
meta.hidden 可以强制子菜单不显示在菜单上(和父级 hideChildrenInMenu 配合)

**Comment by sendya** [comment]
你可以参考一下  这个提交 https://github.com/sendya/ant-design-pro-vue/blob/ddd32afcfe8815d89a1a6a9a94bc73a4037bca24/src/config/router.config.js#L82

但是这个 key 已经由 alwaysShow 修改为 hideChildrenInMenu
并且要跟子菜单 meta.hidden = true 配合。

后面会考虑优化到只要父菜单设置了 hideChildrenInMenu 子菜单就默认被忽略，父菜单自动被选中

**Comment by doitcore** [comment]
`    updateMenu() {
      const routes = this.$route.matched.concat();
      // if (routes.length >= 4 && this.$route.meta.hidden) {
      //   routes.pop();
      //   this.selectedKeys = [routes[2].path];
      // } else {
      //   this.selectedKeys = [routes.pop().path];
      // }
      **this.selectedKeys = [];
      routes.forEach(item => {
        this.selectedKeys.push(item.path);
      });**
      // console.log(this.selectedKeys);
      const openKeys = [];
      if (this.mode === 'inline') {
        routes.forEach(item => {
          openKeys.push(item.path);
        });
      }

      this.collapsed ? (this.cachedOpenKeys = openKeys) : (this.openKeys = openKeys);
    },`
我对menu.js的updateMenu做了更改，这样可以实现
