### ISSUE TITLE
src/config/defaultSettings.js的primaryColor设为'#1890FF'设置抽屉不会勾选

### ISSUE THREAD

**Issue by dcsuibian** [vueComponent/ant-design-vue-pro#1270]
一个小bug：
官方给的例子中，src/config/defaultSettings.js中的主题色是这样的：
```javascript
primaryColor: '#F5222D', // primary color of ant design
```
全大写。当我想改成蓝色时，我很自然地写成了：
```javascript
primaryColor: '#1890FF', // primary color of ant design
```
这样网页整体颜色是会变，但是SettingDrawer的“Theme Color”部分不会自动勾选：
![image](https://user-images.githubusercontent.com/54771493/141777189-b1155642-80f3-4f67-a371-ad853a873d98.png)

而改成
```javascript
primaryColor: '#1890ff', // primary color of ant design
```
就可以。或者其它颜色的大写也可以

用vue devtools查看时会发现只有这个地方的key是小写的：
![image](https://user-images.githubusercontent.com/54771493/141777488-a8c4fa27-d15c-4d79-b20f-28b76f6b1bd2.png)

貌似是与@ant-design-vue/pro-layout组件发生了冲突

**Comment by sendya** [comment]
你清空一下 localStorage 里的数据 在重试看看？

**Comment by dcsuibian** [comment]
找到问题了，应该是pro-layout组件的问题。

https://github.com/vueComponent/pro-layout/blob/next/src/defaultSettings.ts

![image](https://user-images.githubusercontent.com/54771493/143665251-9251d6e1-5542-4cd9-ad35-bfe6ab070e18.png)

defaultSettings.ts的这里用了小写的`#1890ff`，

**Comment by sendya** [comment]
update `@ant-design-vue/pro-layout@1.0.11`
