### ISSUE TITLE
左侧菜单三级菜单无法打开

### ISSUE THREAD

**Issue by yuanyayi** [vueComponent/ant-design-vue-pro#1271]
**Describe the bug （描述 Bug）**
直接下载了master分支当前代码，在本地安装打开。
点击左侧菜单，列表页，搜索列表。菜单会收缩起来，无法显示搜索列表项下一级的菜单。

**Expected behavior（你期待的是什么?）**
正常打开菜单

**Comment by sendya** [comment]
升级到 `@ant-design-vue/pro-layout@1.0.10`
