### ISSUE TITLE
antd pro vue  移动端点击菜单侧边栏如何缩回？

### ISSUE THREAD

**Issue by jammyChan91** [vueComponent/ant-design-vue-pro#1272]
**Question （问题描述）**
How to use component `s-table` paging
"@ant-design-vue/pro-layout": "^1.0.7",
移动端如何监听菜单点击事件，当只有一级菜单时，选中且被点击后，菜单侧边栏自动折叠

**Describe the solution you'd like （你期待的是什么？）**
获取菜单点击事件或者点击侧边栏菜单，自动缩回
**Additional context（附加信息）**

**Comment by sendya** [comment]
watch $route 发生变化时，将 this.collapsed 设置为 true 即可

**Comment by jammyChan91** [comment]
万分感谢，困扰很久了

**Comment by jammyChan91** [comment]
问题已解决
