### ISSUE TITLE
我希望从一个列表页跳转到详情页，如何才能保持左侧菜单不变呢？

### ISSUE THREAD

**Issue by tu6ge** [vueComponent/ant-design-vue-pro#1273]
**Question （问题描述）**
请原谅我使用中文，我在项目中，在做一个订单列表页和详情页，希望左侧菜单都保持在“订单列表”这个菜单，
我使用的是后台添加菜单的功能，我查阅了文档，以及相关的源码，没有找到相关的信息

**Describe the solution you'd like （你期待的是什么？）**
如上所述

**Additional context（附加信息）**
无

**Comment by tu6ge** [comment]
补充一下，我的表单信息
![image](https://user-images.githubusercontent.com/4115242/143524194-aef8679a-7434-44f0-867a-f75d79a798dc.png)

所属上级菜单信息
![image](https://user-images.githubusercontent.com/4115242/143524363-fd4dcc90-853e-4344-a5a5-bb7c330ac39b.png)

# 备注（方便复制）

- 订单详情 
- order-detail
- oms/detail/index
- /oms/factory/detail

**Comment by sendya** [comment]
详情页面的路由 meta 配置为 hideInMenu: true
上级菜单 meta 配置 hideChildrenInMenu: true

**Comment by tu6ge** [comment]
嗨 @sendya , 我根据你说的进行了设置，发现问题如下：
- 进入详情页后，需要在列表页中加上 `route-view` 标签，才能显示详情页的内容，同时显示出来了列表页的内容
- 进入详情页后，左侧菜单的“订单”菜单未处于选中状态

**Comment by larry0442** [comment]
```js
{
  path: '/order',
  name: 'order',
  rediract: 'orderList', // 这里记得加，否则点击无法打开orderList
  component: BlankLayout, // 这里用一个空的壳儿<router-view />承载子路由,
  hideChildrenInMenu: true, // 不确定是否在meta中，先写在这里
  meta: { title: '订单列表'},
  children: [{
     path: '/order/list',
     name: 'orderList',
     component: () => import('xxxxxx'), // 这里引入订单列表的组件，
      hideInMenu: true, // 不确定你项目中是否写在meta中， 目的：隐藏这个菜单
     meta: {title: '订单列表'}
  }, {
    // 同理这里是详情
  }]
}

```

大兄弟，以上

**Comment by tu6ge** [comment]
感谢老哥分享，需要魔改 generator 函数

**Comment by rysinal** [comment]
> 感谢老哥分享，需要魔改 generator 函数

 @tu6ge 大佬，可以分享下如何修改的吗，我也遇到了类似问题 #1281 感激不尽

**Comment by tu6ge** [comment]
@rysinal 其实没什么特别的，就是在遍历到特定的路由的时候，做一些特殊的处理就可以了

```diff
/**
 * 格式化树形结构数据 生成 vue-router 层级路由表
 *
 * @param routerMap
 * @param parent
 * @returns {*}
 */
export const generator = (routerMap, parent) => {
  return routerMap.map(item => {
    // eslint-disable-next-line no-unused-vars
    const { title, show, hideChildren, hiddenHeaderContent, target, icon, link } = item.meta || {}
    
+    if(item.name=='order-factory'){
+      return generator_order(item, 'factory')
+    }else if(item.name=='order-retail'){
+      return generator_order(item, 'retail')
+    }else if(item.name=='custom-planing'){
+      // 定制方案
+      return generator_custom(item)
+    }
   ...
```
