### ISSUE TITLE
刷新如何实现 有没有大佬实现过

### ISSUE THREAD

**Issue by ChinaBygones** [vueComponent/ant-design-vue-pro#1274]
![F060B6EE010D49261D1783FC913690F8](https://user-images.githubusercontent.com/37260709/143672469-29637122-e76b-4e7d-8bdf-16226fa57769.jpg)

这个如何实现呀

**Comment by ZhangTianyi-1998** [comment]
大佬实现了么 弟弟想参考下(哭了)
