### ISSUE TITLE
求助!!!关于如何在vue-cli 3中使用jsx文件写法的配置

### ISSUE THREAD

**Issue by furylee** [vueComponent/ant-design-vue-pro#1277]
**Question （问题描述）**
我看ant-vue-pro像react 写jsx文件那样的写法,应该需要修改什么配置,我才能在vue-cli3中应用?

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
vue-cli 自带 JSX 解析，具体查询 cli.vuejs.org
