### ISSUE TITLE
modal显示、隐藏导致table 列插槽重新渲染

### ISSUE THREAD

**Issue by qiuxinlei** [vueComponent/ant-design-vue-pro#1279]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

沙盒地址：https://codesandbox.io/s/antdzhong-tableyu-modalwen-ti-2pepw?file=/src/components/HelloWorld.vue
1、点击编辑按钮
2、查看console,只要点击了编辑按钮，模态框显示，就会重新渲染table，changeTextFilter就会执行，

**Expected behavior（你期待的是什么?）**

希望帮忙解决下是什么问题，这个我试过element-ui中的table和dialog，不会出现上诉情况，我之前怀疑是有修改表格数据dataSource，但是我现在做的modal显示，根本没有使用到任何数据，也没有对任何数据值做变动

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/30764612/144996191-bb6b34a8-9a08-4464-97a3-03118fdc47a1.png)

**Additional context（附加信息）**

**Comment by qiuxinlei** [comment]
经过测试发现，不仅仅是table，他是会将整个页面的都直接重新渲染，不管filters写在哪

**Comment by sendya** [comment]
麻烦到组件库 github 仓库反馈  https://github.com/vueComponent/ant-design-vue ，这边只能处理 antdv pro 组件相关问题

**Comment by qiuxinlei** [comment]
OK


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月7日(周二) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vueComponent/ant-design-vue-pro] modal显示、隐藏导致table 列插槽重新渲染 (Issue #1279)




 
麻烦到组件库 github 仓库反馈  https://github.com/vueComponent/ant-design-vue ，这边只能处理 antdv pro 组件相关问题
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
