### ISSUE TITLE
FooterToolbar 底部工具栏，应该扣除左侧菜单的宽度

### ISSUE THREAD

**Issue by doitcore** [vueComponent/ant-design-vue-pro#128]
FooterToolbar 底部工具栏，应该扣除左侧菜单的宽度，extra部分被遮挡

**Comment by sendya** [comment]
好像是正常的

![20190313175036](https://user-images.githubusercontent.com/5404542/54269631-a9686180-45b8-11e9-9adb-4774979e2271.png)

**Comment by doitcore** [comment]
![image](https://user-images.githubusercontent.com/1124948/54275045-a1162380-45c4-11e9-8a0b-dd1f9e20054b.png)
