### ISSUE TITLE
升级3.0.3配置路由菜单后，访问页面报错Error: Cannot find module './XXX'

### ISSUE THREAD

**Issue by istudy-run** [vueComponent/ant-design-vue-pro#1284]
**Question （问题描述）**
升级到3.0.3后路由配置后，访问页面报错Error: Cannot find module './BaiduMap'，在3.0.2版本中是正常的，console无报错，路由正常。
![image](https://user-images.githubusercontent.com/59166694/145717789-897ad5de-4159-4351-b61d-0786bc3c1616.png)
**路由配置**
![image](https://user-images.githubusercontent.com/59166694/145717815-18eb64af-2303-4bbd-b330-1110b8711dd8.png)
**user.js**
![image](https://user-images.githubusercontent.com/59166694/145717820-0964aa67-6200-4b88-a65a-1387d31319b1.png)
**menu.js**
![image](https://user-images.githubusercontent.com/59166694/145717830-e053cf75-b70f-4312-a21c-87188d54da87.png)

**Comment by sendya** [comment]
提供一个复现仓库，否则自己加的业务 我没办法帮你判断问题在那

**Comment by istudy-run** [comment]
> 提供一个复现仓库，否则自己加的业务 我没办法帮你判断问题在那

没有其他的业务，我就加了个路由菜单，添加了一个页面，启动就访问不了，然后就报这个错

**Comment by istudy-run** [comment]
> 提供一个复现仓库，否则自己加的业务 我没办法帮你判断问题在那

写的所有代码都在图片上；下面是目录结构
![image](https://user-images.githubusercontent.com/59166694/145931699-20c309a4-d1e2-4160-999d-df24fa4d441e.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/145932964-3c459533-da36-497b-a778-f3651ec6a1cf.png)
你的数据写错了吧

`views/map/BiaduMap`

**Comment by sendya** [comment]
我还是建议你提供复现代码仓库

**Comment by istudy-run** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/145932964-3c459533-da36-497b-a778-f3651ec6a1cf.png) 你的数据写错了吧
> 
> `views/map/BiaduMap`

我是按照上面的例子写的啊，而且在3.0.2版本中都是正常的

**Comment by istudy-run** [comment]
> 我还是建议你提供复现代码仓库

你可以试一下加一个新路由，看看能不能跑；我下载3.0.3版本刚开始加一个路由页面就遇坑了，我也修改了【监控页（外部）】这个路由菜单，还是报一样的错误

**Comment by sendya** [comment]
你知道你用的哪个动态路由生成模式吗

**Comment by istudy-run** [comment]
> 你知道你用的哪个动态路由生成模式吗

不知道，我就按照官方的事例写的

**Comment by sendya** [comment]
那你降级到 3.0.2 吧

**Comment by istudy-run** [comment]
> 那你降级到 3.0.2 吧

3.0.3是有问题吗

**Comment by sendya** [comment]
没有

**Comment by sendya** [comment]
我没复现你的问题，可能是升级有什么不一样吧

**Comment by istudy-run** [comment]
> 我没复现你的问题，可能是升级有什么不一样吧
提供一个复现仓库吧

**Comment by istudy-run** [comment]
这是复现仓库地址，麻烦看看，谢谢
https://gitee.com/istudy-run/ant-design-vue-pro.git

**Comment by sendya** [comment]
建议先看一下这个文档  https://pro.antdv.com/docs/authority-management
![image](https://user-images.githubusercontent.com/5404542/145944088-73a3c166-6338-4c1b-ad22-c5cb0aef9611.png)

你使用的是 https://gitee.com/istudy-run/ant-design-vue-pro/blob/master/src/store/index.js#L11
![image](https://user-images.githubusercontent.com/5404542/145944168-75f369f4-4704-4188-b7a4-81b9c1302839.png)


方案1 使用  src/config/router.config.js 的静态路由进行过滤添加到当前路由系统
方案2 使用 后端返回的路由结构，并自动引入文件或找 src/router/generator-routers.js 下的 constantRouterComponents 值作为路由页面

你现在有两个选择
1. 在 https://gitee.com/istudy-run/ant-design-vue-pro/blob/master/src/router/generator-routers.js#L7 这个属性内添加你的页面KEY 和对应的 import 组件
2. 在 后端返回的菜单JSON中，配置正确的 KEY 和 组件路径，这会让动态路由构建方法自动帮你引入组件  https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/router/generator-routers.js#L125-L126
`component: constantRouterComponents[item.component || item.key] || (() => import(`@/views/${item.component}`)),`

**Comment by istudy-run** [comment]
> 建议先看一下这个文档 https://pro.antdv.com/docs/authority-management ![image](https://user-images.githubusercontent.com/5404542/145944088-73a3c166-6338-4c1b-ad22-c5cb0aef9611.png)
> 
> 你使用的是 https://gitee.com/istudy-run/ant-design-vue-pro/blob/master/src/store/index.js#L11 ![image](https://user-images.githubusercontent.com/5404542/145944168-75f369f4-4704-4188-b7a4-81b9c1302839.png)
> 
> 方案1 使用 src/config/router.config.js 的静态路由进行过滤添加到当前路由系统 方案2 使用 后端返回的路由结构，并自动引入文件或找 src/router/generator-routers.js 下的 constantRouterComponents 值作为路由页面
> 
> 你现在有两个选择
> 
> 1. 在 https://gitee.com/istudy-run/ant-design-vue-pro/blob/master/src/router/generator-routers.js#L7 这个属性内添加你的页面KEY 和对应的 import 组件
> 2. 在 后端返回的菜单JSON中，配置正确的 KEY 和 组件路径，这会让动态路由构建方法自动帮你引入组件  https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/router/generator-routers.js#L125-L126
>    `component: constantRouterComponents[item.component || item.key] || (() => import(`@/views/${item.component}`)),`

感谢您的解答
