### ISSUE TITLE
跳转外部链接并去除localhost前缀

### ISSUE THREAD

**Issue by junny1** [vueComponent/ant-design-vue-pro#1286]
使用prolayout跳转外部路径时按照官网的格式来写了
{
    path: 'https:/www.baidu.com',
    name: 'docs',
    meta: {
        title: '文档', 
        target: '_blank' // 打开到新窗口
   }
}
但是跳转的前缀还是会加上localhost变成http://localhost:3000/https:/www.baidu.com，请问要怎么解决

**Comment by junny1** [comment]
我现在是在Vue3 + ant-design-vue@3.0.0+vue-router4的基础上整合这个pro-layout的 会和这个有关系吗

**Comment by wangjing013** [comment]
> 使用prolayout跳转外部路径时按照官网的格式来写了 { path: 'https:/www.baidu.com', name: 'docs', meta: { title: '文档', target: '_blank' // 打开到新窗口 } } 但是跳转的前缀还是会加上localhost变成[http://localhost:3000/https:/www.baidu.com，请问要怎么解决](http://localhost:3000/https:/www.baidu.com%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%A6%81%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)

path 应该是 **https://www.baidu.com** ?

**Comment by junny1** [comment]
> > 使用prolayout跳转外部路径时按照官网的格式来写了 { path: 'https:/www.baidu.com', name: 'docs', meta: { title: '文档', target: '_blank' // 打开到新窗口 } } 但是跳转的前缀还是会加上localhost变成[http://localhost:3000/https:/www.baidu.com，请问要怎么解决](http://localhost:3000/https:/www.baidu.com%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%A6%81%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)
> 
> path 应该是 **https://www.baidu.com** ?

我菜单中配置的是https://www.baidu.com但是不知道它内部怎么给我解析就少了一个斜杆
![image](https://user-images.githubusercontent.com/44799620/145760267-22e3f253-ca6d-420b-85c1-82d2b8027837.png)

**Comment by wangjing013** [comment]
> > > 使用prolayout跳转外部路径时按照官网的格式来写了 { path: 'https:/www.baidu.com', name: 'docs', meta: { title: '文档', target: '_blank' // 打开到新窗口 } } 但是跳转的前缀还是会加上localhost变成[http://localhost:3000/https:/www.baidu.com，请问要怎么解决](http://localhost:3000/https:/www.baidu.com%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%A6%81%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)
> > 
> > 
> > path 应该是 **https://www.baidu.com** ?
> 
> 我菜单中配置的是[https://www.baidu.com但是不知道它内部怎么给我解析就少了一个斜杆](https://www.baidu.com%E4%BD%86%E6%98%AF%E4%B8%8D%E7%9F%A5%E9%81%93%E5%AE%83%E5%86%85%E9%83%A8%E6%80%8E%E4%B9%88%E7%BB%99%E6%88%91%E8%A7%A3%E6%9E%90%E5%B0%B1%E5%B0%91%E4%BA%86%E4%B8%80%E4%B8%AA%E6%96%9C%E6%9D%86) ![image](https://user-images.githubusercontent.com/44799620/145760267-22e3f253-ca6d-420b-85c1-82d2b8027837.png)

看下菜单逻辑应该不会更改数据内容，要不 debugger 一下

https://github.com/vueComponent/pro-layout/blob/next/src/SiderMenu/BaseMenu.tsx#L214

https://github.com/vueComponent/pro-layout/blob/ad17111ddeebdb04510bde6e7cca0dbbd1ca5c9a/src/utils/isUrl/index.ts#L6

**Comment by junny1** [comment]
还是不可以，我在想是不是我的Vue3 + ant-design-vue@3.0.0+vue-router4这个版本的原因导致不行

**Comment by sendya** [comment]
最新 pro-layout + ant-design-vue@2.2.8 可用

**Comment by junny1** [comment]
> 最新 pro-layout + ant-design-vue@2.2.8 可用

那我现在是ant-design-vue@3.0.0只能切换成2的吗。。。。

**Comment by junny1** [comment]
我已经将ant-design-vue版本切换至2.2.8 但是问题没有得到解决

**Comment by junny1** [comment]
我已经将ant-design-vue版本切换至2.2.8 但是问题没有得到解决
![image](https://user-images.githubusercontent.com/44799620/145930292-618c1661-06d2-41cc-aa38-9ebb28a53c0c.png)

**Comment by junny1** [comment]
> 最新 pro-layout + ant-design-vue@2.2.8 可用

我已经将ant-design-vue版本切换至2.2.8 但是问题没有得到解决
![image](https://user-images.githubusercontent.com/44799620/145930395-841cd598-fac7-45d6-baf1-6644d515a2e5.png)

**Comment by junny1** [comment]
问题解决了，原因是在pro-layout页面中使用了组件自带的方法，他会将我的路径改成错的
![image](https://user-images.githubusercontent.com/44799620/145949688-3390ce9f-1bef-4f6d-8735-3d1856726cd5.png)
重写这个方法就可以解决这个问题了，跟版本没有关系，改成如下方式问题解决
![image](https://user-images.githubusercontent.com/44799620/145949855-6e77394e-7a37-4501-950c-0f2876bdd443.png)
