### ISSUE TITLE
控制台报错 页面自动跳转404页面

### ISSUE THREAD

**Issue by junny1** [vueComponent/ant-design-vue-pro#1288]
跳转某个报错页面或者接口请求不到的情况，控制台报错后会跳转至404页面，比如如下错误，但不限于以下错误
![image](https://user-images.githubusercontent.com/44799620/146107421-81de4b90-ec12-4b0a-bcc2-cc8c5c57b13d.png)
能不能让其报错就只是控制台报错或者跳出提示信息，不要跳转404页面

**Comment by sendya** [comment]
不知道你怎么处理的，建议提供复现仓库
