### ISSUE TITLE
https://cdn.jsdelivr.net 无法访问

### ISSUE THREAD

**Issue by HeyRoy** [vueComponent/ant-design-vue-pro#1292]
**Question （问题描述）**
生产环境报错，jsdelivr无法访问。
![image](https://user-images.githubusercontent.com/7286313/146724340-1c93ae23-14e1-4f9b-942b-87e608f2acc6.png)

这个需要怎么修复呢？

**Comment by CNellie** [comment]
+1

**Comment by qixianc94** [comment]
vue.config.js 修改为其他可用的cdn地址

**Comment by HeyRoy** [comment]
解决办法
在vue.config.js中，将assetsCDN中的文件链接换成其他cdn的镜像文件，如字节跳动的cdn镜像
'https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue/2.6.10/vue.min.js',
'https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue-router/3.1.3/vue-router.min.js',
'https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/vuex/3.1.1/vuex.min.js',
'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/axios/0.19.0/axios.min.js'

**Comment by sendya** [comment]
1. jsdelivr 出故障，等其大陆服务修正。
2. 自行更换其他 CDN 资源
