### ISSUE TITLE
打包后cdn不能正常调用

### ISSUE THREAD

**Issue by Vsa1968911450** [vueComponent/ant-design-vue-pro#1294]
打包后放到nginx上，除ios以外都能正常，但是如果用ios登录发现GET https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js net::ERR_CONNECTION_RESET 导入的cdn报错，求问下大佬怎么解决这个问题

**Comment by Vsa1968911450** [comment]
![ea15482a63c99dd89a70a138d6a26dd](https://user-images.githubusercontent.com/58674709/146857333-a4a5da02-c5b1-4ae9-9c7a-ab49bc5eab11.png)

**Comment by sendya** [comment]
自行处理
https://github.com/vueComponent/ant-design-vue-pro/blob/master/vue.config.js#L22-L38
