### ISSUE TITLE
Bad user experience

### ISSUE THREAD

**Issue by tanjiuyusila** [vueComponent/ant-design-vue-pro#1295]
Is this website still maintained? The website could not be opened yesterday, and the preview cannot be logged in today

**Comment by sendya** [comment]
please use VPN to connect

**Comment by sendya** [comment]
the cdn.jsdelivr.net DNS record failed in china

**Comment by sendya** [comment]
I have no money to deploy a private CDN

**Comment by sendya** [comment]
you can clone project and npm serve to local preview.

**Comment by tanjiuyusila** [comment]
> It is not work,I still can not sign up an account.

**Comment by sendya** [comment]
The Backend API of this project is mock data, there is no real account registration, you can use `admin` to log-in to the dashboard
