### ISSUE TITLE
关于动态菜单排序问题

### ISSUE THREAD

**Issue by li1220** [vueComponent/ant-design-vue-pro#1297]
请问作者 动态生成的菜单可以排序吗 比如添加一个sort之类的 我看已经close的issue里面有提到过可以根据sort排序 但是我用的好像没有作用 请问作者用法

**Comment by sendya** [comment]
排序是你  菜单数据源 自行处理的，跟项目中的菜单没关系。你把 router.addRoute() 数据的顺序搞定就行了

**Comment by li1220** [comment]
好的 感谢  我试一下
