### ISSUE TITLE
启动后登陆无法跳转

### ISSUE THREAD

**Issue by chenjingyuan** [vueComponent/ant-design-vue-pro#13]
登录页，输入用户名/密码无法跳转

**Comment by sendya** [comment]
请提供控制台错误提示

**Comment by Fztomaster** [comment]
登陆页，输入用户名/密码，然后页面提示：错误，用户不存在，控制台报错：xhr.js?b50d:178 POST http://localhost:8080/api/auth/login 401 (Unauthorized)和vue-router.esm.js?8c4f:16 [vue-router] Route with name 'recover' does not exist

**Comment by sendya** [comment]
![20181129090742](https://user-images.githubusercontent.com/5404542/49192505-41e62780-f3b6-11e8-9511-ed3463d93c7f.png)

1. 照页面上提示的账号进行登陆。不要随意填写账号（ admin / admin ）。
2. 用户不存在 肯定不会让你跳转，如果这都跳转了，这项目基本上就没救了

**Comment by Fztomaster** [comment]
知道了，谢谢大佬！
