### ISSUE TITLE
建议在样式表中删除有版权的字体!

### ISSUE THREAD

**Issue by rumcoke** [vueComponent/ant-design-vue-pro#131]
刚刚看了下发现字体中明确的自定了"Microsoft YaHei"微软雅黑, 其他字体我不知道,但是"微软雅黑"是"方正"的一个有版权的字体, 在网页使用的话是需要付版权费用的, 非常建议删除!

**Comment by sendya** [comment]
我咨询过，无商业化不收费。而且你可以自己用在项目的时候删

**Comment by rumcoke** [comment]
我的意思是, 很多人使用 Antd 都可能为了商业用途, 但是很多人不知道这个方面的问题,非常容易出现无意的侵权行为, 所以还是建议官方直接删除, 需要的人自己添加, 或在代码或许可证文件中给予说明!
