### ISSUE TITLE
整体风格设置--暗黑模式, 如何能开启? 或如何 更改成黑色背景, 白字的模式(不是色弱模式)

### ISSUE THREAD

**Issue by 1300308284** [vueComponent/ant-design-vue-pro#1318]
**Question （问题描述）**
整体风格设置--暗黑模式, 如何能开启? 或如何 更改成黑色背景, 白字的模式(不是色弱模式)

**Describe the solution you'd like （你期待的是什么？）**
希望能暗黑模式开启的  解决方案

**Comment by sendya** [comment]
vue2 版本无法提供该功能，需要 antd vue 基础库支持，但仅 vue3+ 支持黑暗模式。
如有需要可以使用 [pro-layout](https://github.com/vueComponent/pro-components/tree/next/packages/pro-layout) 自己搭一个基于 vue3 的 pro
