### ISSUE TITLE
Dropdown 下拉菜单 鼠标右键触发，如果两次触发时间较短，会出现菜单消失的问题

### ISSUE THREAD

**Issue by yss0122** [vueComponent/ant-design-vue-pro#1319]
**Describe the bug （描述 Bug）**
Dropdown 下拉菜单 鼠标右键触发，如果两次触发时间较短，后面几次会出现菜单消失的问题

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

希望能尽快修改bug，谢谢

**Screenshots（截图）**

![c623978af66a22e41716aea698cf735](https://user-images.githubusercontent.com/74843005/160098718-d6e13bb4-9d57-4208-8326-93034564c1e7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
你发错仓库了，请提供复现并发到这个仓库 https://github.com/vueComponent/ant-design-vue
