### ISSUE TITLE
打开后再跳转页面，页面描述不变

### ISSUE THREAD

**Issue by siminx** [vueComponent/ant-design-vue-pro#132]
![image](https://user-images.githubusercontent.com/22373408/54486798-47fe0680-48c8-11e9-8adf-422b2b96e3ad.png)
![image](https://user-images.githubusercontent.com/22373408/54486801-50564180-48c8-11e9-91bd-136159ad97a0.png)
![image](https://user-images.githubusercontent.com/22373408/54486813-6237e480-48c8-11e9-8873-cfc63364914d.png)
![image](https://user-images.githubusercontent.com/22373408/54486814-69f78900-48c8-11e9-85fd-aaba1a56f6d3.png)

**Comment by sendya** [comment]
fixed https://github.com/sendya/ant-design-pro-vue/releases/tag/2.0.0-pre-release
