### ISSUE TITLE
Login 页面 Logo 无法正确加载

### ISSUE THREAD

**Issue by weifengze** [vueComponent/ant-design-vue-pro#1321]
**Question （问题描述）**
UserLayout.vue 文件里面的
 `<img src="~@/assets/logo.svg" class="logo" alt="logo">`
在页面上无法正确的显示 SVG 
![Snipaste_2022-04-02_11-05-34](https://user-images.githubusercontent.com/45350371/161363549-438896f1-f6e0-4858-bca6-0c86acd78b5f.png)

**Comment by sendya** [comment]
最新的 pr 已经处理
