### ISSUE TITLE
菜单文字长度能对齐吗 letter-spacing

### ISSUE THREAD

**Issue by Wjinlei** [vueComponent/ant-design-vue-pro#1323]
**Question （问题描述）**
Sider Menu 菜单文字能对齐吗？ 比如三个字的和四个字的对齐，我发现可以通过css属性，letter-spacing实现
但是我没有找到设置的办法，请问有什么好的办法吗？

**Describe the solution you'd like （你期待的是什么？）**
能够为菜单项设置id或者class

**Additional context（附加信息）**
或者其他解决办法

**Comment by sendya** [comment]
样式表直接写你需要的样式即可
