### ISSUE TITLE
请问有没有属性设置，父菜单只有1个子菜单的时候，隐藏父菜单，只显示子菜单

### ISSUE THREAD

**Issue by wou101771** [vueComponent/ant-design-vue-pro#1324]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
没有，vue3 版本可以直接自己处理菜单数据源，可以考虑用 vue3 版本 pro-layout
