### ISSUE TITLE
和springboot一起打包提示error Building for production...，但还是打包成功了

### ISSUE THREAD

**Issue by ganjiadong** [vueComponent/ant-design-vue-pro#1329]
![image](https://user-images.githubusercontent.com/25759446/165203736-25be6e78-ef63-4137-9d4c-b3d3511a86b2.png)
请问这个是哪的问题

**Comment by sendya** [comment]
不知道呀。我啥信息都没有 只从你一个截图无法得知问题的

**Comment by ganjiadong** [comment]
> 

我把修改好的项目和springboot工程mvn clean package -Dmaven.test.skip=true
一起打包  打包过程中这里有报ERROR 但是还是成功打包了 不知道会有什么问题

**Comment by labike** [comment]
部署上去看看报错日志，猜一下应该是跑不起来
