### ISSUE TITLE
请问下菜单高亮问题

### ISSUE THREAD

**Issue by hogger0** [vueComponent/ant-design-vue-pro#1331]
请问下在在列表页去详情页面的时候，跳转到新的路由地址了。因为详情页面不是一个菜单，所以详情页面不会渲染到左侧栏的，这个时候原来列表页的菜单栏高亮就丢失了，而且菜单就折叠起来了。怎么让其显示高亮和打开？。
![image](https://user-images.githubusercontent.com/6472032/167256137-9a55c1c5-c85c-40f7-ae58-994b52c5a616.png)

**Comment by sendya** [comment]
参考 accounts 页面路由？

**Comment by hogger0** [comment]
> 参考 accounts 页面路由？

具体逻辑有点没搞懂。能否提示下，按照这个标签来写的，还是没生效

![image](https://user-images.githubusercontent.com/6472032/167369397-95fe71ed-c720-42a0-a32a-f044190ef679.png)
![image](https://user-images.githubusercontent.com/6472032/167369439-ad85efda-b832-40c5-a019-0d73a1d0fea7.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/config/router.config.js#L219-L243
