### ISSUE TITLE
首次点击左侧一级菜单直接打开页面时，页面加载了但左侧菜单未高亮选中

### ISSUE THREAD

**Issue by HyalineSoft** [vueComponent/ant-design-vue-pro#1337]
**Question （问题描述）**
问题：点击一级菜单打开页面，左侧菜单无法高亮选中。
我的左侧菜单虽然是一级菜单，但必须有子页面的互相跳转（如新增、编辑页……），因此我将列表查询组件也作为子路由。但就是因为这种情况，首次点击一级菜单打开页面时，左侧菜单未选中。
演示：以下演示两种情况。
![image](https://user-images.githubusercontent.com/39329639/168944194-ff31c876-ac43-4d5f-a567-7f4f46d345ee.png)

情况一：没有子路由的一级菜单，首次点击左侧菜单可高亮选中。
![image](https://user-images.githubusercontent.com/39329639/168945490-0ab6cc97-a6e2-4039-be9f-ab6dd970fe6d.png)

情况二：将一级菜单redirect到子路由组件时，首次点击左侧菜单无高亮选中。
![image](https://user-images.githubusercontent.com/39329639/168945561-aaba069d-e193-4f24-b169-daad8ec4d6b1.png)

**Describe the solution you'd like （你期待的是什么？）**
如何在保证有子路由的情况下，让一级菜单访问页面能保持左侧菜单高亮选中。

**Additional context（附加信息）**
无。

**Comment by sendya** [comment]
hideChildrenInMenu: true, 需要搭配子级菜单 meta 属性的 hidden: true

**Comment by HyalineSoft** [comment]
> hideChildrenInMenu: true, 需要搭配子级菜单 meta 属性的 hidden: true

谢谢，完美解决了。
