### ISSUE TITLE
jsdelivr的cdn被墙了，建议更换下cdn

### ISSUE THREAD

**Issue by chen0610** [vueComponent/ant-design-vue-pro#1338]
建议更换成bootcdn.cn或者其他的

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/commit/24fe79d79285f3c87becb3672a8dec96de4fae8f

参考 commit 自行修改

**Comment by sendya** [comment]
已经从源码中去除 cdn
