### ISSUE TITLE
3.0.3 删除菜单不生效（添加不生效，以为是姿势不对，结果删除也不行为，切换3.0.2后生效）

### ISSUE THREAD

**Issue by iimik** [vueComponent/ant-design-vue-pro#1339]
**Describe the bug （描述 Bug）**

3.0.3 删除菜单不生效（添加不生效，以为是姿势不对，结果删除也不行为，切换3.0.2后生效）

**To Reproduce （重现步骤）**

1. 下载3.0.3的版本
2. 修改`router.config.js`文件，删除其中的某个菜单项
3. 运行服务，菜单还在

**Comment by sendya** [comment]
确定一下用的 动态菜单 方式。
动态拼接从后端发来的菜单是不经过 router.config.js ，仅前端过滤模式可从 router.config.js 操作

https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/store/index.js#L7-L11
