### ISSUE TITLE
移动端菜单栏不能顶部显示

### ISSUE THREAD

**Issue by Alwaysherewithme** [vueComponent/ant-design-vue-pro#1342]
**Describe the bug （描述 Bug）**

为了在移动端把菜单放到顶部，我用Chrome devtool改为移动端设备浏览页面，配置栏里修改导航模式，但并不起作用；
然后我在 src/layouts/BasicLayout.vue 设置了监听isMobile状态为true时，让菜单顶部显示：
```
this.$watch('isMobile', () => {
      this.$store.commit(TOGGLE_MOBILE_TYPE, this.isMobile)
      if (this.isMobile) {
        this.$set(this.settings, 'layout', 'topmenu')
      } else {
        this.$set(this.settings, 'layout', defaultSettings.layout)   // 'sidemenu'
      }
}
```
用Chrome devtool改为移动端设备浏览页面，两个状态变化是正确的：`isMobile: true`, `layout: "topmenu"`，但菜单还是在左侧！
奇怪的是：在Vue Devtools里修改`isMobile: false`，菜单居然就移到顶部了！
感觉这个逻辑有问题，应该是`isMobile: true`，`layout: "topMenu"`时，就应该显示顶部菜单。

**To Reproduce （重现步骤）**
1. Chrome移动设备显示下，点击页面“配置栏”里修改导航模式为顶部显示
2. 修改  src/layouts/BasicLayout.vue 代码，然后在移动显示下观察
3. 具体步骤如问题描述部分

**Expected behavior（你期待的是什么?）**
在移动端设备上，菜单栏能够顶部显示。

**Screenshots（截图）**
![andv-pro-menue-issue-1](https://user-images.githubusercontent.com/19687687/169862728-e8474391-ffb5-40e2-821f-b28a5815611a.png)

![andv-pro-menue-issue-2](https://user-images.githubusercontent.com/19687687/169858722-afa0a149-68cc-4768-999b-7febb5d9c732.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04.4 LTS
 - Browser: Chrome 100.0
 - ant-design-vue: 1.7.8
 - vue: 2.6.14
 - vue-antd-pro: 3.0.0

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
移动端没有顶部菜单模式的设计稿，而且顶部位置太小了，根本放不下。
