### ISSUE TITLE
多标签模式，欲实现预览网站的效果

### ISSUE THREAD

**Issue by Boyka-SS** [vueComponent/ant-design-vue-pro#1348]
**Question （问题描述）**

参考issues成功开启多标签模式，但是我想要预览网站那种，操作menu并不显示，请问，需要怎么操作，才可以实现预览网站的多标签页面那种效果

**Describe the solution you'd like （你期待的是什么？）**

预览网站的效果

**Additional context（附加信息）**

暂无

**Comment by sendya** [comment]
https://preview.pro.antdv.com/

vue2 无提供

**Comment by Boyka-SS** [comment]
方便把实现的，发个链接看看吗，我想看看怎么实现
我看的是这个：
https://store.antdv.com/pro/preview/workplace

**Comment by sendya** [comment]
> 方便把实现的，发个链接看看吗，我想看看怎么实现 我看的是这个： https://store.antdv.com/pro/preview/workplace

不方便

**Comment by Boyka-SS** [comment]
nb




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 晚上7:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vueComponent/ant-design-vue-pro] 多标签模式，欲实现预览网站的效果 (Issue #1348)





  
方便把实现的，发个链接看看吗，我想看看怎么实现 我看的是这个： https://store.antdv.com/pro/preview/workplace
  
不方便
