### ISSUE TITLE
 预览网站打不开呀

### ISSUE THREAD

**Issue by fxmes** [vueComponent/ant-design-vue-pro#1350]
预览网站打不开呀

https://preview.pro.antdv.com/
打不开，

**Comment by sendya** [comment]
正常的哦，检查一下你的网络？

**Comment by meteortears** [comment]
> 正常的哦，检查一下你的网络？

楼上那位兄弟没说错，只是描述不完整。
是能打开，但是cdn资源无法获取，
导致没法正常预览。

用魔法就可以。

**Comment by fxmes** [comment]
这个不行呀，不会科学上网呀，这不是国内用户就用不了了呀

**Comment by fxmes** [comment]
应该是这个打不开https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js

**Comment by sendya** [comment]
已处理
