### ISSUE TITLE
能不能把webpack换成vite

### ISSUE THREAD

**Issue by coolicer** [vueComponent/ant-design-vue-pro#1351]
**Question （问题描述）**
项目大了，开发/打包时间都要很久
**Describe the solution you'd like （你期待的是什么？）**
vite应该能解决开发的问题

**Comment by sendya** [comment]
不能哦，用到的依赖库太多都是 require 的。无法使用 esm 加载器。  你可以自己先尝试

**Comment by coolicer** [comment]
@sendya 我找到了一个可用的，谢谢

**Comment by clddup** [comment]
@coolicer  请问一下你是用什么转的

**Comment by coolicer** [comment]
@clddup 没有办法，有一个别人改的，那个我试了用pnpm才可以。然后你慢慢把旧代码搬回去，还有有点工作量。所以我选择不改
