### ISSUE TITLE
使用pro-layout/SettingDrawer必须使用国际化？

### ISSUE THREAD

**Issue by LuckLin520** [vueComponent/ant-design-vue-pro#1356]
**Describe the bug （描述 Bug）**
项目去掉了国际化，但是领导要求生产环境使用SettingDrawer改变主题风格，这个组件使用后国际化有问题，如图：
![image](https://user-images.githubusercontent.com/33896086/176144139-293952c9-d7ae-43b6-bd8d-ca9a1952911f.png)

**Expected behavior（你期待的是什么?）**
可以单独设置SettingDrawer组件的默认语言或者取消国际化

**Comment by sendya** [comment]
你弄一个对象，把这几个翻译key翻译成中文，这个组件的 i18n 函数传递的 key 取你翻译对象的值。就可以只根据你的业务翻译来。

**Comment by LuckLin520** [comment]
> 你弄一个对象，把这几个翻译密钥翻译成中文，这个组件的i18n函数传递的密钥取你翻译对象的价值。就可以只根据你的业务翻译来。

勉强接受这个解决方案吧，至少不依赖i18n库了
