### ISSUE TITLE
请问一下有主页的代码吗？

### ISSUE THREAD

**Issue by ilovey2009** [vueComponent/ant-design-vue-pro#136]

**Comment by sendya** [comment]
主页代码？ 是说文档库吗？

**Comment by ilovey2009** [comment]
> 主页代码？是说文档库吗？
https://pro.loacg.com/   这个界面的，感觉蛮好，想知道怎么写的？

**Comment by sendya** [comment]
https://github.com/ant-motion/ant-design-pro-landing-page
