### ISSUE TITLE
顶部菜单状态下，菜单过多时出现的问题

### ISSUE THREAD

**Issue by nextdooroldwang** [vueComponent/ant-design-vue-pro#137]
antd-pro是会有一个更多的功能
![image](https://user-images.githubusercontent.com/18671240/54653674-66e1e000-4af6-11e9-84e3-04c9c179b84e.png)
请问是目前还没有实现这里的功能么
![image](https://user-images.githubusercontent.com/18671240/54653754-b4f6e380-4af6-11e9-9113-92961d856678.png)
咱们菜单过多时会一直往后挤

**Comment by sendya** [comment]
有实现，请自行查看官方 demo

![image](https://user-images.githubusercontent.com/5404542/54653796-de177400-4af6-11e9-83a3-da3359655a09.png)

**Comment by nextdooroldwang** [comment]
@sendya 我仔细测试了一下，屏幕可视区域大于1200px时，刷新页面是无法触发折叠菜单的。

**Comment by sendya** [comment]
> @sendya 我仔细测试了一下，屏幕可视区域大于1200px时，刷新页面是无法触发折叠菜单的。

可视区大于 1200px 时，菜单宽度不足于触发折叠

**Comment by nextdooroldwang** [comment]
> > @sendya 我仔细测试了一下，屏幕可视区域大于1200px时，刷新页面是无法触发折叠菜单的。
> 
> 可视区大于 1200px 时，菜单宽度不足于触发折叠

当你再路由中添加几个新的路由，宽度就超过了

**Comment by sendya** [comment]
你可以提前描述清楚问题的

**Comment by sendya** [comment]
另外 你可以自己控制一下菜单的宽度，就会自动隐藏超出的菜单项

**Comment by kokoroli** [comment]
fixed ref b29f9c4
