### ISSUE TITLE
 <a-cascader> - did you register the component correctly?

### ISSUE THREAD

**Issue by QingHuanYuJiu** [vueComponent/ant-design-vue-pro#1378]
**Describe the bug （描述 Bug）**
提示组件未注册

**To Reproduce （重现步骤）**

1. git clone https://github.com/vueComponent/ant-design-vue-pro.git
2. 打开项目 npm i
3. https://1x.antdv.com/components/cascader-cn/ 
4.![image](https://user-images.githubusercontent.com/38201850/183301054-ff065b7e-e38b-4502-ad37-ce9c17c88ad8.png)
5.随便复制到一个页面 打开就会提示  <a-cascader> - did you register the component correctly?

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://pro.antdv.com/docs/faq#%E4%BD%BF%E7%94%A8%E7%BB%84%E4%BB%B6%E9%81%87%E5%88%B0%E6%9C%AA%E6%B3%A8%E5%86%8C(did%20you%20register%E2%80%A6)

**Comment by sendya** [comment]
不好意思最近比较忙 不怎么看issue
