### ISSUE TITLE
Action权限指令判断不正确

### ISSUE THREAD

**Issue by cjzZZZzzz** [vueComponent/ant-design-vue-pro#1382]
**Describe the bug （描述 Bug）**
[https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/core/directives/action.js](url)
22行 
```
const elVal = vnode.context.$route.meta.permission
const permissionId = elVal instanceof String && [elVal] || elVal
```

instanceof这里没法正常判断是否为字符串,导致后面的includes调用的是字符串的函数

**Comment by sendya** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/5404542/186311906-9372a5a6-e2d7-4e18-a133-1ae5d88c9f7a.png">

应该不至于吧，因为这个用了几年了。
是不是可能我这用 permission ，都是给的数组，所以没进到 且 逻辑。
你能提供你的 route meta 数据源吗

**Comment by cjzZZZzzz** [comment]
![image](https://user-images.githubusercontent.com/25816088/186354401-58c6ec6c-be4f-4899-a5d0-baea8751db92.png)

**Comment by cjzZZZzzz** [comment]
![image](https://user-images.githubusercontent.com/25816088/186354639-c3e77a0f-74d3-4d06-8e11-a7d8e1f9d203.png)

**Comment by cjzZZZzzz** [comment]
😂不是浏览器不支持instanceof

**Comment by sendya** [comment]
已处理
