### ISSUE TITLE
是否考虑引入umi ？

### ISSUE THREAD

**Issue by lovesL** [vueComponent/ant-design-vue-pro#1384]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sendya** [comment]
我这边是觉得 vue 生态最好用的还是 vue-cli 官方套件。不知你推荐 umi 的从哪些角度考量？

**Comment by lovesL** [comment]
我之前一直在写react 用的都是阿里他们那套 antd pro+ProComponent,就是觉得更完善一些吧 用着顺手文档也很清晰。  umi也是支持vue的,并且他们的是蚂蚁内部维护，可以省些事吧。😊
