### ISSUE TITLE
不生效的静态路由

### ISSUE THREAD

**Issue by wymli** [vueComponent/ant-design-vue-pro#1385]
**Describe the bug （描述 Bug）**

路由问题，clone最新的代码，即使https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/store/index.js#L9 是设置的静态路由，但是yarn run serve跑起来可以在console看到最终还是发请求到mock拿到的动态路由（可以明确的看到这条log https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/router/generator-routers.js#L88）

表现上，全量删除https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/config/router.config.js#L17 这些配置不影响页面的路由，删除mock里的配置影响路由

**To Reproduce （重现步骤）**

clone最新代码即可

**Expected behavior（你期待的是什么?）**
使用静态路由

**Comment by atorber** [comment]
+1

**Comment by wymli** [comment]
切到tag v3分支可以解决问题

**Comment by sendya** [comment]
已修正，现在可以直接在 store/index.js 中更换路由模式，自动生效静态(前端过滤路由表)或 动态(后端生成路由表)
