### ISSUE TITLE
最新版pro-vue 1.3.1在ie11中不能渲染表格数据

### ISSUE THREAD

**Issue by nofound** [vueComponent/ant-design-vue-pro#139]
window10专业版 1803
ant-design-pro-vue 1.3.1,
ie浏览器11.648
在列表页中不能渲染数据到表格，一直是loading动画。
![image](https://user-images.githubusercontent.com/16830662/54655899-8e3cab00-4afe-11e9-89a3-ec827f4d97a6.png)

打开开发者工具查看，获取到数据了。
![image](https://user-images.githubusercontent.com/16830662/54655878-79f8ae00-4afe-11e9-8950-e7e5854eb8a5.png)
您有时间的话可以看看。
非常棒的项目(๑•̀ㅂ•́)و✧

**Comment by sendya** [comment]
**polyfill** 
regression bug, ref https://github.com/sendya/ant-design-pro-vue/commit/e392885985f9745033f95cad381310eca467567b
