### ISSUE TITLE
菜单路由更新报错Duplicate named routes (router.addRoute)

### ISSUE THREAD

**Issue by shuimupj** [vueComponent/ant-design-vue-pro#1399]
**Question （问题描述）**
在当前路由菜单及权限的基础上增加了一个应用管理功能，不同的应用绑定不同的路由，切换应用时会刷新路由菜单
现在使用router.addRoute更新路由菜单会报错[vue-router] Duplicate named routes definition:，但不会影响功能
![Snipaste_2022-10-17_16-16-48](https://user-images.githubusercontent.com/20787055/196125668-7d1fdb17-b693-49d1-bd3b-fe4726ccad9b.png)

**Describe the solution you'd like （你期待的是什么？）**
请问这是什么原因导致？及如何修复？谢谢！！！

**Comment by sendya** [comment]
切换应用时，把老的路由清空或初始化，然后在 addRoute 就不会提示重复路由
