### ISSUE TITLE
大佬项目还维护吗 隔壁的elemen-plus垃圾的要死  如果还维护我们就用你们的啦

### ISSUE THREAD

**Issue by qianduanlajigou** [vueComponent/ant-design-vue-pro#1425]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by tangjinzhou** [comment]
开源版本 pro 是不维护的，只有收费版了，你可以用  https://github.com/vbenjs/vue-vben-admin
另外 ant-design-vue 也有不同程度的问题，欢迎 pr

**Comment by HMYang33** [comment]
elemen-plus并不垃圾，是你垃圾。你没给任何人一分钱却坐享其成，自己代码没写好，还公开责怪免费给你提供基础设施的组织，三秒不回复就暴怒，恶语相向。如果你真的很急着用，应该是深入基建的底层代码，帮助整个开源社区发现bug，或者你临时修复bug，自己用。就算不会修，也应该对大佬有一个谦逊好学的态度和做人基本的素质。

ElementPlus确实是中国人主要在开发，但不乏也有来自全世界各地的贡献，所以当然有必要用英语交流。

你想要更好的服务就付钱，你想要免费的东西就给我受着，和领导有冲突就找领导解决。

另外，我使用2023年的ElementPlus并没有发现任何你说的那些怪异的bug，纯纯就是你能力差，写了一堆糟糕的代码
