### ISSUE TITLE
请问下，sider menu 有没有提供 顶部主菜单 配合左侧次级菜单的三级菜单显示的解决方案呢

### ISSUE THREAD

**Issue by firefishREAL** [vueComponent/ant-design-vue-pro#144]
如题，不知道有没有时间，能否提供下思路呢

**Comment by sendya** [comment]
没有，项目的基本结构和功能均同步了 React Ant Design Pro，官方没有，这边就没有。 请自行实现。

**Comment by sendya** [comment]
个人中心 的菜单类似，可以参考

**Comment by xiaoweibaniu** [comment]
![image](https://user-images.githubusercontent.com/13979614/61168402-57444680-a580-11e9-9bad-3bc2c649463f.png)
因为文档的原因以为这里是解决配置示例，尝试了各种配置都未能实现。建议优化这里的文档说明，避免误导。谢谢作者提供的项目。

**Comment by sendya** [comment]
@xiaoweibaniu 文档提供了解决思路，并不会什么都帮你们写好，如果帮你们写好，还领工资上班干什么？ 

另外，参考 **个人设置** 就是有次级菜单的
