### ISSUE TITLE
多页签切换后页面初始化的问题

### ISSUE THREAD

**Issue by orilla-cn** [vueComponent/ant-design-vue-pro#149]
多页签面模式中，在其中一个页签表单中输入数据并切换至其他页签后切回，数据会消失，页面初始化。

**Comment by sendya** [comment]
你是说 preview 上，还是你自己实际使用会这样？

**Comment by orilla-cn** [comment]
preview 和自己使用都会出现。

**Comment by sendya** [comment]
自己处理一下就好了 

https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/layouts/RouteView.vue#L23

**Comment by orilla-cn** [comment]
刚试了一下 preview ，进入后直接打开“基础表单”输入标题后切回工作台再切回数据不会消失，但继续打开第三个页签后切回，页面就刷新了。

**Comment by sendya** [comment]
而且我不推荐使用这个功能，这不符合单页应用的风格

**Comment by orilla-cn** [comment]
我看了这个，也试了，keepalive会导致页签关闭后再次打开数据不刷新的问题，不知道有没有更好的解决办法。

**Comment by orilla-cn** [comment]
好的吧，那谢谢了。。。

**Comment by sendya** [comment]
没有。解决办法是不用多标签。何况全部都 keep-alive 指不定内存泄漏呢。
不过 keep-alive 可用 activated，deactivated 周期去处理
