### ISSUE TITLE
大佬 问一下这个问题知道什么原因吗  还有该怎么解决呢  谢谢了

### ISSUE THREAD

**Issue by chenyjyoucan** [vueComponent/ant-design-vue-pro#15]
![WechatIMG418](https://user-images.githubusercontent.com/23470635/58762485-0570cf80-8583-11e9-9fd8-375215f2bea6.jpeg)

**Comment by tangjinzhou** [comment]
最好给个仓库链接，不然不好定位

**Comment by chenyjyoucan** [comment]
https://github.com/chenyjyoucan/ant-design-vue
你有空看一下吧 感谢了老师

**Comment by lpeihan** [comment]
应该是你把`.eslintrc.js` 文件给删了，重新加上去就可以了

**Comment by chenyjyoucan** [comment]
好的，一会儿我试下，感谢


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lpeihan <notifications@github.com>
发送时间: 2019年6月5日 09:20
收件人: vueComponent/ant-design-vue-pro <ant-design-vue-pro@noreply.github.com>
抄送: Giacomo <184913704@qq.com>, Author <author@noreply.github.com>
主题: 回复：[vueComponent/ant-design-vue-pro] 大佬 问一下这个问题知道什么原因吗  还有该怎么解决呢  谢谢了 (#15)

**Comment by chenyjyoucan** [comment]
对了，这个文件开始是没有的，我第二次启动项目的时候报错然后我才加上的，是这个原因吗


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lpeihan <notifications@github.com>
发送时间: 2019年6月5日 09:20
收件人: vueComponent/ant-design-vue-pro <ant-design-vue-pro@noreply.github.com>
抄送: Giacomo <184913704@qq.com>, Author <author@noreply.github.com>
主题: 回复：[vueComponent/ant-design-vue-pro] 大佬 问一下这个问题知道什么原因吗  还有该怎么解决呢  谢谢了 (#15)




应该是你把.eslintrc.js 文件给删了，重新加上去就可以了

**Comment by lpeihan** [comment]
你可以把该项目的 `.eslintrc.js `文件复制到你的项目。也可以用 `vue-cli3`重新生成一个项目，把`src`目录替换一下就好了。

**Comment by chenyjyoucan** [comment]
我就是在这个项目复制过来的，我重新弄一下吧，谢谢了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lpeihan <notifications@github.com>
发送时间: 2019年6月5日 09:33
收件人: vueComponent/ant-design-vue-pro <ant-design-vue-pro@noreply.github.com>
抄送: Giacomo <184913704@qq.com>, Author <author@noreply.github.com>
主题: 回复：[vueComponent/ant-design-vue-pro] 大佬 问一下这个问题知道什么原因吗  还有该怎么解决呢  谢谢了 (#15)

**Comment by tangjinzhou** [comment]
复制的时候注意，有些文件默认隐藏了的 如 点 开头的文件，可能会有遗失

**Comment by chenyjyoucan** [comment]
嗯嗯，重新建了项目添加了这个文件以后就没问题了，可能是之前配置出了问题，谢谢啦，看您课程又学习不少知识。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: tangjinzhou <notifications@github.com>
发送时间: 2019年6月5日 21:57
收件人: vueComponent/ant-design-vue-pro <ant-design-vue-pro@noreply.github.com>
抄送: Giacomo <184913704@qq.com>, Author <author@noreply.github.com>
主题: 回复：[vueComponent/ant-design-vue-pro] 大佬 问一下这个问题知道什么原因吗  还有该怎么解决呢  谢谢了 (#15)
