### ISSUE TITLE
iconfont.cn上的图标怎么加入

### ISSUE THREAD

**Issue by hanxiao123** [vueComponent/ant-design-vue-pro#150]
网上有些教程是针对ant的，antvue下也有一些，但不想修改node_modules的内容。
有办法通过引用css来iconfont加入到a-icon中吗？我尝试加入到index.less,main.js,index.js都没有成功，哪位先行者给指点一下？

**Comment by sendya** [comment]
a-icon 已经从 font icon 换成了 svg icon
你可以直接使用 `<a-icon :component={你的svg component} />` 来引入 icon

或者 https://vue.ant.design/components/icon-cn/#components-icon-demo-custom-icon
或者 https://vue.ant.design/components/icon/#Custom-Font-Icon
