### ISSUE TITLE
如何在没有互联网的环境使用

### ISSUE THREAD

**Issue by weightbomb** [vueComponent/ant-design-vue-pro#152]
在src/components/tools/setting.js使用了互联网的less.min.js， 没有互联网就会出现问题。请问如何能够在没有互联网的环境中使用？

**Comment by sendya** [comment]
那你去掉就好了

**Comment by sendya** [comment]
这个不是核心功能，不影响正常使用。只是少了在线换肤的功能而已。

**Comment by sendya** [comment]
何况编译出来的项目本身就不会带这个

**Comment by weightbomb** [comment]
node_modules里有less组件的代码，有办法直接用吗，不用再去外部下载。

**Comment by sendya** [comment]
> node_modules里有less组件的代码，有办法直接用吗，不用再去外部下载。

不行，不是同一个东西
