### ISSUE TITLE
演示页面的菜单路由被更新了吗

### ISSUE THREAD

**Issue by Xiaohantx** [vueComponent/ant-design-vue-pro#153]
https://preview.pro.loacg.com

我记得以前项目演示左边菜单有搜索，用户列表之类的内容，现在再去看的时候好像没有了

**Comment by sendya** [comment]
同步 React Ant Design Pro 结构。 因为很多用户反馈说各种列表和UI跟他们自己的业务对不上，已经去除业务相关布局例子
