### ISSUE TITLE
下滑时隐藏Header失效

### ISSUE THREAD

**Issue by Coffeeran** [vueComponent/ant-design-vue-pro#155]
*Mac OS Mojave 10.14
*dev/v2
*勾选下滑时隐藏 Header之后下滑并不能隐藏
在搜索列表（应用）页面中选择40/页分页测试

**Comment by sendya** [comment]
什么浏览器？

**Comment by Coffeeran** [comment]
chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by Coffeeran** [comment]
> 什么浏览器？

Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by Coffeeran** [comment]
感谢修复，但是新代码101行：document.body.removeEventListener('scrool', this.handScroll) 中有拼写错误？

**Comment by sendya** [comment]
fixed ref ff3b309e90aff588ce7fd581108d7168c1d877f6
