### ISSUE TITLE
和antd design pro比速度是不是慢了一丢丢？

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#156]
点击左侧菜单栏，右侧出现内容，是不是比antd design pro react 慢了一丢丢？感觉没有react antd design pro更流畅一些。 这是什么原因呢？纯属闲言碎语，只希望越来越好。

**Comment by sendya** [comment]
完全没感觉到，如果你要反馈问题，可以提供使用环境

**Comment by java8site** [comment]
我就是都在浏览器上访问的呀。 然后多次点击， 感觉流畅度差了一点点。

**Comment by sendya** [comment]
不知道哪里影响的，可能是 keep-alive 吧，欢迎 PR 优化
