### ISSUE TITLE
打包之后，正常到登陆界面了。然后会跳转。。

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#157]
打包之后，打开index.html ,能正常到登陆界面 ， 1s之后自动跳转
`file:///F:/user/login?redirect=%2FF%3A%2Fvue%2Fant-design-pro-vue-master%2Fdist%2Findex.html`   这是请求代理什么没生效吗？

**Comment by sendya** [comment]
https://pro.loacg.com/docs/deploy

**Comment by wuyuanwei** [comment]
> 打包之后，打开index.html ,能正常到登陆界面 ， 1s之后自动跳转
> `file:///F:/user/login?redirect=%2FF%3A%2Fvue%2Fant-design-pro-vue-master%2Fdist%2Findex.html` 这是请求代理什么没生效吗？
