### ISSUE TITLE
流式布局异常：多标签、头部右侧组件

### ISSUE THREAD

**Issue by nickevin** [vueComponent/ant-design-vue-pro#160]
[问题截图](https://imgchr.com/i/ADuYn0)
[正常截图](https://imgchr.com/i/AD3rge)

另外，ant design pro 貌似把 多标签的 feature 给去掉了

**Comment by nickevin** [comment]
另外，ant design pro 貌似把 多标签的 feature 给去掉了

**Comment by sendya** [comment]
多标签 ant design pro 打从一开始就没多标签，哪来的 feature 去掉？
