### ISSUE TITLE
不可以更改除@primary-color外的其他变量吗?

### ISSUE THREAD

**Issue by longzhangtong** [vueComponent/ant-design-vue-pro#164]
不可以更改除@primary-color外的其他变量吗?

**Comment by sendya** [comment]
less vars 
推荐从这里改 https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L74

**Comment by longzhangtong** [comment]
> less vars
> 推荐从这里改 https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L74

谢谢您.
可是我的项目需要在light && dark模式之间切换.
我尝试修改color.less文件中的变量,
但并未成功

**Comment by sendya** [comment]
light dark 是 ant 官方的风格，跟 pro 没有任何关系。 pro 提供了使用这两种主题的例子
