### ISSUE TITLE
请问作者有打算做Base template吗？

### ISSUE THREAD

**Issue by bugstark** [vueComponent/ant-design-vue-pro#165]
就像  [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)
提供了一个[Base template](https://github.com/PanJiaChen/vue-admin-template)
使用起来相对方便，按需增加组件

**Comment by sendya** [comment]
lite 分支

**Comment by bugstark** [comment]
嗯嗯，谢谢，看过lite分支，看到有挺多组件，我以为不是Base template

**Comment by sendya** [comment]
建议手动从 master 删除 /views/ 下不要的页面。作为基础脚手架。 lite 的代码与主分支有点老，没有更多人手维护。近期再安排人同步到 v2
