### ISSUE TITLE
DescriptionList.vue 组件报错噢

### ISSUE THREAD

**Issue by cmzz** [vueComponent/ant-design-vue-pro#166]
https://github.com/sendya/ant-design-pro-vue/blob/ff3b309e90aff588ce7fd581108d7168c1d877f6/src/components/DescriptionList/DescriptionList.vue#L27

提示如下错误：

SyntaxError
Unexpected identifier

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/55369310-a2ce6980-5528-11e9-9cca-9eede23eaf15.png)

没有任何问题，用法参考
https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/profile/advanced/Advanced.vue#L47

https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/profile/advanced/Advanced.vue#L139-L141

**Comment by zhuowudd01** [comment]
多谢 我试试
