### ISSUE TITLE
可编辑表格设置rowKey后，rowKey的字段编辑异常

### ISSUE THREAD

**Issue by jiufengdadi** [vueComponent/ant-design-vue-pro#168]
在编辑的过程中会不断的失去焦点，每输入一个字段输入框就会自动失去焦点
比如设置 rowKey=‘code’
dataSource：[{code:000}]
在表格可编辑状态下，code所在的单元格输入时就会每输入一个字符就失去焦点一次，没有任何报错信息
其他字段的编辑都是正常的，将哪个字段设为rowKey，哪个字段就会这样，同时其他的字段编辑正常

**Comment by jiufengdadi** [comment]
@sendya 
@since2006 @mynuolr

**Comment by sendya** [comment]
任何情况下，禁止修改 主键

**Comment by jiufengdadi** [comment]
好的，理应如此
