### ISSUE TITLE
路由页面跳转query传参数，地址栏不显示问题

### ISSUE THREAD

**Issue by wangshaoan** [vueComponent/ant-design-vue-pro#170]
goCost(record){
        this.$router.push({path:'/project/cost',query:{project_id:record.id}})
      },用函数跳转路由，参数在地址栏一闪就没了，导致刷新拿不到所需参数

**Comment by sendya** [comment]
没复现你说的问题

![GIF](https://user-images.githubusercontent.com/5404542/55449675-0cb94280-55ff-11e9-841f-b6882dd0a43c.gif)


```js
goFormPage (record) {
      this.$router.push({
        path: '/form/base-form',
        // name: 'BaseForm',
        query: {
          project_id: record.project_id
        }
      })
    },
```
![image](https://user-images.githubusercontent.com/5404542/55449697-222e6c80-55ff-11e9-87c2-98c0fb2458d6.png)
