### ISSUE TITLE
.env 文件好像没有生效

### ISSUE THREAD

**Issue by cmzz** [vueComponent/ant-design-vue-pro#171]
我在 .env  中定义了 

API_HOST=XXX

但是，page  中 process.env.API_HOST还是 null

**Comment by sendya** [comment]
请阅读 VUE 文档

**Comment by sendya** [comment]
https://cli.vuejs.org/guide/mode-and-env.html#example-staging-mode

**Comment by zhuowudd01** [comment]
搞定了 谢谢。  需要重新启动.

**Comment by cmzz** [comment]
搞定了 谢谢。 需要重新启动.
