### ISSUE TITLE
FooterToolBar只能主内容区置底，放在drawer里？

### ISSUE THREAD

**Issue by CarlosKKK** [vueComponent/ant-design-vue-pro#174]
FooterToolBar能否支持在drawer里时，只是抽屉的宽度，不在主内容区置底。
现在这么写的。
``` vue
    <div :style="{ position: 'absolute', left: 0, bottom: 0, width: '100%', borderTop: '1px solid #e9e9e9', padding: '10px 16px', background: '#fff', textAlign: 'right'}">
      <a-button :disabled="isLoading" :style="{ marginRight: '8px' }" @click="onClose">取消</a-button>
      <a-button :disabled="isLoading" @click="onSave" type="primary">保存</a-button>
    </div>
```
![20190404213405](https://user-images.githubusercontent.com/16091422/55560334-97df2900-5722-11e9-922c-4fa2c5497296.png)

**Comment by CarlosKKK** [comment]
哦对了，如果抽屉内容超过页面高度，下拉后抽屉的头就不固定滚出页面了，关闭的叉子是固定哒。

**Comment by sendya** [comment]
请根据文档描述的使用范围使用

https://pro.loacg.com/components/footer-toolbar

**Comment by CarlosKKK** [comment]
谢谢回复。
看过文档，知道使用范围，只是建议，可以让这个组件更灵活嘛。

**Comment by sendya** [comment]
> 谢谢回复。
> 看过文档，知道使用范围，只是建议，可以让这个组件更灵活嘛。

本项目组件以尽量与 react ant pro 官方组件同步 API ，一般不会对组件做特殊化定制。如果你需要，可以自己定制
