### ISSUE TITLE
列表分页，当选中pageSize为20时，点击查询，pageSize又变回10

### ISSUE THREAD

**Issue by zhaozhenghao1993** [vueComponent/ant-design-vue-pro#175]
![pageSize20](https://user-images.githubusercontent.com/33045226/55569593-6bcca380-5734-11e9-898a-be7bb180c110.png)
点击查询或执行this.$refs.table.refresh(true)
![search](https://user-images.githubusercontent.com/33045226/55569796-c534d280-5734-11e9-91cf-3db766c1a4c6.png)
pageSize就又变回10
![pageSize10](https://user-images.githubusercontent.com/33045226/55569831-d4b41b80-5734-11e9-963f-c75e338efd85.png)

在下面每次执行this.$refs.table.refresh(true)获取的pageSize都是默认的10
![before code](https://user-images.githubusercontent.com/33045226/55569909-f8776180-5734-11e9-824c-97ad57d19046.png)
我的修改是
![after code](https://user-images.githubusercontent.com/33045226/55569952-0f1db880-5735-11e9-8ae1-df1886b380d4.png)

不知道这算不算个问题

**Comment by sendya** [comment]
这样写如果在 用户分页不足一页时，你这个代码会报错

**Comment by zhaozhenghao1993** [comment]
我本地这样写暂时没报错，我再看一看。多谢多谢
