### ISSUE TITLE
能否在READ.md或者homepage补充一下各个branch的特性

### ISSUE THREAD

**Issue by alexnest** [vueComponent/ant-design-vue-pro#176]
作者大大，十分喜欢这个项目。提个小建议哈，能否在READ.md或者homepage简单概述下各个branch的特性。十分感谢。:blush:

**Comment by sendya** [comment]
好的，近期加上

**Comment by sendya** [comment]
added, ref 7ab60644d6656021918882b294d2544249ca856b
