### ISSUE TITLE
项目启动过的时候图示要安装core-js 安装了也还是启动不了是怎么回事

### ISSUE THREAD

**Issue by namixiaochuan** [vueComponent/ant-design-vue-pro#177]
These dependencies were not found:

* core-js/modules/es6.array.copy-within in ./src/main.js
* core-js/modules/es6.array.fill in ./src/main.js

**Comment by namixiaochuan** [comment]
To install them, you can run: npm install --save core-js/modules/es6.array.copy-within core-js/modules/es6.array.fill core-js/modules/es6.array.find core-js/modules/es6.array.find-index core-js/modules/es6.array.from core-js/modules/es6.array.iterator core-js/modules/es6.array.of core-js/modules/es6.array.sort core-js/modules/es6.array.species core-js/modules/es6.date.to-primitive core-js/modules/es6.function.has-instance core-js/modules/es6.function.name core-js/modules/es6.map core-js/modules/es6.math.acosh core-js/modules/es6.math.asinh core-js/modules/es6.math.atanh core-js/modules/es6.math.cbrt core-js/modules/es6.math.clz32 core-js/modules/es6.math.cosh core-js/modules/es6.math.expm1 core-js/modules/es6.math.fround core-js/modules/es6.math.hypot core-js/modules/es6.math.imul core-js/modules/es6.math.log10 core-js/modules/es6.math.log1p core-js/modules/es6.math.log2 core-js/modules/es6.math.sign core-js/modules/es6.math.sinh core-js/modules/es6.math.tanh core-js/modules/es6.math.trunc core-js/modules/es6.number.constructor core-js/modules/es6.number.epsilon core-js/modules/es6.number.is-finite core-js/modules/es6.number.is-integer core-js/modules/es6.number.is-nan core-js/modules/es6.number.is-safe-integer core-js/modules/es6.number.max-safe-integer core-js/modules/es6.number.min-safe-integer core-js/modules/es6.number.parse-float core-js/modules/es6.number.parse-int core-js/modules/es6.object.assign core-js/modules/es6.object.freeze core-js/modules/es6.object.get-own-property-descriptor core-js/modules/es6.object.get-own-property-names core-js/modules/es6.object.get-prototype-of core-js/modules/es6.object.is core-js/modules/es6.object.is-extensible core-js/modules/es6.object.is-frozen core-js/modules/es6.object.is-sealed core-js/modules/es6.object.keys core-js/modules/es6.object.prevent-extensions core-js/modules/es6.object.seal core-js/modules/es6.object.set-prototype-of core-js/modules/es6.object.to-string core-js/modules/es6.promise core-js/modules/es6.reflect.apply core-js/modules/es6.reflect.construct core-js/modules/es6.reflect.define-property core-js/modules/es6.reflect.delete-property core-js/modules/es6.reflect.get core-js/modules/es6.reflect.get-own-property-descriptor core-js/modules/es6.reflect.get-prototype-of core-js/modules/es6.reflect.has core-js/modules/es6.reflect.is-extensible core-js/modules/es6.reflect.own-keys core-js/modules/es6.reflect.prevent-extensions core-js/modules/es6.reflect.set core-js/modules/es6.reflect.set-prototype-of core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.flags core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6.regexp.search core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.set core-js/modules/es6.string.anchor core-js/modules/es6.string.big core-js/modules/es6.string.blink core-js/modules/es6.string.bold core-js/modules/es6.string.code-point-at core-js/modules/es6.string.ends-with core-js/modules/es6.string.fixed core-js/modules/es6.string.fontcolor core-js/modules/es6.string.fontsize core-js/modules/es6.string.from-code-point core-js/modules/es6.string.includes core-js/modules/es6.string.italics core-js/modules/es6.string.iterator core-js/modules/es6.string.link core-js/modules/es6.string.raw core-js/modules/es6.string.repeat core-js/modules/es6.string.small core-js/modules/es6.string.starts-with core-js/modules/es6.string.strike core-js/modules/es6.string.sub core-js/modules/es6.string.sup core-js/modules/es6.symbol core-js/modules/es6.typed.array-buffer core-js/modules/es6.typed.float32-array core-js/modules/es6.typed.float64-array core-js/modules/es6.typed.int16-array core-js/modules/es6.typed.int32-array core-js/modules/es6.typed.int8-array core-js/modules/es6.typed.uint16-array core-js/modules/es6.typed.uint32-array core-js/modules/es6.typed.uint8-array core-js/modules/es6.typed.uint8-clamped-array core-js/modules/es6.weak-map core-js/modules/es6.weak-set core-js/modules/es7.array.flat-map core-js/modules/es7.array.includes core-js/modules/es7.object.define-getter core-js/modules/es7.object.define-setter core-js/modules/es7.object.entries core-js/modules/es7.object.get-own-property-descriptors core-js/modules/es7.object.lookup-getter core-js/modules/es7.object.lookup-setter core-js/modules/es7.object.values core-js/modules/es7.promise.finally core-js/modules/es7.string.pad-end core-js/modules/es7.string.pad-start core-js/modules/es7.string.trim-left core-js/modules/es7.string.trim-right core-js/modules/es7.symbol.async-iterator core-js/modules/web.dom.iterable

**Comment by sendya** [comment]
可以使用 yarn 作为依赖管理包，自动会引入 corejs，如果用 npm 自己引入一下，然后重启

**Comment by namixiaochuan** [comment]
> 可以使用 yarn 作为依赖管理包，自动会引入 corejs，如果用 npm 自己引入一下，然后重启
我用"cnpm install --save core-js@3" 安装了依赖包，启动后还是同样的报错……

**Comment by namixiaochuan** [comment]
页面打开显示
./src/main.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.copy-within' in '

**Comment by sendya** [comment]
我说了 yarn 或者 npm 自己手动引入，没说 cnpm ，cnpm 安装依赖经常出问题为啥不直接换源而要去用 cnpm 呢

**Comment by sendya** [comment]
`npm config set registry https://registry.npm.taobao.org`

**Comment by sendya** [comment]
顺带一说，你要是不知道怎么引入。直接 `npm install core-js` 就好了

**Comment by namixiaochuan** [comment]
解決了，要用2.6的版本，嗨，就奇怪几个星期前还能跑，现在跑不动了……
npm i core-js@2.6.5 --save

**Comment by namixiaochuan** [comment]
解決了，core-js最高版本不好使，要将版本……
嗨，就奇怪几个星期前还能跑，现在跑不动了……
npm i core-js@2.6.5 --save

**Comment by namixiaochuan** [comment]
解決了，core-js最高版本不好使，要降版本……
嗨，就奇怪几个星期前还能跑，现在跑不动了……
npm i core-js@2.6.5 --save

**Comment by StephenOo** [comment]
> 解決了，core-js最高版本不好使，要降版本……
> 嗨，就奇怪几个星期前还能跑，现在跑不动了……
> npm i core-js@2.6.5 --save

管用，太坑了，我也是安装的3.0 +的core-js版本

**Comment by wangshaokaicoder** [comment]
有用，我这里是有2个依赖，一个依赖2.6 版本，另一个依赖3.32 版本，执行npm install 后，会自动升级高版本，导致运行出错。
