### ISSUE TITLE
列表中，某几列包含分支如何展现

### ISSUE THREAD

**Issue by baiLangA** [vueComponent/ant-design-vue-pro#181]
**Question**
How to use component `s-table` paging

**Describe the solution you'd like**

**Additional context**

**Comment by baiLangA** [comment]
我需要单列引出多列数据展示应当如何做呢

**Comment by sendya** [comment]
table 可以直接看官方文档，如果文档没有，就是没有 https://vue.ant.design/components/table-cn/

并且 没看懂你在描述什么场景，有例子吗？
