### ISSUE TITLE
a-table 子表格嵌套问题

### ISSUE THREAD

**Issue by baiLangA** [vueComponent/ant-design-vue-pro#182]
1.header的问题解决了，加入<page-view :title="title">后正常，子表格还是不会嵌套
2.嵌套子表格时，如何传入数据，现在是直接在脚手架的基础上做改造的，这种表格如何嵌入子表格呢
`
  data () {
    return {
      mdl: {},
      // 高级搜索 展开/关闭
      advanced: false,
      // 查询参数
      queryParam: {},
      // 表头
      columns: [
`
谢谢

**Comment by sendya** [comment]
你说表格，又没说哪种表格，能不能描述清楚？描述不清楚也可以给个例子或者图。发一段代码弄这样根本不能看

**Comment by sendya** [comment]
从你提供的描述里，我一个表格都没看到。   要嵌入的表格，我也没看到

**Comment by baiLangA** [comment]
不好意思
我有一个如图1的json，以图2的方式展示到了页面上，如图3，但是里面的commodities是一个子列表，我想展示成图4那样，应该怎么做呢，官方文档中的是默认数据，我的数据应该怎么放入子列表呢，谢谢了

![1](https://user-images.githubusercontent.com/42482547/55797462-0bcf5780-5abc-11e9-84e3-6667db0dbdc0.png)
![2](https://user-images.githubusercontent.com/42482547/55797454-070aa380-5abc-11e9-9d95-f8f5be4f7d78.png)
![3](https://user-images.githubusercontent.com/42482547/55797459-0a059400-5abc-11e9-8563-8906afadbf1f.png)

![4](https://user-images.githubusercontent.com/42482547/55797582-55b83d80-5abc-11e9-88e8-ef882eb20251.png)

**Comment by sendya** [comment]
看文档都不会用吗？

```
  <a-table :columns="columns" :dataSource="data" class="components-table-demo-nested">
    <a slot="operation" slot-scope="text" href="javascript:;">Publish</a>
    <a-table
      slot="expandedRowRender"
      slot-scope="text"
      :columns="innerColumns"
      :dataSource="innerData"
      :pagination="false"
    >
      <span slot="status" slot-scope="text">
        <a-badge status="success" />Finished
      </span>
      <span slot="operation" slot-scope="text" class="table-operation">
        <a href="javascript:;">Pause</a>
        <a href="javascript:;">Stop</a>
        <a-dropdown>
          <a-menu slot="overlay">
            <a-menu-item>
              Action 1
            </a-menu-item>
            <a-menu-item>
              Action 2
            </a-menu-item>
          </a-menu>
          <a href="javascript:;">
            More <a-icon type="down" />
          </a>
        </a-dropdown>
      </span>
    </a-table>
  </a-table>
```


参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
expandedRowRender | 额外的展开行 | Function(record, index, indent, expanded):VNode \| slot="expandedRowRender" slot-scope="record, index, indent, expanded" | -

**Comment by sendya** [comment]
不如这样，你把你的数据用 codesandobx 实现出来 a-table 。然后发出来，我帮你改成支撑展开的
