### ISSUE TITLE
首页sider动画不同步问题

### ISSUE THREAD

**Issue by zkwolf** [vueComponent/ant-design-vue-pro#185]
**Describe the bug**
首页sider在收起时，header和menu动画不同步，menu收回的速度比header慢

**To Reproduce**
1. 展开sider
2. 收回sider，发现menu比header返回左侧的速度慢一点

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 73

**Additional context**

**Comment by sendya** [comment]
![GIF2](https://user-images.githubusercontent.com/5404542/55863457-21707a00-5bad-11e9-8af8-3b09eb209ed6.gif)

**Comment by zkwolf** [comment]
台式机上我这确实没法复现了，可能是因为笔记本性能问题？

**Comment by zkwolf** [comment]
暂时关闭，我这边有时间自己找一下原因
