### ISSUE TITLE
打包部署之后，访问进去左侧菜单样式错乱，开发环境是正常的

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue-pro#188]
1.本地开发正常，
2.修改了登陆和动态路由,添加了几个新的页面
3.build打包之后部署到服务器（centos6.5+nginx1.14.2)登陆之后出现样式错乱
4.pro版本1.3.0，浏览器chrome
本地
![捕获](https://user-images.githubusercontent.com/24693458/55946225-e3dc2180-5c7e-11e9-8f7c-7ff6ab69abc2.PNG)
服务器
![捕获1](https://user-images.githubusercontent.com/24693458/55946252-ee96b680-5c7e-11e9-90ce-88779070544c.PNG)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/55944179-9c539680-5c7a-11e9-873c-5269beecd710.png)

**Comment by sendya** [comment]
控制台有报错吗？看一下控制台选元素 看一下菜单的 dom 结构变成什么样子了

**Comment by ghost** [comment]
> 控制台有报错吗？看一下控制台选元素 看一下菜单的 dom 结构变成什么样子了
控制台没有报错，
![image](https://user-images.githubusercontent.com/24693458/55946362-2c93da80-5c7f-11e9-9fa7-4dae78a15999.png)

**Comment by ghost** [comment]
> 控制台有报错吗？看一下控制台选元素 看一下菜单的 dom 结构变成什么样子了
我重新拉下代码，先不做任何修改，部署看下吧，谢谢了

**Comment by ghost** [comment]
找到问题了，自己写的一个组件样式有问题，麻烦关掉吧，谢谢
