### ISSUE TITLE
请问您怎么解决defaultExpandAllRows这类无效的问题？

### ISSUE THREAD

**Issue by chenxunfeng** [vueComponent/ant-design-vue-pro#19]
defaultExpandAllRows这类设置，只在第一次渲染时执行，异步请求数据导致无效了，请问您是怎么解决的？谢谢

**Comment by sendya** [comment]
default 开头的参数，均只在第一次渲染时生效，后期修改均不会产生效果。
如果要在渲染之后 进行动态的展开数据，可以控制  `expandedRowKeys` 属性，自己控制要展开的行即可
