### ISSUE TITLE
是否有机会支持飞冰呢？

### ISSUE THREAD

**Issue by hodgevk** [vueComponent/ant-design-vue-pro#190]
飞冰是一个前端开发工具，现在官方主要是支持React 物料，Vue物料主要靠社区推动。如果我们的pro能支持飞冰的话对pro的发展应该是有推动的。

**Comment by sendya** [comment]
飞冰 跟 Pro 没什么关系，欢迎有能力人士去做，我个人也没那么多时间维护更多项目
