### ISSUE TITLE
Is there a fully English version of this template?

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue-pro#199]
**Is your feature request related to a problem? Please describe.**
This template project looks great, however for people like me who only speak English it is difficult to fully appreciate the templates and the examples.

**Describe the solution you'd like**
It would be cool to see a repo where there was an english version.

**Describe alternatives you've considered**

**Additional context**

**Comment by Acris** [comment]
Hi,
Thanks for your advice. We are planning to add i18n support in the future: https://github.com/sendya/ant-design-pro-vue/tree/feature/lang, but currently, we have no more time and people to do it. If you have any good ideas, pull request is always welcome.

**Comment by ghost** [comment]
@Acris could you give me a high level description of the process that it would take to add i18n support? It's not something i've done before but I'd be down to help

**Comment by sendya** [comment]
@ChrisDillinger look here https://kazupon.github.io/vue-i18n/
