### ISSUE TITLE
本地跑起来了， 但用admin登录的时候，progress bar走了很久，超过2分钟，才进入里面

### ISSUE THREAD

**Issue by medmin** [vueComponent/ant-design-vue-pro#2]
暂时也没看代码，这是我clone之后遇到的第一个问题

**Comment by medmin** [comment]
测试了很多，为啥点击很多，反应很慢？是什么原因么？

**Comment by sendya** [comment]
考虑可能是请求的接口服务器请求不到，可以看浏览器的 console 网络选项卡的情况

**Comment by medmin** [comment]
@sendya 谢谢，我再研究一下哈。

**Comment by mingyouzhu** [comment]
进不去首页 太卡了不能用啊 Console一堆错误

**Comment by xuanhe168** [comment]
进不去首页 好卡啊~ Console有堆错误

**Comment by sendya** [comment]
> 进不去首页 好卡啊~ Console有堆错误

有问题就开新 issue 按照格式提供问题，不要再已经关闭的 issue 内体温
