### ISSUE TITLE
想把二级菜单隐藏，给父级设置hideChildrenInMenu：true后，父级无发点击，而且父级的链接也变了

### ISSUE THREAD

**Issue by huyunning** [vueComponent/ant-design-vue-pro#201]
**Question**
当我想隐藏二级菜单，给一级加了hideChildrenInMenu:true，确实隐藏了，但是一级的链接不对了，变成当前页面的链接地址。三级菜单没有这个问题，很完美，就像个人设置那个页面，但是同样的方法，设置在一级和二级就有问题了

**Describe the solution you'd like**
想要实现，二级菜单隐藏，并且点一级菜单的时候路由正确，且选中

**Additional context**

**Comment by huyunning** [comment]
一级和二级是这样设置的：
{
        path: '/form',
        redirect: '/form/base-form',
        component: PageView,
        hideChildrenInMenu: true,
        meta: { title: '表单页', icon: 'form', permission: [ 'form' ] },
        children: [
          {
            path: '/form/base-form',
            name: 'BaseForm',
            component: () => import('@/views/form/BasicForm'),
            meta: { title: '基础表单',  hidden: true, permission: [ 'form' ] }
          },
          {
            path: '/form/step-form',
            name: 'StepForm',
            component: () => import('@/views/form/stepForm/StepForm'),
            meta: { title: '分步表单', hidden: true, permission: [ 'form' ] }
          },
          {
            path: '/form/advanced-form',
            name: 'AdvanceForm',
            component: () => import('@/views/form/advancedForm/AdvancedForm'),
            meta: { title: '高级表单',hidden: true, permission: [ 'form' ] }
          }
        ]
      },

**Comment by sendya** [comment]
https://preview.pro.loacg.com/test

```
      {
        path: '/test',
        name: 'testPage',
        component: () => import('@/views/Home'),
        meta: { title: '测试页', icon: 'slack', permission: [ 'dashboard' ] },
        hideChildrenInMenu: true,
        children: [
          {
            path: '/test/page1',
            name: 'testPage1',
            meta: { title: '子页面1', icon: 'app' },
            component: () => import('@/views/exception/404')
          }
        ]
      }
```

![20190417161426](https://user-images.githubusercontent.com/5404542/56271852-fbf2eb80-612b-11e9-9c1f-d168fbff5b9b.png)

**Comment by huyunning** [comment]
谢谢，知道是哪的问题了，项目很强大，👍🏻

**Comment by huyunning** [comment]
还发现一个问题，/test/page1是渲染在/test的组件里的，他里面并没有《router-view  /》,所以访问/test/page1的时候显示的还是/test页面，404页面出不来，请问这个问题怎么解决，谢谢

**Comment by sendya** [comment]
> 还发现一个问题，/test/page1是渲染在/test的组件里的，他里面并没有《router-view /》,所以访问/test/page1的时候显示的还是/test页面，404页面出不来，请问这个问题怎么解决，谢谢

这就要你自己写 `router-view` 了，我写那个 demo 只帮你解决你开 issue 的问题。
如果你还想参考一个菜单下多个隐藏的菜单可以跳转，参考 [CRUD Router View](https://github.com/sendya/ant-design-pro-vue/blob/demo/router-view-table/src/config/router.config.js#L80-L104)
