### ISSUE TITLE
S-Table 分页中分页加载BUG

### ISSUE THREAD

**Issue by monkeyming** [vueComponent/ant-design-vue-pro#202]
**分页加载数据BUG**
有一个判断数据集长度是否为0的判断
` if ( r.list.length === 0 && this.localPagination.current !== 1) {
              this.localPagination.current--
              this.loadData()
              return
            }`
这判断的是数据列表的长度，会引发BUG数据循环加载，进入死循环
应该加上r.total总数据条数的判断

**Comment by sendya** [comment]
几天前已经去掉了

https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/Table/index.js#L148

**Comment by monkeyming** [comment]
66666

**Comment by xtsong** [comment]
table分页的当前页码怎么修改？
