### ISSUE TITLE
权限路由，一直出现错误。

### ISSUE THREAD

**Issue by tony2y** [vueComponent/ant-design-vue-pro#203]
你好，在使用过程中，按照现有的文档，实现了后端返回路由权限的JSON 样式，并且按照文档：https://pro.loacg.com/docs/authority-management，进行更改，但是现在却一直报错！！
![image](https://user-images.githubusercontent.com/38598582/56349386-06c88180-61fb-11e9-84c8-fafb794c6eef.png)

**Comment by tony2y** [comment]
一直是这里报错，具体需要怎么改写代码。
![image](https://user-images.githubusercontent.com/38598582/56349753-cb7a8280-61fb-11e9-8ad7-26af389aa136.png)

**Comment by yichangle** [comment]
得检查routerMap的值为undefined，追踪一下为什么没得到正确的值。

**Comment by tony2y** [comment]
这里的方法是个递归调用，routerMap 从哪里来我都还找不到。。

**Comment by tony2y** [comment]
> 得检查routerMap的值为undefined，追踪一下为什么没得到正确的值。

**Comment by tony2y** [comment]
这个方法在这里只有它自己在调用，routerMap 从哪里来我都没找到

**Comment by tony2y** [comment]
generatorDynamicRouter（）该方法实现的步骤按照文档上面来的，不会错把？![image](https://user-images.githubusercontent.com/38598582/56350979-a50a1680-61fe-11e9-81c5-9fb39470aec3.png)

**Comment by tony2y** [comment]
发现个问题 ，根本没有去获取后台数据，都没执行！！
![image](https://user-images.githubusercontent.com/38598582/56351190-1ea20480-61ff-11e9-92fb-aa575fccace5.png)

**Comment by sendya** [comment]
如果你连自己在改什么东西，都不清楚的话，那这个弄起来难度有点高。我建议你好好看一下文档，然后去了解一下权限一般是怎么设计的。

本框架默认提供了一套基于后端提供角色权限字段，前端进行过滤前端已经写死的路由，过滤出不要的页面，然后渲染显示正常可用页面。

还提供了一套完整由后端提供权限配置信息的配置项用例。

如果你这些都不了解，还请先在网上查一下相关资料

**Comment by tony2y** [comment]
我的意思是，我现在按照 ：https://pro.loacg.com/docs/authority-management 这个步骤在做更改，实现后台返回JSON 实现动态路由菜单，但是照着这上面的步骤一步步实现之后才出现上面的那个问题。下图：
![image](https://user-images.githubusercontent.com/38598582/56359341-e1943d00-6213-11e9-8eb2-29e31e84461a.png)

**Comment by sendya** [comment]
authority-management 哪里说让你动这个文件的这个方法了？
`feature/dynamic-menu` 分支你可以拉取下来，运行看看结果是什么样的。
