### ISSUE TITLE
使用S-table 会跳转页面，但是参数没有带上query

### ISSUE THREAD

**Issue by liangwenle** [vueComponent/ant-design-vue-pro#205]
估计是 表格中的
`watch: {
    'localPagination.current' (val) {
      this.$router.push({
        name: this.$route.name,
        params: Object.assign({}, this.$route.params, {
          pageNo: val
        })
      })
    },`
没有带参数 query

**Comment by sendya** [comment]
请描述清楚

**Comment by liangwenle** [comment]
当B页面使用了S-table，在跳转到B页面的路由中 带了query就有问题。
如 /B?id=123.那么由于S-table 中使用了this.$router.push，
但没有带上query 导致 路由/B?id=123==> /B了。
![image](https://user-images.githubusercontent.com/10026149/56414550-7acb5e00-62bd-11e9-9e48-7891ecd4f2b3.png)

**Comment by sendya** [comment]
如果你未遵循  `/module/:page` 规范，你可以直接去掉这段代码。

这个监听切换路由的作用仅用于页面是 
- 第一页 `/users/1`
- 第二页 `/users/2`

复制地址就能直接切换到对应页的数据
