### ISSUE TITLE
路由跳转执行了2次，导致最后一次获取不到query参数

### ISSUE THREAD

**Issue by gslancer** [vueComponent/ant-design-vue-pro#207]
1：现象如下：
路由跳转了2次，最后一次没有了query的参数。当浏览器回退的时候又出现了带参数的路由
![1](https://user-images.githubusercontent.com/6703111/56423990-fab6ef80-62e0-11e9-8cbd-8e4db5c6cc9f.gif)

2：调试窗口监控vue的路由信息如下
![2](https://user-images.githubusercontent.com/6703111/56424006-07d3de80-62e1-11e9-94eb-0e8f877dc3b2.gif)

3：操作说明：
      使用table的操作功能，跳转到详情页，并传递参数(query方式)
<img width="538" alt="3" src="https://user-images.githubusercontent.com/6703111/56424019-13270a00-62e1-11e9-93fb-548b6b365460.png">

4：路由配置如下：
<img width="547" alt="1" src="https://user-images.githubusercontent.com/6703111/56424288-37371b00-62e2-11e9-94fc-ab6b746fb9bb.png">

5：函数跳转
handleDetail(record) {
      this.$router.push({ path: '/park/pdetail', query: { id: record.id } })
    }

6：当不带query参数时，跳转的路由就正常，只跳转了一次
this.$router.push({ path: '/park/pdetail' })

7:  当用params方式传参时，跳转的路由就正常，只跳转了一次
this.$router.push({ name: 'pdetail', params: { iparams: record.id } })

8:  当用动态路径参数时，跳转的路由就正常，只跳转了一次
path: '/park/pdetail/:id'

**Comment by sendya** [comment]
经过测试没问题，请确认你自己 detail 页面的业务逻辑是否处理到参数或者路由相关的问题

**Comment by sendya** [comment]
![GIF](https://user-images.githubusercontent.com/5404542/56430693-bab03680-62f9-11e9-890b-2e3d68b36a02.gif)

![image](https://user-images.githubusercontent.com/5404542/56430762-f945f100-62f9-11e9-9999-057991e47f1d.png)

**Comment by gslancer** [comment]
> 经过测试没问题，请确认你自己 detail 页面的业务逻辑是否处理到参数或者路由相关的问题

经过跟踪代码，返现是table.js组件中，对分页数据进行了watch导致的路由切换。不知道是不是属于bug，请麻烦看看吧（跳转的页面如果有table，就回出现问题，否则不会有问题）：
![image](https://user-images.githubusercontent.com/6703111/56486442-2cf76580-650a-11e9-8f9c-0cde0fe257df.png)

**Comment by sendya** [comment]
如果你不用到 分页控制页面 url ，可以直接移除这个 watch

**Comment by gslancer** [comment]
谢谢!
