### ISSUE TITLE
S-table 点击查询按钮时没有带上排序参数

### ISSUE THREAD

**Issue by lwQin** [vueComponent/ant-design-vue-pro#208]
**描述**
对表格字段进行排序后，重新执行查询，表格中的排序样式在生效，实际的数据并没有排序

**复现**
1. 对字段进行排序
2. 重新点击`查询`按钮、

**截图**
![avatar](https://i.loli.net/2019/04/21/5cbbfb815d576.png)

**设备信息**
 - OS: macOS 10.14.4
 - Browser: Chrome
 - Version: 73.0.3683.103

**Comment by sendya** [comment]
数据是 mock 的，并没有排序功能。该功能需要后端支持。请自行做支持

**Comment by lwQin** [comment]
请看截图的控制台，第三次输出是重新点击查询按钮后的日志，这个是前端也没有传排序字段到后端吧？

**Comment by sendya** [comment]
点 `查询` 按钮没有记住表格参数功能，如果需要 你可以尝试把表格的参数绑定在 data 下
