### ISSUE TITLE
build后的dist，我做了http-server后，无法正常运行

### ISSUE THREAD

**Issue by 445022889** [vueComponent/ant-design-vue-pro#21]
![tim 20181205130758](https://user-images.githubusercontent.com/8262562/49491371-d48f3680-f88e-11e8-85da-7a13f5a8f31d.png)
![tim 20181205130841](https://user-images.githubusercontent.com/8262562/49491429-10c29700-f88f-11e8-8955-2221297a9485.png)

第一步都进不去，直接git的项目打包后，也是一样。是我这边的问题吗，我是php转的前端vue，可能比较小白，麻烦告知一下如何正确的操作，谢谢啊

**Comment by sendya** [comment]
后端 API 需要自己提供，如果要用演示 API，或者开发前后端分离项目。请为该文件的 `baseUrl` 提供 [src/utils/request.js#L10](https://github.com/sendya/ant-design-pro-vue/blob/master/src/utils/request.js#L10) 接口地址。

如果要防止跨域，你可能还需要在你的编译运行的 dist web 目录的 nginx 上配置一个反代，用来代理 API 到同域名下

eg:
```nginx

server {
        listen 80;
        listen 443;
        server_name pro.loacg.com;
        access_log /data/logs/pro_access.log combined;
        index index.html index.htm index.php;
        root  /data/web/vue-antd-pro/dist;

        add_header Access-Control-Allow-Origin "pro.loacg.com";

        location / {
                try_files $uri $uri/ /index.html =404;
        }

        location /api/ {
                #proxy_set_header        Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
		proxy_set_header	X-Forwarded-Proto $scheme;
                proxy_pass              https://www.easy-mock.com/mock/5b7bce071f130e5b7fe8cd7d/antd-pro/api/;
        }
}

```


如果是为了看运行起来的效果，建议直接依靠 node, webpack devServer 来开发环境运行。因为配置文件 `vue.config.js` 内配置了可访问的 API 接口地址

eg: 
```bash
$ npm run serve
or
$ yarn run serve
```

**Comment by 445022889** [comment]
明白了，刚刚看到还有个baseUrl，谢谢你啦，回复的这么全面！
