### ISSUE TITLE
dynamicMenu分支是最新的模板出来的吗？

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#210]
是从最新的ant-design-pro-vue精简出来的吗？ 如果不是可以麻烦大佬同步一下吗，小白恳求。 这个dynamicMenu中可以使用指令权限吗？

**Comment by sendya** [comment]
dynamic-menu 提供的是一个能正常使用后端数据构建动态路由的例子实例。可正常运行和调试参考。
今后除非有修改到 动态路由 的构建，否则一般不会在进行更新。

如果你需要最新分支，请自行在最新主分支代码中 并入 dynamic-menu 动态路由的实现。
