### ISSUE TITLE
v-action是和所有路由里面权限对比吗？

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#213]
v-action是和所有路由里面权限对比吗？还是只和当前路由下的权限对比？？？？
 我看了一下，好像和全部的做对比。和全部的做对比，那是不是很慢呀。感觉和当前路由下面的权限做对比，或者，进入这个页面的时候，就能获取到他的所有权限，然后对比。

**Comment by sendya** [comment]
只和当前路由下的权限对比

**Comment by java8site** [comment]
> 只和当前路由下的权限对比

/helper/permission.js

  !Vue.prototype.$auth && Object.defineProperties(Vue.prototype, {
    $auth: {
      get () {
        // const _this = this
        // return (permissions) => {
        //   const [permission, action] = permissions.split('.')
        //   const permissionList = _this.$store.getters.roles.permissions
        //   return permissionList.find((val) => {
        //     return val.permissionId === permission
        //   }).actionList.findIndex((val) => {
        //     return val === action
        //   }) > -1
        // }
      }
    }

这一块表达意思，是先在用户角色中找到permissions， 然后在permissions中找到当前的路由， 然后再对比action吗？  @sendya

**Comment by sendya** [comment]
是

**Comment by sendya** [comment]
> 任何的权限相关的实现，请自行根据自己的业务实现，这不是前端框架要为你做的事情，也不是框架强制为你做的限制。你应当由自己来设计你的 权限结构 以及 储存和获取方式。项目提供的几种方案均作为 **"用例"** 提供给你参考的，并不可能符合你的自身业务。

## 指令权限

Pro 封装了一个非常方便实现按钮级别权限的自定义指令。 [v-action](https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L83)



使用

```vue
<!-- eg: 当前页面为 dashboard -->

<template>
	<!-- 校验是否有 dashboard 权限下的 add 操作权限 -->
    <a-button v-action:add >添加用户</a-button>

	<!-- 校验是否有 dashboard 权限下的 del 操作权限 -->
    <a-button v-action:del>删除用户</a-button>

	<!-- 校验是否有 dashboard 权限下的 edit 操作权限 -->
    <a v-action:edit @click="edit(record)">修改</a>
</template>
```

> 需要注意的是，指令权限默认从 store 中获取当前已经登陆的用户的角色和权限信息进行比对，所以也要对指令权限的获取和校验 Action 权限部分进行自定义。



在某些情况下，不适合使用 `v-action`，例如 Tab 组件，只能通过手动设置 v-if 来实现。

这时候，Pro 为其提供了原始 v-if 级别的权限判断。

```vue
<template>
	<a-tabs>
        <a-tab-pane v-if="$auth('dashboard.add')" tab="Tab 1">
            some context..
    	</a-tab-pane>
        <a-tab-pane v-if="$auth('dashboard.del')" tab="Tab 2">
            some context..
    	</a-tab-pane>
        <a-tab-pane v-if="$auth('dashboard.edit')" tab="Tab 3">
            some context..
    	</a-tab-pane>
    </a-tabs>
</template>
```

实现思路：

> 在 Vue 初始化时，[@/utils/helper/permission.js](https://github.com/sendya/ant-design-pro-vue/blob/master/src/utils/helper/permission.js) 作为插件注册到 Vue 原型链上，在 Vue 实例中就可以用 this.$auth() 方法进行权限判断。 当然这里也要对权限的获取和校验 Action 权限部分进行自定义。

**Comment by java8site** [comment]
> > 任何的权限相关的实现，请自行根据自己的业务实现，这不是前端框架要为你做的事情，也不是框架强制为你做的限制。你应当由自己来设计你的 权限结构 以及 储存和获取方式。项目提供的几种方案均作为 **"用例"** 提供给你参考的，并不可能符合你的自身业务。
> 
> ## 指令权限
> Pro 封装了一个非常方便实现按钮级别权限的自定义指令。 [v-action](https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L83)
> 
> 使用
> 
> ```
> 
> 
> <template>
> 	
>     <a-button v-action:add >添加用户</a-button>
> 
> 	
>     <a-button v-action:del>删除用户</a-button>
> 
> 	
>     <a v-action:edit @click="edit(record)">修改</a>
> </template>
> ```
> 
> > 需要注意的是，指令权限默认从 store 中获取当前已经登陆的用户的角色和权限信息进行比对，所以也要对指令权限的获取和校验 Action 权限部分进行自定义。
> 
> 在某些情况下，不适合使用 `v-action`，例如 Tab 组件，只能通过手动设置 v-if 来实现。
> 
> 这时候，Pro 为其提供了原始 v-if 级别的权限判断。
> 
> ```
> <template>
> 	<a-tabs>
>         <a-tab-pane v-if="$auth('dashboard.add')" tab="Tab 1">
>             some context..
>     	</a-tab-pane>
>         <a-tab-pane v-if="$auth('dashboard.del')" tab="Tab 2">
>             some context..
>     	</a-tab-pane>
>         <a-tab-pane v-if="$auth('dashboard.edit')" tab="Tab 3">
>             some context..
>     	</a-tab-pane>
>     </a-tabs>
> </template>
> ```
> 
> 实现思路：
> 
> > 在 Vue 初始化时，[@/utils/helper/permission.js](https://github.com/sendya/ant-design-pro-vue/blob/master/src/utils/helper/permission.js) 作为插件注册到 Vue 原型链上，在 Vue 实例中就可以用 this.$auth() 方法进行权限判断。 当然这里也要对权限的获取和校验 Action 权限部分进行自定义。

好的吧，多谢。
