### ISSUE TITLE
提交代码被告知没权限---完成了该项目的国际化，代码提交不上去

### ISSUE THREAD

**Issue by changhighly** [vueComponent/ant-design-vue-pro#216]
提交代码被告知没权限---完成了该项目的国际化，代码提交不上去

**Comment by Acris** [comment]
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

See also: https://github.com/sendya/ant-design-pro-vue/issues/90

**Comment by mynuolr** [comment]
请使用 Pull requests
