### ISSUE TITLE
build 之后的代码，点击登录无法跳转到 dashboard 页面

### ISSUE THREAD

**Issue by GSANDLY** [vueComponent/ant-design-vue-pro#219]
### 环境

- 系统：macOS 10.14.4
- 浏览器：chrome 73
- 项目版本：提交号 30715b5729cf19f7b162907b50872f430ad2e752

 ### 详细描述

你好，我运行 yarn build 后，进入 dist 目录，启动 http-server 命令，打开浏览器可以正常访问登录页面，输入用户名密码之后，点击登录按钮，页面没反应。以为是接口没法调用的问题，然后把 login.vue 里面点击登录按钮调用的方法注释掉，直接调用 loginSuccess() 方法，发现还是没有反应。
![image](https://user-images.githubusercontent.com/19584808/56786102-5413a700-682a-11e9-91e3-f00313e3e154.png)

![image](https://user-images.githubusercontent.com/19584808/56786300-25e29700-682b-11e9-948d-db0757387189.png)

**Comment by sendya** [comment]
build 是 prod 環境，沒有接口是不能訪問的。
你需要配置自己的接口環境。

另外，直接改 loginSuccess 并不会生效，会被路由守卫的 登录校验拦截。

**Comment by sendya** [comment]
如果你要带 mock 接口数据的编译，可以看看 ，build:preview 编译

**Comment by GSANDLY** [comment]
非常感谢🙏
