### ISSUE TITLE
安装扩展功能，如何功能加载页面

### ISSUE THREAD

**Issue by lanrenbulan** [vueComponent/ant-design-vue-pro#220]
你好，请教一个问题：

前端用antd vue开发的系统，如果后台允许第三方开发扩展，客户可以自由选择扩展并安装使用，那么在前端，如何调用这些扩展的页面呢？ 我的思维被限制在单页应用完成打包后，不知道怎么通过扩展的方式调用其它的代码

数据据有一个Menu表来管理路由，前端动态加载menu（包括扩展的）

**Comment by sendya** [comment]
就目前而言，前端没打包进去的组件，并不知道如何实现由后端传递。
你要真想这么做，完全可以服务端渲染，没必要纯单页应用

**Comment by lanrenbulan** [comment]
后台准备用单页，在单页应用基础上，我目前还没有找到突破点。我想了下，看能不能是第三方开发扩展后单独打包（多页面应用一样，将扩展功能作为多页应用中的一页），然后用iframe使用。

我看了下服务端渲染，了解到是把所有功能都开发好后，打包后有两个，一个是服务器上使用的，一个是客户端使用的。扩展功能是未知的，服务器渲染也好像是跟单页上是一样的问题（在目前的了解到的知识点情况下是这样想）。
