### ISSUE TITLE
路由全部从后台动态获取,路由中meta字段不生效。

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#222]
路由组成的json， meta不生效。

**Comment by sendya** [comment]
路由信息由你构建的，如果不生效请你检查一下生成后的结果。
如果是不会动态构建路由，可以参考分支 [feature/dynamic-menu](https://github.com/sendya/ant-design-pro-vue/tree/feature/dynamic-menu)

如果你是要反馈问题，请参照 #90

**Comment by java8site** [comment]
> 路由信息由你构建的，如果不生效请你检查一下生成后的结果。
> 如果是不会动态构建路由，可以参考分支 [feature/dynamic-menu](https://github.com/sendya/ant-design-pro-vue/tree/feature/dynamic-menu)
> 
> 如果你是要反馈问题，请参照 #90

返回的json信息和文档中定义的都一样。dynamic-menu项目中从后台获取的路由信息中都没有meta字段呀。dynamic-menu和ant-design-pro-vue文档中路由的定义，各个字段是否都相同？？？

**Comment by sendya** [comment]
你可以自己对比以下

**Comment by java8site** [comment]
> 你可以自己对比以下

meta字段相关， 以及设置外链接，就是点击跳转到其他网站。这都在哪几个文件呀。求指教。

**Comment by sendya** [comment]
没有哪几个文件，这就是一个普通的路由配置项，由你构建的。并不存在什么文件

**Comment by jianshen-weo** [comment]
https://github.com/sendya/ant-design-pro-vue/tree/feature/dynamic-menu
这个分支怎么找不到了

**Comment by jianshen-weo** [comment]
@sendya https://github.com/sendya/ant-design-pro-vue/tree/feature/dynamic-menu 这个分支怎么找不到了
