### ISSUE TITLE
如何动态生成新打开的页面的tab名字和面包屑路径呢？

### ISSUE THREAD

**Issue by JADE-Jerry** [vueComponent/ant-design-vue-pro#223]
**Question**
如何动态生成新打开的页面的tab名字和面包屑路径呢？

**Describe the solution you'd like**
比如打开一个 localhost:8000/#/order/123 的页面，tab名字希望是#123，面包屑路径是 Home/ Order Mgmt / #123

**Comment by sendya** [comment]
面包屑只能识别路由 meta.title 作为名称，多层路由嵌套的时候相同处理方式
