### ISSUE TITLE
最新代码下载后，yarn run serve报错

### ISSUE THREAD

**Issue by wangshaoan** [vueComponent/ant-design-vue-pro#224]
These dependencies were not found:

* @/components/Menu/SideMenu in ./node_modules/cache-loader/dist/cjs.js??ref--12
-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref-
-0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/BasicLayout
.vue?vue&type=script&lang=js&
* @/components/Table in ./src/components/index.js

To install them, you can run: npm install --save @/components/Menu/SideMenu @/co
mponents/Table

This relative module was not found:

* ../Menu/ in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/
babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_module
s/vue-loader/lib??vue-loader-options!./src/components/GlobalHeader/GlobalHeader.
vue?vue&type=script&lang=js&

**Comment by mynuolr** [comment]
一切正常。
![image](https://user-images.githubusercontent.com/3831242/56863355-ddbca380-69e7-11e9-979b-9ba27d1c1aa1.png)

**Comment by sendya** [comment]
请确认你的系统能够正确识别目录和文件的大小写。检查一下是不是目录名是小写之类的

**Comment by wangshaoan** [comment]
> 请确认你的系统能够正确识别目录和文件的大小写。检查一下是不是目录名是小写之类的
E:\vue\ant-design-pro-vue-master>       此路径应该没问题吧

**Comment by sendya** [comment]
@wangshaoan 我说的是你报错的路径

这个

> To install them, you can run: npm install --save @/components/Menu/SideMenu @/co
mponents/Table

跟 github 库上的路径对比

**Comment by wangshaoan** [comment]
以前代码可以，这些我都没动过啊

**Comment by sendya** [comment]
> 以前代码可以，这些我都没动过啊

结果呢？

**Comment by wangshaoan** [comment]
原因未知重新下载啥都没用，重新试了多次好了

**Comment by sendya** [comment]
> 原因未知重新下载啥都没用，重新试了多次好了

让你对比，你又不说结果

**Comment by badbye** [comment]
在新建的页面上遇到同样的问题。
macOS系统，文件目录纯小写，文件名是驼峰式的。而且诡异的是，这个问题时好时坏。
