### ISSUE TITLE
如果不按照mook的权限数据格式，修改权限控制

### ISSUE THREAD

**Issue by lpointer** [vueComponent/ant-design-vue-pro#227]
**Question**
现在我们后端返回的菜单数据和mook的菜单格式不一样的，如何做这个权限控制呢

**Describe the solution you'd like**
我们的后端返回的数据格式如下：
perms：是按钮权限，如sys:config:save = 新增按钮
{
	"msg": "success",
	"menuList": [{
		"menuId": 1,
		"parentId": 0,
		"parentName": null,
		"name": "系统管理",
		"url": null,
		"perms": null,
		"type": 0,
		"icon": "fa fa-cog",
		"orderNum": 0,
		"open": null,
		"list": [{
			"menuId": 42,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "供应商管理",
			"url": "organizationalManage/supplierManage",
			"perms": "",
			"type": 1,
			"icon": "",
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 2,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "管理员管理",
			"url": "modules/sys/user",
			"perms": null,
			"type": 1,
			"icon": "fa fa-user",
			"orderNum": 1,
			"open": null,
			"list": null
		}, {
			"menuId": 31,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "部门管理",
			"url": "modules/sys/dept",
			"perms": null,
			"type": 1,
			"icon": "fa fa-file-code-o",
			"orderNum": 1,
			"open": null,
			"list": null
		}, {
			"menuId": 3,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "角色管理",
			"url": "modules/sys/role",
			"perms": null,
			"type": 1,
			"icon": "fa fa-user-secret",
			"orderNum": 2,
			"open": null,
			"list": null
		}, {
			"menuId": 4,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "菜单管理",
			"url": "modules/sys/menu",
			"perms": null,
			"type": 1,
			"icon": "fa fa-th-list",
			"orderNum": 3,
			"open": null,
			"list": null
		}, {
			"menuId": 5,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "SQL监控",
			"url": "druid/sql",
			"perms": null,
			"type": 1,
			"icon": "fa fa-bug",
			"orderNum": 4,
			"open": null,
			"list": null
		}, {
			"menuId": 6,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "定时任务",
			"url": "modules/job/schedule",
			"perms": null,
			"type": 1,
			"icon": "fa fa-tasks",
			"orderNum": 5,
			"open": null,
			"list": null
		}, {
			"menuId": 27,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "参数管理",
			"url": "modules/sys/config",
			"perms": "sys:config:list,sys:config:info,sys:config:save,sys:config:update,sys:config:delete",
			"type": 1,
			"icon": "fa fa-sun-o",
			"orderNum": 6,
			"open": null,
			"list": null
		}, {
			"menuId": 30,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "文件上传",
			"url": "modules/oss/oss",
			"perms": "sys:oss:all",
			"type": 1,
			"icon": "fa fa-file-image-o",
			"orderNum": 6,
			"open": null,
			"list": null
		}, {
			"menuId": 36,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "字典管理",
			"url": "modules/sys/dict",
			"perms": null,
			"type": 1,
			"icon": "fa fa-bookmark-o",
			"orderNum": 6,
			"open": null,
			"list": null
		}, {
			"menuId": 29,
			"parentId": 1,
			"parentName": "系统管理",
			"name": "系统日志",
			"url": "modules/sys/log",
			"perms": "sys:log:list",
			"type": 1,
			"icon": "fa fa-file-text-o",
			"orderNum": 7,
			"open": null,
			"list": null
		}]
	}, {
		"menuId": 41,
		"parentId": 0,
		"parentName": null,
		"name": "机构管理",
		"url": "organizationalManage",
		"perms": "",
		"type": 0,
		"icon": "",
		"orderNum": 0,
		"open": null,
		"list": []
	}],
	"code": 0
}
**Additional context**
希望sendya帮忙看下获取给一个修改的思路

**Comment by sendya** [comment]
动态菜单那一块提供了很多的代码注释， 请按照结构做就行了。就一个名字的区别而已

**Comment by lpointer** [comment]
> 动态菜单那一块提供了很多的代码注释， 请按照结构做就行了。就一个名字的区别而已

我理解的是router.config这里的菜单吗 ？

{
    path: '/new-router',
    name: 'newRouter',
    redirect: '/new-router/ahaha',
    component: RouteView,
    meta: { title: '仪表盘', keepAlive: true, permission: [ 'dashboard' ] },
    children: [
    {
        path: '/new-router/ahaha',
        name: 'ahaha',
        component: () => import('@/views/dashboard/Analysis'),
        meta: { title: '分析页', keepAlive: false, permission: [ 'ahaha' ] }
    }
}

**Comment by sendya** [comment]
@lpointer 
https://github.com/sendya/ant-design-pro-vue/blob/feature/dynamic-menu/src/utils/routerUtil.js#L69-L92

**Comment by lpointer** [comment]
谢谢sendya

**Comment by tangniyuqi** [comment]
@sendya 
git下来没有找到这个文件 是怎么回事呢？
/src/utils/routerUtil.js
