### ISSUE TITLE
使用 <a-back-top /> 好像没有效果 

### ISSUE THREAD

**Issue by doocan** [vueComponent/ant-design-vue-pro#228]
使用 `ant-design-vue` 中的 `<a-back-top/>` 好像没有任何效果，一直触发不了

**Comment by sendya** [comment]
配置 `target`，请根据滚动元素来滚动，在 pro 中 默认的 window 是 100% 高，不能滚动

**Comment by doocan** [comment]
刚试了下，是因为 `global.less` 中的 `html { overflow: auto; }` 的原因，`auto` 的情况下配置 `target` 也没成功

**Comment by sendya** [comment]
已经在上一个版本中还原滚动条
