### ISSUE TITLE
关于移动端适配的文档帮助

### ISSUE THREAD

**Issue by anuger** [vueComponent/ant-design-vue-pro#230]
本人前端小白，最近有需求做个后台，使用了vue+ant-design技术栈，参考这个项目做的，但是在适配这块一直搞不懂，希望可以简单说一下解决适配的思路和使用到的技术，代码研究了半天每看懂。如果有文档的话麻烦发下连接，谢谢啦

**Comment by sendya** [comment]
README 上有本项目的文档。

本项目只能尽量适配移动端，但 ant design 本身就不是应用在移动端的组件库。

**Comment by anuger** [comment]
@sendya  在README里的文档上没有找到适配这一块的内容。因为我看这个项目尽量适配了移动端，所以比较想知道是怎么做的，前端经验少，有点好奇～

**Comment by sendya** [comment]
这个不是一两句就能说的明白的，你可以去查一下 媒体查询 @media 这个关键字。 然后还可以充分利用 antd 支持的栅格化布局

**Comment by anuger** [comment]
@sendya 好的，谢谢啦

**Comment by ZhuBoyang** [comment]
我也在做这个的适配，不过我看readme上完全没有关于适配方面的说明。所以我基本上是重写ant design vue在移动端显示的所有样式。如果有哪位大佬知道怎么适配的话，一定要告知我一哈。
