### ISSUE TITLE
导航菜单点击后，如果to路由被拦截，组件不会切换，但菜单高亮仍会切换到被点击菜单，导致显示和菜单不一致。

### ISSUE THREAD

**Issue by yichangle** [vueComponent/ant-design-vue-pro#235]
这种情况该如何处理，才能让组件显示和菜单保持同步呢？谢谢。

**Comment by sendya** [comment]
正常情况下，会被拦截的菜单都不会在菜单栏上，因为没权限。
特殊情况下，请自己 hack 拦截掉 Menu 组件的 `selectedKeys` 处理，不要让其加载被拦截的路由选中

**Comment by yichangle** [comment]
这里主要用途是在未保存数据的情况下阻止离开当前页面。
谢谢，修改menu.js，增加斜体加粗部分，就达到目的了。
const on = {
      select: obj => {
        _**if (obj.key !== this.$router.currentRoute.path) {           
          obj.selectedKeys = [this.$router.currentRoute.path]
        }**_
        this.selectedKeys = obj.selectedKeys
        this.$emit('select', obj)
      },
      openChange: this.onOpenChange
    }
