### ISSUE TITLE
项目指导页面中“引入外部模块”一节有缺陷

### ISSUE THREAD

**Issue by anuger** [vueComponent/ant-design-vue-pro#237]
### 问题描述：
> 按照文档操作时，页面显示错误，原因是未导入css文件

![image](https://user-images.githubusercontent.com/24793128/57281208-1261e680-70dd-11e9-8a01-b6a0f573d7c4.png)

### 修复：
> 按照官方加入未import的css

![image](https://user-images.githubusercontent.com/24793128/57281353-67056180-70dd-11e9-8db6-5fda6b358840.png)

**Comment by sendya** [comment]
引入外部组件只是一个例子来进行介绍怎么引入。一个组件的具体引入请直接参考组件官网提供需要引入的文件

**Comment by sendya** [comment]
具体你也可以看 https://pro.loacg.com/docs/import 文档底部的描述 
![image](https://user-images.githubusercontent.com/5404542/57286294-8bfed200-70e7-11e9-974f-b2b6b2a02646.png)

**Comment by anuger** [comment]
我的意思是可以的话，在文档上加上引入css的几行，毕竟作为一个有态度的开源项目，我们要尽可能的让文档完美、准确:-D

**Comment by sendya** [comment]
好的，多谢意见
