### ISSUE TITLE
组件缓存，为什么不用keep-alive元素的include属性实现？ 

### ISSUE THREAD

**Issue by ethan666** [vueComponent/ant-design-vue-pro#238]
**Is your feature request related to a problem? Please describe.**
RouteView.vue代码：
 render () {
    const { $route: { meta }, $store: { getters } } = this
    const inKeep = (
      <keep-alive>
        <router-view />
      </keep-alive>
    )
    const notKeep = (
      <router-view />
    )
    // 这里增加了 multiTab 的判断，当开启了 multiTab 时
    // 应当全部组件皆缓存，否则会导致切换页面后页面还原成原始状态
    // 若确实不需要，可改为 return meta.keepAlive ? inKeep : notKeep
    if (!getters.multiTab && meta.keepAlive === false) {
      return notKeep
    }
    return this.keepAlive || getters.multiTab || meta.keepAlive ? inKeep : notKeep
  }

**Describe the solution you'd like**
return   (
      <keep-alive :include="外部配置">
        <router-view />
      </keep-alive>
    )

**Describe alternatives you've considered**

**Additional context**

**Comment by sendya** [comment]
那你还要维护一个 includes 数据？

**Comment by ethan666** [comment]
> 那你还要维护一个 includes 数据？

嗯，要实现对指定组件缓存就得这么做吧
先实现功能，再优化。

**Comment by sendya** [comment]
目前的实现已经是可以使用的了。 如果在维护一个指定组件的缓存列表，工作量更大，易维护性也低

**Comment by zhaozhenghao1993** [comment]
你好，我发现不使用include属性的话，当路由为keep-alive:false时，和keep-alive:true的multiTab切换时会有keep-alive重新刷新的问题，我看vue-element-admin没有这个问题，就仿照他的写的include属性，由于是刚做完，不知道会不会有什么问题
![image](https://user-images.githubusercontent.com/33045226/57464511-74724580-72af-11e9-94fe-e1efe93af878.png)
![image](https://user-images.githubusercontent.com/33045226/57464600-910e7d80-72af-11e9-91a3-f3b987ae20f2.png)
![image](https://user-images.githubusercontent.com/33045226/57464652-ac798880-72af-11e9-8a2a-72ec7f362e34.png)
![image](https://user-images.githubusercontent.com/33045226/57464718-c61ad000-72af-11e9-9fb7-698caf890cc7.png)
![image](https://user-images.githubusercontent.com/33045226/57464746-d3d05580-72af-11e9-8004-a0efe332c98d.png)
![image](https://user-images.githubusercontent.com/33045226/57464786-ee0a3380-72af-11e9-9773-21acb8655e39.png)

**Comment by sendya** [comment]
可以

**Comment by rusenask** [comment]
hello, I like the idea of keep-alive but which lifecycle hook should I then use to refresh data when user changes back to the previous view?
I would normally use `mounted()` but with `</keep-alive>` it's just not firing anymore :) 

Edit: never mind, found it, it's `activated() {}`. Great project! :)

**Comment by xxclyn** [comment]
你好，请问你这个方法成功了吗。
我也尝试了和你类似的方法，但是遇到一个问题就是，路由嵌套多了，include对子路由就不生效了

**Comment by xxclyn** [comment]
> 你好，我发现不使用include属性的话，当路由为keep-alive:false时，和keep-alive:true的multiTab切换时会有keep-alive重新刷新的问题，我看vue-element-admin没有这个问题，就仿照他的写的include属性，由于是刚做完，不知道会不会有什么问题
> ![image](https://user-images.githubusercontent.com/33045226/57464511-74724580-72af-11e9-94fe-e1efe93af878.png)
> ![image](https://user-images.githubusercontent.com/33045226/57464600-910e7d80-72af-11e9-91a3-f3b987ae20f2.png)
> ![image](https://user-images.githubusercontent.com/33045226/57464652-ac798880-72af-11e9-8a2a-72ec7f362e34.png)
> ![image](https://user-images.githubusercontent.com/33045226/57464718-c61ad000-72af-11e9-9fb7-698caf890cc7.png)
> ![image](https://user-images.githubusercontent.com/33045226/57464746-d3d05580-72af-11e9-8004-a0efe332c98d.png)
> ![image](https://user-images.githubusercontent.com/33045226/57464786-ee0a3380-72af-11e9-9773-21acb8655e39.png)

你好，请问你这个方法成功了吗
我也用了和你类似的方法，但是出现一个bug就是 路由层级嵌套之后，include对子路由就失效了

**Comment by zhaozhenghao1993** [comment]
> > 你好，我发现不使用include属性的话，当路由为keep-alive:false时，和keep-alive:true的multiTab切换时会有keep-alive重新刷新的问题，我看vue-element-admin没有这个问题，就仿照他的写的include属性，由于是刚做完，不知道会不会有什么问题
> > ![image](https://user-images.githubusercontent.com/33045226/57464511-74724580-72af-11e9-94fe-e1efe93af878.png)
> > ![image](https://user-images.githubusercontent.com/33045226/57464600-910e7d80-72af-11e9-91a3-f3b987ae20f2.png)
> > ![image](https://user-images.githubusercontent.com/33045226/57464652-ac798880-72af-11e9-8a2a-72ec7f362e34.png)
> > ![image](https://user-images.githubusercontent.com/33045226/57464718-c61ad000-72af-11e9-9fb7-698caf890cc7.png)
> > ![image](https://user-images.githubusercontent.com/33045226/57464746-d3d05580-72af-11e9-8004-a0efe332c98d.png)
> > ![image](https://user-images.githubusercontent.com/33045226/57464786-ee0a3380-72af-11e9-9773-21acb8655e39.png)
> 
> 你好，请问你这个方法成功了吗
> 我也用了和你类似的方法，但是出现一个bug就是 路由层级嵌套之后，include对子路由就失效了

是的，在第三级目录的时候 keepalive 就失效了，这个是我用这个框架改成 include 做的 
http://106.12.21.222/monitor/performance/system
你会发现选择第三级的时候，会出现失效的问题，所以我现在只能保证两级菜单，尽量不要出现三级
