### ISSUE TITLE
代码修改后，无法热更新

### ISSUE THREAD

**Issue by ikilobyte** [vueComponent/ant-design-vue-pro#240]
系统：macOS 
浏览器：Google Chrome，版本 74.0.3729.131（正式版本） （64 位）
Pro版本：2.0.0

更改代码后，无法更新，这个很蛋疼啊。按照文档的流程来的
yarn install
yarn run serve
webSocket也正常，也有推送，但就是不更新页面

**Comment by laravelup** [comment]
从文更改任何配置，刚下载的代码

**Comment by ikilobyte** [comment]
从未更改任何配置，刚刚clone

**Comment by kokoroli** [comment]
![QQ20190508-165237](https://user-images.githubusercontent.com/25897806/57362676-e95f5580-71b1-11e9-9196-edc0bedec5f6.gif)

**Comment by kokoroli** [comment]
系统： macOS Mojave 10.14.4 
浏览器： 74.0.3729.131（正式版本） （64 位）

没能复现你所说的热更新失效

**Comment by ikilobyte** [comment]
稍等，我弄个动图给你看一下

**Comment by ikilobyte** [comment]
您好，请看我录制的视频
https://wujiao-app.oss-cn-shenzhen.aliyuncs.com/QQ20190508-170349-HD.mp4

**Comment by kokoroli** [comment]
项目是用 vue-cli3 构建，并没有修改热更新配置。可能是个人开发环境因素导致，建议你检查一下你的个人开发环境

**Comment by ikilobyte** [comment]
环境符合要求，vue-cli也是3.5.5版本

**Comment by sendya** [comment]
热更新不生效请自行寻找解决方案，本项目未对 Vue-CLI3 的热重载相关设置做任何改动。
并且全新 `clone` 的项目也无法复现你的问题。

ref #108

**Comment by jjandxa** [comment]
建议删除项目，关机重启再试一次（手动狗头

**Comment by ikilobyte** [comment]
我用vue-cli新创建空项目，都是可以热更新的，还有我的其它项目，都是可以热更新的，都是基于现在的环境。并非环境问题

**Comment by ikilobyte** [comment]
还有，我看了其它人也反馈了，有人说关机重启后能修复，。。。。我也试了，没用！

**Comment by ikilobyte** [comment]
不能热更新。。。这得浪费多少开发时间呢。

**Comment by ikilobyte** [comment]
能否加个QQ，或者哪位大神留下个QQ/微信，能即时联系的，请教一下如何解决

**Comment by sendya** [comment]
图例是与你所修改的地方一致，项目目前的用户数量挺高，而且也很多企业在用 如果不能热重载，早就炸锅了，怎么会让你一个人发现呢。我已经向前端组确认过，没有问题。 你还是在过一过自己的环境。比如清理掉 npm 或 yarn 的缓存，重装依赖等

![GIF2](https://user-images.githubusercontent.com/5404542/57364741-5ffe5200-71b6-11e9-9411-96fb87b75f47.gif)

**Comment by ikilobyte** [comment]
是一致的，因为我是刚刚clone下来的。找了很多后台，最后才确定选择这边。

**Comment by ikilobyte** [comment]
我下班后，用个人电脑再看一下能不能热更新吧。现在是公司电脑

**Comment by laravelup** [comment]
和yarn的版本有关

**Comment by ikilobyte** [comment]
和yarn的版本有关？？

**Comment by ikilobyte** [comment]
其它可以热更新的项目我是用npm，唯独这个是yarn，而且新clone项目，不做任何改动，按照文档来，都是无法热更新。请问和这个有关系吗

**Comment by ikilobyte** [comment]
果然！升级yarn版本就ok了。
