### ISSUE TITLE
table表格增加input编辑出现不能编辑情况

### ISSUE THREAD

**Issue by chenxi2015** [vueComponent/ant-design-vue-pro#241]
![C596800C-329D-4857-A283-05D7BDBF7C73](https://user-images.githubusercontent.com/13269485/57358249-97b1cd80-71a7-11e9-856b-5e2d0607af7a.png)
![7A90F8EC-4FA0-4c17-A368-0F0194827C81](https://user-images.githubusercontent.com/13269485/57358250-97b1cd80-71a7-11e9-844f-ddeae64120db.png)
![41CE9127-8423-40fe-82E8-F738E4162FF9](https://user-images.githubusercontent.com/13269485/57358252-97b1cd80-71a7-11e9-9b06-08384f9cd37d.png)

编辑只能输入一位数字

**Comment by sendya** [comment]
v-model
