### ISSUE TITLE
封装的S-table树形状态样式错乱

### ISSUE THREAD

**Issue by viewhang** [vueComponent/ant-design-vue-pro#243]
**Describe the bug**
将easy-mock的service 返回值中加children[]，生成的树形表格树形展开按钮和复选框在同一列。
如下图
![TIM图片20190509143239](https://user-images.githubusercontent.com/26957298/57432083-64cf0e80-7267-11e9-8157-37736f6a974a.png)
将s-table换成a-table正常显示
![image](https://user-images.githubusercontent.com/26957298/57432038-410bc880-7267-11e9-86a7-46d732dee040.png)
win10 Google Chrome 74.0.3729.131

**Comment by sendya** [comment]
`s-table` 不适合大量个性化配置的使用，封装主要针对普通业务列表。对树的 table 支持并不好。你可以直接使用 `a-table`
