### ISSUE TITLE
s-table 如何点击重置按钮时清空 sorter 排序 和 filters

### ISSUE THREAD

**Issue by keke122765** [vueComponent/ant-design-vue-pro#244]
1.点击重置时如何清空排序
![image](https://user-images.githubusercontent.com/44694221/57548378-5847d480-7393-11e9-9a37-026e46cf89c5.png)
2.实现列筛选 和 点击重置按钮清空列筛选
![image](https://user-images.githubusercontent.com/44694221/57548430-7d3c4780-7393-11e9-8f8e-094fb59af090.png)

**Comment by sendya** [comment]
参考 a-table 的实现自行控制即可 
https://vue.ant.design/components/table-cn/#components-table-demo-reset-filters-and-sorters
