### ISSUE TITLE
多页签模式下，个人设置页面bug

### ISSUE THREAD

**Issue by leslieeilsel** [vueComponent/ant-design-vue-pro#247]
如图：
![](https://raw.githubusercontent.com/leslieeilsel/Pictures/master/images/20190513154818.gif)
#### 重现步骤
- 打开多页签模式
- 打开个人设置页面
- 点击切换个人设置页面中不同的功能Tab，这时会打开多个页签
- 切换不同的页签，页面中的功能Tab的激活状态没有同步更新

#### 版本
ant-design-pro-vue：https://preview.pro.loacg.com 上的版本（2019-05-13 16:00）
Chrome：74.0.3729.131（正式版本） （64 位）
Windows：Win 10 教育版 1809

**Comment by meowYap** [comment]
你好，你的问题解决了嘛？我这边也有这样的需求，切换不同的页签时，不会像打开页签时一样加载页面的数据

**Comment by kokoroli** [comment]
`router.config.js`
![001A15D1-E6E6-4051-A90D-AAEC0FFA305F](https://user-images.githubusercontent.com/25897806/57709031-ecb87c80-769c-11e9-86c9-afd395e2f3eb.png)
`MulitTab.vue`
![EDCB0685-CAFB-4801-8307-758923E893AD](https://user-images.githubusercontent.com/25897806/57709039-ef1ad680-769c-11e9-8c16-b8a74bb61768.png)

这样可以解决你们当前的问题
需要注意的是**子路由**第一个不可设置`hiddenTabMenu`，`MulitTab.vue` 的 `created` 也需要做相应修改。

**Comment by meowYap** [comment]
> Mu

好的，非常感谢，我去试一试

**Comment by meowYap** [comment]
> `router.config.js`
> ![001A15D1-E6E6-4051-A90D-AAEC0FFA305F](https://user-images.githubusercontent.com/25897806/57709031-ecb87c80-769c-11e9-86c9-afd395e2f3eb.png)
> `MulitTab.vue`
> ![EDCB0685-CAFB-4801-8307-758923E893AD](https://user-images.githubusercontent.com/25897806/57709039-ef1ad680-769c-11e9-8c16-b8a74bb61768.png)
> 
> 这样可以解决你们当前的问题
> 需要注意的是**子路由**第一个不可设置`hiddenTabMenu`，`MulitTab.vue` 的 `created` 也需要做相应修改。

你好，我这边的问题和原问题还是有点区别，我的问题和 https://segmentfault.com/q/1010000016866230/a-1020000017766085 这里描述的问题更类似，两个路由使用同一组件时，数据会覆盖，不再去请求新的数据，请问该如何解决

**Comment by sendya** [comment]
@MonyaPeng 无解，请直接重新渲染页面。或者强制触发 update 周期

**Comment by meowYap** [comment]
> @MonyaPeng 无解，请直接重新渲染页面。或者强制触发 update 周期

谢谢答复，我再尝试一下
