### ISSUE TITLE
补充一下图表内容，柱状图。

### ISSUE THREAD

**Issue by dengclcl** [vueComponent/ant-design-vue-pro#248]
**Question**
How to use component `s-table` paging

**Describe the solution you'd like**

**Additional context**

**Comment by sendya** [comment]
你可以自行寻找想要的图表，引入使用即可。
https://viserjs.github.io/docs.html#/viser/guide/installation

**Comment by dengclcl** [comment]
谢谢，我可以实现我的图标功能了。
