### ISSUE TITLE
表单下拉框定位错误

### ISSUE THREAD

**Issue by Cacaci** [vueComponent/ant-design-vue-pro#249]
![Bug_2019-05-14_17-12-24](https://user-images.githubusercontent.com/22025787/57686386-19a06b80-766c-11e9-8434-4fd4f2b604d7.png)

移除`/src/components/global.less`文件下body { overflow-y: scroll; }样式即可

**Comment by sendya** [comment]
fixed #commit d2d3f3bd79316ca13e5b0fccde368d83d23ceb1a
