### ISSUE TITLE
vue 多标签页面切换页面问题，路由取消缓存失效

### ISSUE THREAD

**Issue by sky-rainy** [vueComponent/ant-design-vue-pro#252]
路由已经设置 keepAlive:false 但是 跳转详情页面的数据获取的还是第一次的数据，取消缓存失效。。应该怎么设置啊？？？？？？？？？？？？？？？？？？

**Comment by sendya** [comment]
多标签 无法取消 keepAlive ，这属于一个强制性设定，并且 多标签 是一个不受长期支持的组件。进后可能会取消该组件的支持和维护

**Comment by sky-rainy** [comment]
好的，谢谢回复



------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 下午2:21
收件人: "sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com>; 
抄送: "Dragon"<1923021@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sendya/ant-design-pro-vue] vue 多标签页面切换页面问题，路由取消缓存失效 (#252)




多标签 无法取消 keepAlive ，这属于一个强制性设定，并且 多标签 是一个不受长期支持的组件。进后可能会取消该组件的支持和维护

**Comment by liresky** [comment]
@sendya 想问下不考虑支持多标签的一个原因和考虑？
在国内多数企业系统里多任务同时处理还是个很常见的场景，而且多数用户对计算机的应用不深入，多标签是个很有用的界面或者说布局模式。

**Comment by sendya** [comment]
@liresky 这是一个伪功能，并且也不是 antd 或者说已经不符合前端单页应用的东西。并且性能消耗也很过。如果你愿意，你可以采用曾经的 iframe 方式去实现。

**Comment by liresky** [comment]
@sendya 这东西不适合互联网产品的逻辑好像没问题，antd pro也明确说了这个功能不符合他们内部业务场景。不过这个伪功能您是怎么认识的，请教下，如果是个伪功能是不是可以用别的方案代替，我也学习下，下次跟客户好沟通

**Comment by sendya** [comment]
@liresky 这本身就不是真的多标签页面，都是模拟出来的，靠的是把其他页面隐藏掉。
而以前用 iframe 实现的才可以说是真实多标签页，每个页面变量等不互相干扰。

**Comment by wenxiayili** [comment]
@sendya 如何开启这个功能呢？
