### ISSUE TITLE
查询表格根据权限显示操作

### ISSUE THREAD

**Issue by Lninn** [vueComponent/ant-design-vue-pro#253]
用管理员登陆之后，查询表格的批量操作无法使用。
代码用的 action 是 edit, 接口返回的好像是 update 

https://github.com/sendya/ant-design-pro-vue/blob/dde01c1a49a4691e40ace02ed8b274519f7be455/src/views/list/TableList.vue#L67

**Comment by sendya** [comment]
preview 中的项目并不是真实数据，不可能完全控制。仅作为参考
