### ISSUE TITLE
modal中嵌入表单，setFiledsValue无效

### ISSUE THREAD

**Issue by vishellhj** [vueComponent/ant-design-vue-pro#255]
我在编辑中使用了modal弹出表单来执行修改的操作，把当前行的数据传入modal中，然后用如下方法设置表单内容：
        this.$nextTick(() => {
          let recordInfo = pick(record, ['title', 'index', 'intro', 'video', 'show'])
          setFieldsValue(recordInfo)
        })

第一次可以成功设置，关闭了modal后再点另外的修改，表单无内容，关掉modal，再点同一行的编辑，表单内容已填充，关掉，点另一行的编辑，又是无内容。

我把recordInfo打印出来，每次都有新的那一行信息没错，控制台无错误弹出

**Comment by vishellhj** [comment]
后来我用一种迂回的方式解决了此问题，但这种解决方式不大正常

      if(this.created){
        let recordInfo = pick(record, ['title', 'index', 'intro', 'video', 'show'])
        setFieldsValue(recordInfo)
      }else{
        this.$nextTick(() => {
          this.created = true
          let recordInfo = pick(record, ['title', 'index', 'intro', 'video', 'show'])
          setFieldsValue(recordInfo)
        })
      }

加了一个判断后，如果有初始化过就不用$nextTick()可以解决这个问题。

**Comment by sendya** [comment]
请使用 https://codesandbox.io/s/2wpk21kzvr 复现
