### ISSUE TITLE
vue.config.js 怎么配置多个域名？路由问题！

### ISSUE THREAD

**Issue by sky-rainy** [vueComponent/ant-design-vue-pro#257]
在配置文件里
`  devServer: {
    // development server port 8000
    port: 8000,
    proxy: {
      '/api': {
        target: 'https://mock.ihx.me/mock/5baf3052f7da7e07e04a5116/antd-pro',
        ws: false,
        changeOrigin: true
      },
    }
  }`

怎么配置第2个域名？ 可以配置吗？
还有就是，动态路由的设置，还不是很明确。。。能多给点指导吗？
@sendya

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/issues/91

**Comment by sky-rainy** [comment]
> [＃91](https://github.com/sendya/ant-design-pro-vue/issues/91)

谢谢，指点，已配好，还有请问rbac的表结构和路由表结构。。。有吗？给一份可以么。

**Comment by sendya** [comment]
![](https://camo.githubusercontent.com/aee237f6349dfb932d927e5a58b8fabb157e2446/68747470733a2f2f7374617469632d322e6c6f6163672e636f6d2f6f70656e2f7374617469632f6769746875622f7065726d697373696f6e732e706e67)

**Comment by sky-rainy** [comment]
静态里有mate： keepAlive  ，动态路由里怎么设置的？  是要mate再给个数组吗
