### ISSUE TITLE
vue.config.js 配置多个域名，request.js base_url该如何处理

### ISSUE THREAD

**Issue by roneywei** [vueComponent/ant-design-vue-pro#258]
vue.config.js 怎么配置多个域名

我现在项目有多个服务，一个是订单服务，一个是购物车服务

       '/order': {
   target: 'http://127.0.0.1:8080', //mock API接口系统
   ws: false,
   changeOrigin: true,
   pathRewrite: {
     '/order': ''  //默认所有请求都加了admin-sso前缀，需要去掉
   }
 },

      '/cart': {
        target: 'http://127.0.0.1:8080', //mock API接口系统
          ws: false,
          changeOrigin: true,
          pathRewrite: {
          '/cart': ''  //默认所有请求都加了admin-sso前缀，需要去掉
        }
      },
但是在request里面有一个base_url,我应该怎么处理呢

![image](https://user-images.githubusercontent.com/5858867/58075190-a94c9980-7bd9-11e9-81c1-91fd97001bd4.png)

**Comment by sendya** [comment]
使用 / 或者你们自定一个值，它能匹配到所有 api 即可
