### ISSUE TITLE
更改dark模式主题颜色，代码更新了，但是颜色没变

### ISSUE THREAD

**Issue by changhighly** [vueComponent/ant-design-vue-pro#259]
我想更改左侧和上方菜单的主题颜色，想把dark模式下的颜色换个颜色值，把color.less中的background：#001529的颜色值换成#ff6700，在浏览器中审查元素发现起效果是的color.less中5455行的
.ant-menu-dark,
.ant-menu-dark .ant-menu-sub {
  color: rgba(255, 255, 255, 0.65);
  background: #001529;
}
把    background: #001529;改为    background: #ff6700;
但是编译之后，审查元素，    background: 值还是    #001529;，把color.less中所有的#001529换成#ff6700也不生效！

**Comment by sendya** [comment]
`color.less` 是用于在线样式覆盖动态编译的样式文件，不可用于正常覆盖 ant 样式。

覆盖 ant 样式请参考 antd vue 官方文档，或采用全局样式覆盖，或局部样式穿透
