### ISSUE TITLE
table组件prop设置showPagination false控制台报错

### ISSUE THREAD

**Issue by C-somnus** [vueComponent/ant-design-vue-pro#267]
**Describe the bug**
table组件prop设置showPagination false控制台报错

**To Reproduce**

**Comment by sendya** [comment]
报什么错？

**Comment by C-somnus** [comment]
不能全部显示所有的表格数据
ant-design-vue的table组件props里pagination ----报custom validator check failed for prop
组件table里render函数 268行
if (localKeys.includes(localKey)) {
        props[k] = this[localKey]
       /***我的修改
        if (k === 'pagination' && !this.showPagination) props[k] = false
        return props[k]
 }

**Comment by zhangmrit** [comment]
加个判断

**Comment by sunpe** [comment]
我修复了这个问题, 提了merge fixes error when set property is false #272

**Comment by wenxiayili** [comment]
> 报什么错？

我今天也遇到了：Invalid prop: custom validator check failed for prop "pagination".  我的代码：showPagination="false"
请问在哪个版本可以用？？？？
