### ISSUE TITLE
pro里加载了很多其他地方的svg，怎么设置下载到本地呢

### ISSUE THREAD

**Issue by bingheyiomiao** [vueComponent/ant-design-vue-pro#268]
https://gw.alipayobjects.com/zos/rmsportal/JopDzEhOqwOjeNTXkoje.svg
https://gw.alipayobjects.com/zos/rmsportal/KDNDBbriJhLwuqMoxcAr.svg
这一些怎么弄到本地，或者静态资源里加载

**Comment by mynuolr** [comment]
？？？？？？？？？？？？？？？？？？？？

**Comment by sendya** [comment]
手动下载到本地

**Comment by bingheyiomiao** [comment]
建议把这些都弄到本地静态文件，有些公司的开发是无网的状态，或者网络很慢，会影响开发

> 手动下载到本地
