### ISSUE TITLE
怎么支持IE呢？

### ISSUE THREAD

**Issue by dnstfly** [vueComponent/ant-design-vue-pro#27]
您好，请问怎么支持IE？当前项目启动后，不能再IE10~11下运行

**Comment by dnstfly** [comment]
已经解决了，解决思路：
1、修改babel.config.js 为：
`module.exports = {
  presets: [
    ['@vue/app', {
      "useBuiltIns": "entry"
    }]
  ]
}`
2、在入口文件main.js中导入：
`import '@babel/polyfill'`

测试：

- IE11 运行良好

- IE10 界面错位

- IE9控制台报错：**matchMedia not present, legacy browsers require a polyfill**

**Comment by sendya** [comment]
现代浏览器和 IE9 及以上（需要 [polyfills](https://vuecomponent.github.io/ant-design-vue/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7)）

 babel-polyfill 和 babel-plugin-transform-runtime

**Comment by yundingy** [comment]
> 现代浏览器和 IE9 及以上（需要 [polyfills](https://vuecomponent.github.io/ant-design-vue/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7)）
> 
> babel-polyfill 和 babel-plugin-transform-runtime

是babel-polyfill 和 babel-plugin-transform-runtime都需要吗?
我只引了babel-polyfill, IE9上报错matchMedia not present, legacy browsers require a polyfill

**Comment by jiufengdadi** [comment]
module.exports = {
  presets: [
    '@vue/app',
    [
      '@babel/preset-env',
      {
        'useBuiltIns': 'entry'
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "absoluteRuntime": false,
        "corejs": false,
        "helpers": true,
        "regenerator": true,
        "useESModules": false
      }
    ]
  ]
}

已经配了插件，但貌似媒体查询不能转啊
matchMedia not present, legacy browsers require a polyfill

这个是在哪个功能用到了？我们项目希望支持到ie9
@sendya 远子大佬

**Comment by sendya** [comment]
只支持 IE10 及以上，IE9 不支持。如果你有能力重构该方法，你可以自己尝试
