### ISSUE TITLE
请问怎么删了登陆页

### ISSUE THREAD

**Issue by YuppyHub** [vueComponent/ant-design-vue-pro#270]
**Question**
ant ui 很漂亮， 我想用 ANT 做一个类似于博客系统

**Describe the solution you'd like**
进入 http://localhost:8000 后如果没有登陆的话， 是会被 login 拦截了跳转到 login 页面

**Additional context**
请问怎么删除 login 页面， 我不想被拦截， 我删除 permission.js 后所有的页面都不能显示了， 请你帮帮我，谢谢了~

**Comment by sendya** [comment]
https://pro.loacg.com/docs/remove-authority-management
