### ISSUE TITLE
项目build后导航设置等无效

### ISSUE THREAD

**Issue by orilla-cn** [vueComponent/ant-design-vue-pro#271]
**Question**
项目build后侧导航如何变为顶部导航

**Describe the solution you'd like**
开发者模式下设置侧面导航为顶部导航后，build项目后，设置没有生效

**Additional context**
在config目录下defaultsetting设置后biuld也无效

**Comment by sendya** [comment]
清空 localStorage 或者不要和本地开发相同域名地址

**Comment by orilla-cn** [comment]
谢谢，是应该在每次build之前清空localstorage吗

**Comment by sendya** [comment]
那只是本地设置，完全不影响其他人，你自己不访问那么不清也行

**Comment by orilla-cn** [comment]
好的，谢谢你

**Comment by orilla-cn** [comment]
你好，清空localStorage无效啊，在其他机器上访问也是一样的，还是侧面导航

**Comment by sendya** [comment]
配置栏只在开发环境用于预览，生产环境不会展现，请手动修改配置文件 src/config/defaultSettings.js

**Comment by orilla-cn** [comment]
谢谢
