### ISSUE TITLE
排序表示多了end

### ISSUE THREAD

**Issue by zhangmrit** [vueComponent/ant-design-vue-pro#273]
descend ascend
这个如何自定义

**Comment by sendya** [comment]
无法自定义。官方组件不支持，我查阅过 react ant 也无法支持

**Comment by sendya** [comment]
另外这个建议我会向官方开发组记录，你可以后期关注 https://github.com/vueComponent/ant-design-vue 的新动态，如果这个功能有加上，应该会在 changelog 列出

**Comment by zhangmrit** [comment]
thanks
