### ISSUE TITLE
在 pro-vue里面封装的table 怎样设置行的checkbox的disable属性

### ISSUE THREAD

**Issue by curiousPeng** [vueComponent/ant-design-vue-pro#274]
**Question**
在 pro-vue里面封装的table 怎样设置行的checkbox的disable属性，因为有的行不需要被选中了。

**Comment by sendya** [comment]
问题在最新提交中，已经修正。你可以对比 `Table/index.js`  的 commit 更新到你本地

**Comment by curiousPeng** [comment]
thank you !
