### ISSUE TITLE
请问build后,我想直接打开dist的index本地查看效果,需要怎么修改配置?

### ISSUE THREAD

**Issue by FrontEnd-Hub** [vueComponent/ant-design-vue-pro#277]
请问build后,我想直接打开dist的index本地查看效果,需要怎么修改配置?
- build后直接打开index文件资源无法加载显示白屏, 如何修改可以实现纯静态本地查看?
谢谢!

**Comment by sendya** [comment]
请去阅读 Vue 官方文档

**Comment by FrontEnd-Hub** [comment]
![image](https://user-images.githubusercontent.com/46841851/58698043-124bc280-83cd-11e9-9863-082d0ff3c05e.png)
单纯在vue,config.js中配置,打包报错
![image](https://user-images.githubusercontent.com/46841851/58698087-2db6cd80-83cd-11e9-982b-cd89a9b32749.png)

**Comment by sendya** [comment]
@FrontEnd-Hub https://github.com/sendya/ant-design-pro-vue/issues/91

**Comment by wangshaoan** [comment]
publicPath: process.env.NODE_ENV === 'production'?'':'/',  //vue.config.js
  // mode: 'history',//路由

**Comment by miaomiaogege** [comment]
你的设计思路真的是太混乱了
