### ISSUE TITLE
建议增加一些常用组件：富文本/markdown编辑器组件,  城市联动组件，图片裁切组件

### ISSUE THREAD

**Issue by huaiguoguo** [vueComponent/ant-design-vue-pro#278]
**Is your feature request related to a problem? Please describe.**
在表单中常常要编辑富文本或者markdown文本，或者要填写城市，商品图片裁切

**Describe the solution you'd like**
建议增加一些常用组件：富文本/markdown编辑器组件,  城市联动组件，图片裁切组件

**Describe alternatives you've considered**
备选的是  iview 的城市联动和图片裁切和富文本/markdown编辑器，但是我怕有冲突，iview的风格界面设计不一致，放在一起不好看

**Additional context**

**Comment by sendya** [comment]
富文本在 /components 中有提供两款

图片裁剪也有提供，参考 个人设置（商品图片裁剪 这种东西都属于业务功能了，请自己根据现有组件扩展）

联动组件 antd 自带，根据自己业务提供数据即可
