### ISSUE TITLE
新拉取的项目，修改主题页面并没任何变化

### ISSUE THREAD

**Issue by bing127** [vueComponent/ant-design-vue-pro#279]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sendya** [comment]
试试请清理本地 localStorage。

另外，请描述清楚问题，根据格式

**Comment by Kchengz** [comment]
> 试试请清理本地 localStorage。
> 
> 另外，请描述清楚问题，根据格式

我的也是，新拉取的项目修改配置栏里的主题色无变化，尝试清理了localStorage

**Comment by sendya** [comment]
ref 8f7600143be405cf8de6c950070ac7a80abb1235
ref package https://github.com/hzsrc/webpack-theme-color-replacer

该文档待我考虑一下怎么处理

**Comment by hzsrc** [comment]
试下新的，这个应该解决了：
https://github.com/sendya/ant-design-pro-vue/pull/293
