### ISSUE TITLE
build后dist中缺少文件

### ISSUE THREAD

**Issue by MalavitaC** [vueComponent/ant-design-vue-pro#280]
我build以后dist中会缺少这些文件
![image](https://user-images.githubusercontent.com/38742840/58787627-ca22df00-861c-11e9-8677-fea515e61b3d.png)
但是我同事build以后是完整的，我们两个的代码是同样的
由于是刚开始做全栈开发所以对build不是很了解

**Comment by sendya** [comment]
请提供完整的环境 和使用场景，一张图给我猜也猜不出答案的
