### ISSUE TITLE
日期选择器月份选择器选择了月份不会自动关闭

### ISSUE THREAD

**Issue by Everytimeyumi** [vueComponent/ant-design-vue-pro#282]
日期选择器设置了成了月份选择，选择了开始月份和结束月份他不会自动关闭 大佬们有什么办法可以设置关闭吗 ？
![image](https://user-images.githubusercontent.com/30947975/58932927-39710e00-8798-11e9-8587-140e4bac7284.png)

- [ ]

**Comment by sendya** [comment]
这是组件问题，提交到 https://github.com/vueComponent/ant-design-vue  repo 去，另外，需要提供 codesandbox 复现
