### ISSUE TITLE
最新master版本启动按需加载报错

### ISSUE THREAD

**Issue by free-pan** [vueComponent/ant-design-vue-pro#287]
**Describe the bug**
`babel.config.js`将按需加载的注释去除,然后启动,会报错:

```
ReferenceError: Antd is not defined
```

**To Reproduce**
1. 在`babel.config.js`中启用按需加载
2. 重新启动`yarn run serve`
3. 一直显示加载中图标
4. 控制台报错`ReferenceError: Antd is not defined`

**Desktop (please complete the following information):**
  - OS: macOS 10.14.5
 - Browser chrome
 - Version 74.0.3729.169（正式版本） （64 位）

**Comment by sendya** [comment]
请按照 [Ant Design Vue](https://vue.ant.design/docs/vue/introduce-cn/) 文档配置按需
