### ISSUE TITLE
登录出现错误提示

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue-pro#288]
**Describe the bug**
注册帐号页，密码提示错误，在登录也提示不消失

**To Reproduce**

1. 跳转注册页，输错帐号密码
2. 跳转登录页，错误提示框没有消失

**Expected behavior**
登录页不显示错误提示

**Screenshots**
![image](https://user-images.githubusercontent.com/17247526/59199275-290dc880-8bc8-11e9-85a8-137a1508e7d2.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sendya** [comment]
已知 bug
