### ISSUE TITLE
按需加载

### ISSUE THREAD

**Issue by bingheyiomiao** [vueComponent/ant-design-vue-pro#289]
请问文档按需加载的这句话是什么意思

开启组件按需加载 /src/main.js L7 修改为 import './core/lazy_use'

是第七行修改为这句话 ，还是直接加入这句话

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/main.js#L14

```js
import './core/use'
```

修改为

```js
import './core/lazy_use'
```

并且开启 [babel.config.js](https://github.com/sendya/ant-design-pro-vue/blob/master/babel.config.js) 配置中的按需配置项

**Comment by bingheyiomiao** [comment]
感谢
