### ISSUE TITLE
编译、打包比较慢，编译需要4分多钟，打包7分多钟，热更新--JS stacktrace，node内存溢出

### ISSUE THREAD

**Issue by changhighly** [vueComponent/ant-design-vue-pro#290]
现在项目有点大了，使用yarn run serve，项目跑起来有时需要4分多钟
<img width="434" alt="WX20190612-143149@2x" src="https://user-images.githubusercontent.com/22925367/59328429-f1fdfb00-8d1e-11e9-8207-57e09a7a8b03.png">

 项目起来后，修改代码，自动热更新时，报---JS stacktrace

build的时候有时候需要7分钟左右
百度了下网上，看他们的解决办法很多都是装插件，让单线程变多线程，开辟内存空间max_old_space_size=4096等等，想知道咱们官方的解决办法，提升编译和打包速度，以及解决内存泄露问题，谢谢！！

**Comment by sendya** [comment]
#90

**为了更好的解决你的问题, 建议在发表前, 先浏览以下内容。**

## issue

- 提供你的系统信息(发行版名字，版本号，浏览器等)。
- 提供你所使用的 Pro 版本。可以对比 github 上的版本列表页, 看看是否为最新版, 也许你的问题在新版本中已经修复了。
- 尽量详细描述你的问题，以及这个问题是如何出现的，最好能把 操作步骤大概说一下，以便我能重现这个问题。可以通过截图，录屏，浏览器`Console`报错等方式提交更多的信息。
- 超过 7 天未对 `Contributors` 的回复进行反馈的，默认将认为已解决关闭 Issue
- **请使用提供的 Issue 模板格式发布**
- **提问前请确认已经查找过** [Vue 文档](https://cn.vuejs.org/v2/guide/) | [Vue-Cli3](https://cli.vuejs.org/zh/guide/) | [Ant Design Vue](https://vue.ant.design/docs/vue/introduce-cn/) | [Webpack](https://webpack.docschina.org/configuration/) | [Cli3 完全配置例示](https://github.com/staven630/vue-cli3-config)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/59329265-15c24080-8d21-11e9-924b-91360e10eeed.png)
