### ISSUE TITLE
怎么关闭mock数据？

### ISSUE THREAD

**Issue by euii** [vueComponent/ant-design-vue-pro#294]
**Question**
怎么关闭mock数据？

**Describe the solution you'd like**
我是后端工程师，同时开发前后端，我想知道如何关闭mock数据，打开的vue.config.js里的devServer也不行，难道只能是打包之后才能关闭mock数据吗？
请教，如果想在开发的时候关闭mock服务，应该如何操作？

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/main.js#L11
