### ISSUE TITLE
打包后头像显示不出来

### ISSUE THREAD

**Issue by gou95275** [vueComponent/ant-design-vue-pro#295]
打包后我在vue.config.js里更改了发布路径，也就是发布到env路径下
publicPath: process.env.NODE_ENV === 'production' ? '/env/' : '/'

其他文件路径没问题，能正常访问，但theme-colors.css 和头像avatar的路径还是如下这样，导致了404
https://gou95275/avatar2.jpg
https://gou95275/css/theme-colors.css

应为如下才对：
https://gou95275/env/avatar2.jpg
https://gou95275/env/css/theme-colors.css

**Comment by sendya** [comment]
那你就自己修改一下文件路径，毕竟是硬编码写死的

**Comment by qyb** [comment]
avatar2.jpg 头像出不来的原因应该是这个资源是 mock 返回的，没有通过打包处理；但是 theme-colors.css 为啥出不来我还正在研究..
