### ISSUE TITLE
请问怎么设置一开始左侧菜单关闭

### ISSUE THREAD

**Issue by miaomiaogege** [vueComponent/ant-design-vue-pro#298]
首先 项目非常好 可是对于低级我这种小白玩家 目录结构实在是太迷了 无法清晰的知道各种底层的修改逻辑 单纯的功能 还比较容易 可是细节修改就很难受了
 我希望第一 可以重新编排一下目录结构 
第二 我想咨询一下如何把左侧菜单从默认打开 变成默认关闭

第三 希望这不是一个kpi 项目 再次表示对你们贡献的感谢

**Comment by sendya** [comment]
第一，目录结构已经很清晰了。你可以对比其他开源 admin 项目

第二 设计上菜单就是默认展开
    如果不想展开 1 可以写死变量。 2 可以 commit 一个关闭菜单的 state 

第三 这项目 **目前** 没有归属到任何一个组织

**Comment by sendya** [comment]
另外，你希望我重排，那么你有什么比较好的重排建议吗？

**Comment by jjandxa** [comment]
建议自己写个

**Comment by miaomiaogege** [comment]
谢谢  我觉得也许是加了 vuex 之后 使得整个项目面目全非 期待有更好的解决方式 其实我更希望有一种显示的状态树 能够随时调用 而不是通过这种 管道式的调用 因为这非常hack 侵蚀了业务层的逻辑

**Comment by miaomiaogege** [comment]
为了获取可追踪的状态 强行构建了整一个状态周期 在频繁的变量交互中 这种方式 实在是令人难以接受 虽然本身 本人是一个小白玩家 可是 已经感觉到了非常难受 这样不友好的体验 我觉得会在不久的将来得到解决

**Comment by miaomiaogege** [comment]
另外 现在的项目感觉 已经是 【交互】》【状态】》【数据】》【view】从设计角度讲 现在已经是状态分析设计项目角度理解了 好久没写前端了 回来之后思维模式还没跟上 我再想想

**Comment by miaomiaogege** [comment]
你说的 解决方案 不符合需求 写死我需求是 刚开始默认左侧折叠 然后可以开启 第二 写一个状态  状态本身就有 我想问的是 为何刚开始是 开启的 通过改什么 能够变换一下 初始样式 这是一个小需求 我觉得应该是可配置的

**Comment by miaomiaogege** [comment]
官方的是可配置的 不知道为何到你这里 通过修改变量初始值 并不能生效

**Comment by mynuolr** [comment]
本项目跟不上你的水平。请自己实现吧

**Comment by sendya** [comment]
@miaomiaogege

> 官方的是可配置的 不知道为何到你这里 通过修改变量初始值 并不能生效

哪个 官方 的？

**Comment by sendya** [comment]
@miaomiaogege

如果你觉得 Vuex 不符合你的需求，你可以重构，使用市面上其他的状态管理插件，或者更简单的，变量挂在 window 上，都是可以实现的。

至于你上述看法，状态管理在 ant pro 这种较大型的项目上，完全符合 Vuex 的逻辑。你可以去参考其他开源项目所使用的 Vuex 结构，是否跟本项目相差无几。

给你列个需要修改的文件地址，另外 如果是修改初始值 要生效必须清空 `LocalStorage`
https://github.com/sendya/ant-design-pro-vue/blob/master/src/core/bootstrap.js#L19
https://github.com/sendya/ant-design-pro-vue/blob/master/src/utils/mixin.js#L60

> 附： 对 `AppDeviceEnquire` 进行修改，将会导致响应式改变菜单状态出现状态违背，希望你自己能解决。对于修改这个状态产生的问题，我将不接受任何反馈。

最后，我接受对项目好的意见。但我不接受主观因数过强，并且没经过实际测试和经过生产环境考验的
