### ISSUE TITLE
在左侧增加一个新的菜单，点击后，右侧白页面

### ISSUE THREAD

**Issue by euii** [vueComponent/ant-design-vue-pro#299]
**Question**
如何增加一个新的左侧菜单？

**Describe the solution you'd like**
在/下，复制任意一个children路由片段，将name与path改名；刷新后左侧会出现一个新的菜单选项，但是点击后右侧是白页面。
对于增加菜单我还需要做些什么吗？我漏掉了什么？
遇到这种情况，应该如何debug？

**Additional context**
新添加router.js部分
![Xnip2019-06-22_01-53-30](https://user-images.githubusercontent.com/701552/59941800-b38bdd00-9490-11e9-8b0e-8f58dbfbfe43.jpg)

浏览器截图
![Xnip2019-06-22_01-36-29](https://user-images.githubusercontent.com/701552/59940852-58f18180-948e-11e9-9a39-13a4b39514c8.jpg)

**Comment by sendya** [comment]
vue-router 需要有 view 承载它，请查阅 vue-router 用法和 api

**Comment by euii** [comment]
谢谢，academy-lib下 增加了 component: pageview 就可以工作了。
我去好好研究一下文档。🙏️
