### ISSUE TITLE
sidebar can not shrink

### ISSUE THREAD

**Issue by peter527** [vueComponent/ant-design-vue-pro#30]
sidebar can not shrink

**Comment by sendya** [comment]
the branch you pulled is feature/antd-vue1.2.0 ?

**Comment by peter527** [comment]
same issue

**Comment by sendya** [comment]
If you switch from branch other to *master*, required reinstall dependencies

**Comment by peter527** [comment]
> If you switch from branch other to _master_, required reinstall dependencies

i remove the whole project

**Comment by sendya** [comment]
I tested without the bug you described, do you have a demo?

**Comment by peter527** [comment]
> I tested without the bug you described, do you have a demo?

i run it on my own pc, no web link

**Comment by sendya** [comment]
![20181218115116](https://user-images.githubusercontent.com/5404542/50131019-3e5e0600-02bb-11e9-9b91-122ff8cdfae2.jpg)
~~お兄さんが大好きです~~



***I can't help for you. sorry***

**Comment by peter527** [comment]
> @peter527 GlobalHeader.vue , change click.native to click, it can work, I test it

ok, i will check it

**Comment by peter527** [comment]
> @peter527 GlobalHeader.vue , change click.native to click, it can work, I test it

it works, thanks

**Comment by naixinxiaozi** [comment]
the root cause may be the version of ant-design-vue

**Comment by sendya** [comment]
recommend ant-design-vue `1.1.10` , Not yet supported `^1.2.0` 

And package management [YARN](http://yarnpkg.org/) is recommend ( yarn.lock file).

**Comment by peter527** [comment]
> recommend ant-design-vue `1.1.10` , Not yet supported `^1.2.0`
> 
> And package management [YARN](http://yarnpkg.org/) is recommend ( yarn.lock file).

OK, thanks
