### ISSUE TITLE
登录提示路由找不到dashboard

### ISSUE THREAD

**Issue by tangniyuqi** [vueComponent/ant-design-vue-pro#300]
**Question**
登录页面提交后提示：Route with name 'dashboard' does not exist
这个路由name在router.config.js里面明明是存在的，请问是怎么回事呢？

**Comment by sendya** [comment]
动态路由的通病，不影响使用就无所谓了。

**Comment by tangniyuqi** [comment]
有点强迫症。。好嘛忍了 谢谢！
