### ISSUE TITLE
有大神能分享一下多级菜单的SQL数据结构吗？（非json）

### ISSUE THREAD

**Issue by tangniyuqi** [vueComponent/ant-design-vue-pro#301]
谢谢~

**Comment by sendya** [comment]
```sql
CREATE TABLE `t_permission` (
  `id` varchar(32) NOT NULL,
  `name` varchar(128) NOT NULL,
  `actions` text,
  `describe` varchar(257) DEFAULT NULL,
  `parent` varchar(32) DEFAULT NULL,
  `component` varchar(255) NOT NULL,
  `icon` varchar(30) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  `sort` int(10) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by tangniyuqi** [comment]
3Q

**Comment by bing127** [comment]
> ```sql
> CREATE  TABLE ` t_permission `（
>    ` ID `  VARCHAR（32）NOT NULL，
>    `名`  VARCHAR（128）NOT NULL，
>    `动作` 文本，
>    `描述`  VARCHAR（257）DEFAULT NULL，
>    `父`  VARCHAR（32）DEFAULT NULL，
>    `部件`  VARCHAR（255）NOT NULL，
>    `图标`  VARCHAR（30）DEFAULT NULL，
>    `路径`  VARCHAR（255）DEFAULT NULL，
>    `排序`  INT（10）DEFAULT ' 0 '，
>    PRIMARY KEY（` ID `）
> ）ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
> ```

大佬，能否把用户-角色-菜单-权限这几张表给共享下，谢谢了大佬
