### ISSUE TITLE
treeSelect在完全受控（treeCheckStrictly）情况下有没有办法实现选中子节点的时候勾选对应的父节点，父节点选中时子节点不需要选中，但是当父节点取消选中时如果有已经选中的子节点也设置取消选中。

### ISSUE THREAD

**Issue by AhJane** [vueComponent/ant-design-vue-pro#304]
**Question**
treeSelect在完全受控（treeCheckStrictly）情况下有没有办法实现选中子节点的时候对应的父节点也选中，父节点选中时子节点不需要选中，但是当父节点取消选中时如果有已经选中的子节点也设置取消选中。

**Describe the solution you'd like**
可以提供一个实现思路或者最好有demo,谢谢。

**Additional context**
![image](https://user-images.githubusercontent.com/11899930/60174137-fa882280-9842-11e9-85ed-ec6ef3de169f.png)
![image](https://user-images.githubusercontent.com/11899930/60174164-096ed500-9843-11e9-8531-335ff966bb86.png)

**Comment by sendya** [comment]
遍历子节点去取消。

另外 请向组件库提 issue ，这里是 pro 业务模板库

**Comment by AhJane** [comment]
好的，谢谢大大
