### ISSUE TITLE
封装好的表格s-table中如何使用关键字查询条件

### ISSUE THREAD

**Issue by loveFemi** [vueComponent/ant-design-vue-pro#306]
表格外面有很多查询条件，设置点击后更改参数queryParam，调用查询服务，

parameter => {
          return this.$http.get('/service', {
            params: Object.assign(parameter, this.queryParam)
          }).then(res => {
            return res.result
          })
        }
这里会报错。
正确使用姿势如何？

**Comment by sendya** [comment]
报什么错？请说明

另外，可以阅读 #90 (Issue / PR 编写建议 (必读) )

**Comment by loveFemi** [comment]
> 报什么错？请说明
> 
> 另外，可以阅读 #90 (Issue / PR 编写建议 (必读) )

表格初始数据：
// 表格数据
      tabledata: parameter => {
        return getServiceList(Object.assign(parameter, this.queryParam))
          .then(res => {
            return res.result
          })
      },
表格外添加查询字段后调用的方法：
getTableList: parameter => {
      return getServiceList(Object.assign(parameter, this.queryParam))
        .then(res => {
          this.tabledata = res.result
        })
    }
其中getServiceList是封装好的axios请求
报错信息如下截图：
![image](https://user-images.githubusercontent.com/34272706/60332905-53ce8e00-99ca-11e9-9cef-2160a36f1af4.png)

**Comment by sendya** [comment]
错误看不懂吗？  `queryParam` 找不到，你把这个参数怎么了？如果你要自己换变量，请把变量修改到请求方法里的 `Object.assgin()` 里

https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/list/TableList.vue#L152
