### ISSUE TITLE
关于RouteView的一些问题

### ISSUE THREAD

**Issue by evanoxu** [vueComponent/ant-design-vue-pro#307]
https://github.com/sendya/ant-design-pro-vue/blob/161934db568d0ccac05ab57f0bbf80847104b42b/src/layouts/RouteView.vue#L29
这里默认设置的this.keepAlive用意？
如何关闭？

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/60331801-0f41f300-99c8-11e9-8555-c426b00dc1c5.png)

**Comment by evanoxu** [comment]
我的意思是："this.keepAlive" 是否需要默认开启？因为meta.keepAlive再怎么设置，组件keepAlive永远返回true。
