### ISSUE TITLE
关于根据后台数据动态生成路由的问题

### ISSUE THREAD

**Issue by huntermr** [vueComponent/ant-design-vue-pro#308]
在获取完权限数据，开始生成路由的时候，component () = > impot(xxx) 的时候，报了如下错误
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]

**Comment by sendya** [comment]
请按照 #90 提供完整信息

**Comment by huntermr** [comment]
![image](https://user-images.githubusercontent.com/11734937/60378401-aeacc780-9a54-11e9-81b7-23bc1075ab75.png)
![image](https://user-images.githubusercontent.com/11734937/60378406-bf5d3d80-9a54-11e9-85d9-9dfdff2fc80c.png)，通过控制台日志查看到的报了上面的错误

**Comment by huntermr** [comment]
![image](https://user-images.githubusercontent.com/11734937/60378439-23800180-9a55-11e9-824e-f9b1ba31f27d.png)
控制台错误日志如上

**Comment by irongiants** [comment]
I met the same question,but you guy didn't tell us the cause.
