### ISSUE TITLE
求大神帮我解答一下这行代码的意思

### ISSUE THREAD

**Issue by brucemeteor** [vueComponent/ant-design-vue-pro#310]
to.meta && (typeof to.meta.title !== 'undefined' && setDocumentTitle(`${to.meta.title} - ${domTitle}`))

这一行代码是什么意思？
我大概理解了一下不知道对不对，
首先 to.meta一定要为真值
其次 typeof to.meta.title !== 'undefined' 和执行方法返回值也为真值

但是后续就看不懂了，既没有if else控制流程语句，也没有其他的代码控制

**Comment by wuchang** [comment]
```js
if( to.meta && typeof to.meta.title !== 'undefined' )
{
  setDocumentTitle( ${to.meta.title} - ${domTitle} )
}
```

**Comment by sendya** [comment]
你可能需要学习 JS 基础

**Comment by brucemeteor** [comment]
> 你可能需要学习 JS 基础

谢谢大佬的建议，我确实是基础薄弱了。
不过我还有一点点小小疑惑
`to.meta && (typeof to.meta.title !== 'undefined' && setDocumentTitle(${to.meta.title} - ${domTitle}))`
还要非常谢谢 @wuchang 大神已经写出来了代码逻辑为我解答。
但为什么  `(typeof to.meta.title !== 'undefined' && setDocumentTitle(${to.meta.title} - ${domTitle}))`在后面要加上括号呢？
直接这样子
`to.meta && typeof to.meta.title !== 'undefined' && setDocumentTitle(${to.meta.title} - ${domTitle})`
我觉得可能更加清晰一点

**Comment by sendya** [comment]
你觉得这样写也行，能执行就好了。我只是按照规范而已

**Comment by brucemeteor** [comment]
> 你觉得这样写也行，能执行就好了。我只是按照规范而已

噢 ヽ(￣▽￣)و好的，我晓得了~ 谢谢大佬
