### ISSUE TITLE
开发环境与服务器交互问题

### ISSUE THREAD

**Issue by marscj** [vueComponent/ant-design-vue-pro#311]
devServer: {
    proxy: {
      '/api': {
        target: 'http://localhost:8080/api',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      },
      '/api/xxxx': {
        target: 'http://localhost:8080/api',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    }
这样配置以后 npm run serve 网页还是取mock数据， 后台并没有看到相关请求。谢谢

**Comment by marscj** [comment]
现在都是全栈开发啊，服务器后端也要调试啊。谁有空mock 这玩意啊。

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/main.js#L11

**Comment by yoage** [comment]
直接吧main.js 的 import './mock'注释就可以

vue.config.js的devServer 配置后端环境 
```  devServer: {
    // development server port 8000
    port: 8000,
    // If you want to turn on the proxy, please remove the mockjs /src/main.jsL11
    proxy: {
      '/api': {
        target: 'http://api.test',
        ws: false,
        changeOrigin: true
      }
    }
  },```
