### ISSUE TITLE
开发环境生产环境无法交互，亲测

### ISSUE THREAD

**Issue by marscj** [vueComponent/ant-design-vue-pro#312]
`devServer: {
    proxy: {
      '/api': {
        target: 'http://localhost:8080/api',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      },
      '/api/xxxx': {
        target: 'http://localhost:8080/api',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    }`

这种方式数据还是mock 没有走服务器API 亲测

**Comment by marscj** [comment]
ant-design-pro-vue 就说一坨屎，垃圾

**Comment by zhuduotao** [comment]
我这边也发现过这个问题,但是你骂开发者就太过分了,自己不能解决,只能说你自己辣鸡.

**Comment by marscj** [comment]
我承认我是垃圾，我是新手，对于新手开发的框架就有问题，你让新手如何解决。而且这个帖子我昨天就发过一个，今天早上来就被删除了。这什么垃圾啊。不解决问题 ，不回答问题，还删帖。干脆关闭得了。

**Comment by marscj** [comment]
@zhuduotao 我承认我是垃圾，我是新手，对于新手开发的框架就有问题，你让新手如何解决。而且这个帖子我昨天就发过一个，今天早上来就被删除了。这什么垃圾啊。不解决问题 ，不回答问题，还删帖。干脆关闭得了。

**Comment by zhuduotao** [comment]
你就没先翻一下issue列表?

**Comment by marscj** [comment]
#311 根本解决不了问题，明明就是有问题的，还关闭提问。

**Comment by marscj** [comment]
#91 明明就是有问题的，还关闭评论，后来我发了issue，今天早上还被删。能不火大么
#91 我测试了很多遍，昨天搞到晚上12点都没搞定， 浪费我那么多时间。能不火大么

**Comment by zhuduotao** [comment]
最简单粗暴的,你把mockapi删掉

**Comment by marscj** [comment]
最火大的就是 把所有mock 相关配置，文件全部删除，无法通过编译。这么粗暴的方法我也试过了。

**Comment by zhuduotao** [comment]
编译不通过那不是最好解决的问题吗?

**Comment by marscj** [comment]
现在在看 ant-desing-pro  rn框架了  真的不能比  从脚手架开始，到typesript ，在看看这个分支，有存在到必要么？ unstart 了。

**Comment by zhuduotao** [comment]
相信我,vue入门简单...如果不是react推广太难,我是不会回来用vue的

**Comment by sendya** [comment]
@marscj  这位 全栈开发 大哥，请您带着稍微学习一下 Github 的用法，我可以说明 github issue 是不能被删除的。 你的 issue #311 一直在 issue 列表。

另外，你可以多学习基础知识，我希望你不要什么事情都怪到其他人身上，我没对你做任何对不起你的事情。希望你能自知

**Comment by sendya** [comment]
一个开发代码，连 `main` 里面的函数和用到的支持库都不看，就发这种 issue，只会让我更加无视你的问题，给你贴了代码行，你自己消息不看，说人删你 issue

**Comment by Mkdms** [comment]
@marscj 麻烦您带点脑子？您的大脑需要升级，升级需要 1145141919 个大脑升级币，我这边还顺便能配钥匙，您配吗？只需要这些我可以帮您大脑构架进行全面的升级.做一个大 脑 升 级 壬。

**Comment by Acris** [comment]
脑子是个好东西。

**Comment by kokoroli** [comment]
你用着免费的东西，自己能力不够，怪开发者？
你这么厉害，你咋不自己做一个呢，干嘛还用着这些开源的呢。
你这种“全栈开发”，连前端文档都不愿自己看一下，就嚷嚷着自己是全栈，你咋就这么厉害呢

**Comment by zhuduotao** [comment]
@sendya 平心静气洗把脸,框架本身还原度和完成度已经很高了,没必要生气.

**Comment by zhuduotao** [comment]
@sendya 这个世界什么都有

**Comment by marscj** [comment]
我tm 就是不会发issus 怎么了 ，跟我开发有什么关系。管理不回答问题，你倒是让别人回答，删帖，关评论？还有这种操作。。我也是醉了。 我没有那么多功夫，成本，学习一个新的垃圾的框架。

**Comment by SoyMeng** [comment]
别在issues上聊天吧，又是这种没质量的，别把喷子的习惯带到github上

**Comment by sendya** [comment]
@marscj 

这个项目没收任何一个人的钱，项目的 demo，文档  CDN 和服务器均是由我自己掏钱搞的，作为开源项目。
我甚至可以直接不回答你的问题，但是为了这个项目负责，才本着最基本的心态为你解决问题，不要认为我缺一个 star，才回复你问题。

我是一名后端开发，我对我自己甚至都不敢称呼 全栈开发，我也是学习文档一步步把这个 ant pro vue 写出来的。

希望你能自己学习文档，根据文档一步步学习基础知识

**Comment by marscj** [comment]
各位大哥，我不是在座各位，有着BAT的高工资，无忧无虑的随便谢谢issue（还是有问题的）完事了。 全栈 1个月要出产品，出不来就没工资，没饭吃。本来前端就是个半调子，没那么多时间浪费。

**Comment by jjandxa** [comment]
脑子呢？都拿来装垃圾了？

**Comment by Ambra0921** [comment]
能消停点么，邮件叮叮的弹。。

**Comment by marscj** [comment]
行，我脑子装垃圾，我垃圾。我还是去看element ui了，至少那个比较成熟，对于我这种脑子装垃圾的人，也已经完成了一款上线都产品， 你们都是牛人，

**Comment by jjandxa** [comment]
赶紧赶紧，早去早上线
