### ISSUE TITLE
开发模式下怎么使用Gzip

### ISSUE THREAD

**Issue by lsdiao** [vueComponent/ant-design-vue-pro#313]
前后端分离后，前端页面初次加载的时候会有点慢，想问下怎么在开发模式下使用gzip，因为生成的时候不知道dist文件放在哪里，代码配置如下
` new compressionPlugin({
        algorithm: 'gzip',
        test: new RegExp('\\.(' + productionGzipExtensions.join('|') + ')$'),
        threshold: 10240,
        deleteOriginalAssets:false,
      }),`

**Comment by sendya** [comment]
开发模式一般推荐不开 gzip，会导致热重载变很慢。而且本地开发都是在内存生产的 js 文件，不会慢

**Comment by lsdiao** [comment]
自己访问本地很快，但是局域网里测试访问我的时候就加载很慢了

**Comment by sendya** [comment]
那我没办法了，让你们公司升级内网千兆网就不会有这个问题了，另外 内网应该不会超过 3秒。除非你接 wifi 。

再者，想改的话 去找 vue 官方文档，我也不知道要加哪
