### ISSUE TITLE
2.0.2 master版本中 内联编辑表格 操作列表头不显示

### ISSUE THREAD

**Issue by pandaiiz** [vueComponent/ant-design-vue-pro#316]
https://preview.pro.loacg.com/other/list/edit-table

这个列表 操作那一列的表头不显示 研究了好久也没找到原因 辛苦大佬看看了

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/other/TableInnerEditList.vue#L168

**Comment by pandaiiz** [comment]
![image](https://user-images.githubusercontent.com/25072780/60693418-cc72a480-9f0c-11e9-8d04-42706ed9bfb8.png)
抱歉，忘记上图了～我看了下代码 这个地方用<template></template>包裹起来就不显示

**Comment by sendya** [comment]
有问题的地方 上一个回复已经告诉你错在哪了

**Comment by pandaiiz** [comment]
![image](https://user-images.githubusercontent.com/25072780/60697126-588bc880-9f1b-11e9-8cc9-6de8dfb379f0.png)

![image](https://user-images.githubusercontent.com/25072780/60697107-43af3500-9f1b-11e9-9ea0-7b9d168ed854.png)


还发现了一个新的bug，当某一行设置为fixed的时候，会出现重复渲染

**Comment by pandaiiz** [comment]
![image](https://user-images.githubusercontent.com/25072780/60697217-e1a2ff80-9f1b-11e9-8bc6-eb2b57a46f76.png)

我发的截图是来自 https://preview.pro.loacg.com/other/list/edit-table 可以点开看一下，部署在服务器上的静态页面操作栏也是不显示title的

**Comment by sendya** [comment]
> 还发现了一个新的bug，当某一行设置为fixed的时候，会出现重复渲染

![image](https://user-images.githubusercontent.com/5404542/60697325-49f1e100-9f1c-11e9-8c1c-8a8a781dbea9.png)

**Comment by sendya** [comment]
> 我发的截图是来自 https://preview.pro.loacg.com/other/list/edit-table 可以点开看一下，部署在服务器上的静态页面操作栏也是不显示title的

都是一套代码，源代码都是错的
