### ISSUE TITLE
bug: 日期范围选择, 选择当前的日期, 字体颜色与背景颜色一样, 导致看不到当前的日期

### ISSUE THREAD

**Issue by free-pan** [vueComponent/ant-design-vue-pro#317]
**Describe the bug**
* 日期范围选择, 选择当前的日期, 字体颜色与背景颜色一样, 导致看不到当前的日期
* ant-design-vue的官方示例中, 没有该问题

**To Reproduce**
如: 当前日期为: 2019-07-05

1. 点击日期选择框,进行日期选择
2. 开始时间选择: 2019-07-05 此时,日期的字体颜色会与背景颜色保持一致.

**Expected behavior**
日期文字的颜色依旧是白色就可以了

**Screenshots**
![image](https://user-images.githubusercontent.com/37232676/60700936-6433bb00-9f2c-11e9-8296-9d831abeb79a.png)

**Desktop (please complete the following information):**
 - OS: mac os 10.14.5 (18F132)
 - Browser chrome 75.0.3770.100（正式版本） （64 位）
 - Version 最新的master版本

**Comment by sendya** [comment]
已知问题

**Comment by free-pan** [comment]
要怎样修改呢?

**Comment by sendya** [comment]
@free-pan 暂无解决方案 

ref #284

**Comment by free-pan** [comment]
暂行解决办法, 不知道你们以前是否有用过类似解决办法 @sendya 

1. 去除`vue.config.js`中`changeSelector`关于日期部分的配置

```js
changeSelector(selector) {
          switch (selector) {
             // 此处注释掉(master中是没有注释掉的)
            // case '.ant-calendar-today .ant-calendar-date':
            //   return ':not(.ant-calendar-selected-date)' + selector
            case '.ant-btn:focus,.ant-btn:hover':
              return '.ant-btn:focus:not(.ant-btn-primary),.ant-btn:hover:not(.ant-btn-primary)'
            case '.ant-steps-item-process .ant-steps-item-icon > .ant-steps-icon':
              return null
            case '.ant-btn.active,.ant-btn:active':
              return '.ant-btn.active:not(.ant-btn-primary),.ant-btn:active:not(.ant-btn-primary)'
            case '.ant-menu-horizontal>.ant-menu-item-active,.ant-menu-horizontal>.ant-menu-item-open,.ant-menu-horizontal>.ant-menu-item-selected,.ant-menu-horizontal>.ant-menu-item:hover,.ant-menu-horizontal>.ant-menu-submenu-active,.ant-menu-horizontal>.ant-menu-submenu-open,.ant-menu-horizontal>.ant-menu-submenu-selected,.ant-menu-horizontal>.ant-menu-submenu:hover':
            case '.ant-menu-horizontal > .ant-menu-item-active,.ant-menu-horizontal > .ant-menu-item-open,.ant-menu-horizontal > .ant-menu-item-selected,.ant-menu-horizontal > .ant-menu-item:hover,.ant-menu-horizontal > .ant-menu-submenu-active,.ant-menu-horizontal > .ant-menu-submenu-open,.ant-menu-horizontal > .ant-menu-submenu-selected,.ant-menu-horizontal > .ant-menu-submenu:hover':
              return '.ant-menu-horizontal > .ant-menu-item-active,.ant-menu-horizontal > .ant-menu-item-open,.ant-menu-horizontal > .ant-menu-item-selected,.ant-menu-horizontal > .ant-menu-item:hover,.ant-menu-horizontal > .ant-menu-submenu-active,.ant-menu-horizontal > .ant-menu-submenu-open,.ant-menu-horizontal:not(.ant-menu-dark) > .ant-menu-submenu-selected,.ant-menu-horizontal:not(.ant-menu-dark) > .ant-menu-submenu:hover'
            default :
              return selector
          }
        }
```

2. 编写用于全局的`global.less`

`:not(.x)`的作用只是为了增强`.ant-calendar-selected-date .ant-calendar-date`的优先级, 覆盖掉`antd`原始设置值

```less
:not(.x) .ant-calendar-selected-date .ant-calendar-date{
  color:#FFF;
}
.ant-calendar-today .ant-calendar-date[aria-selected="true"]{
  color:#FFF;
}
```

3. 在`main.js`中引入`global.less`

```
import './global.less'
```

默认打开的效果:

![image](https://user-images.githubusercontent.com/37232676/60750433-cba84400-9fda-11e9-8681-48f57f531db3.png)


只选中开始日期的效果(且开始日期是当天)

![image](https://user-images.githubusercontent.com/37232676/60750436-e5e22200-9fda-11e9-904d-f1ac8b8458ec.png)

选中开始日期和结束日期(开始日期是当前)

![image](https://user-images.githubusercontent.com/37232676/60750442-090cd180-9fdb-11e9-94de-21fd218f8e41.png)

选中开始日期和结束日期(开始日期非当前)

![image](https://user-images.githubusercontent.com/37232676/60750447-23df4600-9fdb-11e9-81eb-b9cc15f58759.png)
