### ISSUE TITLE
docker run failed with Error: EBUSY: resource busy or locked, rmdir '/usr/src/app/dist'

### ISSUE THREAD

**Issue by liudonghua123** [vueComponent/ant-design-vue-pro#320]
**Describe the bug**
When you want to build and run a production docker image. Then you got `EBUSY: resource busy or locked, rmdir '/usr/src/app/dist'` error.

**To Reproduce**
1. cd docker
2. Run `docker-compose up`
3. See error

**Expected behavior**
The container could run normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/2276718/60798368-98fd7780-a1a3-11e9-96fc-36f7712d7e7f.png)
![image](https://user-images.githubusercontent.com/2276718/60798391-a3b80c80-a1a3-11e9-92b4-89fc2c0e6750.png)

**Additional context**
The problem is that When you tried to execute `npm run build`, The build process first tried to remove the `dist` directory which is error in docker container which the `dist` was actually a named volume and could not removed.

Could we only clear the `dist`  directory instead of removing the `dist`.

**Comment by sendya** [comment]
这和你的 docker 容器环境配置有关，和本项目无关。请自行解决

**Comment by sendya** [comment]
另外，你也可以试试编译输出目录修改到其他地方

**Comment by liudonghua123** [comment]
这个和 docker 容器环境配置其实无关，在docker中挂载的数据卷是删除不掉的，类似于mount一个文件系统，查看vue-cli-service build的参数，可以使用`--no-clean`(do not remove the dist directory before building the project) 参数，只是不完美，antd pro的可以正常工作是因为不会删掉整个dist目录（https://github.com/ant-design/ant-design-pro/blob/master/package.json#L8）

**Comment by sendya** [comment]
那 你可以参看 vue-cli 的文档，看是否有解决方案。

**Comment by sendya** [comment]
另外，如果 docker volumes 挂载在更上级，就没这个问题

**Comment by liudonghua123** [comment]
嗯，挂载在上一级不会有这个问题，但数据卷里面的内容就包括了源码等内容，不完美，我使用 `--no-clean` 这个参数就不会有这个问题，其实在docker容器中使用这个参数是安全的，因为代码如果有变化的话，每次build都相当于是新的build，如果是非docker环境，可能使用这个参数就可能会有奇怪的问题出现。比较好的方式是build的时候不删除dist，而是删除 dist/* ，不过不是这个项目可以控制的了。
