### ISSUE TITLE
如何缩短页面刷新时loading的时间

### ISSUE THREAD

**Issue by junior-lianyuan** [vueComponent/ant-design-vue-pro#322]
感觉现在页面刷新时的loading时间有点儿长，想知道能不能手动设置页面loading的时间

**Comment by zkwolf** [comment]
首次进入或者ctrl+f5刷新的时候那个动画？

**Comment by sendya** [comment]
不能

**Comment by sendya** [comment]
不喜欢就自己去掉

**Comment by junior-lianyuan** [comment]
> 不喜欢就自己去掉

你好，那请问如何去掉呢～

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/public/index.html

**Comment by junior-lianyuan** [comment]
其实我想问的是刷新后中间那个空白的时间怎样缩短，不是把动画去掉～

**Comment by sendya** [comment]
不懂你说的是什么，请提供 GIF 或视频

**Comment by luyu1314** [comment]
我觉得你指的是减少网站体积，这样响应速度会快一些。
你可以按需加载 减小打包[https://github.com/sendya/ant-design-pro-vue/blob/master/docs/load-on-demand.md](url)

也可以使用webpack-bundle-analyzer[webpack-bundle-analyzer](url)来看看自己的是哪个库占的体积多

**Comment by chenzway** [comment]
> https://github.com/sendya/ant-design-pro-vue/blob/master/public/index.html

请问个动画效果实现原理是什么，求赐教？是怎么移除动画的？
