### ISSUE TITLE
目前没有实现路由懒加载吗？

### ISSUE THREAD

**Issue by MalavitaC** [vueComponent/ant-design-vue-pro#323]
如题
因为目前要实现路由懒加载，对首页加载进行优化，发现官方没有实现懒加载，所以来问下

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/config/router.config.js#L25

**Comment by MalavitaC** [comment]
意思是实现了懒加载吗？可是我看https://preview.pro.loacg.com
在加载首页的还是把所有js都加载了，是为什么呢？
![image](https://user-images.githubusercontent.com/38742840/61020957-18708e00-a3d2-11e9-9552-2923dd3cb9c6.png)

**Comment by sendya** [comment]
我的 preview 加载也不慢阿，而且懒加载不一定要访问到什么页面，才加载什么页面的 js，一定程度上也会导致 “性能” 变低。 具体请自己去查阅 vue-cli 官方文档
