### ISSUE TITLE
动态导航

### ISSUE THREAD

**Issue by Zhangdeli1993** [vueComponent/ant-design-vue-pro#327]
请问有根据用户权限，来动态加载的导航的模板吗

**Comment by MalavitaC** [comment]
https://github.com/sendya/ant-design-pro-vue/issues/227
这个应该有用

**Comment by sendya** [comment]
为什么首页的文档都不阅读一下 

https://pro.loacg.com/docs/authority-management

**Comment by Zhangdeli1993** [comment]
不好意思，没看仔细




------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 上午10:07
收件人: "sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com>; 
抄送: "問天"<245219281@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sendya/ant-design-pro-vue] 动态导航 (#327)




为什么首页的文档都不阅读一下
 
https://pro.loacg.com/docs/authority-management
