### ISSUE TITLE
setFieldsValue给checkbox-group 报错

### ISSUE THREAD

**Issue by hunji** [vueComponent/ant-design-vue-pro#328]
**Describe the bug**
setFieldsValue给checkbox-group 报错：Error in render: "TypeError: checkboxGroup.sValue.indexOf is not a function"

**To Reproduce**
checkbox组代码：
```
<a-checkbox-group name="roleIdList" v-decorator="['roleIdList']">
          <a-checkbox v-for="role in roleList" :key="role.roleId" :value="role.roleId">{{ role.roleName }}</a-checkbox>
        </a-checkbox-group>
```
赋值代码：
```
getUserInfo(id).then(data => {
            if (data && data.code === 200) {
              this.form.setFieldsValue({
                username: data.user.username,
                mobile: data.user.mobile,
                email: data.user.email,
                realName: data.user.realName,
                status: data.user.status,
                roleIdList: data.user.roleIdList
              })
            }
          })
```
**Expected behavior**
结果可以给到值，但是控制台报错了
 Error in render: "TypeError: checkboxGroup.sValue.indexOf is not a function"

**Comment by sendya** [comment]
roleIdList 数据是什么

**Comment by hunji** [comment]
[{
	"roleId": 1,
	"roleName": "admin",
	"remark": "admin",
	"createUserId": 1,
	"menuIdList": null,
	"createTime": "2019-06-03 15:22:07"
}, {
	"roleId": 2,
	"roleName": "动车段",
	"remark": "动车段/运用所",
	"createUserId": 1,
	"menuIdList": null,
	"createTime": "2019-06-06 14:11:55"
}, {
	"roleId": 3,
	"roleName": "技术科",
	"remark": "技术科",
	"createUserId": 1,
	"menuIdList": null,
	"createTime": "2019-06-06 14:14:18"
}, {
	"roleId": 8,
	"roleName": "test123",
	"remark": "12345",
	"createUserId": 1,
	"menuIdList": null,
	"createTime": "2019-07-12 17:10:43"
}]

**Comment by hunji** [comment]
现在临时是用initialValue解决了，但是这种方式太绕了，是不是这个checkbox-group组件的问题。
```
<a-checkbox-group name="roleIdList" v-decorator="['roleIdList',{initialValue: roleChecked}]">
          <a-checkbox v-for="role in roleList" :key="role.roleId" :value="role.roleId">{{ role.roleName }}</a-checkbox>
        </a-checkbox-group>
```
```
getUserInfo(id).then(data => {
            if (data && data.code === 200) {
              this.form.setFieldsValue({
                username: data.user.username,
                mobile: data.user.mobile,
                email: data.user.email,
                realName: data.user.realName,
                status: data.user.status
              })
              // 这里个checkboxgroup直接赋值会报错，转为赋值给initialvalue
              this.roleChecked = data.user.roleIdList
            }
          })
```

**Comment by hunji** [comment]
> roleIdList 数据是什么

[{
"roleId": 1,
"roleName": "admin",
"remark": "admin",
"createUserId": 1,
"menuIdList": null,
"createTime": "2019-06-03 15:22:07"
}, {
"roleId": 2,
"roleName": "动车段",
"remark": "动车段/运用所",
"createUserId": 1,
"menuIdList": null,
"createTime": "2019-06-06 14:11:55"
}, {
"roleId": 3,
"roleName": "技术科",
"remark": "技术科",
"createUserId": 1,
"menuIdList": null,
"createTime": "2019-06-06 14:14:18"
}, {
"roleId": 8,
"roleName": "test123",
"remark": "12345",
"createUserId": 1,
"menuIdList": null,
"createTime": "2019-07-12 17:10:43"
}]

**Comment by sendya** [comment]
设置 checkbox-group 必须是数组的 option value
