### ISSUE TITLE
hi，我想移除antv/g2，lodash，moment，但是不清楚哪使用了，一直失败

### ISSUE THREAD

**Issue by Joker-lifeng** [vueComponent/ant-design-vue-pro#329]
hi，我想移除antv/g2，lodash，moment，但是不清楚哪使用了，一直失败
![image](https://user-images.githubusercontent.com/39844897/61105268-eb90a980-a4ab-11e9-8e69-a61cebd809fa.png)

**Comment by Joker-lifeng** [comment]
![image](https://user-images.githubusercontent.com/39844897/61105342-34486280-a4ac-11e9-8994-d3af05489e65.png)

感觉到处都被引用

**Comment by sendya** [comment]
moment 属于不能移除，属于框架需要。其他的只要不用 dashboard 模板，均可移除。
注意 src/components/Charts 目录下几乎都是 antv/g2 的功能引入

**Comment by joinwen** [comment]
我已经把src/components/Charts删除了，但是打包的文件还是有antv/g2

**Comment by yichangle** [comment]
删除很多页面和组件，检查留下的页面和组件，确定没有使用antv/g2的，打包时还是有这个g2。没办法，粗暴地将antv目录改名，重新编译，果然报错，原来有个叫viser-vue的包依赖antv/g2.

**Comment by ideacco** [comment]
找到了。
1.先删除 components/index.js 中 的Charts引用，然后删掉 Charts 文件夹
2. 在 src/core/lazy_use.js 中删除 import Viser from 'viser-vue 和 Vue.use(Viser)

**Comment by Neal-Wei** [comment]
> 找到了。
> 1.先删除 components/index.js 中 的Charts引用，然后删掉 Charts 文件夹
> 2. 在 src/core/lazy_use.js 中删除 import Viser from 'viser-vue 和 Vue.use(Viser)

这个亲测有效
