### ISSUE TITLE
数据解析问题

### ISSUE THREAD

**Issue by Zhangdeli1993** [vueComponent/ant-design-vue-pro#330]
登录后台返回数据一定要是下面格式才能正常解析吗
{"message":"","status":200,"timestamp":1534844188679,"body":{"password":"21232f297a57a5a743894a0e4a801fc3","username":"admin"},"result":{"id":"4291d7da9005377ec9aec4a71ea837f","name":"Joseph Young","username":"admin","password":"","avatar":"https://gw.alipayobjects.com/zos/rmsportal/jZUIxmJycoymBprLOUbT.png","status":1,"telephone":"","lastLoginIp":"127.0.0.1","lastLoginTime":1534837621348,"creatorId":"admin","createTime":1497160610259,"deleted":0,"roleId":"admin","token":"4291d7da9005377ec9aec4a71ea837f"}}

**Comment by sendya** [comment]
pro 没规定返回数据的，均由你自己控制
