### ISSUE TITLE
sidebar在固定侧边栏后样式出现滚动条

### ISSUE THREAD

**Issue by hunji** [vueComponent/ant-design-vue-pro#331]
**Describe the bug （描述 Bug）**
选中固定侧边栏后，侧边栏样式出现问题。如下图：
![image](https://user-images.githubusercontent.com/6678566/61169004-1866be80-a589-11e9-9821-159fd0920ace.png)

![image](https://user-images.githubusercontent.com/6678566/61168961-aa21fc00-a588-11e9-9b7a-06cc812b0f66.png)

**Desktop (please complete the following information):**

 - OS: windows10
 - Browser chrome
 - Version 75.0.3770.100

**Comment by sendya** [comment]
不是 bug

**Comment by sendya** [comment]
不是 bug

**Comment by hunji** [comment]
> 不是 bug

好快。。。这个问题要怎么解决

**Comment by sendya** [comment]
@hunji 去掉就真的是 bug 了。

> 菜单固定后，高度就是固定的了，如果菜单数量过多，超过浏览器高度，则无法看到下面更多的菜单

**Comment by hunji** [comment]
> @hunji 去掉就真的是 bug 了。
> 
> > 菜单固定后，高度就是固定的了，如果菜单数量过多，超过浏览器高度，则无法看到下面更多的菜单

恩恩，但是这样很丑啊；是不是有办法可以隐藏掉或者覆盖掉这个滚动条的样式

**Comment by kokoroli** [comment]
::-webkit-scrollbar {display: none;} 只对chrome有效
另外的办法就是覆盖了，但是有人浏览器是默认隐藏滚动条(比如我)，如果用覆盖的办法就会有多出一段样式的问题。

**Comment by hunji** [comment]
> ::-webkit-scrollbar {display: none;} 只对chrome有效
> 另外的办法就是覆盖了，但是有人浏览器是默认隐藏滚动条(比如我)，如果用覆盖的办法就会有多出一段样式的问题。

恩恩，目前的方案就是覆盖了，全局增加了样式进行覆盖。滚动条样式可以参考

```
::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	background-color: #F5F5F5;
}

::-webkit-scrollbar
{
	width: 6px;
	background-color: #F5F5F5;
}

::-webkit-scrollbar-thumb
{
	background-color: #000000;
	border: 2px solid #555555;
}
```
