### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by Zhangdeli1993** [vueComponent/ant-design-vue-pro#333]
为什么登录接口，后台成功返回数据后，直接被catch 抓住而走1
![CU O0W 5VUIF6KJR(}UORUD](https://user-images.githubusercontent.com/22495072/61204295-63b2d580-a71f-11e9-97bc-a63a0ddfdf0f.png)
，
![$183~9L~E0NKCVQXWHPO L2](https://user-images.githubusercontent.com/22495072/61204334-7e854a00-a71f-11e9-9e28-a6b0aa24561c.png)

**Comment by sendya** [comment]
用户名不存在 不 catch 还能 loginSuccess ?

**Comment by sendya** [comment]
另外，接口返回不一样的时候，请自己修改接口输出函数的结构

**Comment by Zhangdeli1993** [comment]
谢谢
