### ISSUE TITLE
请问怎么引入vue-amap组件

### ISSUE THREAD

**Issue by Zhangdeli1993** [vueComponent/ant-design-vue-pro#334]
按照官网方式引入，一直报错
![NM3AN} ZX)A%WMUF4) T9W](https://user-images.githubusercontent.com/22495072/61342051-63c7e800-a87b-11e9-9c6a-7f3dbfa05246.png)

**Comment by sendya** [comment]
请去咨询 `vue-amap` 官方

**Comment by Zhangdeli1993** [comment]
项目中有其他 在中国地图上 描点的组件吗

**Comment by sendya** [comment]
项目中和文档中没描述的，本项目就没有提供
