### ISSUE TITLE
请问，当我点击进入详情页，如何保持当前的menu高亮呢？

### ISSUE THREAD

**Issue by liuwenhao19960508** [vueComponent/ant-design-vue-pro#335]
**Question （问题描述）**
比如我通过左侧menu 进入到A页面，然后通过A页面进入到一个详情页，要让左侧menu保持选中A页面的状态，该怎么解决呢？

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
pro 提供的 menu 封装已经是能够高亮当前页面的菜单项。
如果要自己实现，请参考官方组件 menu 的 API selectedKeys 和 openKeys

**Comment by free-pan** [comment]
@liuwenhao19960508 楼上(`luyu1314`)说的是对的.具体的路由配置大概是这个样子

```
{
    path: '/product/list',
    name: 'ProductList',
    component: () => import('@/views/product-ui/product-index'),
    meta: { title: '产品列表页' },
    hideChildrenInMenu: true,
    children: [{
        path: '/product/detail',
        name: 'ProductDetail',
        component: () => import('@/views/product-ui/product-detail'),
        meta: { title: '产品详情页', hide:true }
    }]
}
```

注意: 产品列表页的`hideChildrenInMenu=true`, 产品详情页的`hide=true`

**Comment by YYlele** [comment]
@free-pan 我也遇到同样的问题，配置方法跟你说的是一样的写法，但是点击详情按钮跳转不到详情页。
{
        path: '/course',
        component: PageView,
        redirect: '/course/courseList',
        name: 'courseManage',
        meta: { title: '课程管理', icon: 'eye' },
        children: [
          {
            path: '/course/courseList',
            name: 'courseList',
            component: CourseListPage,
            meta: { title: '课程列表' },
            hideChildrenInMenu: true,
            children: [
              {
                path: '/course/courseList/courseDetail',
                name: 'courseDetail',
                component: CourseDetailPage,
                meta: { title: '新建课程', hidden: true }
              }
            ]
          }
        ]
      }

**Comment by liuwenhao19960508** [comment]
@free-pan 跟楼上的问题一样，点击不跳转，也不会跳到404页面，请问是什么问题？

**Comment by liuwenhao19960508** [comment]
@free-pan  地址栏发生了变化，路由应该已经变了，但是视图并没有触发更新
代码是这样的：
  //老师管理
        {
          path: '/educationalCenter/teacherManage',
          name: 'teacherManage',
          component: () => import('@/views/educationalCenter/teacherManage'),
          hideChildrenInMenu: true,
          meta: {
            title: '教师管理',
            keepAlive: false
          },
          children: [
            {
              path: '/educationalCenter/teacherDetail/:id',
              name: 'watchDetail',
              component: () => import('@/views/educationalCenter/teacherDetail'),
              meta: {
                title: '教师详情',
                keepAlive: false,
                hide: true
              }
            }
          ]
        }

**Comment by sendya** [comment]
@liuwenhao19960508 @free-pan 我推荐你们先把 `Vue-Router` 学会如何使用，文档在这 https://router.vuejs.org/guide/essentials/named-views.html#nested-named-views

**Comment by liuwenhao19960508** [comment]
@luyu1314  我已经解决了，路由配置的问题：
` {
            path: '/educationalCenter/teacher',
            name: 'teacher',
            component: RouteView,
            hideChildrenInMenu: true,
            redirect: '/educationalCenter/teacherManage',
            meta: {
              title: '教师管理'
            },
            children: [
              {
                path: '/educationalCenter/teacherManage',
                name: 'teacherManage',
                component: () => import('@/views/educationalCenter/teacherManage'),
                meta: {
                  title: '教师管理',
                  hidden: true
                }
              },
              {
                path: '/educationalCenter/teacherDetail/:id',
                name: 'watchDetail',
                hidden: false,
                component: () => import('@/views/educationalCenter/teacherDetail'),
                meta: {
                  title: '教师详情',
                  hidden: true
                }
              }
            ]
          },`

**Comment by liuwenhao19960508** [comment]
@luyu1314  

- 我已经解决了，路由配置的问题：
 {
            path: '/educationalCenter/teacher',
            name: 'teacher',
            component: RouteView,
            hideChildrenInMenu: true,
            redirect: '/educationalCenter/teacherManage',
            meta: {
              title: '教师管理'
            },
            children: [
              {
                path: '/educationalCenter/teacherManage',
                name: 'teacherManage',
                component: () => import('@/views/educationalCenter/teacherManage'),
                meta: {
                  title: '教师管理',
                  hidden: true
                }
              },
              {
                path: '/educationalCenter/teacherDetail/:id',
                name: 'watchDetail',
                hidden: false,
                component: () => import('@/views/educationalCenter/teacherDetail'),
                meta: {
                  title: '教师详情',
                  hidden: true
                }
              }
            ]
          

- },

**Comment by free-pan** [comment]
个人认为你们可能需要的是这样的效果:
http://free_pan.gitee.io/ant-design-pro-vue-modify/#/list-route-detail/list

@liuwenhao19960508 @YYlele

**Comment by Zfang0620ls** [comment]
> 个人认为你们可能需要的是这样的效果:
> http://free_pan.gitee.io/ant-design-pro-vue-modify/#/list-route-detail/list
> 
> @liuwenhao19960508 @YYlele

@free-pan :请问这个是怎么实现的呢，有源码吗？
