### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by Zhangdeli1993** [vueComponent/ant-design-vue-pro#337]
首次登录成功后页面空白，必须刷新一下才能加载页面。请问这是什么原因

**Comment by sendya** [comment]
不知道是什么原因，pro 原本并不会这样。
提问请阅读 #90 ，问一些谁都答不上来的问题，和让人猜的问题 是没人能帮你解决问题的

**Comment by free-pan** [comment]
登录成功之后,默认转入的界面不存在,会导致你说的现象
