### ISSUE TITLE
结合electron,改造项目

### ISSUE THREAD

**Issue by hunji** [vueComponent/ant-design-vue-pro#338]
**Question （问题描述）**
有人修改成electron版本吗？需要怎么做

**Comment by wenbobao** [comment]
你好，我也遇到同样的问题，请问你改成功了吗

**Comment by SangeCoder** [comment]
@hunji @wenbobao 你们修改成功了吗？我现在遇到一些环境依赖问题，一直过不去

**Comment by liaoyongxiong** [comment]
同问，有没有人用electron打包成功过？

**Comment by Kimmyzhao** [comment]
同求

**Comment by Neal-Wei** [comment]
> **Question （问题描述）**
> 有人修改成electron版本吗？需要怎么做

进入项目文件夹
vue add electron-builder
使用开发模式运行：npm run electron:serve
打包：npm run electron:build

开发模式下不会报错，打包后会报 Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'，这是Viser引起的，将/core/lazy_user.js中的Viser注释掉，至于登录报错，需要使用127.0.0.1:8000代理,
