### ISSUE TITLE
怎么设置一个一级菜单呢？

### ISSUE THREAD

**Issue by jerryjiao** [vueComponent/ant-design-vue-pro#34]
我想设置一个一级菜单，跳到一个PageView的页面。
但是把children都隐藏后，还是不行。。
最后我是另外又写了一个路由，把这个路由hidden,这个路由的children是我想跳的那个一级页面。
菜鸟问题。。

**Comment by sendya** [comment]
![20181227092643](https://user-images.githubusercontent.com/5404542/50461519-e65d8880-09b9-11e9-8664-85e7d561ac64.png)

在 `首页` / 下面的 children 直接插入一个菜单即可。然后你自己的页面想用哪个页面当基础页面组件直接在你页面上 import 并使用即可，如下

----

router.config.js :
```javascript
  {
    path: '/tpage',
    name: 'tpage',
    component: () => import('@/views/form/TestForm'),
    meta: { title: '测试FORM', icon: 'user', permission: ['user'] }
  }
```

![20181227093123](https://user-images.githubusercontent.com/5404542/50461566-42281180-09ba-11e9-93a5-b66017c12e2a.png)

**Comment by nuochong** [comment]
按照示例，如果在原有一级菜单下添加子菜单可以，但是自己新建一级菜单，不会显示。不知道什么原因。
