### ISSUE TITLE
树目录表格在手机上的问题

### ISSUE THREAD

**Issue by zinda2000** [vueComponent/ant-design-vue-pro#340]
其他组件》业务布局》树目录表格，在手机上效果不好，这个大家都需要吧，有没有已经尝试过的朋友，提供比较好的参考方案

**Comment by sendya** [comment]
后期可以考虑试试兼容 手机，不过别做过高期望， 这种组件在手机上一般都不好展示。而且 antd 本身就不是为了手机端设计的

**Comment by zinda2000** [comment]
jeasyui 里的 tree  vue 版：
http://www.jeasyui.com/demo-vue/main/index.php?plugin=Tree&theme=material-teal&dir=ltr&pitem=&sort=asc

jquery
https://www.jstree.com/demo/
