### ISSUE TITLE
请问日历组件Calendar 如何多选？

### ISSUE THREAD

**Issue by liuwenhao19960508** [vueComponent/ant-design-vue-pro#342]
**Question （问题描述）**
我想在选择日期的时候可以选择多个，应该怎么实现呢？
卡片模式的那种，我可以选择多个日期

**Comment by Luffyying** [comment]
Hello,have you solved the problem?

**Comment by nongzhenli** [comment]
同问，我也有这个需求！查看整个antd 官方中，在17年的时候有提及过，但是官方一直都没有拓展这个功能。难道在使用过程中没有人遇到过吗？求分享解决方案（或者拓展组件）

**Comment by liuwenhao19960508** [comment]
> Hello,have you solved the problem?

https://github.com/kuan1/kuan-vue-calendar
try this

**Comment by liuwenhao19960508** [comment]
> 同问，我也有这个需求！查看整个antd 官方中，在17年的时候有提及过，但是官方一直都没有拓展这个功能。难道在使用过程中没有人遇到过吗？求分享解决方案（或者拓展组件）

https://github.com/kuan1/kuan-vue-calendar

我是拿这个组件的源码修改的，你试一下
