### ISSUE TITLE
开启MultiTab时候，同一路由不同参数数 组件不刷新

### ISSUE THREAD

**Issue by cuteCloud** [vueComponent/ant-design-vue-pro#344]
我有一张表格，每一行有一个配置选项，点击进入配置页面，配置页面query变了 ，看了下multiTab  是记录的fullpath 每次都会新打开一个页面 但是新页面确是就页面的东西 即使在配置页面设置一个watch 这样几个配置页面的东西都变成最新的了 试了几种方法 改造了multiTab 但发现每种都有弊端

**Comment by sendya** [comment]
不推荐使用 `mutil-tab` 组件，而且每个人对这个组件的用法均不一致。导致有很多差异化实现在里面，本项目 目前无法做到为了这个组件实现很多种 使用方式

**Comment by cuteCloud** [comment]
> 不推荐使用 `mutil-tab` 组件，而且每个人对这个组件的用法均不一致。导致有很多差异化实现在里面，本项目 目前无法做到为了这个组件实现很多种 使用方式

好的 谢谢 目前重写了mutil-tab的相关实现 其实就是多加了一个pathList数组 进行相关判断 目前能满足我的业务需求了 你们提供的mutil-tab思路是不错的

**Comment by JADE-Jerry** [comment]
Multi-tab的功能真的建议强化一下，大多数人还是希望用到这个功能的。

**Comment by zinda2000** [comment]
@cuteCloud 
云兄，你的MultiTab修改方案的代码可以共享下吗？我遇到同样问题
