### ISSUE TITLE
个人设置页的路由有bug

### ISSUE THREAD

**Issue by afresh** [vueComponent/ant-design-vue-pro#347]
个人设置页面中的基本设置子页内容显示的是安全设置的内容。

重现步骤：
1. 点击菜单个人设置 -> 安全设置
2. 点击菜单表单页 -> 基础表单
3. 再次点击菜单个人设置出现上述bug

期望第3步显示的子页内容为基本设置的内容。

截图：
![image](https://user-images.githubusercontent.com/5461256/61990547-24687b00-b075-11e9-8a2f-ea7e81156954.png)

 - OS: [Windows 10]
 - Browser [chrome]
 - Version [75.0.3770.142（正式版本） （64 位）]

**Comment by afresh** [comment]
@sendya Preview: https://preview.pro.loacg.com 依然存在这个问题。

**Comment by sendya** [comment]
@afresh 请使用方案1路由，方案2路由还没有调试完成
