### ISSUE TITLE
在store/modules下import "config/defaultSetting"拿不到数据

### ISSUE THREAD

**Issue by zivgit** [vueComponent/ant-design-vue-pro#349]
**Question （问题描述）**
RT，在`store/modules`下面的文件中使用`import`拿不到`config/defaultSetting`中的数据

**Additional context（附加信息）**
```
import defaultConfig from '@/config/defaultSettings'
console.log(defaultConfig) // undefined
```

**Comment by sendya** [comment]
没有任何异常

![image](https://user-images.githubusercontent.com/5404542/62104154-5413bf00-b2d1-11e9-82e9-c1b905eaaafe.png)

**Comment by zivgit** [comment]
@sendya 如果你是在store/modules下面的文件测试的，而且没问题，那可能是我在ant-design-pro-vue项目上改动造成的问题，也可能是旧版ant-design-pro-vue有这个问题，我用的是0.9.5。
但这个问题奇怪的是 在其他目录的文件中是没有异常的！
