### ISSUE TITLE
左侧菜单图标如何修改

### ISSUE THREAD

**Issue by cuteCloud** [vueComponent/ant-design-vue-pro#351]
我在core文件夹下重新注册了一个新的图标组件
const myIcon = Icon.createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_649097_sr4pfz47wg.js', // 在 iconfont.cn 上生成
})
Vue.component('myIcon',kdIcon)
在各个页面中可以正常显示，修改Menu文件夹下menu.js第147行 <Icon {... { props } }/>为
 <myIcon {... { props } }/> 发现在左侧菜单框架自带的图标仍然能正常显示 但是自定义的不能显示 求解 先行谢过

**Comment by sendya** [comment]
目前仅兼容 antd 自带 icon 和直接引入 svg icon 文件，请参考 `仪表盘` 菜单项配置。其他方式均未通过测试，如果你要自己改动，请注意根据图标类型判断要用 `<Icon />` 组件渲染，还是用你的自定义组件渲染。

**Comment by cuteCloud** [comment]
> 目前仅兼容 antd 自带 icon 和直接引入 svg icon 文件，请参考 `仪表盘` 菜单项配置。其他方式均未通过测试，如果你要自己改动，请注意根据图标类型判断要用 `<Icon />` 组件渲染，还是用你的自定义组件渲染。
好的 谢谢 目前也是根据你说的去解决的 也发现另一个问题  Icon.createFromIconfontCN生成的实例通过<myIcon {... { props } }/>这种方式是显示不出来的 只能直接指定type才能出来 虽然解决了 但还是有点不明白createFromIconfontCN派生出了什么 等有空去研究一下
