### ISSUE TITLE
布局和路由耦合是否不合适？

### ISSUE THREAD

**Issue by li-xiaoyin** [vueComponent/ant-design-vue-pro#352]
很多时候，我的页面布局，并不想将其作为一级菜单（或者面包屑导航）显示出来。比如下面这个需求，一个菜单，两个页面，按现有的路由我应该如何配置？

页面（2个）：
XX列表（PageView布局）
XX编辑（PageView布局）

主菜单（1级）：
XX管理

面包屑：
首页 / XX列表 / XX编辑

**Comment by sendya** [comment]
参考文档说明，并把不想展示在菜单上的使用 hidden 来隐藏掉。https://pro.loacg.com/docs/router-and-nav

另外，请问有 “合适” 的布局和路由不耦合用例吗

**Comment by li-xiaoyin** [comment]
> 参考文档说明，并把不想展示在菜单上的使用 hidden 来隐藏掉。https://pro.loacg.com/docs/router-and-nav
> 
> 另外，请问有 “合适” 的布局和路由不耦合用例吗

在我这个case里 实际上我要隐藏的是父级菜单，一旦hidden，子菜单就也没了，也就是我只想要一个布局，但不希望体现在菜单上，昨天我想了一下，我也可以自定义一个布局融合BaseLayout和PageView来实现，之前用react，布局可以通过一个高阶函数实现，感觉更灵活一些，vue似乎没有对应的实现方法？

**Comment by sendya** [comment]
你可以自己去寻找 vue 是否有相关解决方案，反正我所知道的 Vue-Router 必须依靠嵌套来实现层级路由。

不过 这样做，并且处理一下面包屑要隐藏的层级即可

```
 {
  path: '/parent1/',
  component: () => <router-view />
  meta: { title: 'XX管理' },
  children: [
   {
     path: '/parent1/children1',
     component: () => import('children/xx1'),
     meta: { title: 'xx列表' }
   },
   {
     path: '/parent1/children2',
     component: () => import('children/xx2'),
     meta: { title: 'xx编辑' }
   }
  ]
}
```

**Comment by li-xiaoyin** [comment]
> 你可以自己去寻找 vue 是否有相关解决方案，反正我所知道的 Vue-Router 必须依靠嵌套来实现层级路由。
> 
> 不过 这样做，并且处理一下面包屑要隐藏的层级即可
> 
> ```
>  {
>   path: '/parent1/',
>   component: () => <router-view />
>   meta: { title: 'XX管理' },
>   children: [
>    {
>      path: '/parent1/children1',
>      component: () => import('children/xx1'),
>      meta: { title: 'xx列表' }
>    },
>    {
>      path: '/parent1/children2',
>      component: () => import('children/xx2'),
>      meta: { title: 'xx编辑' }
>    }
>   ]
> }
> ```

好的 多谢 咱们的Ant Design Vue Pro做的非常好，相比react，其实我更愿意使用vue，等了好久，终于等来了vue版本，希望咱们越做越好。这个case很多方式都能处理，我只是感觉布局这个东西，和页面耦合会更好，而不是和路由耦合，只是个建议。

**Comment by li-xiaoyin** [comment]
> 你可以自己去寻找 vue 是否有相关解决方案，反正我所知道的 Vue-Router 必须依靠嵌套来实现层级路由。
> 
> 不过 这样做，并且处理一下面包屑要隐藏的层级即可
> 
> ```
>  {
>   path: '/parent1/',
>   component: () => <router-view />
>   meta: { title: 'XX管理' },
>   children: [
>    {
>      path: '/parent1/children1',
>      component: () => import('children/xx1'),
>      meta: { title: 'xx列表' }
>    },
>    {
>      path: '/parent1/children2',
>      component: () => import('children/xx2'),
>      meta: { title: 'xx编辑' }
>    }
>   ]
> }
> ```

下面是一个分支问题，关于面包屑导航：
我自己实现了一版面包屑导航，不是依靠vue嵌套路由，而是靠路径之间的匹配关系来确定面包屑关系，比如我有下面几个页面：
/customerlist
/customerlist/:id
/customerlist/:id/productlist
/customerlist/:id/productlist/:id
它们本身在布局上是平级的，没有嵌套路由关系，但面包屑我希望是下面这样的：
客户列表 / xxx客户 / 产品列表 / yyy产品
因为它们满足这样的关系，从页面浏览上一般也希望按这样的顺序浏览或回退

所以我觉得用路径关系生成面包屑比用路由关系生成面包屑更合适，可以参考一下这个场景，我觉得这个逻辑更合理也更灵活一些。

**Comment by sendya** [comment]
欢迎 PR
