### ISSUE TITLE
登出问题

### ISSUE THREAD

**Issue by miaomiaogege** [vueComponent/ant-design-vue-pro#354]
![image](https://user-images.githubusercontent.com/19725212/62351305-b3730880-b537-11e9-8edd-4996fd94502a.png)
这里先将 token 在状态 存储中全部删除 这样的话 请求后端 token字段为空 请问后端怎么将这个token注销掉呢？
 要采取什么策略注销当前的token 以及如果不注销 这个token 存留的安全性问题该怎么办呢

**Comment by sendya** [comment]
Vue.ls.remove(ACCESS_TOKEN) 放到 logout 的 then 即可，pro 由于没有后端，所以不需要验证 token 既没做相应处理，如果你是一名开发者，应该能理解这种东西应该放在什么地方
