### ISSUE TITLE
s-table，单击行时实现左侧checkbox选中

### ISSUE THREAD

**Issue by changhighly** [vueComponent/ant-design-vue-pro#358]
用的s-table组件，想在table表中单击整行时实现选中左侧checkbox功能，自己写了个方法，修改selectedRowKeys数据实现行选中，但是当首次点击行时，数据改变了，但是并没有选中，当有一个选中时再单击行，才会选中，哪位大神帮忙解决下这个bug。
![image](https://user-images.githubusercontent.com/22925367/62515594-5e940280-b855-11e9-820b-1b36eba76e13.png)
![image](https://user-images.githubusercontent.com/22925367/62515620-766b8680-b855-11e9-9065-353e816b36eb.png)

当单击checkbox时与单击行时，selectedRowKeys的id是不一样的
![image](https://user-images.githubusercontent.com/22925367/62515786-e1b55880-b855-11e9-85da-414da1c36158.png)

附代码：

`<s-table
      ref="table"
      :columns="columns"
      :loading="loading"
      :scroll="{ x: true}"
      size="small"
      :rowKey="(record) => record.id"
      :rowClassName="() => 'word_break_keep_all'"
      :data="loadData"
      :alert="options.alert"
      :customRow="(record) => { return {
        on:{
          dblclick:(record)=>{
            this.doubleClickOnRow(record,true)
          },
          click:(record)=>{
            this.clickOnRow(record)
          }
        }
      }}"
      :rowSelection="options.rowSelection">
    </s-table>`
--------------------------------------
`clickOnRow(record){
      console.log(record)
      let that=this;
      let rowKey = record.target.parentNode.dataset.rowKey
      console.log('rowKey:',Number(rowKey))
      let ind=that.selectedRowKeys.indexOf(Number(rowKey))
      console.log(ind)
      if(ind>-1){
        that.selectedRowKeys.splice(ind, 1);
      }else{
        that.selectedRowKeys.push(Number(rowKey))
      }
      console.log(that.selectedRowKeys)
    },`

**Comment by changhighly** [comment]
解决了，请参考该大神帖子https://blog.csdn.net/qq_35331167/article/details/90174428

**Comment by sendya** [comment]
请使用 codesandbox 提供一个可运行复现，或者提取有问题/疑问的一部分代码成为一个可正常运行的项目 发给我。

PS： 学一下如何使用 markdown ，你贴这样格式的代码，让维护者很难下手

**Comment by sendya** [comment]
我测试过了你描述的业务了，这个对 stable 这种重封装业务组件不太合适，你可以直接用 a-table 去实现

可以参考这个改动
components/table/index.js 343 行起，增加代码
```
          const { selectedRows, selectedRowKeys } = this.rowSelection;
          selectedRowKeys && (this.selectedRowKeys = selectedRowKeys);
          selectedRows && (this.selectedRows = selectedRows);
```

https://codesandbox.io/s/antd-pro-template-kv2xd

**Comment by changhighly** [comment]
```
我提出这个问题后就找到了解决方法，现在来完善下，拖的有点久，有不足之前请提出来
html代码
```
```html
<s-table
      ref="table"
      :columns="columns"
      :loading="loading"
      :scroll="{ x: true}"
      :rowClassName="() => 'word_break_keep_all'"
      size="small"
      :rowKey="(record) => record.dnNumber"
      :data="loadData"
      :alert="options.alert"
      :customRow="(record) => { return {
        on:{
          dblclick:(record)=>{
            this.doubleClickOnRow(record,true)
          },
          click:(record)=>{
            this.clickOnRow(record,this.selectedRowKeys)
          }
        }
      }}"
      :rowSelection="options.rowSelection">
    </s-table>
```
JS代码
```javascript
data () {
    return {
      selectedRowKeys: [], // 选中的行的keys数组
      selectedRows: [], // 选中的行的全部数组
      columns: [],// 表头
      // 加载数据方法 必须为 Promise 对象
      loadData: parameter => {
        console.log('loadData.parameter', parameter)
        console.log('loadData.parameter', this.queryParam)
        return list(Object.assign(parameter, this.queryParam))
          .then(res => {
            console.log(res.result)
            return res.result
          })
      },
      options: {
        // alert: { show: true, clear: () => { this.selectedRowKeys = [] } },
        rowSelection: {
          selectedRowKeys: this.selectedRowKeys,
          onChange: this.onSelectChange
        }
      }
    },
methods: {
    // 选择列表
    onSelectChange (selectedRowKeys, selectedRows) {
      console.log('selectedRowKeys changed: ', selectedRowKeys)
      console.log('selectedRows: ', selectedRows)
      this.selectedRowKeys = selectedRowKeys
      // this.selectedRows = selectedRows
      this.options = {
        rowSelection: {
          selectedRowKeys: selectedRowKeys,
          onChange: this.onSelectChange
        },
        // alert: { show: true, clear: () => {  this.selectedRowKeys = [] } }
      }
    },
   clickOnRow (record, selectedRowKeys) {
      clickOnRowFun(record, selectedRowKeys)
    },

}
  
```
#这是在js文件中封装的方法，在VUE中import { clickOnRowFun } from '@/utils/util'//你得js目录
```javascript
export function clickOnRowFun(record,selectedRowKeys) {
  // console.log(record)
  // console.log(selectedRowKeys)
  let arr = [];
  arr = selectedRowKeys
  let rowKey = record.target.parentNode.dataset.rowKey
  console.log(rowKey)
  let ind = arr.indexOf(Number(rowKey))
  console.log(ind)
  if (ind > -1) {
    arr.splice(ind, 1)
  } else {
    arr.push(Number(rowKey))
  }
  return arr;
}
```

**Comment by changhighly** [comment]
> 我测试过了你描述的业务了，这个对 stable 这种重封装业务组件不太合适，你可以直接用 a-table 去实现
> 
> 可以参考这个改动
> components/table/index.js 343 行起，增加代码
> 
> ```
>           const { selectedRows, selectedRowKeys } = this.rowSelection;
>           selectedRowKeys && (this.selectedRowKeys = selectedRowKeys);
>           selectedRows && (this.selectedRows = selectedRows);
> ```
> 
> https://codesandbox.io/s/antd-pro-template-kv2xd

只有300行啊，没有343行

**Comment by changhighly** [comment]
> 我测试过了你描述的业务了，这个对 stable 这种重封装业务组件不太合适，你可以直接用 a-table 去实现
> 
> 可以参考这个改动
> components/table/index.js 343 行起，增加代码
> 
> ```
>           const { selectedRows, selectedRowKeys } = this.rowSelection;
>           selectedRowKeys && (this.selectedRowKeys = selectedRowKeys);
>           selectedRows && (this.selectedRows = selectedRows);
> ```
> 
> https://codesandbox.io/s/antd-pro-template-kv2xd
有一个bug，这个选中数量并不变化，也没找出问题在哪
![image](https://user-images.githubusercontent.com/22925367/63920834-41c5a600-ca74-11e9-9ed5-72d78a249b12.png)

**Comment by changhighly** [comment]
> > 我测试过了你描述的业务了，这个对 stable 这种重封装业务组件不太合适，你可以直接用 a-table 去实现
> > 可以参考这个改动
> > components/table/index.js 343 行起，增加代码
> > ```
> >           const { selectedRows, selectedRowKeys } = this.rowSelection;
> >           selectedRowKeys && (this.selectedRowKeys = selectedRowKeys);
> >           selectedRows && (this.selectedRows = selectedRows);
> > ```
> > 
> > 
> > https://codesandbox.io/s/antd-pro-template-kv2xd
> > 有一个bug，这个选中数量并不变化，也没找出问题在哪
> > ![image](https://user-images.githubusercontent.com/22925367/63920834-41c5a600-ca74-11e9-9ed5-72d78a249b12.png)

知道了，应为this.selectedRowKeys.length
