### ISSUE TITLE
登录后有时无法正常进入主页

### ISSUE THREAD

**Issue by Zhangdeli1993** [vueComponent/ant-design-vue-pro#360]
登录后有时无法正常进入主页，控制台会出现如下错误
![image](https://user-images.githubusercontent.com/22495072/62588387-285b8f00-b8f8-11e9-94fc-327180d745ad.png)
关闭浏览器后重新登录即可正常进入主页

**Comment by sendya** [comment]
请不要自己修改后导致的问题 非常简略 的就到这里提问，甚至连代码  和 自己的过程分析都没

**Comment by aiddroid** [comment]
我完全搞不懂，这就是个前端项目，为啥跑起来后还需要登录注册，而且注册成功之后并不能登录，我就是想看看效果而已，给个默认账号多简单

**Comment by sendya** [comment]
@aiddroid 年轻人不要这么暴躁，做事细心点 就好了

![image](https://user-images.githubusercontent.com/5404542/62768921-850ea380-baca-11e9-8a7e-dd2aa11157d6.png)

**Comment by aiddroid** [comment]
@sendya  我的8000端口曾经被项目占用，有被记住的密码，进到登录界面输入框里默认是有填充内容的，根本看不着placeholder。我还专门找了一遍文档，并没看到哪里写了默认账号。
我觉得这是个值得考虑的点，最好就是把admin/admin设置为默认值或者readme提一下

**Comment by sendya** [comment]
@aiddroid 代码是开源的，你甚至可以自己审查代码，看是怎么校验的。我觉得这个应该作为第一步要做的事情
