### ISSUE TITLE
sockjs-node

### ISSUE THREAD

**Issue by huxiaozhong** [vueComponent/ant-design-vue-pro#365]
http://localhost:8000/sockjs-node/info?t=1565251584045
一直自动发起这个请求  这是干什么呢 ，怎么关掉

**Comment by sendya** [comment]
这是 webpack 用于热重载页面的功能，跟 antd pro 没任何关系，如果你不需要，请自己找 webpack 资料怎么关。

**Comment by huxiaozhong** [comment]
好的十分感谢
