### ISSUE TITLE
s-table里面有s-table数据没有更新

### ISSUE THREAD

**Issue by kule2018** [vueComponent/ant-design-vue-pro#366]
s-table

**Comment by kule2018** [comment]
> s-table里面还有一个s-table，但是怎么样到不能更新下面那个s-table里面的数据，只能更新外面的s-table，用了这个方法也不行this.$refs.table.refresh(true)

**Comment by sendya** [comment]
愣着干嘛，上代码，上报错信息，上系统环境

**为了更好的解决你的问题, 建议在发表前, 先浏览以下内容。**

## issue

- 提供你的系统信息(发行版名字，版本号，浏览器等)。
- 提供你所使用的 Pro 版本。可以对比 github 上的版本列表页, 看看是否为最新版, 也许你的问题在新版本中已经修复了。
- 尽量详细描述你的问题，以及这个问题是如何出现的，最好能把 操作步骤大概说一下，以便我能重现这个问题。可以通过截图，录屏，浏览器`Console`报错等方式提交更多的信息。
- 超过 7 天未对 `Contributors` 的回复进行反馈的，默认将认为已解决关闭 Issue
- **请使用提供的 Issue 模板格式发布**
- **提问前请确认已经查找过** [Vue 文档](https://cn.vuejs.org/v2/guide/) | [Vue-Cli3](https://cli.vuejs.org/zh/guide/) | [Ant Design Vue](https://vue.ant.design/docs/vue/introduce-cn/) | [Webpack](https://webpack.docschina.org/configuration/) | [Cli3 完全配置例示](https://github.com/staven630/vue-cli3-config)

**Comment by kule2018** [comment]
<template>
  <s-table
    ref="table"
    size="default"
    :rowKey="(record) => record.data.id"
    :columns="columns"
    :data="loadData"
    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }" >
	 <template #expandedRowRender="record, index">
        <s-table
          size="small"
          :columns="innerColumns"
          row-key="purchaseDetailId"
          :data="params => loadlistdata(params, record)"
        />
      </template>
  </s-table>
</template>
是分开接口的，想做成两个到是分页。我想更新里面的表格数据，我怎么样更新比较效好啊。

**Comment by kule2018** [comment]
<template>
  <s-table
    ref="table"
    size="default"
    :rowKey="(record) => record.data.id"
    :columns="columns"
    :data="loadData"
    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }" >
	 <template #expandedRowRender="record, index">
        <s-table
          size="small"
          :columns="innerColumns"
          row-key="purchaseDetailId"
          :data="params => loadlistdata(params, record)"
        />
      </template>
  </s-table>
</template>
是分开接口的，想做成两个到是分页。我想更新里面的表格数据，我怎么样更新比较效好啊。

**Comment by kule2018** [comment]
<template>
  <s-table
    ref="table"
    size="default"
    :rowKey="(record) => record.data.id"
    :columns="columns"
    :data="loadData"
    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }" >
	 <template #expandedRowRender="record, index">
        <s-table
          size="small"
          :columns="innerColumns"
          row-key="purchaseDetailId"
          :data="params => loadlistdata(params, record)"
        />
      </template>
  </s-table>
</template>

**Comment by kule2018** [comment]
<template>
  <s-table
    ref="table"
    size="default"
    :rowKey="(record) => record.data.id"
    :columns="columns"
    :data="loadData"
    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }" >
	 <template #expandedRowRender="record, index">
        <s-table
          size="small"
          :columns="innerColumns"
          row-key="purchaseDetailId"
          :data="params => loadlistdata(params, record)"
        />
      </template>
  </s-table>
</template>

**Comment by kule2018** [comment]
<template>
  <s-table
    ref="table"
    size="default"
    :rowKey="(record) => record.data.id"
    :columns="columns"
    :data="loadData"
    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }" >
	 <template #expandedRowRender="record, index">
        <s-table
          size="small"
          :columns="innerColumns"
          row-key="purchaseDetailId"
          :data="params => loadlistdata(params, record)"
        />
      </template>
  </s-table>
</template>
![image](https://user-images.githubusercontent.com/41567126/62865897-353a1180-bd42-11e9-95cf-899a5d98261a.png)
![image](https://user-images.githubusercontent.com/41567126/62865899-3703d500-bd42-11e9-89ba-da174aec64bd.png)

**Comment by kule2018** [comment]
有没有信息啊。有微信给我加一下，我们聊聊




------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午5:59
收件人: "sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com>;
抄送: ""<125586657@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sendya/ant-design-pro-vue] s-table里面有s-table数据没有更新 (#366)




愣着干嘛，上代码，上报错信息，上系统环境
 
为了更好的解决你的问题, 建议在发表前, 先浏览以下内容。
 
issue
  
提供你的系统信息(发行版名字，版本号，浏览器等)。
 
提供你所使用的 Pro 版本。可以对比 github 上的版本列表页, 看看是否为最新版, 也许你的问题在新版本中已经修复了。
 
尽量详细描述你的问题，以及这个问题是如何出现的，最好能把 操作步骤大概说一下，以便我能重现这个问题。可以通过截图，录屏，浏览器Console报错等方式提交更多的信息。
 
超过 7 天未对 Contributors 的回复进行反馈的，默认将认为已解决关闭 Issue
 
请使用提供的 Issue 模板格式发布
 
提问前请确认已经查找过 Vue 文档 | Vue-Cli3 | Ant Design Vue | Webpack | Cli3 完全配置例示

**Comment by mynuolr** [comment]
有什么是不能在这里讨论 一定要私聊？
