### ISSUE TITLE
关于eslint错误和警告的配置

### ISSUE THREAD

**Issue by huxiaozhong** [vueComponent/ant-design-vue-pro#367]
Binding "disabled" should be on a new line 
Expected indentation of 14 spaces but found 16 spaces 
对于这两个错误我配置了
package.json下的eslintConfig 的rules
"indent": [
        "off",
        2
      ],
      "linebreak-style": [
        0,
        "error",
        "windows"
      ],
不清楚为何不行，是配置错了还是，咱们这个项目有特殊之处，
我不习惯vue组件的每个属性都换行，我关闭了换行 他就出现这个问题，我现在代码格式如下图
![image](https://user-images.githubusercontent.com/4412791/62751971-43fd9b80-ba98-11e9-901d-e5ccac6b4319.png)
请教怎么消除这两个错误，我只想eslint不提示这2个错误，并不想关闭eslint
十分感谢

**Comment by sendya** [comment]
属性换行是 `vue/max-attributes-per-line` 这个 rules 控制的
另外，任何 eslint 相关的配置，麻烦你去查询 eslint 的配置属性该如何配置

**Comment by huxiaozhong** [comment]
好的解决了 十分感谢
