### ISSUE TITLE
引入第三方js插件时跳过eslint校验

### ISSUE THREAD

**Issue by mchobbylong** [vueComponent/ant-design-vue-pro#369]
**Question （问题描述）**
我正在尝试给项目集成海康威视web3.0的控件包，js文件格式不规范。

```js
import { WebVideoCtrl } from '@/../public/hikvision/webVideoCtrl'
```

直接通过上述语句引入，会报 `SyntaxError` 错误。尝试过在 `babel.config.js` 里设置 ignore 属性，但是并没有起作用：

```
// In babel.config.js
module.exports = {
  // ...
  ignore: ['public/hikvision/*']
}
```

**Describe the solution you'd like （你期待的是什么？）**
配置项目使eslint忽略 `public/hikvision/` 目录下的脚本格式校验。

**Additional context（附加信息）**
暂无

**Comment by sendya** [comment]
请去查阅 eslint 相关资料，本项目不提供 `eslint` 相关问题解决，另外 也可以去参阅 vue-cli 官方文档看是否有解决办法

实在找不到解决办法，就去掉 eslint 也行

**Comment by mchobbylong** [comment]
此问题已解决，贴一下我的解决方案：

针对 `babel-loader` 转译忽略，在 `vue.config.js` 的 `chainWebpack` 函数中加一句：
```js
config.module.rule('js').exclude.add(path.resolve('public/hikvision')).end()
```

针对 `eslint` 的代码规范检测忽略，同样在 `chainWebpack` 函数中加一句：
```js
config.module.rule('eslint').exclude.add(path.resolve('public/hikvision')).end()
```

即可。
