### ISSUE TITLE
打包后在Microsoft Edge浏览器上，滚动时左侧固定菜单栏闪动

### ISSUE THREAD

**Issue by Thlq** [vueComponent/ant-design-vue-pro#374]
**Describe the bug （描述 Bug）**

打包后在Microsoft Edge浏览器上，滚动时左侧固定菜单栏闪动

**To Reproduce （重现步骤）**

打包后在微软Microsoft Edge浏览器上运行时，顶部header和左侧菜单固定，滚动con的时候左侧菜单和顶部header闪动

**Expected behavior（你期待的是什么?）**
不闪动

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/21211777/62851751-baf59700-bd19-11e9-8d27-3ffec6eb52ff.png)

**Desktop (please complete the following information):**

 - OS: windows
 - Browser: Microsoft Edge
 - Version:  Microsoft Edge 44.17763.1.0

**Comment by sendya** [comment]
有访问地址吗？

**Comment by Thlq** [comment]
等我部署下

**Comment by Thlq** [comment]
> 有访问地址吗？

http://114.55.112.30/SSS/dist/index.html

**Comment by Thlq** [comment]
> 有访问地址吗？

114.55.112.30/SSS/dist/index.html @sendya

**Comment by sendya** [comment]
确实有问题，但无法定位。因为打开开发者工具 就不抖动了

**Comment by Thlq** [comment]
> 确实有问题，但无法定位。因为打开开发者工具 就不抖动了

我这边打开调试工具还在抖。。。

**Comment by Thlq** [comment]
edge报了一个错，不知道是不是这方面的问题
CSS3121: 媒体查询 -ms-viewport 已弃用。
