### ISSUE TITLE
yarn run build时如何过滤*.svn文件夹

### ISSUE THREAD

**Issue by liukefu2050** [vueComponent/ant-design-vue-pro#376]
**Question （问题描述）**

我使用的是svn代码管理，yarn run build时会复制*.svn文件

**Describe the solution you'd like （你期待的是什么？）**
我对webpack配置不熟悉，请问如何过滤这些svn文件夹呢，我该如何配置

**Additional context（附加信息）**
非常感谢

**Comment by sendya** [comment]
编译只会把 public 和 src 打包进去，其余的不会打包， `.svn` 文件夹应当是在项目根目录，而不会存在于 `/public/.svn` 如果在 `/public` 下也有 `.svn` 目录，应该是你 svn 使用上出了问题

**Comment by liukefu2050** [comment]
/public 下是有 .svn 目录的，因为整个项目是svn管理的，打包后的文件我们是需要提交的，这样后台开发人员就无需配置node环境，而每次打包又会覆盖svn文件，所以版本控制就乱了。请问这个该如何配置呢？

**Comment by sendya** [comment]
我刚刚不是说了吗？ public 下不应该存在 .svn 你们 svn 到底是怎么使用的？

正常的 svn 库应该是在项目的根目录有一份 .svn 而不应该在其他目录也有 .svn 文件夹

**Comment by sendya** [comment]
把你的根目录用 tree 命令打印出来 发上来看一下

**Comment by liukefu2050** [comment]
大概我们用老版本的svn的原因，├─view 是我们的dist目录
├─docs
├─public
│  └─loading
│      └─option2
├─src
│  ├─api
│  ├─assets
│  │  └─icons
│  ├─components
│  │  ├─ArticleListContent
│  │  ├─AvatarList
│  │  ├─Charts
│  │  ├─CountDown
│  │  ├─DescriptionList
│  │  ├─Editor
│  │  ├─Ellipsis
│  │  ├─Exception
│  │  ├─FooterToolbar
│  │  ├─GlobalFooter
│  │  ├─GlobalHeader
│  │  ├─IconSelector
│  │  ├─Menu
│  │  ├─MultiTab
│  │  ├─NoticeIcon
│  │  ├─NumberInfo
│  │  ├─PageHeader
│  │  ├─PageLoading
│  │  ├─Result
│  │  ├─SettingDrawer
│  │  ├─StandardFormRow
│  │  ├─Table
│  │  ├─TagSelect
│  │  ├─tools
│  │  ├─Tree
│  │  ├─Trend
│  │  └─_util
│  ├─config
│  ├─core
│  │  ├─directives
│  │  └─lazy_lib
│  ├─layouts
│  ├─mock
│  │  └─services
│  ├─router
│  ├─store
│  │  └─modules
│  ├─utils
│  │  └─helper
│  └─views
│      ├─account
│      │  ├─center
│      │  │  └─page
│      │  └─settings
│      ├─basicSettings
│      │  └─modules
│      ├─dashboard
│      ├─equipment
│      │  └─modules
│      ├─exception
│      ├─form
│      │  ├─advancedForm
│      │  ├─modules
│      │  ├─productionTask
│      │  └─stepForm
│      ├─list
│      │  ├─modules
│      │  ├─search
│      │  │  └─components
│      │  └─table
│      ├─material
│      ├─other
│      │  └─modules
│      ├─productionManage
│      │  ├─advancedForm
│      │  ├─order
│      │  └─productionTask
│      ├─profile
│      │  ├─advanced
│      │  └─basic
│      ├─result
│      ├─role
│      ├─user
│      └─usermanagerment
├─tests
│  └─unit
├─view
│  ├─assets
│  ├─css
│  ├─img
│  ├─js
│  └─loading
│      └─option2
└─WEB-INF

**Comment by liukefu2050** [comment]
此问题，暂时升级了SVN客户端解决，TortoiseSVN-1.12.2.28653-x64-svn-1.12.2
