### ISSUE TITLE
使用多页模式失败。出现引用死循环 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bing086** [vueComponent/ant-design-vue-pro#378]
**Question （问题描述）**
使用多页模式失败。出现引用死循环 RangeError: Maximum call stack size exceeded
 

**Additional context（附加信息）**
 RangeError: Maximum call stack size exceeded
  
  - Array.join
  
  - loader.js:229 Function.Module._findPath
    internal/modules/cjs/loader.js:229:56
  
  - loader.js:579 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:579:25
  
  - loader.js:508 Function.Module._load
    internal/modules/cjs/loader.js:508:25
  
  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17
.....

**Comment by sendya** [comment]
如何使用的？我这没复现

**Comment by bing086** [comment]
vue.config.js增加 pages 参考：https://github.com/seizeDev/vue-more-pages 方式实现出现该错误

**Comment by gslancer** [comment]
封装的axios
导致的。换成通用的封装封装方法就好了

**Comment by gslancer** [comment]
> vue.config.js增加 pages 参考：https://github.com/seizeDev/vue-more-pages 方式实现出现该错误

框架封装的axios导致的。替换成网上通用的axios封装就好了。

**Comment by bing086** [comment]
> > vue.config.js增加 pages 参考：https://github.com/seizeDev/vue-more-pages 方式实现出现该错误
> 
> 框架封装的axios导致的。替换成网上通用的axios封装就好了。

具体是哪部分有问题，能发下看下吗 谢谢！

**Comment by gslancer** [comment]
> > > vue.config.js增加 pages 参考：https://github.com/seizeDev/vue-more-pages 方式实现出现该错误
> > 
> > 
> > 框架封装的axios导致的。替换成网上通用的axios封装就好了。
> 
> 具体是哪部分有问题，能发下看下吗 谢谢！

就是这种方式：https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/request.js

**Comment by supeijin** [comment]
我也出现了这个问题。
