### ISSUE TITLE
TableList as home page.

### ISSUE THREAD

**Issue by JackDan9** [vueComponent/ant-design-vue-pro#379]
When i use `TableList.vue` as home page, Configured the route. But it brings some problems. Can you give me a hand ? 
```
browser.js?e834:49 Warning: Each record in table should have a unique `key` prop,or set `rowKey` to an unique primary key.
browser.js?e834:49 Warning: Each record in dataSource of table should have a unique `key` prop, or set `rowKey` of Table to an unique primary key,
```
If i don't ues `TableList.vue` as home page, it not be brought some problems
Thanks!

**Comment by sendya** [comment]
https://vue.ant.design/components/table/#Note

**Comment by JackDan9** [comment]
Ok, I solved these problems. `response.data` have some default value. From the document[https://vue.ant.design/components/table/#Note](https://vue.ant.design/components/table/#Note), I am more aware of the propertis of the `Table`.
Thanks! @sendya
