### ISSUE TITLE
一点界面上的小修改

### ISSUE THREAD

**Issue by iota9star** [vueComponent/ant-design-vue-pro#380]
### 环境
- 浏览器版本：Chrome 76.0.3809.100
- pro 版本：2.0.2

### 建议修改内容
1. 页面header 头像未和其他文字图标垂直居中
![s1](https://user-images.githubusercontent.com/21272154/62993696-28750500-be8b-11e9-83ae-3e204bd34989.png)
2. 页面标签没有和内容块对齐，同时建议修改tab标签的样式，感觉和其他页面不太搭，需要细微调整一下:joy:
![s2](https://user-images.githubusercontent.com/21272154/62993791-8d305f80-be8b-11e9-855e-f1947573a7c1.png)
  
### 废话
**个人已在项目中修改，但还是希望大佬你可以修改一下，:ambulance:拯救一下其他的强迫症患者:joy:，万分感谢**

**Comment by sendya** [comment]
欢迎 PR
