### ISSUE TITLE
请教大佬，vue中的jsx语法和react中的jsx语法不同吗

### ISSUE THREAD

**Issue by yixinagqingyuan** [vueComponent/ant-design-vue-pro#382]
为什么这段代码在react中无法触发事件呢，同样都是jsx语法，有啥却别吗，求大佬指导
 <a class="btn" style="width: 20px;z-index:1300" {...{ on: { click: () => this.handlePlus(item) } }}><a-icon type="plus"/></a>

**Comment by sendya** [comment]
https://zhuanlan.zhihu.com/p/37920151
