### ISSUE TITLE
咨询 yarn build:preview 打包出来用的是mock数据吗

### ISSUE THREAD

**Issue by yaoshanliang** [vueComponent/ant-design-vue-pro#384]
我想部署个和[https://preview.pro.loacg.com](https://preview.pro.loacg.com)一样的演示站。

yarn build:preview 打包出来用的是mock数据吗？

还有，使用yarn build打包，按照[https://pro.loacg.com/docs/deploy](https://pro.loacg.com/docs/deploy)里配置了nginx，请求接口的时候提示400未备案，我自己的域名已经备案了呀，`proxy_pass https://preview.pro.loacg.com;` 这个也应该备案了呀。

**Comment by sendya** [comment]
请不要反代我的站点，请自己处理自己的 mock 或者后端接口

preview 打包出来有包含 mock，另外 想要 mock 只需要把 mock/index.js 里面的环境判断去掉就可以在任何环境加载 mock

**Comment by gaixm** [comment]
> 请不要反代我的站点，请自己处理自己的 mock 或者后端接口
> 
> preview 打包出来有包含 mock，另外 想要 mock 只需要把 mock/index.js 里面的环境判断去掉就可以在任何环境加载 mock

按照您说的把mock的环境判断去掉了，按生产环境打包后放到nginx中，nginx配置文件中的/api该如何设置？
