### ISSUE TITLE
浏览器第一次加载文件过大，第一次登录页面白板，刷新才能出来首页

### ISSUE THREAD

**Issue by dbmcp** [vueComponent/ant-design-vue-pro#385]
用火狐浏览器看，app.js  20.8M
第一次登录进去白板，只有欢迎小弹窗，需刷新一次当前页面在能显示首页

求助：
1、如何压缩文件大小？
2、登录后白板如何处理？

**Comment by dbmcp** [comment]
我做的前后端分离，用nginx做容器

**Comment by sendya** [comment]
请不要用 dev 模式部署项目
