### ISSUE TITLE
代码中现成的图表组件不是很丰富，不够用

### ISSUE THREAD

**Issue by DavidWhom** [vueComponent/ant-design-vue-pro#388]
**Question （问题描述）**
代码中现成的图表组件不是很丰富，不够用（比如说我需要折线图，甚至双折线图...），且关于已有的图表组件的使用也没有ant-design-pro-vue的官方文档

**Describe the solution you'd like （你期待的是什么？）**
希望有文档介绍现成图表组件

**Additional context（附加信息）**
因为有图表需求，因此自己引入了antV，解决了问题。这种方式对吗，或者说有更好的解决办法？
新手提问，有冒昧之处还请见谅，打扰了，谢谢~

**Comment by sendya** [comment]
项目本身就引入了 antv，你要做的只是去阅读文档，进而直接开始使用

https://viserjs.github.io/docs.html#/viser/guide/installation
https://antv.alipay.com/zh-cn/index.html

**Comment by DavidWhom** [comment]
好的，谢谢
