### ISSUE TITLE
请问生产环境如何在线换肤

### ISSUE THREAD

**Issue by ch656409110** [vueComponent/ant-design-vue-pro#39]
请问生产环境如何在线换肤？

配置栏只在开发环境用于预览，生产环境不会展现，请手动修改配置文件 src/defaultSettings.js

谢谢美女

**Comment by sendya** [comment]
你可以选择不去掉 `SettingDrawer` 那么就可以在生产环境保留设置栏的所有功能。但我不能保证线上环境该功能的性能问题

**Comment by ch656409110** [comment]
感谢回复，这个功能非常有用，用户可以根据自己喜好来设置。
但是除了更新主题色会报错：Failed to update theme
其他都是好的，请求可以修复吗？或者可以教我怎么做吗？我是前端小白。感谢美女。

**Comment by sendya** [comment]
你把 `public/` 的 `color.less` 删了吗？如果没有，切换主题色，贴控制台输出

**Comment by ch656409110** [comment]
你说控制台，我就去看了 发现color.less 竟然404，然后配置IIS 的mime类型就好了。感谢~~
