### ISSUE TITLE
一级菜单, 暗色风格, 顶部栏导航风格, 样式出现问题

### ISSUE THREAD

**Issue by free-pan** [vueComponent/ant-design-vue-pro#392]
**Describe the bug （描述 Bug）**

设置一个没有子菜单的一级菜单, 主题设置为暗色风格, 采用顶部导航栏. 样式出现问题.

注意: **只有暗色主题存在问题, 亮色的没问题**

演示地址: http://free_pan.gitee.io/ant-design-pro-vue-modify/#/welcome/index
账号/密码: admin/admin

**To Reproduce （重现步骤）**

演示地址: http://free_pan.gitee.io/ant-design-pro-vue-modify/#/welcome/index
账号/密码: admin/admin

1. 打开主题设置, 切换到暗色风格
2. 导航方式选择顶部导航
3. 点击"欢迎"菜单, 此时就可以看到问题了

**Expected behavior（你期待的是什么?）**
没有子菜单的这种一级菜单, 在暗色风格下, 选中时文字和图标的颜色都是白色

**Comment by sendya** [comment]
没有任何问题。

另外，既然你 fork 并且自己独立分支，出 bug 时，请先确认我这边主分支是否有问题，在提交 Bug，不要你那边自己随便改改，出 bug 了还跑到我这里来问

![image](https://user-images.githubusercontent.com/5404542/63637874-673d6300-c6b4-11e9-8c29-813902cc5d89.png)

**Comment by free-pan** [comment]
@sendya 我刚准备补充内容,你就关闭了.
这个有一点特别的是, 直接`tyarn run serve`是正常的, 但`build`之后, 就有问题了.
不知道你看的时候是不是`build`之后看的

**Comment by sendya** [comment]
@free-pan  Please confirm this page https://preview.pro.loacg.com/dashboard/analysis and Read **Commit Log** https://github.com/sendya/ant-design-pro-vue/commits/master

**Comment by free-pan** [comment]
@saraka  好的, 非常感谢! 这是我的问题, 以后会全面排查之后,再提问题. 对于我的疏忽导致你的不愉快, 我再次表示抱歉.

**Comment by sendya** [comment]
如果颜色有问题，提这边来 不要单独开贴了 https://github.com/sendya/ant-design-pro-vue/issues/284

**Comment by free-pan** [comment]
最后, 再次感谢 sendya 大神的耐心解答. 即使这个是我自己的原因导致的问题, 大神也耐心的帮我分析问题. 真的非常感谢. 大神说的对, 以后遇到问题, 一定要先排查是不是自己导致的问题.

以下是我出现这个问题的原因:
我修改了`vue.config.js`中的主题替换插件的配置

我修改之后的配置方式:
```js
....其它配置省略

// 注意,我去除了if判断
vueConfig.configureWebpack.plugins.push(createThemeColorReplacerPlugin())

....其它配置省略
```

pro原本的配置方式
```js
....其它配置省略

// preview.pro.loacg.com only do not use in your production;
if (process.env.NODE_ENV !== 'production' || process.env.VUE_APP_PREVIEW === 'true') {
  // add `ThemeColorReplacer` plugin to webpack plugins
  vueConfig.configureWebpack.plugins.push(createThemeColorReplacerPlugin())
}

....其它配置省略
```

使用我修改之后的配置方式, 在`tyarn run serve`下运行时没问题, 但是build之后, 会导致css的优先级问题.

正常情况下的css解析结果:

![image](https://user-images.githubusercontent.com/37232676/63644962-4eba6080-c727-11e9-909e-3cd4560ea44a.png)


采用我的配置方式,导致的错误的css解析结果:

![image](https://user-images.githubusercontent.com/37232676/63644996-def8a580-c727-11e9-94d9-d7d323a81065.png)

**为什么我要做这个修改?**
因为我想在生产环境启用这个主题替换组件. 然后做了这个修改. 后面经过测试, 发现, 要在生产环境启用主题替换插件, 只需要修改`defaultSettings.js`中的`production`属性为false即可.

**如何解决:**
既然是自己修改`vue.config.js`导致的问题, 那么, 将主题替换插件的配置方式, 修改为pro原来的方式即可.

如果你也需要在生产环境启用这个主题切换插件, 那么只需要修改`defaultSettings.js`中的`production`属性为false即可. 不要再重复我的错误.
