### ISSUE TITLE
图片上传完以后有的时候URL为空，小缩略图不显示，但是再上传一张，前面的小缩略图就显示出来了

### ISSUE THREAD

**Issue by yangyanju** [vueComponent/ant-design-vue-pro#393]
图片上传完以后有的时候URL为空，小缩略图不显示，但是再上传一张，前面的小缩略图就显示出来了

怎么能让上传图片后就显示小缩略图呢

效果如图所示：
![image](https://user-images.githubusercontent.com/7056767/63735981-3035a000-c8b4-11e9-8287-de196dafff1a.png)

但是再上传一张图片，前面的小缩略图就出来了，但是新上传的图片又不显示了：
![image](https://user-images.githubusercontent.com/7056767/63736036-5f4c1180-c8b4-11e9-9c70-13e2af877ed4.png)

@change="uploadChange"的代码如下：
uploadChange ({ fileList }) {
        console.log(fileList,'fileList')
        fileList.forEach(item=>{
          if(!item.url){
            item.url = item.thumbUrl
          }
        })
        this.fileList = fileList
        this.$forceUpdate()//强制刷新
      },

**Comment by sendya** [comment]
这个是组件库的 Bug，尚未修复

**Comment by Amyff** [comment]
` uploadImage: function (e) {
      let formdata = new FormData()
      formdata.append('file', e.file)
      axios({
        url: '/api/file/upload',
        method: 'post',
        data: formdata
      }).then((res) => {
        if (this.multiple === 1) {
          this.fileList = [{
            uid: '-1', // 文件唯一标识，建议设置为负数，防止和内部产生的 id 冲突
            name: e.file.name, // 文件名
            status: 'done', // 状态有：uploading done error removed
            url: this.GLOBAL.imgUrl + res.result.fileId
          }]
        } else {
          if (this.fileList.length < this.multiple) {
            this.fileList.push({
              uid: '-' + (this.fileList.length + 1), // 文件唯一标识，建议设置为负数，防止和内部产生的 id 冲突
              name: e.file.name, // 文件名
              status: 'done', // 状态有：uploading done error removed
              url: this.GLOBAL.imgUrl + res.result.fileId
            })
          }
        }
        this.$emit('getImageId', res.result.fileId)
      })
    }`


可以试下 我本来也是这个样子 后来解决了
