### ISSUE TITLE
expand and expandedRowsChange are not work in "s-table"

### ISSUE THREAD

**Issue by loveFemi** [vueComponent/ant-design-vue-pro#394]
**Describe the bug （描述 Bug）**

expand and expandedRowsChange are not work in "s-table"

**To Reproduce （重现步骤）**
main code:
<s-table
      size="default"
      rowKey="id"
      ref="table"
      expandRowByClick
      @expandedRowsChange="expandedRowsChange"
      @expand="expand"
      :columns="columns"
      :data="loadData"
    ></s-table>
methods: {
expand (expanded, record) {
      console.log(expanded, record)
    },
    expandedRowsChange (expandedRows) {
      console.log(expandedRows)
    },
}

**Expected behavior（你期待的是什么?）**
why does it do not work?And how to do?

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
`s-table` not support `expand` and `expandedRowsChange` prop,  please use `a-table`

**Comment by keroes000** [comment]
--

**Comment by keroes000** [comment]
hope can support soon
