### ISSUE TITLE
作者或者大家有没有遇到过当文件超级多时的编译速度和打包速度超级慢的问题

### ISSUE THREAD

**Issue by changhighly** [vueComponent/ant-design-vue-pro#397]
作者或者大家有没有试过或者遇到过当vue文件超过100个甚至200多个时的编译速度和打包速度，目前遇到的问题是当文件超级多时，编译速度超级慢，时间成几何数值增加，经常卡在70%位置就不动了，打包也是，在1000s左右，当把VUE文件减少到50个左右时，打包时间成几何数值降低，当达到一定量时打包时间又几何数值增加。
也没有更改过项目cli
有遇到并解决的同学希望分享下解决办法
![image](https://user-images.githubusercontent.com/22925367/63853650-d45f3a00-c9cd-11e9-8b43-041990b042de.png)
![image](https://user-images.githubusercontent.com/22925367/63853696-f48ef900-c9cd-11e9-84e9-9d7f166f02d5.png)

**Comment by sendya** [comment]
列出你的 webpack 配置等，供分析

**Comment by changhighly** [comment]
> 列出你的 webpack 配置等，供分析

这个引用的比较早，我看Pro项目现在的配置和这个不太一样

```javascript
const path = require('path')
const webpack = require('webpack')

function resolve(dir) {
  return path.join(__dirname, dir)
}

// vue.config.js
module.exports = {
  productionSourceMap:false,
  /*
    Vue-cli3:
    Crashed when using Webpack `import()` #2463
    https://github.com/vuejs/vue-cli/issues/2463

   */
  /*
  pages: {
    index: {
      entry: 'src/main.js',
      chunks: ['chunk-vendors', 'chunk-common', 'index']
    }
  },
  */
  configureWebpack: {
    plugins: [
      // Ignore all locale files of moment.js
      new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
    ]
  },

  chainWebpack: (config) => {
    config.resolve.alias
      .set('@$', resolve('src'))
      .set('@api', resolve('src/api'))
      .set('@assets', resolve('src/assets'))
      .set('@comp', resolve('src/components'))
      .set('@views', resolve('src/views'))
      .set('@layout', resolve('src/layout'))
      .set('@static', resolve('src/static'))

    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()
    svgRule
      .oneOf('inline')
      .resourceQuery(/inline/)
      .use('vue-svg-icon-loader')
      .loader('vue-svg-icon-loader')
      .end()
      .end()
      .oneOf('external')
      .use('file-loader')
      .loader('file-loader')
      .options({
        name: 'assets/[name].[hash:8].[ext]'
      })
  },

  css: {
    loaderOptions: {
      less: {
        modifyVars: {
          /* less 变量覆盖，用于自定义 ant design 主题 */

          /*
          'primary-color': '#F5222D',
          'link-color': '#F5222D',
          'border-radius-base': '4px',
          */
        },
        javascriptEnabled: true
      }
    }
  },

  devServer: {
    // development server port 8000
    port: 8000,
    proxy: {
      '/api/sys': {
        target: 'http://aaa.com',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api/sys': ''
        }
      },
    }
  },

  lintOnSave: undefined,
  // babel-loader no-ignore node_modules/*
  transpileDependencies: []
}


```

**Comment by sendya** [comment]
.. 
package.json

**Comment by changhighly** [comment]
> ..
> package.json

```json
{
  "name": "pro",
  "version": "2.0.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "build:preview": "vue-cli-service build --mode preview",
    "lint": "vue-cli-service lint",
    "lint:nofix": "vue-cli-service lint --no-fix",
    "test:unit": "vue-cli-service test:unit",
    "fix-memory-limit": "cross-env LIMIT=8192 increase-memory-limit",
    "postinstall": "opencollective-postinstall"
  },
  "dependencies": {
    "@antv/data-set": "^0.10.1",
    "ant-design-vue": "~1.3.9",
    "axios": "^0.19.0",
    "core-js": "^2.6.5",
    "enquire.js": "^2.1.6",
    "js-cookie": "^2.2.0",
    "js-file-download": "^0.4.7",
    "lodash.get": "^4.4.2",
    "lodash.pick": "^4.4.0",
    "md5": "^2.2.1",
    "mockjs2": "^1.0.5",
    "moment": "^2.24.0",
    "nprogress": "^0.2.0",
    "viser-vue": "^2.3.3",
    "vue": "^2.5.22",
    "vue-clipboard2": "^0.2.1",
    "vue-cropper": "0.4.4",
    "vue-i18n": "^8.10.0",
    "vue-ls": "^3.2.0",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "^3.0.1",
    "vue-svg-component-runtime": "^1.0.1",
    "vuex": "^3.1.0",
    "wangeditor": "^3.1.1"
  },
  "devDependencies": {
    "@ant-design/colors": "^3.1.0",
    "@babel/polyfill": "^7.2.5",
    "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-unit-jest": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^5.2.0",
    "increase-memory-limit": "^1.0.3",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "opencollective": "^1.0.3",
    "opencollective-postinstall": "^2.0.2",
    "vue-svg-icon-loader": "^2.1.1",
    "vue-template-compiler": "^2.5.22",
    "webpack-theme-color-replacer": "^1.1.5"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/strongly-recommended",
      "@vue/standard"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {
      "generator-star-spacing": "off",
      "no-mixed-operators": 0,
      "vue/max-attributes-per-line": [
        2,
        {
          "singleline": 5,
          "multiline": {
            "max": 1,
            "allowFirstLine": false
          }
        }
      ],
      "vue/attribute-hyphenation": 0,
      "vue/html-self-closing": 0,
      "vue/component-name-in-template-casing": 0,
      "vue/html-closing-bracket-spacing": 0,
      "vue/singleline-html-element-content-newline": 0,
      "vue/no-unused-components": 0,
      "vue/multiline-html-element-content-newline": 0,
      "vue/no-use-v-if-with-v-for": 0,
      "vue/html-closing-bracket-newline": 0,
      "vue/no-parsing-error": 0,
      "no-console": 0,
      "no-useless-concat": 0,
      "no-tabs": 0,
      "quotes": [
        2,
        "single",
        {
          "avoidEscape": true,
          "allowTemplateLiterals": true
        }
      ],
      "semi": [
        2,
        "never",
        {
          "beforeStatementContinuationChars": "never"
        }
      ],
      "no-delete-var": 2,
      "prefer-const": [
        2,
        {
          "ignoreReadBeforeAssign": false
        }
      ]
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "collective": {
    "type": "opencollective",
    "url": "https://opencollective.com/ant-design-pro-vue"
  }
}

```

**Comment by changhighly** [comment]
> > ..
> > package.json
> name不是项目真实名称
> ```json
> {
>   "name": "pro",
>   "version": "2.0.0",
>   "private": true,
>   "scripts": {
>     "serve": "vue-cli-service serve",
>     "build": "vue-cli-service build",
>     "build:preview": "vue-cli-service build --mode preview",
>     "lint": "vue-cli-service lint",
>     "lint:nofix": "vue-cli-service lint --no-fix",
>     "test:unit": "vue-cli-service test:unit",
>     "fix-memory-limit": "cross-env LIMIT=8192 increase-memory-limit",
>     "postinstall": "opencollective-postinstall"
>   },
>   "dependencies": {
>     "@antv/data-set": "^0.10.1",
>     "ant-design-vue": "~1.3.9",
>     "axios": "^0.19.0",
>     "core-js": "^2.6.5",
>     "enquire.js": "^2.1.6",
>     "js-cookie": "^2.2.0",
>     "js-file-download": "^0.4.7",
>     "lodash.get": "^4.4.2",
>     "lodash.pick": "^4.4.0",
>     "md5": "^2.2.1",
>     "mockjs2": "^1.0.5",
>     "moment": "^2.24.0",
>     "nprogress": "^0.2.0",
>     "viser-vue": "^2.3.3",
>     "vue": "^2.5.22",
>     "vue-clipboard2": "^0.2.1",
>     "vue-cropper": "0.4.4",
>     "vue-i18n": "^8.10.0",
>     "vue-ls": "^3.2.0",
>     "vue-quill-editor": "^3.0.6",
>     "vue-router": "^3.0.1",
>     "vue-svg-component-runtime": "^1.0.1",
>     "vuex": "^3.1.0",
>     "wangeditor": "^3.1.1"
>   },
>   "devDependencies": {
>     "@ant-design/colors": "^3.1.0",
>     "@babel/polyfill": "^7.2.5",
>     "@vue/cli-plugin-babel": "^3.7.0",
>     "@vue/cli-plugin-unit-jest": "^3.7.0",
>     "@vue/cli-service": "^3.7.0",
>     "@vue/test-utils": "^1.0.0-beta.20",
>     "babel-core": "7.0.0-bridge.0",
>     "babel-jest": "^23.6.0",
>     "babel-plugin-import": "^1.11.0",
>     "cross-env": "^5.2.0",
>     "increase-memory-limit": "^1.0.3",
>     "less": "^3.8.1",
>     "less-loader": "^4.1.0",
>     "opencollective": "^1.0.3",
>     "opencollective-postinstall": "^2.0.2",
>     "vue-svg-icon-loader": "^2.1.1",
>     "vue-template-compiler": "^2.5.22",
>     "webpack-theme-color-replacer": "^1.1.5"
>   },
>   "eslintConfig": {
>     "root": true,
>     "env": {
>       "node": true
>     },
>     "extends": [
>       "plugin:vue/strongly-recommended",
>       "@vue/standard"
>     ],
>     "parserOptions": {
>       "parser": "babel-eslint"
>     },
>     "rules": {
>       "generator-star-spacing": "off",
>       "no-mixed-operators": 0,
>       "vue/max-attributes-per-line": [
>         2,
>         {
>           "singleline": 5,
>           "multiline": {
>             "max": 1,
>             "allowFirstLine": false
>           }
>         }
>       ],
>       "vue/attribute-hyphenation": 0,
>       "vue/html-self-closing": 0,
>       "vue/component-name-in-template-casing": 0,
>       "vue/html-closing-bracket-spacing": 0,
>       "vue/singleline-html-element-content-newline": 0,
>       "vue/no-unused-components": 0,
>       "vue/multiline-html-element-content-newline": 0,
>       "vue/no-use-v-if-with-v-for": 0,
>       "vue/html-closing-bracket-newline": 0,
>       "vue/no-parsing-error": 0,
>       "no-console": 0,
>       "no-useless-concat": 0,
>       "no-tabs": 0,
>       "quotes": [
>         2,
>         "single",
>         {
>           "avoidEscape": true,
>           "allowTemplateLiterals": true
>         }
>       ],
>       "semi": [
>         2,
>         "never",
>         {
>           "beforeStatementContinuationChars": "never"
>         }
>       ],
>       "no-delete-var": 2,
>       "prefer-const": [
>         2,
>         {
>           "ignoreReadBeforeAssign": false
>         }
>       ]
>     }
>   },
>   "postcss": {
>     "plugins": {
>       "autoprefixer": {}
>     }
>   },
>   "browserslist": [
>     "> 1%",
>     "last 2 versions",
>     "not ie <= 10"
>   ],
>   "collective": {
>     "type": "opencollective",
>     "url": "https://opencollective.com/ant-design-pro-vue"
>   }
> }
> ```

**Comment by changhighly** [comment]
name不是项目真实名称

**Comment by iota9star** [comment]
我之前热更新超级慢，个人的项目vue文件大概有六七十个文件，后台返回的json异步生成的router信息，组件都是异步加载，修改一下到热更新到完成大概要一分钟左右，后面在开发环境配置文件中加了  
`VUE_CLI_BABEL_TRANSPILE_MODULES=true`  
配置后修改一次到热更新完成大概两秒左右，加了这个有效减少等待时间，针对热更新慢的可以试一下这个
