### ISSUE TITLE
<keep-alive>组件使用无效问题

### ISSUE THREAD

**Issue by MalavitaC** [vueComponent/ant-design-vue-pro#398]
需求：详情页返回列表页，列表页缓存不刷新，其他页面跳转列表页正常刷新。
代码：
App.vue
```
<template>
  <a-locale-provider :locale="locale">
    <div id="app">
      <keep-alive include="TableList">
        <router-view/>
      </keep-alive>
    </div>
  </a-locale-provider>
</template>
```
将查询列表组件TableList页面添加缓存
结果：路由跳转到查询列表页面还是会刷新。
问题：如何实现离开页面，页面内容缓存，动态修改缓存的页面？

**Comment by sendya** [comment]
你搞错层级了，页面路由是在 https://github.com/sendya/ant-design-pro-vue/blob/master/src/layouts/BasicLayout.vue#L46
