### ISSUE TITLE
filterAsyncRouter 函数中的关于route.children的判断和赋值

### ISSUE THREAD

**Issue by cjc2011** [vueComponent/ant-design-vue-pro#399]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by cjc2011** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/store/modules/permission.js#L43#L45

我在看权限判断这块的代码时 没太理解这段代码的作用 注释掉的话好像也没影响

**Comment by sendya** [comment]
过滤子菜单权限
