### ISSUE TITLE
这个项目，Header顶部菜单和左侧菜单默认是false，即不固定时是正常的，当Header顶部菜单或者左侧菜单固定时，就会出问题，内容区和顶部菜单的左边会被覆盖住。这个项目真心很不错，辛苦

### ISSUE THREAD

**Issue by fwj722** [vueComponent/ant-design-vue-pro#40]
这个项目，Header顶部菜单和左侧菜单默认是false，即不固定时是正常的，当Header顶部菜单或者左侧菜单固定时，就会出问题，内容区和顶部菜单的左边会被覆盖住。这个项目真心很不错，辛苦

**Comment by sendya** [comment]
清理浏览器 `localStorage` 应该能解决

**Comment by sendya** [comment]
如果不行，建议看一下控制台有没有什么错误输出 。贴上来
