### ISSUE TITLE
请教一下,打包部署之后违和主题色没有更换

### ISSUE THREAD

**Issue by zhichao8756** [vueComponent/ant-design-vue-pro#400]
![image](https://user-images.githubusercontent.com/24514251/64013511-8c1d5480-cb52-11e9-9a13-63f406205a96.png)

这是我的vue.config.js文件
![image](https://user-images.githubusercontent.com/24514251/64013546-9e978e00-cb52-11e9-835d-811418b21edc.png)
![image](https://user-images.githubusercontent.com/24514251/64013753-1d8cc680-cb53-11e9-8ec6-dda563a5e203.png)

![image](https://user-images.githubusercontent.com/24514251/64013586-b4a54e80-cb52-11e9-90d6-5e0528542e74.png)
这是我的defaultSetting文件
![image](https://user-images.githubusercontent.com/24514251/64013640-d7cffe00-cb52-11e9-8fd7-e21e8ac3ae22.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/64035629-d834bd00-cb83-11e9-8fd2-5f15767f4877.png)

打包请用这个设定主题色，换色插件仅在开发模式中存在。编译就不会存在了
