### ISSUE TITLE
流式布局，顶部导航栏右侧留有大片空白没有自适应

### ISSUE THREAD

**Issue by tanshion** [vueComponent/ant-design-vue-pro#405]
**Describe the bug （描述 Bug）**

流式布局，顶部导航栏右侧留有大片空白没有自适应

![image](https://user-images.githubusercontent.com/9196558/64146649-55945200-ce50-11e9-83e5-74f70b5809ba.png)

应该如以下正常效果

![image](https://user-images.githubusercontent.com/9196558/64146978-77420900-ce51-11e9-88b6-9e625e361f85.png)

**Comment by kokoroli** [comment]
![image](https://user-images.githubusercontent.com/25897806/64224408-ec711500-cf09-11e9-8348-70d319d72c0c.png)
已修复

**Comment by tanshion** [comment]
完美

**Comment by zhengyeye** [comment]
我新拉取是代码，运行起来，上面这个导航栏还是没有自适应显示。而是把超出来的部分隐藏掉了。
![2222](https://user-images.githubusercontent.com/22360278/86876713-e8101c80-c117-11ea-9797-cf5be9eda3c5.png)
我看上面说，已经修复了，请问是要修改哪里吗？
![111](https://user-images.githubusercontent.com/22360278/86876772-04ac5480-c118-11ea-9ae1-89d191432716.png)
谢谢。
