### ISSUE TITLE
不太适合后端人员开发

### ISSUE THREAD

**Issue by ChinaBygones** [vueComponent/ant-design-vue-pro#406]
项目很好，但是作为我们后端开发人员来说不是很友好，动不动就报错，定义接口改了就报错了，报错还不显示文件，很苦恼，有什么解决方法没，学习成本太大，后端人员同感用木有

根本不知道在哪引入了那些文件，鄙人有强迫证， = = 删除了一个感觉没用的文件就报错了，关键是报错还不现实那个文件报错的，这就很苦恼，有没有更好的解决方案

**Comment by sendya** [comment]
本项目不推荐没有基础的后端使用，谢谢

**Comment by iota9star** [comment]
@ChinaBygones 我上来就把mock删了都还好，这个还是得有点基础才行，报错的话会有提示，我也是个菜鸟，遇到问题多多百度谷歌，解决不了再提问题，尽量把问题描述清楚，这样对大家都好，不浪费大家的时间，而不是说一个笼统的问题，最后啥也没搞成，报错太多就注释掉router无用的，一个一个来，想要啥界面打开[项目的预览](https://preview.pro.loacg.com/user/login?redirect=%2F)对比一下再添加就好:heart:
