### ISSUE TITLE
如何设置动态路由名称, 非路由

### ISSUE THREAD

**Issue by FrontEnd-Hub** [vueComponent/ant-design-vue-pro#408]
![image](https://user-images.githubusercontent.com/46841851/64223309-001a7c80-cf06-11e9-9569-d76027e84829.png)
名称由后台返回

**Comment by sendya** [comment]
https://pro.loacg.com/docs/authority-management

**Comment by XinJiangQingMang** [comment]
动态路由  后端真的不用给前端返一个role 然后再根据role去获取路由，token交互，后端直接根据token就能直接返路由菜单。

**Comment by sendya** [comment]
@XinJiangQingMang  我只提供一个思路，怎么实现是你们做后端的人的事情

**Comment by free-pan** [comment]
@XinJiangQingMang 我试了一种方式实现. 也许对你有一定的参考价值, 如果有兴趣可以看下: [我的修改](https://gitee.com/free_pan/ant-design-pro-vue-modify)
