### ISSUE TITLE
生产环境下主题应用不生效

### ISSUE THREAD

**Issue by myforest0** [vueComponent/ant-design-vue-pro#409]
**Question （问题描述）**
在右侧栏拷贝主题配置代码后并覆盖`defaultSettings.js`,开发环境没问题，打包上线后，主题并没有生效

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L43-L47

主题不对生成环境产生效果，请直接使用这个覆盖

**Comment by myforest0** [comment]
明白了，请问生产环境下怎么固定导航头部和侧边栏，需要配置吗 @sendya

**Comment by free-pan** [comment]
@xiang-shilin 设置好你要的主题后, 拷贝设置的js, 然后复制到 `defaultSettings.js` 中. 你的没有改变, 可能是缓存导致的吧, 你清除缓存再看下.

**Comment by myforest0** [comment]
@free-pan 我已经解决了，非常感谢！
