### ISSUE TITLE
请问build以后发布路由访问的问题

### ISSUE THREAD

**Issue by ch656409110** [vueComponent/ant-design-vue-pro#41]
美女你好：
请教一个build的问题，项目我build以后 发现访问首页 http://192.168.6.11:8011/index.html 没有问题，它后面跳转到路由地址也没有问题，比如 http://192.168.6.11:8011/dashboard/workplace ，但是如果F5刷新，或者get访问访问这个路由，浏览器就返回404了，我开始以为是服务器的问题，后来我用了IIS 和Tomcat都是一样的结果，请问你有遇到过吗？

PS：开发环境一点问题没有。

**Comment by sendya** [comment]
使用 `history` 的基本常识是，任何请求均指向到 `/index.html`
```nginx
        location / {
                try_files $uri $uri/ /index.html =404;
        }
```

eg:
```nginx

server {
        listen 80;
        listen 443;
        server_name pro.loacg.com;
        access_log /data/logs/pro_access.log combined;
        index index.html index.htm index.php;
        root  /data/web/vue-antd-pro/dist;

        add_header Access-Control-Allow-Origin "pro.loacg.com";

        location / {
                try_files $uri $uri/ /index.html =404;
        }

        location /api/ {
                #proxy_set_header        Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
		proxy_set_header	X-Forwarded-Proto $scheme;
                proxy_pass              https://www.easy-mock.com/mock/5b7bce071f130e5b7fe8cd7d/antd-pro/api/;
        }
}

```

**Comment by ch656409110** [comment]
非常感谢，今天受益匪浅，学会Nginx了。

我读懂你的配置了，之前我配置api路径这么来的 baseURL: 'http://192.168.6.11:8011/api', // api base_url 
现在直接配置/api 就可以了，还可以保护api服务器。真高级。

66666，感谢~~

**Comment by aochuangkeji** [comment]
clone下来的项目yarn run serve正常，但是build后打开index文件报错
![image](https://user-images.githubusercontent.com/38239757/64512485-203ca800-d319-11e9-8163-0722171ed73b.png)

**Comment by aochuangkeji** [comment]
可以明确下该怎么处理吗？
