### ISSUE TITLE
 slot 和 slot-scope 特性语法已废弃的使用

### ISSUE THREAD

**Issue by TonyLuo** [vueComponent/ant-design-vue-pro#410]
slot-scope 自 2.6.0 起被废弃 
v-slot 指令自 Vue 2.6.0 起被引入，提供更好的支持 slot 和 slot-scope 特性的 API 替代方案。v-slot 完整的由来参见这份 RFC。在接下来所有的 2.x 版本中 slot 和 slot-scope 特性仍会被支持，但已经被官方废弃且不会出现在 Vue 3 中。

https://cn.vuejs.org/v2/guide/components-slots.html#%E5%BA%9F%E5%BC%83%E4%BA%86%E7%9A%84%E8%AF%AD%E6%B3%95

### 旧语法
```html
 <span slot="action" slot-scope="record"> 
```
### 新语法
```html
   <template v-slot:action="record">
```

**Comment by sendya** [comment]
你好，我们用的是 2.x 版本，不是 3.x 版本。另外 新语法 在底层是兼容的，你自己编写项目的时候可以直接使用新语法。
