### ISSUE TITLE
分析页布局错乱了

### ISSUE THREAD

**Issue by free-pan** [vueComponent/ant-design-vue-pro#412]
**Describe the bug （描述 Bug）**

分析页布局错乱了

**To Reproduce （重现步骤）**

打开 https://preview.pro.loacg.com/dashboard/analysis

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/37232676/64410661-14a17500-d0be-11e9-8e64-18c5269327af.png)

**Desktop (please complete the following information):**

 - OS: Mac OS
 - Browser Chrome
 - Version chrome(版本 76.0.3809.132（正式版本） （64 位）)

**Comment by sendya** [comment]
视窗分辨率多少？

**Comment by free-pan** [comment]
显示器大小: 15.4 英寸
我屏幕本身的分辨率是: 2880 x 1800
从调试工具看到的元素占用的分辨率
![image](https://user-images.githubusercontent.com/37232676/64413995-29353b80-d0c5-11e9-949f-dd35d18078d6.png)

![image](https://user-images.githubusercontent.com/37232676/64414146-6f8a9a80-d0c5-11e9-8dc6-e9f4f5df2940.png)

![image](https://user-images.githubusercontent.com/37232676/64414221-921cb380-d0c5-11e9-8423-a410b6222ff8.png)

![image](https://user-images.githubusercontent.com/37232676/64414257-a82a7400-d0c5-11e9-9bf0-d43cb3c063a7.png)

**Comment by free-pan** [comment]
浏览器已处于全屏状态. 这个是body的大小

![image](https://user-images.githubusercontent.com/37232676/64414705-6c43de80-d0c6-11e9-85a6-42597426a50e.png)

**Comment by free-pan** [comment]
貌似是这个class`antd-pro-pages-dashboard-analysis-twoColLayout`影响的. 我去掉这个class之后就恢复正常了. 对原本的样式好像也没什么影响

原始:

![image](https://user-images.githubusercontent.com/37232676/64476356-6500fb80-d1c0-11e9-8380-93578d9fad68.png)

去掉之后:

![image](https://user-images.githubusercontent.com/37232676/64476444-261f7580-d1c1-11e9-8092-1673a747eaa1.png)

**Comment by zkwolf** [comment]
@free-pan 其实你认真看会发现，去掉了以后左右card高度就不一样了

**Comment by DaskV** [comment]
> 貌似是这个class`antd-pro-pages-dashboard-analysis-twoColLayout`影响的. 我去掉这个class之后就恢复正常了. 对原本的样式好像也没什么影响
> 
> 原始:
> 
> ![image](https://user-images.githubusercontent.com/37232676/64476356-6500fb80-d1c0-11e9-8380-93578d9fad68.png)
> 
> 去掉之后:
> 
> ![image](https://user-images.githubusercontent.com/37232676/64476444-261f7580-d1c1-11e9-8092-1673a747eaa1.png)

仔细看 css ，last-child 为absolute 定位，只写了 right:0  , css 加一个 top: 0 就好了。

**Comment by sendya** [comment]
> 仔细看 css ，last-child 为absolute 定位，只写了 right:0 , css 加一个 top: 0 就好了。

在 chrome 76 以前的版本一直没有问题，在 edge / ie11 / firefox 也没有问题。
并且这段代码 9 个月至今没改过，我更觉得是 chrome 在这个版本对 style 的解析渲染暗改了

**Comment by sendya** [comment]
fixed https://github.com/sendya/ant-design-pro-vue/commit/426a2cc98cb990c38092c1992744b1cf9b58fcc3#diff-7ffb6f6262b6ea35a18c169991e62b48R103-R170
