### ISSUE TITLE
想去掉一些用到的模板文件以及代码

### ISSUE THREAD

**Issue by ChinaBygones** [vueComponent/ant-design-vue-pro#413]
想去掉一些用到的模板文件以及代码

删除之后就报错，可能有别的地方引入了吧，

请问你们都是怎么做的

**Comment by free-pan** [comment]
在你还不熟悉的情况下, 可以按路由先一个一个删除, 删除一个, 然后启动看下有没有报错. 没有报错, 就再删除下一个.`Workplace`这个比较特殊, 因为登录成功之后, 默认是转入这个路由的. 
希望我的回答对你有用

**Comment by sendya** [comment]
报错请提供报错信息

**Comment by ChinaBygones** [comment]
> 报错请提供报错信息

嗯，是有再别的地方引入这个文件了，很难找到在哪引入的,我的想法是怎么快速去掉一些文件，如果没有办法就算了，我自己一点一点找代码吧 = =
