### ISSUE TITLE
组件按需加载后登录页错乱

### ISSUE THREAD

**Issue by tongxin3267** [vueComponent/ant-design-vue-pro#416]
**Describe the bug （描述 Bug）**

修改为`import './core/lazy_use'`按需加载后登录页错乱

**Comment by sendya** [comment]
改 `babel.config` 了没？

**Comment by tongxin3267** [comment]
早上只按README.zh-CN.md文档修改了。开启组件按需加载 `/src/main.js` L14 修改为 `import './core/lazy_use'`。现在找到文档修改了。可以了。感谢
