### ISSUE TITLE
无法在chrome中使用Vue Devtools

### ISSUE THREAD

**Issue by xcy96** [vueComponent/ant-design-vue-pro#418]
**Question （问题描述）**
版本号2.0.0
从 GitHub 仓库中直接安装脚手架代码，然后安装依赖，运行yarn run serve，在chrome浏览器选中vue devtools会提示Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author.
![image](https://user-images.githubusercontent.com/31194211/64486494-80bbde80-d260-11e9-8379-3daf07fb0e13.png)
在入口文件main.js加入Vue.config.devtools = true后，Vue Devtools提示Vue.js is detected on this page. Open DevTools and look for the Vue panel.但是vue那个devtools里的panel就是不出来
![image](https://user-images.githubusercontent.com/31194211/64486464-2b7fcd00-d260-11e9-8828-620e2f1393f2.png)
![image](https://user-images.githubusercontent.com/31194211/64486481-51a56d00-d260-11e9-84d8-bc7cd5150d0c.png)

**Comment by sendya** [comment]
76 版本 chrome 最新 devtools 没复现你的问题。如果不能显示，手动在 main.js 里加 `Vue.config.devtools = true` 试试 也行

**Comment by free-pan** [comment]
可能是cdn方式引入vue导致, 我这里也出现了这个问题. 我将`vue.config.js`中的cdn配置注释掉, 然后重新编译, 再重新打开`开发者工具`,然后刷新一下就好了.

**Comment by winrey** [comment]
我最近也遇到了这个问题，而最神奇的是大概2个月前的另一个项目，完全一样的配置就没有这个问题。

我刚刚去确认了下，`vue.config.js`里的CDN确实是新代码。

CDN引入的是`vue.min.js`，这个版本没有chrome vue  devtool。问题大概就是如 @free-pan 所说。

在模板中把这个cdn的设置，改成只有生产环境才会启用，会不会更好些？

**Comment by free-pan** [comment]
@sendya 
建议升级下vue-router版本,因为我在去掉cdn配置后, 重新启动, 切换路由时出现如下异常:

```
Uncaught (in promise) NavigationDuplicated {_name:""NavigationDuplicated"
```

然后我将`vue-router`升级到3.1.3就好了. 然后发现, vie-router官方的升级中也说了这个问题:

详见: https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md

![image](https://user-images.githubusercontent.com/37232676/64487428-39881a80-d26d-11e9-9929-0f7a4fa166bd.png)

还有个问题, 最新代码, 配置了cdn, 是表示以后会完全改成这种方式吗?

**Comment by xcy96** [comment]
感谢大家的解答！现在有两种方法。
1.将cdn中的vue.min.js改为vue.js，min.js中不支持devtools
2.将cdn和externals全部注释掉，再重新yarn run serve即可

**Comment by sendya** [comment]
@free-pan 在我没发 release 之前，任何 feature 都有可能被添加，也有可能被删除
