### ISSUE TITLE
build后访问index.html页面报错

### ISSUE THREAD

**Issue by aochuangkeji** [vueComponent/ant-design-vue-pro#419]
**Describe the bug （描述 Bug）**

clone下来的项目yarn run serve页面正常；
yarn build 后访问dist下的index.html文件页面报错。
![image](https://user-images.githubusercontent.com/38239757/64513039-457de600-d31a-11e9-901f-157e9fd7f9bf.png)

**To Reproduce （重现步骤）**

1. 按“入门”文档构建项目
2. yarn run build
3. 在HBubilder或其它编辑器中使用chrone浏览器打开index.html文件
4. 页面报错，加载不出来。

**Expected behavior（你期待的是什么?）**
正常显示页面

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/38239757/64513291-c210c480-d31a-11e9-8777-04a4dec38cfc.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**
可能是我这边操作的问题，请大佬指教。

**Comment by sendya** [comment]
ref https://github.com/sendya/ant-design-pro-vue/issues/41

**Comment by aochuangkeji** [comment]
可以明却说明下该怎么处理吗？谢谢。

**Comment by sendya** [comment]
https://pro.loacg.com/docs/deploy

**Comment by aochuangkeji** [comment]
是必须使用 nginx 、spring boot、express、egg 中的一种配置后才可以使用吗？

**Comment by sendya** [comment]
https://cli.vuejs.org/zh/guide/deployment.html

**Comment by aochuangkeji** [comment]
好的，谢谢。请问build后mock数据还可以使用吗？react版本的好像可以。

**Comment by sendya** [comment]
preview / dev 会带 mock ，其余不会。可以自己进 src/mock/ 下改判断

**Comment by aochuangkeji** [comment]
好的，谢谢。
