### ISSUE TITLE
更新到最新版后，之前很多正常的页面都显示不出来了

### ISSUE THREAD

**Issue by TonyLuo** [vueComponent/ant-design-vue-pro#420]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/3250305/64515079-7e1fbe80-d31e-11e9-981f-18c5578aa759.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
请始用 release 版

**Comment by TonyLuo** [comment]
release 版是六月份的，有很多bugfix都没有 T_T

**Comment by iota9star** [comment]
> 请始用 release 版

借楼问一下大佬，预览页一般啥时候更新一次啊？，看到新增了一些特性，但是预览页好像都没有更新，不知道具体效果，求更新

**Comment by sendya** [comment]
@iota9star  预览页随 release 更新

**Comment by iota9star** [comment]
> @iota9star 预览页随 release 更新

好的，release一般是达到什么样的要求才会放出来呢

**Comment by sendya** [comment]
> > @iota9star 预览页随 release 更新
> 
> 好的，release一般是达到什么样的要求才会放出来呢

达到可用的程度
没问题就不要叠楼了，这里不是贴吧，很多人会收到 issue 邮件骚扰的
