### ISSUE TITLE
界面无法暂时页面数据

### ISSUE THREAD

**Issue by XiaoBingBy** [vueComponent/ant-design-vue-pro#427]
![image](https://user-images.githubusercontent.com/9722096/64550036-99adb800-d364-11e9-9dc7-5e89b631e061.png)

**Comment by sendya** [comment]
正常 请使用 release 或者欢迎 PR 补全 mock

**Comment by XiaoBingBy** [comment]
好的谢谢

**Comment by nongzhenli** [comment]
> 正常 请使用 release 或者欢迎 PR 补全 mock

你好！我一直疑惑，release  版本 我该怎下载/拉取呀？ 也没见有这个分支呢！谢谢~
