### ISSUE TITLE
大佬求助一个页面问题

### ISSUE THREAD

**Issue by ChinaBygones** [vueComponent/ant-design-vue-pro#429]
太难啦,好几个星期没整明白那个页面引入那个页面,删除无用页面就报错

太难啦,

比如说 我就想要首页和个人设置页 怎么单独提取出来

**Comment by ChinaBygones** [comment]
小弟略懂vue知道组件 知道语法 知道路由

但是这个框架也太难了吧, 俺是一个业余前端 主要做后端 = =

求大佬指点一二

**Comment by sendya** [comment]
我也是业余前端，主要做后端。如果这个略懂不能搞定，那么应该去 Vue.js 官网文档多参考一下相关文档。

**Comment by mynuolr** [comment]
那不适合你 ，你选择其他框架

**Comment by ChinaBygones** [comment]
好吧 那我知道了我退出

**Comment by iota9star** [comment]
> 太难啦,好几个星期没整明白那个页面引入那个页面,删除无用页面就报错
> 
> 太难啦,
> 
> 比如说 我就想要首页和个人设置页 怎么单独提取出来

@ChinaBygones 到 Router配置文件哪儿把你不要的界面都注释了，只要没删除到引用的文件，其他删除完都没有问题，你只要首页和个人页的话，把这些[router.config.js#L14-L202](https://github.com/sendya/ant-design-pro-vue/blob/37de1c92deeaa9681c282ee4f99fb9824f73858d/src/config/router.config.js#L14-L202)，[router.config.js#L259-L319](https://github.com/sendya/ant-design-pro-vue/blob/37de1c92deeaa9681c282ee4f99fb9824f73858d/src/config/router.config.js#L259-L319)注释或者删除了应该就好了，其他不相关的页面和文件想咋删除都行，我记得你之前是不是发过这个哦。。。

**Comment by ChinaBygones** [comment]
> > 太难啦,好几个星期没整明白那个页面引入那个页面,删除无用页面就报错
> > 太难啦,
> > 比如说 我就想要首页和个人设置页 怎么单独提取出来
> 
> @ChinaBygones 到 Router配置文件哪儿把你不要的界面都注释了，只要没删除到引用的文件，其他删除完都没有问题，你只要首页和个人页的话，把这些[router.config.js#L14-L202](https://github.com/sendya/ant-design-pro-vue/blob/37de1c92deeaa9681c282ee4f99fb9824f73858d/src/config/router.config.js#L14-L202)，[router.config.js#L259-L319](https://github.com/sendya/ant-design-pro-vue/blob/37de1c92deeaa9681c282ee4f99fb9824f73858d/src/config/router.config.js#L259-L319)注释或者删除了应该就好了，其他不相关的页面和文件想咋删除都行，我记得你之前是不是发过这个哦。。。

谢谢大佬耐心讲解,之前发过没人告诉我,可能觉着我太弱了吧😳
