### ISSUE TITLE
permission.js中调用GetInfo这个store的逻辑怎么去掉呢？

### ISSUE THREAD

**Issue by wtt1203** [vueComponent/ant-design-vue-pro#434]
**Question （问题描述）**
目前业务需要直接加载本地路由，但是需要token拦截，如果直接去掉GenerateRoutes里的roles会报错

**Describe the solution you'd like （你期待的是什么？）**
将permission.js中调用GetInfo这个store的逻辑

**Additional context（附加信息）**
现在将GetInfo去掉，路由跳转出现白屏页面。放constantRouterMap里的路由可以正常显示，但是左侧菜单不显示，跪求。

**Comment by sendya** [comment]
参考 https://github.com/sendya/ant-design-pro-vue/issues/76

**Comment by zhangjiagithub** [comment]
已解决,谢谢
