### ISSUE TITLE
真正的路由文件在哪里呢？我把route.config.js的 export const asyncRouterMap 都删除掉可是路由还在

### ISSUE THREAD

**Issue by WOSHIliuhailong** [vueComponent/ant-design-vue-pro#435]
**问题**
真正的路由文件在哪里呢？我把route.config.js的export const asyncRouterMap 都删除掉可是路由还在，求解，实在是找不到。
![chrome](https://github.com/WOSHIliuhailong/djangovue/blob/dev/chrome_2019-09-11_16-07-40.png)
![route](https://github.com/WOSHIliuhailong/djangovue/blob/dev/Code_2019-09-11_16-07-30.png)

**Comment by WOSHIliuhailong** [comment]
@sendya 谢谢

**Comment by loongmxbt** [comment]
马克一下
如果想修改动态路由到静态路由，修改 https://github.com/sendya/ant-design-pro-vue/blob/master/src/store/index.js#L7-L8 中的 permission 导入。
