### ISSUE TITLE
发布到线上环境后更换的主题未生效；刷新页面报错，请问是什么原因呢？该怎么解决？

### ISSUE THREAD

**Issue by aochuangkeji** [vueComponent/ant-design-vue-pro#436]
**Describe the bug （描述 Bug）**

发布到线上环境后更换的主题未生效；点击“退出登录”页面报错。

**To Reproduce （重现步骤）**

1. 发布到线上环境
2.修改的主题未生效
3. 刷新页面
4. 页面报错

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/38239757/64682528-329f1900-d4b4-11e9-8a2c-b78f30d841ca.png)

![image](https://user-images.githubusercontent.com/38239757/64682534-3763cd00-d4b4-11e9-8b4e-7c7ea6e9e41c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
1. 更换主题并不存在与编译的线上环境，更换主题只提供给 preview 预览使用，线上环境请使用 less 的 `modifyVars` 替换主题色。

2. https://github.com/sendya/ant-design-pro-vue/issues/41
https://github.com/sendya/ant-design-pro-vue/issues/91

**Comment by aochuangkeji** [comment]
看了#41和#91后，刷新的问题还是还是不明白~~
我使用的express+pm2发布：
var express = require('express');
var app = express();
const path = require('path')
const port = 8086;
app.use(express.static('./'));
app.listen(port)
路由采用的是：hashHistory

**Comment by aochuangkeji** [comment]
app.get('/*', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});是少了这个吗？

**Comment by sendya** [comment]
https://router.vuejs.org/guide/essentials/history-mode.html
