### ISSUE TITLE
打包去掉 console.log 的问题

### ISSUE THREAD

**Issue by zinda2000** [vueComponent/ant-design-vue-pro#437]
yarn build 没有去掉 console.log
修改 vue.config.js webpack 配置（UglifyJs）
或修改 babel.config.js (bable插件transform-remove-console）
都出错

**Comment by zinda2000** [comment]
小弟菜鸟一枚
补充：修改babel.config.js 参考  https://forum.vuejs.org/t/vue-cli3-0-console/43788

修改webpack配置：
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          compress: {
            warnings: false,
            drop_debugger: true,
            drop_console: true
          }
        }
      })
    ]
  },

**Comment by sendya** [comment]
```
npm i --D babel-plugin-transform-remove-console
```

babel.config.js
```
const IS_PROD = ["production", "prod"].includes(process.env.NODE_ENV);

const plugins = [];
if (IS_PROD) {
  plugins.push("transform-remove-console");
}

module.exports = {
  presets: ["@vue/app", { useBuiltIns: "entry" }],
  plugins
};
```

**Comment by sendya** [comment]
能说明出错都出的什么错吗？

**Comment by zinda2000** [comment]
谢谢回复！但也出错
yarn run v1.16.0
$ vue-cli-service build --dest wwwroot

 ERROR  Failed to compile with 1 errors10:16:10 AM

 error  in ./src/main.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot find module 'babel-plugin-transform-remove-console' from 'D:\temp\ant-design-pro-vue'
    at PoolWorker.fromErrorObj (D:\temp\ant-design-pro-vue\node_modules\thread-loader\dist\WorkerPool.js:258:12)
    at Function.module.exports [as sync] (D:\temp\ant-design-pro-vue\node_modules\resolve\lib\sync.js:69:15)
    at resolveStandardizedName (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePlugin (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\files\plugins.js:54:10)
    at loadPlugin (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\files\plugins.js:62:20)
    at createDescriptor (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at items.map (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPluginDescriptors (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\config-descriptors.js:105:10)
    at plugins (D:\temp\ant-design-pro-vue\node_modules\@babel\core\lib\config\config-descriptors.js:40:19)

 @ multi ./src/main.js

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zinda2000** [comment]
用 UglifyJsPlugin 或者 TerserPlugin

yarn run v1.16.0
$ vue-cli-service build --dest wwwroot
 ERROR  Invalid options in vue.config.js: "optimization" is not allowed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

我的作法，修改 vue.config.js

增加
const TerserPlugin = require('terser-webpack-plugin')

增加
module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: { drop_console: true }
        }
      })
    ]
  },
  configureWebpack: {

**Comment by zinda2000** [comment]
用 UglifyJsPlugin 或者 TerserPlugin

yarn run v1.16.0
$ vue-cli-service build --dest wwwroot
 ERROR  Invalid options in vue.config.js: "optimization" is not allowed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

我的作法，修改 vue.config.js

增加
const TerserPlugin = require('terser-webpack-plugin')

增加
`module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: { drop_console: true }
        }
      })
    ]
  },
  configureWebpack: {`

**Comment by zinda2000** [comment]
用 UglifyJsPlugin 或者 TerserPlugin

yarn run v1.16.0
$ vue-cli-service build --dest wwwroot
 ERROR  Invalid options in vue.config.js: "optimization" is not allowed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

我的作法，修改 vue.config.js

增加
const TerserPlugin = require('terser-webpack-plugin')

增加
> module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: { drop_console: true }
        }
      })
    ]
  },
  configureWebpack: {

**Comment by zinda2000** [comment]
用 UglifyJsPlugin 或者 TerserPlugin

yarn run v1.16.0
$ vue-cli-service build --dest wwwroot
 ERROR  Invalid options in vue.config.js: "optimization" is not allowed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

我的作法，修改 vue.config.js

增加
const TerserPlugin = require('terser-webpack-plugin')

增加
`    module.exports = {
      optimization: {
        minimizer: [
          new TerserPlugin({
            terserOptions: {
              compress: { drop_console: true }
            }
          })
        ]
      },
      configureWebpack: {
`

**Comment by sendya** [comment]
dest 参数干嘛用的？我发的那种方式加好。直接 build 没任何问题

**Comment by zinda2000** [comment]
dest 是打包后输出的文件夹
我修改你的 babel.config.js 倒数第三行后：
`presets: [['@vue/app', { useBuiltIns: 'entry' }]],`
打包成功，谢谢!
