### ISSUE TITLE
打包后的发布路径在哪修改啊

### ISSUE THREAD

**Issue by gou95275** [vueComponent/ant-design-vue-pro#439]
之前的版本不是在vue.config.js的publicPath吗？,怎么现在不行了

**Comment by sendya** [comment]
https://cli.vuejs.org/config/#publicpath

**Comment by gou95275** [comment]
不行啊，我就想在https://gou95275.github.io/agricultural_park/这样访问啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言肆"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月12日(星期四) 中午11:23
收件人:&nbsp;"sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com&gt;;
抄送:&nbsp;"唐老鸭"<736726698@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sendya/ant-design-pro-vue] 打包后的发布路径在哪修改啊 (#439)




https://cli.vuejs.org/config/#publicpath

**Comment by sendya** [comment]
脚手架没有修改过任何与 cli publicPath 相关的参数，请按照 cli 官方文档处理。
另外，提问我希望能够描述详细点
