### ISSUE TITLE
关于路由中重定向的问题

### ISSUE THREAD

**Issue by Xiaohantx** [vueComponent/ant-design-vue-pro#441]
**Question （问题描述）**
How to use component `s-table` paging
在详情页跳到登录页，登录完成后控制台会出现一个红色的`vue-router.esm.js?8c4f:2007 Uncaught (in promise)`报错

**Describe the solution you'd like （你期待的是什么？）**
详情页跳转到登录页后登录后跳回

**Additional context（附加信息）**
![](https://cdn.markone.xyz/images/20190912163409.png)

https://cdn.markone.xyz/images/20190912163409.png

24行`to.path`不知道为啥一直是`/dashboard/workplace`,导致每次运行是，24>30>24>27,但是如果重定向的地址是`/dashboard/workplace`就没问题

**Comment by zinda2000** [comment]
/src/permision.js 文件里修改 
        if (to.path === '/user/login') {
          next({ path: '修改的地方' })
          NProgress.done()
        }

**Comment by wyvin** [comment]
Uncaught (in promise) 这个是vue route@3.1.0新增的，解决需要catch一下push的方法。

**Comment by wtt1203** [comment]
11

**Comment by sendya** [comment]
最新 master / v3 均修正
