### ISSUE TITLE
新版路由 meta 的 show 起什么作用?

### ISSUE THREAD

**Issue by zinda2000** [vueComponent/ant-design-vue-pro#444]

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/65030752-a341ac00-d972-11e9-95ae-00db01e0fcf8.png)


任何新版实现，都不会脱离组件的 API 。搞来搞去，也只是一个方法封装，生成出来的数据，和老版本的路由结构是一致的
