### ISSUE TITLE
IE9支持问题

### ISSUE THREAD

**Issue by Roy1006** [vueComponent/ant-design-vue-pro#446]
项目需要兼容IE9,然后我查看资料，项目已经使用了Polyfill，但是实际run的时候，IE9下会报错：matchMedia not present, legacy browsers require a polyfill，请问有什么解决方案？谢谢

**Comment by sendya** [comment]
项目 目前只支持到 IE10，再往下都不好处理。所以不会兼容 IE9

**Comment by Roy1006** [comment]
好的，谢谢！
