### ISSUE TITLE
导航中英切换

### ISSUE THREAD

**Issue by yuejie89** [vueComponent/ant-design-vue-pro#447]
router.config.js 里配置导航的时候 
能不能把meta: { title：中文} 里的title值设置成变量
可以根据右上角的语言切换按钮一起切换啊？

尝试过直接把 meta: { title：$t(lang) ...}
会报找不到 $t

弄了半天没搞定  求指教啊
之前弄个 ant-design-pro react版  提前配置好en cn配置文件 是直接可以切换的

**Comment by yuejie89** [comment]
ant-design-pro vue 是不是只能切换内容模板里文字做切换啊？

**Comment by sendya** [comment]
可以。
另外，别忘了 this 作用域。 不是哪都可以直接 调用挂在 vue 原型链上的方法

**Comment by yuejie89** [comment]
你的意思是router.config.js  meta：{title：$ t（lang）...}这个地方超出了this的作用域吗？

**Comment by yuejie89** [comment]
哪我应该在哪个地方 怎么实现变量切换  菜单导航啊？

**Comment by yuejie89** [comment]
> 可以。另外
> ，别忘了这个作用域。不是哪都可以直接调用挂在vue原型链上的方法

还在吗？跪求指点啊

**Comment by sendya** [comment]
https://kazupon.github.io/vue-i18n/zh/api/#%E6%96%B9%E6%B3%95

**Comment by xcy96** [comment]
在router.config.js文件中引入i18n实例，检查localStorage里面是否有预设语言，没有就是实例中的default locale
![image](https://user-images.githubusercontent.com/31194211/65296883-91415280-db98-11e9-96c9-d71323c7f14d.png)
然后直接在routes中的meta.title里面这么写
![image](https://user-images.githubusercontent.com/31194211/65296959-dfeeec80-db98-11e9-9a53-498340e97b70.png)
搞定
![image](https://user-images.githubusercontent.com/31194211/65296980-ee3d0880-db98-11e9-9d09-b10a752a0647.png)

**Comment by zhanligui** [comment]
> > 可以。另外
> > ，别忘了这个作用域。不是哪都可以直接调用挂在vue原型链上的方法
> 
> 还在吗？跪求指点啊

请问这个问题解决了吗 如何解决的

**Comment by RyanWangGit** [comment]
在feat/i18n分支中，已经有对的menu的i18n实现，可以参考以下代码：
store/i18n.js, 
store/moudules/i18n.js, 
components/menu/menu.js
locales/*

**Comment by askareija** [comment]
Hi, how to use locale from localstorage when first load?
i've uncommenting this code from branch feat/i18n (`src/locales/index.js`)
![image](https://user-images.githubusercontent.com/21377617/69208902-db8a8400-0b87-11ea-8ae7-f9bb99d8795e.png)
 but it gives me error :
![image](https://user-images.githubusercontent.com/21377617/69208941-fceb7000-0b87-11ea-9b14-d3b35e0b58c2.png)

**Comment by RyanWangGit** [comment]
In locales/index.js:
you need to set lang properties in new VueI18n block,  the value of lang can be got from Vue.ls.get(lang), writing a function to read lang from Vue.ls would be better.

**Comment by farlandliu** [comment]
> Hi, how to use locale from localstorage when first load?
> i've uncommenting this code from branch feat/i18n (`src/locales/index.js`)
> ![image](https://user-images.githubusercontent.com/21377617/69208902-db8a8400-0b87-11ea-8ae7-f9bb99d8795e.png)
> but it gives me error :
> ![image](https://user-images.githubusercontent.com/21377617/69208941-fceb7000-0b87-11ea-9b14-d3b35e0b58c2.png)
```
if (defaultLanguage !== localStorage.lang) {
  loadLanguageAsync(localStorage.lang)
}
```

**Comment by farlandliu** [comment]
> > > 可以。另外
> > > ，别忘了这个作用域。不是哪都可以直接调用挂在vue原型链上的方法
> > 
> > 
> > 还在吗？跪求指点啊
> 
> 请问这个问题解决了吗 如何解决的


My solution:
1. set default lang from localstorage, in lang/index.js
```
const defaultLanguage = localStorage.lang ? localStorage.lang : 'en-US'
```
2. router.confg.js
```
import i18n from '@/lang'
...
//change from
meta: { title: '仪表盘', keepAlive: true, icon: bxAnaalyse, permission: [ 'dashboard' ] },
// to
meta: { title: title: i18n.t('menu.dashboard'), keepAlive: true, icon: bxAnaalyse, permission: [ 'dashboard' ] },

```
3. lang/locale/zh-CN.js , en-US.js

```
// add dashboard title key
menu : {
  dashboard:  '仪表盘'
},
...
```
4. reload page
