### ISSUE TITLE
怎样可以更改多页签的标题

### ISSUE THREAD

**Issue by changhighly** [vueComponent/ant-design-vue-pro#449]
如题，在不去更改路由中meta中的title情况下，在当前页，有没有什么特定的方法可以更改多页签的标题，就是官方封装好的方法，如图标注的地方
![image](https://user-images.githubusercontent.com/22925367/65244886-1c313700-db1e-11e9-835b-7fcefb017bae.png)

**Comment by sendya** [comment]
在这个类里自己加方法，

https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/MultiTab/index.js

在这里处理你改标题名事件
https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/MultiTab/MultiTab.vue#L16-L27

**Comment by changhighly** [comment]
好的，谢谢，我去实现下

**Comment by changhighly** [comment]
按照您的指导，MultiTab/index.js页面中的MultiTab.install并没有执行啊

**Comment by sendya** [comment]
为什么要执行 install ? 那是给 Vue.use 用的，不是任何时候都可以执行的

如果你要自己定制组件，你可能需要先去 Vue 官网学习一下如果开发 Vue 插件，组件等

**Comment by sendya** [comment]
我抽空给你加了一个临时的方法 你可以看看

https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/MultiTab/index.js#L13-L15

用法在这里
https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/dashboard/TestWork.vue#L106

**Comment by w18701660942** [comment]
![image](https://user-images.githubusercontent.com/20851373/65503723-0ba30700-def8-11e9-9741-145dd19e8d63.png)
 我按照 你说的加了，但是在vue原型上找不到这个方法
