### ISSUE TITLE
copyright的显示不正常

### ISSUE THREAD

**Issue by xiaofengsha** [vueComponent/ant-design-vue-pro#45]
![image](https://user-images.githubusercontent.com/37805425/50738712-3f2aed80-1212-11e9-9687-51da447a7473.png)

**Comment by sendya** [comment]
最新提交中已修正，该问题为 **回归** 问题。
参考： 可能是 `ant-design-vue` 同步最新 `ant-design` 样式后，对 `layout` 一部分样式有影响，原本写的兼容代码，在新版本中不仅失效。还导致了容器高度出现问题。
