### ISSUE TITLE
用户数据中的permissionList未追踪到如何添加，求大佬们指点

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#451]

**Comment by sendya** [comment]
https://pro.loacg.com/docs/authority-management

**Comment by SangeCoder** [comment]
@sendya Thank you for your help.

**Comment by SangeCoder** [comment]
模拟假数据中缺失了permissionList这个key值，应该默认添加一个 permissionList: []，大佬可以检测一下，获取用户数据的地方会报一个undefined
