### ISSUE TITLE
登录后的路由不能自动跳转问题

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#452]
追踪过程如下图：

![image](https://user-images.githubusercontent.com/12948798/65373825-1b7ed900-dcb5-11e9-9d21-5c71cd1e3e71.png)

**Comment by SangeCoder** [comment]
其中redirect始终是为 / ，Login.vue中添加了路由跳转也为生效

**Comment by sendya** [comment]
本地没有复现你说的问题。

如果是你自己修改了什么导致的，那只能请你自己解决了。

**Comment by SangeCoder** [comment]
我继续再看看是不是路由那里被误删掉了

**Comment by sendya** [comment]
![GIF](https://user-images.githubusercontent.com/5404542/65374031-acef4a80-dcb7-11e9-8043-f26eb4e65e63.gif)

**Comment by SangeCoder** [comment]
我拉取的master跑起来依然是这样，你这样操作一下，清空所有缓存数据，然后只访问域名或IP:port

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/store/index.js#L8

如果有问题，就用这套路由把。 其他的我也没怎么做测试

**Comment by SangeCoder** [comment]
好的，不过，你先确定一下这个问题是否真的存在，存在的话，可以一起修复一下

**Comment by SangeCoder** [comment]
master里面的路由是这样的：
![image](https://user-images.githubusercontent.com/12948798/65374208-e923aa80-dcb9-11e9-956c-c7fda6ed4dd3.png)

**Comment by Siffre** [comment]
路由的加载过程迟了一步

**Comment by SangeCoder** [comment]
是master分支下Login.vue的this.$router.push({name: 'analysis'}) 这个名称配置错误导致的，应该是大写的Analysis
