### ISSUE TITLE
Vue-Router版本导致重复路由报错问题

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#453]
解决方案参考：https://forum.vuejs.org/t/navigationduplicated/71600

![image](https://user-images.githubusercontent.com/12948798/65375497-fa27e800-dcc8-11e9-942c-6e5ec79ba866.png)

**Comment by sendya** [comment]
fixed e2f827359fc22e7cee9702cf8268c30eb36c827f
