### ISSUE TITLE
开启代理proxy模式，注册接口不能自动添加baseURL

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#455]
**Describe the bug （描述 Bug）**
开启代理proxy模式：
1. 新增的注册接口不能自动添加baseURL，手动添加/api会多出来一个/api/api
2. 获取验证码、登录等接口可以调用，自动添加/api

**To Reproduce （重现步骤）**
1. 新增请求封装
    
![image](https://user-images.githubusercontent.com/12948798/65385361-76b9d580-dd60-11e9-8ee9-42ada4c14373.png)

2. 调用处理
![image](https://user-images.githubusercontent.com/12948798/65385386-aa94fb00-dd60-11e9-89d2-da4724bd39ce.png)

3. Vue中main.js中调用 this.$http.axios()去创建请求实例是可以

**Comment by SangeCoder** [comment]
4. vue.config.js
![image](https://user-images.githubusercontent.com/12948798/65385419-05c6ed80-dd61-11e9-93c8-6a947e22b234.png)

**Comment by SangeCoder** [comment]
新增请求，从现象来看并没有走service as axios的封装实例

**Comment by SangeCoder** [comment]
坑死我了，在接口后面添加一个 /  ，这个baseURL才能自动添加上 @sendya

**Comment by SangeCoder** [comment]
![image](https://user-images.githubusercontent.com/12948798/65388417-cc04df80-dd7e-11e9-8daf-e5c58e1db200.png)

**Comment by Siffre** [comment]
但是后台接口没有后面的那个斜杠 / ， 求大佬指点一下解决方案

**Comment by SangeCoder** [comment]
这个有没有好的解决方案呢？

**Comment by sendya** [comment]
控制台 network 请求地址是什么？

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/65389203-25bcd800-dd86-11e9-8349-2ae19091513f.png)

![image](https://user-images.githubusercontent.com/5404542/65389207-29e8f580-dd86-11e9-9141-6f2fcdc59c50.png)

![image](https://user-images.githubusercontent.com/5404542/65389208-2d7c7c80-dd86-11e9-9686-09a63b5d7536.png)

![image](https://user-images.githubusercontent.com/5404542/65389210-34a38a80-dd86-11e9-80bb-c44627295878.png)


没复现你说的问题。

**Comment by SangeCoder** [comment]
后端API接口的问题，应该在最后加上一个/ ，应该是后端的问题，这个算是特殊情况了吧
