### ISSUE TITLE
左侧菜单栏切换成移动端的时候，点击menuItem，左侧菜单栏不自动回收

### ISSUE THREAD

**Issue by Thlq** [vueComponent/ant-design-vue-pro#457]
左侧菜单栏切换成移动端的时候，点击menuItem，当第一次点击的时候，菜单栏会自动回收，但是第二次点击同一个菜单栏的时候菜单栏就不回收了

**Comment by sendya** [comment]
现在点击 menuitem 不会在收回菜单了，收回菜单请点 drawer 空白位置

**Comment by Thlq** [comment]
这个可以增加一个配置吗，感觉移动端点击item之后，回收左侧菜单，体验好一点

**Comment by sendya** [comment]
@Thlq 我按照 antd 官方版的方案做的。不会加配置来开关。你需要的这样的功能，可以自己改。

**Comment by sendya** [comment]
另外，antd 并不是针对移动端的 UI 框架，本项目的移动端兼容只是给这样一个中后台项目一个应急时使用的

**Comment by Thlq** [comment]
好的，非常感谢
