### ISSUE TITLE
CardList 报错

### ISSUE THREAD

**Issue by staticage** [vueComponent/ant-design-vue-pro#458]
CardList 页面报错
Error in render: "TypeError: Cannot read property 'key' of null"
found in
---> <AList>
       <CardList> at src/views/list/CardList.vue
         <PageView> at src/layouts/PageView.vue
           <RouteView> at src/layouts/RouteView.vue
             <Anonymous>
               <ALayoutContent>
                 <Anonymous>
                   <ALayout>
                     <Anonymous>
                       <ALayout>
                         <BasicLayout> at src/layouts/BasicLayout.vue
                           <ALocaleProvider>
                             <App> at src/App.vue
                               <Root>

**貌似是ant-design-vue新版本的问题 换成1.3.16显示正常**

**Comment by sendya** [comment]
fixed 7a940d8
