### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by EryouHao** [vueComponent/ant-design-vue-pro#46]
https://github.com/sendya/ant-design-pro-vue/blob/db0ea064f086c56189c6e8a948f3badbee5130d4/src/views/user/Login.vue#L173

为什么这里要用 that 呢？好像项目中有很多地方都有这样用，建议优化一下代码

**Comment by sendya** [comment]
`this` 作用域问题，虽然 vue 实例修改了 `this` 一定指向到当前 vue 实例。
但是在一部分的操作中，作用域还是会错误。目的仅为防止。
不存在需要优化的问题，并且即使去掉这行指向代码， `babel` 插件也会在编译时，在第一行帮你添加上这一行。既然这样，还不如更加明确的编码方式指明变量指向。

如果你有更加正确的意见用于去掉这行代码 欢迎指教

扩展： 你可以去了解一下 js this 作用域，百度搜索一下就有了。很多案例

**Comment by sendya** [comment]
每个人都有一套自己的习惯，你喜欢不明示作用域也没问题。

我看 issue 是中文的，担心普遍问题访问不了。也就不给推荐了。
