### ISSUE TITLE
怎么把项目中使用的ant-design-vue这个UI库，使用CND加速？

### ISSUE THREAD

**Issue by joinwen** [vueComponent/ant-design-vue-pro#460]
**Question （问题描述）**
How to use component `s-table` paging
I don't know how to use or config cdn to accelerate the ui framework of ant-desing-vue in this project
**Describe the solution you'd like （你期待的是什么？）**
I want find a solution that it can erase  ant-design-vue dependency instead of using script label
**Additional context（附加信息）**

**Comment by sendya** [comment]
外部扩展(externals)：
https://webpack.docschina.org/configuration/externals/
