### ISSUE TITLE
如何build后仍然显示主题配置面板

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#461]
打包后依旧行显示主题配置面板

**Comment by sendya** [comment]
build:preview  若采用 preview ,出现性能问题请自行处理

**Comment by SangeCoder** [comment]
好的，感谢！

**Comment by SangeCoder** [comment]
![image](https://user-images.githubusercontent.com/12948798/65578840-2d0ffb80-dfa9-11e9-822a-93e096d32378.png)

主题配置中的路径，在vue.config.js中配置了publicPath后路径并未发生改变！！

**Comment by sendya** [comment]
自行处理一下即可，这个也不是给生产环境用的

**Comment by SangeCoder** [comment]
嗯的，已经处理好了
