### ISSUE TITLE
在NoticeIcon引入axios之后无报错白屏

### ISSUE THREAD

**Issue by chenchifeng** [vueComponent/ant-design-vue-pro#463]
**Describe the bug （描述 Bug）**

在NoticeIcon引入axios之后无报错白屏(Loading和登录页面还在).
我在\src\components\NoticeIcon\NoticeIcon.vue(右上角消息提醒Icon组件)里要发出一个请求,也就是获取消息通知的接口,但是我import了axios之后,整个页面就白屏了

**To Reproduce （重现步骤）**

1. 在\src\components\NoticeIcon\NoticeIcon.vue里import { axios } from '@/utils/request'或者某个接口
2. 打开页面
3. 白屏而且没有报错

**Expected behavior（你期待的是什么?）**
能够正常请求接口

**Screenshots（截图）**
![图片](https://user-images.githubusercontent.com/16933868/65585024-5eda8f80-dfb4-11e9-8e32-c81f9d1beef2.png)

**Desktop (please complete the following information):**

 - OS: Windows10
 - Browser : chrome, safari, FireFox
 - Version : all

**Smartphone (please complete the following information):**

**Additional context（附加信息）**
去掉这句import后能打开页面

**Comment by sendya** [comment]
不要在基础组件里引入 axios ，要用可以选择 Vue 原型链上挂载的 `this.$http or this.$axios`

**Comment by chenchifeng** [comment]
> 
> 
> 不要在基础组件里引入 axios ，要用可以选择 Vue 原型链上挂载的 `this.$http or this.$axios`

嗯嗯,解决了,感谢!

那这里不可以像其他页面那样例如把api写在@/api/sys.js里面,然后在.vue组件中import进去调用吗? 我这样写也是白屏了

**Comment by chenchifeng** [comment]
这里和基础组件相关的都要使用this.$http or this.$axios这种方式,而不能使用更平时那种把接口写到@/api/的js文件里面,然后引入的方式?

我后来还有几个地方更一用import接口这种方式就白屏无内容了.

我是这样使用接口的,就算只是引入还没有使用都白屏了.
```js
// src\api\system.js
import { axios } from '@/utils/request'

export function getMessageContent(parameter) {
  return axios({
    url: '/Com_Msg/index',
    method: 'get',
    params: parameter
  })
}
```

```html
// src\components\NoticeIcon\NoticeIcon.vue
...
<script>
import { getMessageContent } from '@/api/system' // 获取消息内容
...
</script>

```

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/65652041-fe466380-e042-11e9-8676-ecc16e2b4598.png)


没有你描述的问题，请自查

**Comment by chenzhanym** [comment]
> 这里和基础组件相关的都要使用this.$http or this.$axios这种方式,而不能使用更平时那种把接口写到@/api/的js文件里面,然后引入的方式?
> 
> 我后来还有几个地方更一用import接口这种方式就白屏无内容了.
> 
> 我是这样使用接口的,就算只是引入还没有使用都白屏了.
> 
> ```js
> // src\api\system.js
> import { axios } from '@/utils/request'
> 
> export function getMessageContent(parameter) {
>   return axios({
>     url: '/Com_Msg/index',
>     method: 'get',
>     params: parameter
>   })
> }
> ```
> 
> ```
> // src\components\NoticeIcon\NoticeIcon.vue
> ...
> <script>
> import { getMessageContent } from '@/api/system' // 获取消息内容
> ...
> </script>
> ```

我也遇到这个问题了，兄弟你解决了吗？

我试了下，官方示例又能正常import，不知道是改了啥影响的 →_→

**Comment by chenchifeng** [comment]
> 
> 
> > 这里和基础组件相关的都要使用this.$http or this.$axios这种方式,而不能使用更平时那种把接口写到@/api/的js文件里面,然后引入的方式?
> > 我后来还有几个地方更一用import接口这种方式就白屏无内容了.
> > 我是这样使用接口的,就算只是引入还没有使用都白屏了.
> > ```js
> > // src\api\system.js
> > import { axios } from '@/utils/request'
> > 
> > export function getMessageContent(parameter) {
> >   return axios({
> >     url: '/Com_Msg/index',
> >     method: 'get',
> >     params: parameter
> >   })
> > }
> > ```
> > 
> > 
> > ```
> > // src\components\NoticeIcon\NoticeIcon.vue
> > ...
> > <script>
> > import { getMessageContent } from '@/api/system' // 获取消息内容
> > ...
> > </script>
> > ```
> 
> 我也遇到这个问题了，兄弟你解决了吗？
> 
> 我试了下，官方示例又能正常import，不知道是改了啥影响的 →_→

没找到原因,暂时就把相关的axios都改成挂载成全局方法的方式用着先了,如果解决了麻烦在这分享一下啦^-^

**Comment by chenzhanym** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/65652041-fe466380-e042-11e9-8676-ecc16e2b4598.png)
> 
> 没有你描述的问题，请自查

你好，动态菜单的分支有这个问题。

**Comment by sendya** [comment]
> > ![image](https://user-images.githubusercontent.com/5404542/65652041-fe466380-e042-11e9-8676-ecc16e2b4598.png)
> > 没有你描述的问题，请自查
> 
> 你好，动态菜单的分支有这个问题。

![image](https://user-images.githubusercontent.com/5404542/65844505-20a0ef80-e369-11e9-8dfc-d9337de2bf17.png)
还是没复现

**Comment by chenzhanym** [comment]
@sendya 别的都没改。。。
![image](https://user-images.githubusercontent.com/20638473/65853754-1f81b980-e38d-11e9-849e-7c730ec6928b.png)

**Comment by chenchifeng** [comment]
> 
> 
> @sendya 别的都没改。。。
> ![image](https://user-images.githubusercontent.com/20638473/65853754-1f81b980-e38d-11e9-849e-7c730ec6928b.png)

我也复现了,
import并使用axios(没内容没报错)
![图片](https://user-images.githubusercontent.com/16933868/65859782-87d79780-e39b-11e9-9ab8-c98c17028345.png)
只import了axios(没内容没报错)
![图片](https://user-images.githubusercontent.com/16933868/65859842-a63d9300-e39b-11e9-9346-5660b8e38871.png)
没import axios(有内容)
![图片](https://user-images.githubusercontent.com/16933868/65859996-f3ba0000-e39b-11e9-9558-d043d0bcf5b8.png)

系统环境:
- OS: window10
- Browser: Chrome or FireFox
- Node: 10.15.0
- 其他依赖是直接使用 yarn import 安装的

**Comment by chenchifeng** [comment]
@chenzhanym 试了一遍,接口的axios不用二次封装过的,改成把import { axios } from '@/utils/request'改成import axios from 'axios'后就没有白屏了

**Comment by chenzhanym** [comment]
@chenchifeng 好的，谢谢~
