### ISSUE TITLE
build后不能显示icon图标

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#467]
**Question （问题描述）**
1. 静态资源路径存在:  /static/favicon.ico
2. build后不能显示icon图标，手动调试加上前缀 /api/static/favicon.ico 才能显示，那么问题来了，静态资源不需要加前缀的，为何这里需要，还不能动态？？

**Comment by sendya** [comment]
不知道，本项目没有 static 目录，如果你是自己做的修改，请先自己排查
