### ISSUE TITLE
IE 缺少标识符、字符串或数字

### ISSUE THREAD

**Issue by freshzxf** [vueComponent/ant-design-vue-pro#468]
Can't open under IE

![微信截图_20190926103528](https://user-images.githubusercontent.com/28848999/65653954-b5de7400-e049-11e9-965c-a296b366ff44.png)

**Comment by dargoner** [comment]
> Can't open under IE
> 
> ![微信截图_20190926103528](https://user-images.githubusercontent.com/28848999/65653954-b5de7400-e049-11e9-965c-a296b366ff44.png)

请问这个怎么解决的

**Comment by freshzxf** [comment]
当时是彻底删除所有依赖，然后使用npm命令重新安装依赖，就好了。今天又出现这个问题，反复删除几次都没用，后面切换分支，删除依赖，重装依赖，再切换回来，又好了，我暂时也不清楚具体原因，很奇怪！

**Comment by MinosIE** [comment]
sourceMap 开起来 看看是哪边的代码出了问题

**Comment by sendya** [comment]
不开启 mock 服务既不会报错
