### ISSUE TITLE
怎么升级ant-design-vue版本

### ISSUE THREAD

**Issue by Zuojiangtao** [vueComponent/ant-design-vue-pro#470]
**Question （问题描述）**
如题

**Describe the solution you'd like （你期待的是什么？）**
由于某些新的功能不能使用，需要在已有的项目上平滑升级ant-design-vue版本，但是升级报错:下载超时，多次尝试均失败

**Additional context（附加信息）**
尝试删除过yarn.lock文件，也更改了package.json文件中的版本信息，但是没用.下载源用的是淘宝镜像。

**Comment by sendya** [comment]
`下载超时` 请检查自己网络问题。或者自己环境问题。本脚手架是无法限制你更新依赖的

**Comment by seolck01** [comment]
yarn cache clean

**Comment by StarRain-L** [comment]
请问升级ant-design-vue版本的步骤是什么?
