### ISSUE TITLE
npm run serve 无法直接打开浏览器

### ISSUE THREAD

**Issue by peade** [vueComponent/ant-design-vue-pro#471]
**Question （问题描述）**
配置了devServer里open:true , 运行npm run serve, 未能自动打开浏览器，显示项目页面。 
我检查了配置，确认自己没有配错，如下：
    ```
port: 8000,
open: true,
```
查了很长时间，没查出问题所在。
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
下的是最新版本

**Comment by sendya** [comment]
可能是有哪个插件拦截了打开，我这边也没查到。后续在跟进吧

**Comment by zcSkr** [comment]
这个问题跟进了吗？打不开浏览器不方便

**Comment by sendya** [comment]
@peade @zcSkr
启动参数加个 `--open`

https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve

**Comment by Blankstation** [comment]
这个问题解决了吗，"serve": "vue-cli-service serve --open"，添加--open还是未能自动打开浏览器
