### ISSUE TITLE
您好，这种动态生成的路由警告，怎么解决呢

### ISSUE THREAD

**Issue by w18701660942** [vueComponent/ant-design-vue-pro#473]
![image](https://user-images.githubusercontent.com/20851373/65829798-bbeb8380-e2db-11e9-84cb-02bc66e3a269.png)

**Comment by sendya** [comment]
可能是重复了把，自己检查是不是多次 addRouters 了相同的路由

**Comment by daodao90** [comment]
你的router 配置里面name重复了， 请给节点提供不同的name
