### ISSUE TITLE
Edge下不兼容https://preview.pro.loacg.com演示站

### ISSUE THREAD

**Issue by desosaa** [vueComponent/ant-design-vue-pro#474]
Edge访问演示站，和自己的站都不行，提示

SEC7120: [CORS] 原点“ms-appx-web://microsoft.microsoftedge”无法支持“ms-appx-web:///assets/Fonts/BrowserMDL.ttf#Browser MDL2 Assets”的 cross-origin font 资源。

CSS3119: 无可用于 @font-face 规则的字体

**Comment by sendya** [comment]
兼容问题是 mockjs 导致的，正式环境可以不启用 mockjs ，就不会导致不兼容，具体可看 branches/dev/2.1.0 分支处理
