### ISSUE TITLE
表单校验input框输入时显示下拉记录会断层 用:getPopupContainer="trigger => trigger.parentNode"无效果

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#475]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
能描述一下 `表单校验input框输入时显示下拉记录会断层` 这句该怎么理解吗？

**Comment by lovehebe330** [comment]
![Kobe24](https://user-images.githubusercontent.com/20655248/66381529-18415800-e9ec-11e9-8c4b-f251e92c9e2b.png)
填写输入框提示下拉记录时然后往下滑 下拉提示与input框断层。

**Comment by lovehebe330** [comment]
![Kobe24](https://user-images.githubusercontent.com/20655248/66381653-50e13180-e9ec-11e9-9abc-a33dca9e34d2.png)

**Comment by lovehebe330** [comment]
![gaitubao_Kobe24_jpg](https://user-images.githubusercontent.com/20655248/66383606-e92ce580-e9ef-11e9-9e51-88ceeeb04b8a.jpg) 填写输入框提示下拉记录时然后往下滑 下拉提示与input框断层。

**Comment by lovehebe330** [comment]
> 能描述一下 `表单校验input框输入时显示下拉记录会断层` 这句该怎么理解吗？

![gaitubao_Kobe24_jpg](https://user-images.githubusercontent.com/20655248/66383753-22655580-e9f0-11e9-818d-b547b78bd09e.jpg)
填写输入框提示下拉记录时然后往下滑 下拉提示与input框断层。

**Comment by sendya** [comment]
这应该不是 ant design 的问题把，antd 的弹层不会长这样，都是带圆角的。
你这应该是浏览器的 `自动填表` 功能。

**Comment by lovehebe330** [comment]
> 这应该不是 ant design 的问题把，antd 的弹层不会长这样，都是带圆角的。
> 你这应该是浏览器的 `自动填表` 功能。

那可以用样式解决吗

**Comment by sendya** [comment]
> 那可以用样式解决吗

没遇到过，请自己网上查查能不能处理吧。
