### ISSUE TITLE
Login.vue中Login请求的then中获取的res为undefined

### ISSUE THREAD

**Issue by nefeed** [vueComponent/ant-design-vue-pro#477]
**Question （问题描述）**
request.js中的axios的response拦截器service.interceptors.response.use打印response是完整的返回，然后按照demo return response.data。
但是Login.vue中Login请求的then中获取的res为undefined，如果改走catch能够获取err。
request.js: https://github.com/nefeed/dingtalk-robot/blob/master/page/src/utils/request.js
Login.vue: https://github.com/nefeed/dingtalk-robot/blob/master/page/src/views/user/Login.vue

**Describe the solution you'd like （你期待的是什么？）**
如何在then中获取res？

**Additional context（附加信息）**

**Comment by sendya** [comment]
你 `Login.vue` 里调用的结果并不是直接从 `request.js` 获得的，而是从 vuex 中获得的。
请自行跟踪或者查阅一遍代码，理解其逻辑

https://github.com/sendya/ant-design-pro-vue/blob/master/src/store/modules/user.js#L37

**Comment by 343512292** [comment]
Login.vue中Login请求的then中获取的res为undefined，是因为源码在 vux 中 Login方法 的 resolve() 返回为空

**Comment by nefeed** [comment]
已经解决了,谢谢两位

**Comment by lkangjing** [comment]
> 已经解决了,谢谢两位

怎么解决的？求指点

**Comment by weixians** [comment]
把结果往resolve里传就可以，比如resolve(result);
