### ISSUE TITLE
目前ant-design-pro-vue 有关于路由拦截的配置么？

### ISSUE THREAD

**Issue by mlzk** [vueComponent/ant-design-vue-pro#478]
目前ant-design-pro-vue 有关于路由拦截的配置么？

例如在/a页面继续表单填写，点击路由进行拦截对用户进行页面跳转确认？

**Comment by sendya** [comment]
路由守卫自己加逻辑判断

这是 pro 默认的路由守卫
https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L16

**Comment by mlzk** [comment]
> 路由守卫自己加逻辑判断
> 
> 这是 pro 默认的路由守卫
> https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L16

了解了
