### ISSUE TITLE
表单验证时，发现前几次input框输入的信息填完验证成功后，接下来要获取input框输入的历史信息，要怎么做？？

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#479]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
业务功能请自己想办法实现，最多只能跟你说你每次 input 改变都把值存起来
