### ISSUE TITLE
请问下表单子页面提交的问题

### ISSUE THREAD

**Issue by ch656409110** [vueComponent/ant-design-vue-pro#48]
请问下，列表打开的子页面的确定按钮的点击事件如何通用绑定，我连确定都看不到，肯定是封装了，只是不知道如何实现，麻烦告知下。
![1546854840 1](https://user-images.githubusercontent.com/32993363/50761483-772f4080-12a5-11e9-9949-7113c50aee1b.png)

**Comment by sendya** [comment]
ant-design-vue 组件就是这样提供好的。你可以去看官方文档， pro 没有对 modal 进行封装

**Comment by sendya** [comment]
基本 Modal：https://vuecomponent.github.io/ant-design-vue/components/modal-cn/#components-modal-demo-basic

自定义 Modal 页脚：https://vuecomponent.github.io/ant-design-vue/components/modal-cn/#components-modal-demo-customized-footer

**Comment by ch656409110** [comment]
非常感谢，要学的东西好多。我多研究研究。###
