### ISSUE TITLE
一级菜单没有子菜单如何直接点击之后直接路由跳转该怎么修改

### ISSUE THREAD

**Issue by springmmc** [vueComponent/ant-design-vue-pro#482]
就像下面图这样的 广告列表是个一级菜单 下面没有二级菜单 该如何修改路由文件 或者说菜单文件让他能点击这个一级菜单可以直接跳转路由呀

![1570616074](https://user-images.githubusercontent.com/56344894/66472857-b1da3980-eac0-11e9-9b69-88ea1de77524.jpg)

**Comment by sendya** [comment]
https://pro.loacg.com/docs/router-and-nav

https://router.vuejs.org/

**Comment by goukuDev** [comment]
![image](https://user-images.githubusercontent.com/30975895/87026802-d8273400-c20e-11ea-8368-8bfb5525b4a8.png)

**Comment by goukuDev** [comment]
![image](https://user-images.githubusercontent.com/30975895/87027071-3227f980-c20f-11ea-8ef3-bf29e46a8aa4.png)

像这样就可以了
