### ISSUE TITLE
关于table表格分页快速跳转问题

### ISSUE THREAD

**Issue by useryechen** [vueComponent/ant-design-vue-pro#484]
**Describe the bug （描述 Bug）**
标准列表页中进行快速跳转分页无效
**To Reproduce （重现步骤）**
**Expected behavior（你期待的是什么?）**
快速跳转生效

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/16095736/66629245-c12dc400-ec33-11e9-8565-2662b7844b85.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

 - Device: [e.g. Thankpad T420]
 - OS: [e.g. window7]
 - Browser [e.g. chromex]
 - Version [e.g. 77]
]

**Additional context（附加信息）**

**Comment by sendya** [comment]
没有真实数据 跳转没有任何作用。如果你是为了了解如何使用分页器，请前往 antd vue 官方文档参考文档实现

**Comment by useryechen** [comment]
> 没有真实数据 跳转没有任何作用。如果你是为了了解如何使用分页器，请前往 antd vue 官方文档参考文档实现

其实我就是参考官网文档，在pagination对象中配置onchange没有生效，所以才来找答案，结果发现网上的都不能进行跳转，所以才来问问

**Comment by Cc9410** [comment]
我这里遇到的情况是 跳转页面时的keyup.enter事件并不能触发table的@change事件
