### ISSUE TITLE
a-modal弹窗组件想在确定和取消两个按钮的基础上再加一个按钮，发现用<div slot="footer">         <a-button type="primary" htmlType="submit">编辑</a-button>       </div>会把之前的确定和取消两个按钮覆盖掉，而且只能在a-form里面绑定表单域，有木有办法能在确定和取消两个按钮的基础上再加一个按钮？

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#485]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
那就 slot=footer 里写上你自己的按钮，和原本设计有的 取消 确定，另外事件也控制好

**Comment by lovehebe330** [comment]
> 那就 slot=footer 里写上你自己的按钮，和原本设计有的 取消 确定，另外事件也控制好

<div slot="footer">
        <a-button type="primary" htmlType="submit">编辑</a-button>
        <a-button type="primary" htmlType="submit">确定</a-button>
        <a-button type="primary">取消</a-button>
 </div>
但这样的话绑定不了表单域吧，要放在a-form里面才有效

**Comment by lovehebe330** [comment]
> 那就 slot=footer 里写上你自己的按钮，和原本设计有的 取消 确定，另外事件也控制好

<div slot="footer">
        <a-button type="primary" htmlType="submit">编辑</a-button>
        <a-button type="primary" htmlType="submit">确定</a-button>
        <a-button type="primary">取消</a-button>
 </div>
但这样的话绑定不了表单域吧

**Comment by sendya** [comment]
绑定表单域是什么意思？  a-modal 的组件按钮跟表单域有什么关系吗？

**Comment by lovehebe330** [comment]
在a-modal 里面有一组表单用a-form包裹，然后除了默认的确认和取消按钮之外，还要再footer里加一个编辑的按钮，但我用slot=footer后发现加了一个编辑按钮后默认的确认按钮和取消按钮被覆盖了，我绑定表单的方式如下图，但现在这种情况要怎么在slot=footer里绑定表单？
![gaitubao_图片pppppppppppp_jpg](https://user-images.githubusercontent.com/20655248/66695974-20eea280-ecfa-11e9-993a-4bf23b4d7c1e.jpg)

![gaitubao_图片_jpg](https://user-images.githubusercontent.com/20655248/66696206-83e13900-ecfc-11e9-811d-0a5cdd14b311.jpg)

**Comment by sendya** [comment]
form 可以直接调用 submit 也可以你按钮直接调用 handleOk ,没有规定表单一定要用 htmlType=submit 来提交

**Comment by lovehebe330** [comment]
> form 可以直接调用 submit 也可以你按钮直接调用 handleOk ,没有规定表单一定要用 htmlType=submit 来提交

3q已经解决了
![gaitubao_图片yyyyyyyy_jpg](https://user-images.githubusercontent.com/20655248/66698632-222bc980-ed12-11e9-9f7e-b0e1cc93244d.jpg)
![gaitubao_图片poppppoo_jpg](https://user-images.githubusercontent.com/20655248/66698637-2952d780-ed12-11e9-8f8b-851f574884b4.jpg)
