### ISSUE TITLE
关于 头像和昵称 刷新后 不显示的一点疑问

### ISSUE THREAD

**Issue by Everan-1994** [vueComponent/ant-design-vue-pro#486]
你好，我是后端的童鞋，对前端不是很了解，望多包涵。
问题：接口都已经和服务端交互了，在登录后保存了头像和昵称，
```
commit('SET_NAME', { name: data.info.name, welcome: welcome() })
commit('SET_AVATAR', data.info.avatar)
```
然后刷新就不显示了，之前也知道，这个问题的存在，所以我就干脆用localStorage来存，突然想到，角色权限也是用 ```commit``` 形式来保存的，我是不是也要用localStorage来存呢？疑惑的是我看演示站，登录后刷新，都是正常的。

**Comment by sendya** [comment]
重要的数据，隐私数据等。不推荐往 localStorage 储存，应当直接放在 Vuex(内存) 中比较保险。

另外，刷新不能显示，考虑看一下路由守卫有一个判断是否登录，有登录会去请求一次用户信息，重新初始化到 Vuex 。如果你没对这一块处理保存头像，那么刷新后，丢失就属于正常情况了

**Comment by Everan-1994** [comment]
谢谢，明白了。
