### ISSUE TITLE
登录校验

### ISSUE THREAD

**Issue by aiyou666666** [vueComponent/ant-design-vue-pro#487]
怎么强制绕过登录 因为登录接口还没有写好  现在绕过登录 想做做其他的页面  但是现在是空白页面

**Comment by Everan-1994** [comment]
有一个路由白名单，你可以试试。在 ```src\permissions.js``` 大概 13 行 和 58 行的地方。

**Comment by sendya** [comment]
你大可直接 mock 登录接口，按照你后台的规范 mock。接口开发完直接关闭 mock 就直接用上后端的 API
