### ISSUE TITLE
菜单栏点击颜色切换BUG

### ISSUE THREAD

**Issue by forever-thinker** [vueComponent/ant-design-vue-pro#489]
菜单切换时，需要点击新主菜单的子菜单，上一主菜单颜色才会变成失去焦点的状态。如果不点击新主菜单的子菜单，此时新主菜单和上一主菜单的颜色同时都是获得焦点的颜色。这样体验不是太好，应该是一个BUG。

比较合理的方式应该是点击新主菜单，那么上一主菜单颜色就应该变成失去焦点的颜色。

**Comment by sendya** [comment]
那你能修正它吗？

另外 换个角度。如果点开之后 取消了高亮，这时候我不切换菜单了。是不是就一直不能高亮了？
在另外 如果没切换菜单，就把高亮移除了，是不是也不合理？（我都还没切换到别的页面呢，怎么菜单都焦点当前页面了）
在另外 如果要点了新菜单，把之前的菜单高亮清除掉，违背了 Menu 的设计， Menu 在子菜单被激活时，父菜单是要高亮显示 用来表示该菜单的子菜单有其一被选中。你这做法 就是如果点了任意主菜单，就不知道目前打开的是哪个菜单了

**Comment by forever-thinker** [comment]
仔细想了一下，你说的也有道理，不过个人还是不大习惯。
以前用的方式是主菜单没有高亮，所有主菜单一个颜色，当前点击的主菜单只管下拉和收起。根据下拉和收起判断当前的主菜单焦点状态，如果全部收起，就不做区别。从我个人来说，这样会习惯一些。
感谢回复！

**Comment by forever-thinker** [comment]
对于上次点了哪个主菜单，在页面路由的title里面也有呈现了，点击其他主菜单而使得活动页面的主菜单失去焦点时，不再在菜单栏高亮呈现也算可以接受。

**Comment by sendya** [comment]
> 对于上次点了哪个主菜单，在页面路由的title里面也有呈现了，点击其他主菜单而使得活动页面的主菜单失去焦点时，不再在菜单栏高亮呈现也算可以接受。

描述的这个问题，可能不会接受修改。因为这个项目打算尽量按照 antd 的设计规范做。 antd 的 Menu 组件就是这样设计的，所以...

**Comment by forever-thinker** [comment]
> > 对于上次点了哪个主菜单，在页面路由的title里面也有呈现了，点击其他主菜单而使得活动页面的主菜单失去焦点时，不再在菜单栏高亮呈现也算可以接受。
> 
> 描述的这个问题，可能不会接受修改。因为这个项目打算尽量按照 antd 的设计规范做。 antd 的 Menu 组件就是这样设计的，所以...

好的，我试试自己是否能够修改，感谢回复！
