### ISSUE TITLE
$auth() 鉴权,判断好像有问题

### ISSUE THREAD

**Issue by KKaitong** [vueComponent/ant-design-vue-pro#49]
按照原来的判断 没有起到作用，增加判断后可使用
![tim 20190108113308](https://user-images.githubusercontent.com/24431121/50808396-5284a880-1339-11e9-9bd2-d5e2d9ffa5b7.png)

**Comment by sendya** [comment]
请自行实现，action 操作权限仅提供实现思路

**Comment by KKaitong** [comment]
明白了
