### ISSUE TITLE
一个a-form-item标签里有两个input框，用v-decorator分别绑定不同的两个变量，分别加了requrie数组，发现只能验证前面一个input框，后面一个验证不了。

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#490]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
#90 

![image](https://user-images.githubusercontent.com/5404542/66743950-bbdbae00-eead-11e9-89eb-913569b629b0.png)

**Comment by wangkris03** [comment]
解决方案是什么？

**Comment by wangkris03** [comment]
分别写两个form.item就可以了，包裹一下。
