### ISSUE TITLE
表格搜索功能的控制台报错

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#491]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

![gaitubao_pu_jpg](https://user-images.githubusercontent.com/20655248/66880509-c4d79700-eff5-11e9-8373-9d2f729cc260.jpg)

**Comment by sendya** [comment]
antd vue 相关问题，请直接提交到 antd 的仓库： https://github.com/vueComponent/ant-design-vue
