### ISSUE TITLE
有关axios的用法

### ISSUE THREAD

**Issue by ZhaoWei9527** [vueComponent/ant-design-vue-pro#492]
vue install 插件这种有什么好处吗？这一块儿没太搞明白，大佬可以给解答一下吗

文档说插件用法只会install  1次，和原型链那种用法有啥不一样嘛

还有您在request.js中
const installer = {
  vm: {},
  install (Vue) {
    Vue.use(VueAxios, service)
  }
}

这里也看不懂，请教一下。

**Comment by sendya** [comment]
https://cn.vuejs.org/v2/guide/plugins.html#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6
