### ISSUE TITLE
请问怎么在菜单栏使用自定义图标？

### ISSUE THREAD

**Issue by forever-thinker** [vueComponent/ant-design-vue-pro#493]
如题，感谢！

**Comment by sendya** [comment]
参考 /config/router.config.js 文件内用到的 `bxAnaalyse`

**Comment by forever-thinker** [comment]
已经可以，非常感谢！
再请教一下，如何调整这个图标的大小呢？没有看到可以覆盖的类，只看到在style中定义了宽高。
