### ISSUE TITLE
使用echart + Bmap地图加载不出来

### ISSUE THREAD

**Issue by atzw1988** [vueComponent/ant-design-vue-pro#495]
echart的其他功能都可以正常使用，但是结合Bmap地图一直加载不出来，请问是什么问题
const myChart = this.$echarts.init(this.$refs.map)
      const pointsData = baiduJSON
      var points = [].concat.apply([], pointsData.map(function (track) {
        return track.map(function (seg) {
          return seg.coord.concat([1])
        })
      }))
      myChart.setOption({
        animation: false,
        bmap: {
          center: [120.140501, 30.250184],
          zoom: 14,
          roam: true
        },
        visualMap: {
          show: false,
          top: 'top',
          min: 0,
          max: 5,
          seriesIndex: 0,
          calculable: true,
          inRange: {
            color: ['blue', 'blue', 'green', 'yellow', 'red']
          }
        },
        series: [{
          type: 'heatmap',
          coordinateSystem: 'bmap',
          data: points,
          pointSize: 5,
          blurSize: 6
        }]
      })

**Comment by sendya** [comment]
我没用过 `Bmap` 不太清楚，引入第三方组件不行，直接去查阅第三方组件的相关文档吧

**Comment by atzw1988** [comment]
好的，谢谢
