### ISSUE TITLE
路由配置问题

### ISSUE THREAD

**Issue by xiumubai** [vueComponent/ant-design-vue-pro#496]
实在不好意思，如有打扰，请多多包涵
问题：我在列表页点击查看详情，需要跳转到详情页，带参数id，详情页不需要展示在左侧导航路由，请问这时候我的路由 应该怎么配置？

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/67170440-65f29300-f3e4-11e9-86ce-e4883dd0b0b7.png)

第一条
