### ISSUE TITLE
再次求助，如何调整菜单栏图标大小？

### ISSUE THREAD

**Issue by forever-thinker** [vueComponent/ant-design-vue-pro#497]
如题，感谢！

**Comment by sendya** [comment]
components/Menu/menu.js 修改 renderIcon 方法

**Comment by ethan666** [comment]
`    renderIcon (icon) {
      if (icon === 'none' || icon === undefined) {
        return null
      }
      const props = {}
      typeof icon === 'object' ? (props.component = icon) : (props.type = icon)
      // props.rotate = 90
      props.style = { fontSize: '24px' }

      return <Icon {...{ props }} />
    }`


`  
  name: 'AIcon',

  props: {
    tabIndex: PropTypes.number,
    type: PropTypes.string,
    component: PropTypes.any,
    viewBox: PropTypes.any,
    spin: PropTypes.bool.def(false),
    rotate: PropTypes.number,
    theme: PropTypes.oneOf(['filled', 'outlined', 'twoTone']),
    twoToneColor: PropTypes.string,
    role: PropTypes.string
  },
`

尝试了rotate属性，生效。 尝试style属性没有生效。估计跟Icon属性有关系

**Comment by sendya** [comment]
`style` 不是 props 放在 props 里当然无效

https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

**Comment by ethan666** [comment]
> `style` 不是 props 放在 props 里当然无效
> 
> https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

`    renderIcon (icon) {
      if (icon === 'none' || icon === undefined) {
        return null
      }
      const props = {}
      typeof icon === 'object' ? (props.component = icon) : (props.type = icon)
      // props.rotate = 90
      // props.style = { fontSize: '24px' }

      return <Icon {...{ props, style: { fontSize: '24px' } }} />
    }`
多谢指教
