### ISSUE TITLE
多个子菜单keepalive有true有false时，出现点击左侧菜单右边content不刷新的现象

### ISSUE THREAD

**Issue by zhangjinzhangjin** [vueComponent/ant-design-vue-pro#498]
**Describe the bug （描述 Bug）**
在router.config.js中，如仪表盘里，二级菜单项的meta中的keepalive必须全部为true或者为false，如果有不一致的情况，在实际预览中多点几下左侧菜单就会出现右侧content组件不刷新，即点什么菜单都没效果了。

**To Reproduce （重现步骤）**
1 在仪表盘的子菜单中，添加一个自定义菜单路由，然后将该路由的meta中keepAlive设置成false
2 将仪表盘中其他的子菜单，如工作台，分析页等，找到keepAlive设置成true
3 浏览器访问localhost:8000，点击工作台，再点击分析页，再点击刚才新添加的keepAlive为false的菜单
4 此时右侧content会一直不动，无论后续再点击什么菜单也不会再变化
PS：其实不光是同一个一级菜单下的一组二级菜单。全站的二级菜单中，不要求是同一组在同一个一级菜单下，只要有一个keepalive为false,其他为true。此时连续点击两个keepalive为true的菜单，再点击一次keepalive为false的菜单，就会出现上述的BUG

**Expected behavior（你期待的是什么?）**
无论每个菜单是否需要缓存，都应该在右侧content中正确的刷新组件

**Screenshots（截图）**
预设：分析页、工作台keepAlive为true，张津测试页keepAlive为false
正常情况：
![image](https://user-images.githubusercontent.com/42567006/67189615-1f6f5980-f421-11e9-8ac9-c1be658d1589.png)
点击一次分析页：
![image](https://user-images.githubusercontent.com/42567006/67189728-56de0600-f421-11e9-9268-81dfd708f781.png)
再点击张津测试页：
![image](https://user-images.githubusercontent.com/42567006/67189849-8d1b8580-f421-11e9-9156-b9c3e631ed9c.png)
此时无论再点击什么菜单，右侧content永远会是这个样子。

当刷新网页，或者直接通过url打开张津测试页时，页面如下：
![image](https://user-images.githubusercontent.com/42567006/67189957-b50ae900-f421-11e9-89b0-a531fc191e8f.png)

代码是几天前下载的，肯定是新的版本，现在突然发现这个问题，不知道是不是BUG，麻烦大神们帮解决一下，真的很喜欢这个框架。如果需要文件包，我的QQ是864296998

**Comment by zhangjinzhangjin** [comment]
![image](https://user-images.githubusercontent.com/42567006/67190549-bdafef00-f422-11e9-9bc3-70dffcbb4122.png)
我是这样写的路由菜单，同组的二级菜单中，只有一个keepAlive是false，其他全部为true.
其实不自己添加，用demo的例子直接把其中一项的keepAlive改成true，就可以重现这个问题
希望大神们能看到我的问题，帮助解决一下，不胜感激

**Comment by sendya** [comment]
已知问题，你可以自己给 keepalive 组件加 includes 解决

**Comment by zhangjinzhangjin** [comment]
> 已知问题，你可以自己给 keepalive 组件加 includes 解决

谢谢您的回答，我反应的问题您这是不是也可以重现了啊？

我现在vue的基础比较差，keepalive组件的includes应该怎么添加呢，有办法还是在router.config.js中配置生效吗？

我的代码在这里，直接点击就可以看到我说的问题现象。如果可以的话，麻烦您帮做一个demo示例或者粘贴点相关代码也行，不胜感激。谢谢谢谢
[ant-design-pro-text.zip](https://github.com/sendya/ant-design-pro-vue/files/3751649/ant-design-pro-text.zip)

**Comment by zhangjinzhangjin** [comment]
我自己写了一个测试例子，仿照ant-design-pro-vue，写了一个App->BasicLayout->两层RouteView->页面这样的组件嵌套，也是重现了一样的问题。连续点两次keepAlive为true的，再点一次keepAlive为false的，就会变成再点什么路由页面都不再渲染的情况。下面是我的测试代码
点击pageB,再点pageC，再点pageA就会出BUG了
[alive.zip](https://github.com/sendya/ant-design-pro-vue/files/3753570/alive.zip)

**Comment by zhangjinzhangjin** [comment]
不用render，直接写在template就没事。。神奇，感觉有可能是vue本身的BUG~~~关了关了
