### ISSUE TITLE
console.log不打印信息，怎么解决？

### ISSUE THREAD

**Issue by peade** [vueComponent/ant-design-vue-pro#499]
**Question （问题描述）**
下载了最新的代码，出现了这个问题，怎么解决？

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
不知道

**Comment by sendya** [comment]
可否详细描述下？

**Comment by peade** [comment]
所有的地方，在js里写console.log(111),都不打印信息

**Comment by peade** [comment]
> 可否详细描述下？
例如这样子，能alert，不能console
‘’‘
created () {
    console.log('workplace')
    alert('workplace')
}
’‘’

**Comment by peade** [comment]
> 可否详细描述下？


我在workplce页面，login页面，store/module/user.js里，api里，都试过了，都存在这个问题。

**Comment by sendya** [comment]
脚手架中自带的几个组件都能正常输出 log，如果你不详细提供你做了什么改动 或者基于什么环境，你的问题我不能为你解答。请自行解决  详情请看 #90 

![image](https://user-images.githubusercontent.com/5404542/67273116-67a97d00-f4f0-11e9-8511-b4772e29a139.png)

**Comment by peade** [comment]
> 脚手架中自带的几个组件都能正常输出 log，如果你不详细提供你做了什么改动 或者基于什么环境，你的问题我不能为你解答。请自行解决 详情请看 #90
> 
> ![image](https://user-images.githubusercontent.com/5404542/67273116-67a97d00-f4f0-11e9-8511-b4772e29a139.png)


非常感谢，是我自己的问题。不知道操作了什么，把chrome devtool里的console.log的信息关掉了。我重置devtool设置就好了。
给你添麻烦了。
