### ISSUE TITLE
这个应该是一个判断吧？现在是赋值。

### ISSUE THREAD

**Issue by chenghf** [vueComponent/ant-design-vue-pro#50]
https://github.com/sendya/ant-design-pro-vue/blob/6de407cb91c6bfd2655d3234fee54a2a8eae454c/src/components/table/index.js#L116

**Comment by sendya** [comment]
我映像中这个是赋值 不是判断。
请问为什么认为是判断呢？

**Comment by sendya** [comment]
当没有 `r.totalCount` 且 `this.showPagination` 是 `auto|false` 时，`this.localPagination = false` 用于关闭 `Pagination` 功能，如果最后一个是判断的话，那么这一行就没任何意义了。至少它应该取到逻辑值用于其他的判断处理，但是这里并没有赋值处理

**Comment by chenghf** [comment]
遇到一个问题，数据从服务器获取，第一次有数据，第二次无数据（表格为空），第三次有数据，提示错误，pagination 错误，当前pagination=false，修改为判断后正常了，就没有深究。

**Comment by sendya** [comment]
请确认你的返回结果中有 `r.totalCount`，如果没有，你需要根据文档说明把
`r.totalCount, // 返回结果中的总记录数` 修改为你的接口返回结果中的 `"total"` 字段

**Comment by sendya** [comment]
![20190111091459](https://user-images.githubusercontent.com/5404542/51007174-71757b80-1581-11e9-83e3-af303bb5aabf.png)

**Comment by chenghf** [comment]
![image](https://user-images.githubusercontent.com/60983/51008992-2a8b8400-1589-11e9-961e-3392bc7ef23b.png)
![image](https://user-images.githubusercontent.com/60983/51009014-45f68f00-1589-11e9-8736-587b5e58f747.png)
![image](https://user-images.githubusercontent.com/60983/51009027-53137e00-1589-11e9-9e61-12b833716253.png)

**Comment by chenghf** [comment]
找到原因了，是data:[{}]惹的祸
