### ISSUE TITLE
表单检验promise返回的字段

### ISSUE THREAD

**Issue by xiumubai** [vueComponent/ant-design-vue-pro#503]
form表单如何检验promise返回的字段，然后给出错误信息提示

**Comment by sendya** [comment]
不知道你说的什么意思，给个例子？
另外，表单校验是用来校验表单的。跟 promise 返回字段 控制 要校验的 字段 没任何关系，你不要把这个概念搞混了。

如果是想动态控制要校验的字段，有两条路，一条是每个表单的 required 动态控制，
另一个是 form 的 `validateFields` 方法，具体自己去查文档

**Comment by xiumubai** [comment]
我是想验证后台返回的错误信息，在前端表单给出错误提示，哪个字段错了就提示哪个，后台数据是这样的
![image](https://user-images.githubusercontent.com/18414131/67355317-932c7600-f589-11e9-8955-e76b5c8c7c8f.png)

**Comment by sendya** [comment]
我已经说明完了
