### ISSUE TITLE
build后的dist文件使用nginx服务托管问题

### ISSUE THREAD

**Issue by ipanocloud** [vueComponent/ant-design-vue-pro#505]
**Question （问题描述）**
按照官方文档 https://pro.loacg.com/docs/deploy 里所说, build后的dist文件使用nginx服务托管
此时没有后端服务,需要转发/api
location /api {
        proxy_pass https://preview.pro.loacg.com;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
但是目前遇到的问题是按照官网所提供的nginx配置后,请求总是 400 bad request or  405 not allowed

**Comment by sendya** [comment]
请不要代理本站的 API ，会被拦截。


另外，请咨询你的后端开发 或者运维，让他们帮你处理 nginx 的问题，本项目为前端项目，只提供可行方案和例子，不包处理服务器部署相关问题。

**Comment by ipanocloud** [comment]
> 请不要代理本站的 API ，会被拦截。
> 
> 另外，请咨询你的后端开发 或者运维，让他们帮你处理 nginx 的问题，本项目为前端项目，只提供可行方案和例子，不包处理服务器部署相关问题。

你这个么说我就明白什么意思了,谢谢
