### ISSUE TITLE
路由失效：在快速切换菜单的时候，停在一个页面，无法切换

### ISSUE THREAD

**Issue by tanshion** [vueComponent/ant-design-vue-pro#506]
**Describe the bug （描述 Bug）**

路由失效：在快速切换菜单的时候，停在一个页面，无法切换

**To Reproduce （重现步骤）**

快速切换 ：分析页、工作台、测试功能、快速点击这 3个菜单会导致路由失效

**Expected behavior（你期待的是什么?）**

希望快速点击菜单也可以正常切换

**Screenshots（截图）**

![image](https://s2.ax1x.com/2019/10/24/KUYTd1.gif)

**Desktop (please complete the following information):**

mac
 chrome
78

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
好的。已经发现是 master 分支上有问题
