### ISSUE TITLE
table使用scroll后，有警告

### ISSUE THREAD

**Issue by desosaa** [vueComponent/ant-design-vue-pro#507]
提示`expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.

expandedRowRender并没有设置

**Comment by sendya** [comment]
如果是 `s-table` 复杂逻辑请使用 a-table 实现。
如果是 a-table 请提供 codesandbox 复现。

**Comment by desosaa** [comment]
就是用的a-table，就普通的列表读取，没包含什么复杂的功能，

这是设置的a-table的属性
<a-table rowKey="id" :columns="this.columns" :dataSource="data" :pagination="false" bordered :scroll="{x:1500}">
        <span slot="serial" slot-scope="text, record,index">
          {{index+1}}
        </span>
      </a-table>

定义的columns
columns = [
      {
        title: '#',
        align:'center',
        scopedSlots: { customRender: 'serial' }
      }
    ]

就出现了
Warning: `expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.

**Comment by sendya** [comment]
请提供 codesandbox 复现

**Comment by desosaa** [comment]
`<template>

    <a-table
      rowKey="key"
      :columns="columns"
      :dataSource="loadData"
      :scroll="{x:1500}"
    >
      <span slot="serial" slot-scope="text, record, index">
        {{ index + 1 }}
      </span>
    </a-table>
<template>
`
`
<script>

import { Table} from 'ant-design-vue';
export default {
  name: 'ProductType',
  components: {
    ATable:Table
  },
  data () {
    return {
      // 表头
      columns: [{
        title: '#',
        align:'center',
        width: '50px',
        scopedSlots: { customRender: 'serial' }
      }],
      loadData: [{key: '1',},
      {key: '2',},
      {key: '3',},]
    };
  },
  mounted(){
  }
}
</script>
`

**Comment by ethan666** [comment]
> 提示`expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.
> 
> expandedRowRender并没有设置
用你的代码测试，没有出现警告。 没有用这个项目测试，自己搭建的环境测试（vue-cli, ant-design-vue）

**Comment by ethan666** [comment]
> 提示`expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.
> 
> expandedRowRender并没有设置

用你的代码测试，没有出现警告。 没有用这个项目测试，自己搭建的环境测试（vue-cli, ant-design-vue）
