### ISSUE TITLE
a-date-picker求助

### ISSUE THREAD

**Issue by forever-thinker** [vueComponent/ant-design-vue-pro#509]
a-date-picker选择了日期，传给后台的是当前的UTC时间（带毫秒的UTC时间），用什么办法可以让它只传日期到后台，并且是GMT+8的，非常感谢！

 <a-date-picker v-model="queryParam.startDate" style="width: 100%" type="date" format="YYYY-MM-DD" placeholder="请选择开始日期"   @on-change="(date) => {queryParam.startDate = date}"/>

**Comment by hudianlao48** [comment]
dataPicker是moment对象，传到后台之前你format一下或者get一下，能获取各种需要的格式。详细可以参考moment文档
