### ISSUE TITLE
/sockjs-node/info接口报错

### ISSUE THREAD

**Issue by xiumubai** [vueComponent/ant-design-vue-pro#510]
/sockjs-node/info接口不知道从哪里来的，文件也没找到，一直报错，请问是不是项目自带的？怎么删除？

![image](https://user-images.githubusercontent.com/18414131/67542314-d2400000-f71e-11e9-924e-df9b5c36162a.png)

**Comment by sendya** [comment]
webpack 环境自带，你不用找到，报错是因为跟项目配置的 dev 端口不一致 你占用了 8000 端口，不是项目自带的，不能删除

**Comment by xiumubai** [comment]
明白了。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言肆"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 中午12:01
收件人:&nbsp;"sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com&gt;;
抄送:&nbsp;"朽木白"<1547702880@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sendya/ant-design-pro-vue] /sockjs-node/info接口报错 (#510)




webpack 环境自带，你不用找到，报错是因为跟项目配置的 dev 端口不一致 你占用了 8000 端口，不是项目自带的，不能删除
