### ISSUE TITLE
vue-infinite-scroll这个插件怎么让它一进来滚动条就在内容区域底部，我看a-list-item有用到这个插件，但不知道怎么让滚动条默认滚到底部。

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#512]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
不清楚，我没用过 vue-infinite-scroll 这个组件，请自己查阅相关文档
