### ISSUE TITLE
修改router.config.js无效

### ISSUE THREAD

**Issue by shidashui** [vueComponent/ant-design-vue-pro#513]
根据文档添加修改路由时，重新加载没有响应的效果出现

**Comment by sendya** [comment]
请先确认用的路由是默认路由 还是动态路由，提问请尽量详细的提供相关信息 #90

**Comment by shidashui** [comment]
使用的应该是默认路由
![image](https://user-images.githubusercontent.com/38198038/67735760-147b8100-fa40-11e9-990e-b4c85dc671d8.png)
![image](https://user-images.githubusercontent.com/38198038/67735778-28bf7e00-fa40-11e9-881b-c7b0779af83e.png)

**Comment by shidashui** [comment]
大佬，有没有交流群，小白啊🤣orz

**Comment by sendya** [comment]
提供你的系统信息(发行版名字，版本号，浏览器等)。
提供你所使用的 Pro 版本。
尽量详细描述你的问题，
操作步骤，截图，录屏，浏览器 Console 报错

能提供的都提供了
