### ISSUE TITLE
2.0版本为啥登录页会加载一个27.4mb的app.js文件

### ISSUE THREAD

**Issue by murongqingsi** [vueComponent/ant-design-vue-pro#514]
![image](https://user-images.githubusercontent.com/10190370/67747138-199df780-fa63-11e9-985e-dad42a695f9d.png)
这个ba版本，打开登录页面会加载一个app.js文件，该文件大小有27.4mb
![image](https://user-images.githubusercontent.com/10190370/67747195-35090280-fa63-11e9-84b4-c205588ab3fc.png)

**Comment by sendya** [comment]
请了解一下 Vue 和前端工程化，这是 Vue 和 Vue 依赖的一些核心代码，包含路由，状态管理，和一些调试工具。并且代码没有经过压缩，包含了所有备注信息等便于在浏览器中 debug

**Comment by murongqingsi** [comment]
明白明白，可能昨天我看错了，我昨天是打包后，发现登录页还请求那么大的文件，今天看竟然没有了，抱歉抱歉
