### ISSUE TITLE
路由使用了PageView，如何在页面中使用组件的slot功能？

### ISSUE THREAD

**Issue by loongmxbt** [vueComponent/ant-design-vue-pro#515]
**Question （问题描述）**
路由使用了PageView，如何在页面中使用组件的slot功能？
目前案例看使用PageView组件功能需要路由里使用RouteView，在页面中引入PageView组件，然后slot传入组件。

**Describe the solution you'd like （你期待的是什么？）**
请问如何在路由定义使用的PageView的情况下，在页面中使用PageView的功能，如在headerContent、extra等区块添加内容。

**Additional context（附加信息）**

**Comment by sendya** [comment]
在页面中引入PageView组件，然后slot传入组件。

**Comment by loongmxbt** [comment]
我查了一下，好像slot只可以父组件到子组件。本意是由于router.config.js已经定义了使用PageView，希望可以在页面中不用再次引用就可以使用PageView的slots功能。
现在还是按照示例的在路由中用 RouteView，每个子页面引入并使用PageView组件好了。
