### ISSUE TITLE
打包后，src/config/defaultSettings.js配置的主题色失效

### ISSUE THREAD

**Issue by Amyff** [vueComponent/ant-design-vue-pro#516]
**Question （问题描述）**
打包后，src/config/defaultSettings.js配置的主题色失效，本地是正确的

**Describe the solution you'd like （你期待的是什么？）**
希望打包后，主题色正常

**Additional context（附加信息）**

**Comment by sendya** [comment]
打包不会提供主题样式，请自行使用 less 变量覆盖进行覆盖

https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L81-L87

**Comment by Amyff** [comment]
找到原因了 按本地右侧设置里面的提示 去修改src/config/defaultSettings.js 我感觉是没用的。。
然后clone下来的项目 根目录下的vue.config.js里的css配置被注释掉了，打开然后修改就可以了
