### ISSUE TITLE
登陆用户切换时，前端路由权限导致显示404页面

### ISSUE THREAD

**Issue by yichangle** [vueComponent/ant-design-vue-pro#517]
**Question （问题描述）**
前端做了路由权限控制，用户A登陆后访问Page A，登出A用户，B用户登入，此时因为B用户没有PageA对应的路由，登陆后直接显示了404页。此时在浏览器手工输入B用户路由表中存在的地址，才能正常显示出页面。

用户A和用户B都有Dashboard路由权限，login页面中，用户登陆后默认都是跳转到这个页面，但是目前软件似乎是记录了上次打开的页面，下次自动打开上次记录的页面，结果因为路由问题导致404页。
我目前没能找到在哪记录的，登出后或者关闭浏览器，应该让这个记录失效，登陆后打开的第一个页面始终是默认页面。
请大家给予帮助，谢谢。

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L34
