### ISSUE TITLE
动态路由怎么用？

### ISSUE THREAD

**Issue by ChartWay** [vueComponent/ant-design-vue-pro#518]
**Question （问题描述）**
看了半天文档，把路由权限通篇都看完了，但是感觉还是没搞明白动态路由怎么用，能不能写详尽点的教程，比如在什么文件中，修改什么配置，这样就相当于启用了动态路由，另外，启用动态路由后，原来的文件配置的路由是不是就不起作用了，或者怎么让它不起作用？

**Comment by sendya** [comment]
如果看不懂脚手架自带的路由控制，可以自己根据路由结构生成路由。使用脚手架自带的生成方式 `不是必须的`

**Comment by ChartWay** [comment]
> 如果看不懂脚手架自带的路由控制，可以自己根据路由结构生成路由。使用脚手架自带的生成方式 `不是必须的`

那个写死的路由我清楚，现在是比较感兴趣动态路由，就是不想把太多的东西写死，所以想了解下怎么用。

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/router/generator-routers.js

**Comment by xiechao1211** [comment]
中心思想就是前端需要定义好所有的页面对应的组件路径，如：
'TableList': () => import('@/views/list/TableList')
其他路由信息根据后端返回的数据拼接，但是路由的component必须从这个文件配置好的值里边取，其他所有路由数据都可以由后端返回

**Comment by wsz7777** [comment]
模板一下子开了三种路由方式
emmm，确实让新手感到头晕目眩
我看了第一遍代码 感觉 ？？？ ，这里有路由控制 router.config
第二编代码？？？，这里还有路由控制！！！generator-routers.js
第三遍代码？？？，我去！这里还有？！？！async-router.js
....
这三处都干嘛的啊，会不会相互影响啊，天~我太难了
。。。
最后发现三个随便用一个就好，emmmm

**Comment by wsz7777** [comment]
一句话：官方文档能不能分开三部分介绍一下路由配置

**Comment by sendya** [comment]
@wsz7777 

> 模板一下子开了三种路由方式
> emmm，确实让新手感到头晕目眩
> 我看了第一遍代码 感觉 ？？？ ，这里有路由控制 router.config
> 第二编代码？？？，这里还有路由控制！！！generator-routers.js
> 第三遍代码？？？，我去！这里还有？！？！async-router.js
> ....
> 这三处都干嘛的啊，会不会相互影响啊，天~我太难了
> 。。。
> 最后发现三个随便用一个就好，emmmm

你还是错了
路由控制只有一处，`/src/permission.js` 利用路由守卫控制访问时的动态路由生成和拦截

动态为 vue-router 构建路由 有两套，一套是固定结构体完整的路由，并利用路由守卫访问时，根据用户信息过滤无权限的路由

另一套为 利用路由守卫放问时，根据用户信息，请求后端，拉取完整路由表信息`（已经被后端过滤了，不需要前端再次过滤）`。

----
题外话： 熟悉 `vue-router` 的人不会有这些烦恼。动态路由的最终，都是构建一个 `vue-router` 的结构体数据给 `vue-router`，无论过程怎么样。

**Comment by yanduhantan1991** [comment]
@sendya 能详细说一下  “动态为 vue-router 构建路由 有两套，一套是固定结构体完整的路由，并利用路由守卫访问时，根据用户信息过滤无权限的路由” 么，我现在是后台返回不需要过滤权限的路由，所以我修改了 /src/permission.js，因为没有权限的内容，所以通过role.length判断修改了，在getInfor直接获取路由存储到本地，generator-routers.js  里面generatorDynamicRouter这个方法直接从本地获取的路由返回，并且通过"analysis": () => import('@/views/dashboard/Analysis.vue'),方式引入了所有的组件，问题是，登录之后进入到首页可以，但是切换菜单没有反应，没有进行路由切换，刷新当前页面就变成空白了。
src/permission.js
`router.beforeEach((to, from, next) => {
  NProgress.start() // start progress bar
  to.meta && (typeof to.meta.title !== 'undefined' && setDocumentTitle(`${to.meta.title} - ${domTitle}`))
  if (Vue.ls.get(ACCESS_TOKEN)) {
    /* has token */
    if (to.path === '/user/login') {
      next({ path: defaultRoutePath })
      NProgress.done()
    } else {
    //    if (store.getters.roles.length === 0 ) {
		if (!Vue.ls.get('getInfo')) {
        store
          .dispatch('GetInfo')//同时获取路由信息
          .then(res => {
			  //本地存储一个标识
			  Vue.ls.set('getInfo','true')
			// const roles = res.result && res.result.role
			const roles = res.returnData.roleList
            store.dispatch('GenerateRoutes', { roles }).then(() => {
              // 根据roles权限生成可访问的路由表
              // 动态添加可访问路由表
              router.addRoutes(store.getters.addRouters)
			  const redirect = decodeURIComponent(from.query.redirect || to.path)
			  //第一个判断是自己加的
			  if(to.path === redirect && redirect === '/'){
				next({ path: defaultRoutePath })
			  }else if (to.path === redirect && redirect !== '/') {
				// if(to.path === redirect){
                // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
				next({ ...to, replace: true })
              } else {
                // 跳转到目的路由
                next({ path: redirect })
              }
            })
          })
          .catch(() => {
            notification.error({
              message: '错误',
              description: '请求用户信息失败，请重试'
            })
            store.dispatch('Logout').then(() => {
              next({ path: '/user/login', query: { redirect: to.fullPath } })
            })
          })
      } else {
        next()
      }
    }
  } else {
    if (whiteList.includes(to.name)) {
      // 在免登录白名单，直接进入
      next()
    } else {
      next({ path: '/user/login', query: { redirect: to.fullPath } })
      NProgress.done() // if current page is login will not trigger afterEach hook, so manually handle it
    }
  }
})`
获取菜单的方法
`        getInfo(url).then(response => {
		  response.returnData.menuList=selfMenu
		  const result = response.returnData
		  Vue.ls.set(MENU_ROUTER_DATA, result.menuList)
          **//这里的result.role 会是一个空数组**
          if (result.role && result.role.permissions.length > 0) {
            const role = result.role
            role.permissions = result.role.permissions
            role.permissions.map(per => {
              if (per.actionEntitySet != null && per.actionEntitySet.length > 0) {
                const action = per.actionEntitySet.map(action => { return action.action })
                per.actionList = action
              }
            })
            role.permissionList = role.permissions.map(permission => { return permission.permissionId })
            commit('SET_ROLES', result.role)
            commit('SET_INFO', result)
		  }
		  commit('SET_NAME', { name: result.loginName, welcome: welcome() })
          commit('SET_AVATAR', result.avatar)

          resolve(response)
        }).catch(error => {
          reject(error)
        })`
