### ISSUE TITLE
a-table表格怎么让它点击选中某一行的区域时触发checkbox事件，而不单单是选中了checkbox才触发. 

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#520]
*Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
![gaitubao_cccccccccppppp_jpg](https://user-images.githubusercontent.com/20655248/68106455-aaba1600-ff1c-11e9-972f-20972f2d09d2.jpg)

**Comment by kokoroli** [comment]
![image](https://user-images.githubusercontent.com/25897806/68112299-faeca480-ff2b-11e9-8daf-4cb902d3354d.png)
https://www.antdv.com/components/table-cn/
ant-design-vue 文档中已经提供对应的示例
