### ISSUE TITLE
权限列表编辑功能BUG

### ISSUE THREAD

**Issue by camry** [vueComponent/ant-design-vue-pro#522]
**权限列表编辑功能BUG**

权限列表编辑功能表单里面的 “状态” 默认为数字

![20191105172249](https://user-images.githubusercontent.com/790303/68195348-ab70ac00-fff1-11e9-9062-316b7627fa4e.png)

**Comment by camry** [comment]
`this.form.setFieldsValue(record)`

找原因了，是在设置值的时候，值的数据类型必须为字符串。

建议官方能修复这个BUG

**Comment by sendya** [comment]
这只是业务 demo，请自行处理。
