### ISSUE TITLE
想请教下，为什么编译速度变得很慢，一直卡在70%

### ISSUE THREAD

**Issue by zhichao8756** [vueComponent/ant-design-vue-pro#527]
每次热更新很慢，一直卡在70%，找了半天没找出原因。。。
![image](https://user-images.githubusercontent.com/24514251/68569591-73f27b80-0499-11ea-90c2-b9683b56d0f9.png)

**Comment by sendya** [comment]
你做了何改动? 我本地原版的 pro 代码并没这种情况

**Comment by PriestsHsiung** [comment]
![image](https://user-images.githubusercontent.com/2756959/69517090-a7033780-0f8e-11ea-88f9-ea6acdf0f41a.png)
我的也是，常常卡在76%
只是把本地路由变成了 重后端获取路由

**Comment by zhichao8756** [comment]
问题已解决,参考 https://github.com/webpack/webpack/issues/8557

**Comment by nickolboy** [comment]
> 问题已解决,参考 [webpack/webpack#8557](https://github.com/webpack/webpack/issues/8557)

我用babel-plugin-dynamic-import-node，异步组件挂了
