### ISSUE TITLE
浏览器头部标题和icon图标

### ISSUE THREAD

**Issue by ramocky** [vueComponent/ant-design-vue-pro#528]
如何配置浏览器的头部标题信息和图标？

**Comment by sendya** [comment]
https://www.baidu.com/s?wd=%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%A4%B4%E9%83%A8%E6%A0%87%E9%A2%98%E4%BF%A1%E6%81%AF%E5%92%8C%E5%9B%BE%E6%A0%87&rsv_spt=1&rsv_iqid=0x88e6839e001664e3&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=0&rsv_dl=ib&rsv_sug3=21&rsv_sug1=19&rsv_sug7=100&rsv_n=2&inputT=10671&rsv_sug4=10672

**Comment by ramocky** [comment]
> [https://www.baidu.com/s?wd=%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%B5%8F%E8%A7%88 ％E5％99％A8％E7％9A％84％E5％A4％B4％E9％83％A8％E6％A0％87％E9％A2％98％E4％BF％A1％E6％81％AF％E5 ％92％8C％E5％9B％BE％E6％A0％87＆rsv_spt = 1＆rsv_iqid = 0x88e6839e001664e3＆issp = 1＆f = 8＆rsv_bp = 1＆rsv_idx = 2＆ie = utf-8＆tn = baiduhome_pg＆rsv_rsv_s = ug＆sv_s = 4＆sv_s = 4＆sv_s = 4＆sv_s = 7＆sg_sv_s = 7＆sg_sv_s = 7＆sg_sv_s = 7 && sv_s = 1＆sv_s = 7 && sv_s = 7 && sv_s = 7 && sv_s = 7 && sv_s = 7 && sv_s = 7 && sv_s = 1 && sv_s = 7 && sv_s = 7 && sv_s = 7＆s](https://www.baidu.com/s?wd=%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%A4%B4%E9%83%A8%E6%A0%87%E9%A2%98%E4%BF%A1%E6%81%AF%E5%92%8C%E5%9B%BE%E6%A0%87&rsv_spt=1&rsv_iqid=0x88e6839e001664e3&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=0&rsv_dl=ib&rsv_sug3=21&rsv_sug1=19&rsv_sug7=100&rsv_n=2&inputT=10671&rsv_sug4=10672)

hhh...是我憨憨了
