### ISSUE TITLE
部署在IIS上

### ISSUE THREAD

**Issue by ramocky** [vueComponent/ant-design-vue-pro#529]
**Question （问题描述）**
官方文档提供了几种关于部署的方案 但是不包含IIS 
我想知道下我想部署在IIS上本地预览需要做什么调整吗？

**Comment by sendya** [comment]
不清楚，请自行查询 vue-cli 部署相关问题

**Comment by legenself** [comment]
直接build放进去就可以使用hash模式的路由了，不过history模式的路由需要使用IIS URLRewrite

**Comment by ramocky** [comment]
解决了谢谢 要url 重写
