### ISSUE TITLE
进入其他页面后如何让表格又回到原本的分页页码

### ISSUE THREAD

**Issue by csnan** [vueComponent/ant-design-vue-pro#532]
进入其他页面后如何让表格又回到原本的分页页码

**Comment by sendya** [comment]
路由控制 e.g.  `/user/:page` /user/1 , /user/2
或
缓存控制 keep-alive

**Comment by cai148480** [comment]
`{
            path: '/quizzesManagement/quiz',
            name: 'Quiz',
            redirect: '/quizzesManagement/quiz/list',
            component: RouteView,
            hideChildrenInMenu: true,
            meta: { title: '单测试' },
            children: [
              {
                path: '/quizzesManagement/quiz/list',
                name: 'QuizList',
                component: () => import('@/views/quizzesManagement/quiz/QuizList'),
                meta: { title: '单测试列表', hidden: true, keepAlive: true }
              },
              {
                path: '/quizzesManagement/quiz/operate',
                name: 'QuizOperate',
                component: () => import('@/views/quizzesManagement/quiz/QuizOperate'),
                meta: { title: '测试题编辑', hidden: true, keepAlive: true }
              }
            ]
          },`

单侧试列表就是有表格的页面，加了keepAlive: true，但是进入该页面还是会刷新到第一页

**Comment by cai148480** [comment]
`{
            path: '/quizzesManagement/quiz',
            name: 'Quiz',
            redirect: '/quizzesManagement/quiz/list',
            component: RouteView,
            hideChildrenInMenu: true,
            meta: { title: '单测试' },
            children: [
              {
                path: '/quizzesManagement/quiz/list',
                name: 'QuizList',
                component: () => import('@/views/quizzesManagement/quiz/QuizList'),
                meta: { title: '单测试列表', hidden: true, keepAlive: true }
              },
              {
                path: '/quizzesManagement/quiz/operate',
                name: 'QuizOperate',
                component: () => import('@/views/quizzesManagement/quiz/QuizOperate'),
                meta: { title: '测试题编辑', hidden: true, keepAlive: true }
              }
            ]
          }`

**Comment by csnan** [comment]
为什么我有表格的那一页在路由那里设置 `keepAlive: true` 后还是会强制刷新到第一页

**Comment by csnan** [comment]
我看框架那里 tableList 那个页面的 path 是` path: '/list/table-list/:pageNo([1-9]\\d*)?',` ，这个就是实现这个分页缓存的么

**Comment by csnan** [comment]
知道了！框架里面有个多标签模式可切换缓存！
