### ISSUE TITLE
多标签场景，设置keepAlive: false不生效，已有标签输入信息，关闭后重新打开，原输入内容仍然存在。

### ISSUE THREAD

**Issue by luo4210** [vueComponent/ant-design-vue-pro#536]
**Describe the bug （描述 Bug）**

多标签场景，设置keepAlive: false不生效，已有标签输入信息，关闭后重新打开，原输入内容仍然存在。

**To Reproduce （重现步骤）**

打开A标签，输入数据AAA
打开B标签，输入数据BBB
关闭A标签
打开A标签---此时数据AAA仍然存在

**Expected behavior（你期待的是什么?）*

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
多标签模式下 无法关闭 keep alive

**Comment by luo4210** [comment]
> 
> 
> 多标签模式下 无法关闭 keep alive

i请问这个问题后续有实现的计划吗？
对于多标签应用，关闭后还缓存，的确是不太合理。

**Comment by sendya** [comment]
后续计划移除当前 multi-tab 组件
