### ISSUE TITLE
多页签模式下，一个带参数动态路由，显示在两个页签种，每个页签的操作相互有影响，可以像iframe那样吗，

### ISSUE THREAD

**Issue by wuchr** [vueComponent/ant-design-vue-pro#537]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
不能
