### ISSUE TITLE
重新登录后定位到之前的页面

### ISSUE THREAD

**Issue by ramocky** [vueComponent/ant-design-vue-pro#540]
请问下关于登录登出再登录后之后定位到之前的操作页面是怎么实现的？

**Comment by sendya** [comment]
路由守卫 https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L34

**Comment by ramocky** [comment]
> 路由守卫https://github.com/sendya/ant-design-pro-vue/blob/master/src/permission.js#L34

可能我描述不清楚,我详细说下
就是 我之前访问 table页面然后我退出再登录进来马上导航栏和router定位到了table 能讲讲大概怎么实现的嘛 
#34这行代码有点懵

**Comment by sendya** [comment]
就很简单的 Menu 组件赋值，具体查阅 antd vue 文档
