### ISSUE TITLE
怎么点击表格行的时候触发checkbox的onchange的事件

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#541]
![gaitubao_chan3_jpg](https://user-images.githubusercontent.com/20655248/69135482-1e9b1780-0af4-11ea-8509-49dff23cc215.jpg)

![gaitubao_chann_jpg](https://user-images.githubusercontent.com/20655248/69135733-8ea99d80-0af4-11ea-9613-0980ebdea1ba.jpg)
![gaitubao_chann2_jpg](https://user-images.githubusercontent.com/20655248/69135827-b7319780-0af4-11ea-9c40-418c10a7dbca.jpg)
![gaitubao_chan5_jpg](https://user-images.githubusercontent.com/20655248/69136115-3cb54780-0af5-11ea-981a-3dd7b199997a.jpg)
![gaitubao_chan6_jpg (1)](https://user-images.githubusercontent.com/20655248/69136326-9fa6de80-0af5-11ea-9c35-ecc16748e275.jpg)

**Comment by sendya** [comment]
不能触发

不过也没必要触发，你可以换个思路， Vue 是数据驱动框架，你完全可以用数据驱动界面的变化
customRow 的 click 触发时，直接把当前的 selectedRows, selectedRowKeys 数据都更新了就好了
