### ISSUE TITLE
怎么开启多页签模式，默认拉取的代码没有多页签，好奇怪

### ISSUE THREAD

**Issue by kkrout** [vueComponent/ant-design-vue-pro#543]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by useryechen** [comment]
在`layouts`-`BasicLayout`文件中将数据中的`multitabs`改为`true`，作者默认没有开启`MultiTab`组件

**Comment by sendya** [comment]
不是有 **设置栏**？

**Comment by zhang-mol** [comment]
首先作者提供了配置文件defaultSettings.js，配置multiTab为true，其次，这样修改是无效的，作者通过设置栏来改变localStorage里的multi_tab（所以直接修改是无效，而通过设置栏是有效的），你必须退出重新登录才有效，ps：BasicLayout里的multiTab是计算属性，来源于mixin。
