### ISSUE TITLE
electron-vue 打包文件无法正常启动运行（一直停留在转圈画面)

### ISSUE THREAD

**Issue by liaoyongxiong** [vueComponent/ant-design-vue-pro#545]
**Describe the bug （描述 Bug）**
利用Vue CLI Plugin Electron Builder（https://github.com/nklayman/vue-cli-plugin-electron-builder）打包该项目，运行时抛异常无法进入系统

**To Reproduce （重现步骤）**
Mac OS下
1. git clone该项目到本地；
2. 进入ant-design-pro-vue目录执行 
    vue add electron-builder 
3、yarn electron:serve 可以启动进入系统,开发环境下可以正常运行

![截屏2019-11-2115 04 05](https://user-images.githubusercontent.com/9619081/69314878-2c75a780-0c70-11ea-907b-56361b665d9d.png)

![截屏2019-11-2115 04 38](https://user-images.githubusercontent.com/9619081/69314904-3eefe100-0c70-11ea-9f39-9d0d82cdea0c.png)

4、yarn electron:build 打成发行包后，点击生成的 dist_electron/mac/vue-antd-pro 发行包启动应用。应用启动后，一直停留在转圈画面，无法进入系统
![截屏2019-11-2114 58 31](https://user-images.githubusercontent.com/9619081/69314552-6a260080-0c6f-11ea-9017-5d1e3ea88fae.png)

**Expected behavior（你期待的是什么?）**
打包生成的执行文件，应能正确运行，进入登录界面

**Screenshots（截图）**
![截屏2019-11-2115 01 31](https://user-images.githubusercontent.com/9619081/69314728-d143b500-0c6f-11ea-945a-04ba8de9872f.png)

**Desktop (please complete the following information):**

 - OS: Mac OS

**Comment by Siffre** [comment]
资源找不到，我这里遇到的是打包问题，也在处理中，多多交流

**Comment by Siffre** [comment]
@liaoyongxiong    遇到同样的问题了

![image](https://user-images.githubusercontent.com/12948798/69607173-a25a8400-105f-11ea-9436-b4975676553d.png)

这是升级babel到最新并且匹配jsx语法后的结果

**Comment by Siffre** [comment]
@sendya

**Comment by Siffre** [comment]
这个应该是框架里面的jsx导致的，不知道改怎么转义一下，jsx语法兼容问题

**Comment by Siffre** [comment]
@liaoyongxiong   目前没找到有效的方法，只能把jsx语法去掉改成Vue版本的或者整体全部用ts重新来一份

**Comment by Siffre** [comment]
1. 问题已经解决：依赖库的问题
2. 把  "viser-vue": "^2.4.6"  相关的功能及其组件全部删掉即可

**Comment by Siffre** [comment]
@sendya   能处理一下这个库的问题吗？

**Comment by SangeCoder** [comment]
*** 问题描述
> 依赖库的问题：viser-vue 这个库里面隐含的一个bug   Object.assign() 使用时里面对象属性获取不到

*** 解决方案
> 把 "viser-vue": "^2.4.6" 相关的功能及其组件全部删掉即可

@sendya 能处理一下这个库的问题吗？

**Comment by JaneYork** [comment]
@liaoyongxiong   后来时怎么处理的？引用外部CDN？
