### ISSUE TITLE
组件a-tree-select 无法使用，请问应该需要引入

### ISSUE THREAD

**Issue by xuanlvdgg** [vueComponent/ant-design-vue-pro#546]
组件a-tree-select 无法使用，请问应该需要引入；

**Comment by sendya** [comment]
https://www.antdv.com/docs/vue/getting-started/

**Comment by xuanlvdgg** [comment]
你好，ant-design-pro-vue不是全局引入的吗？为什么a-tree-select不能使用?




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言肆"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 下午3:45
收件人:&nbsp;"sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com&gt;;
抄送:&nbsp;"热爱.&amp;生命"<1426827311@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sendya/ant-design-pro-vue] 组件a-tree-select 无法使用，请问应该需要引入 (#546)




https://www.antdv.com/docs/vue/getting-started/

**Comment by xuanlvdgg** [comment]
![image](https://user-images.githubusercontent.com/52984806/69408366-a590ff80-0d41-11ea-85bd-c6ad11230079.png)
![image](https://user-images.githubusercontent.com/52984806/69408390-b93c6600-0d41-11ea-9f6a-d47f16e9b573.png)
![image](https://user-images.githubusercontent.com/52984806/69408403-bfcadd80-0d41-11ea-8409-c09a3fd9662f.png)

**Comment by xuanlvdgg** [comment]
原来要从这引入才行。。。

**Comment by xuanlvdgg** [comment]
谢谢。

**Comment by sendya** [comment]
不全局引入，在局部使用 components: { 'xxName': xxComponent } 一样可以
