### ISSUE TITLE
请问表格怎么隐藏列？非常感谢！

### ISSUE THREAD

**Issue by forever-thinker** [vueComponent/ant-design-vue-pro#547]
表格列我需要areaId属性的值，但是我不希望显示该列，请问怎么隐藏？非常感谢！
 {
            title: '区域ID',
            dataIndex: 'areaId',
            align: 'center',
            width: "100px"
          }

**Comment by sendya** [comment]
columns 数组不加入不要的列

**Comment by forever-thinker** [comment]
> columns 数组不加入不要的列
已经开源，感谢！
