### ISSUE TITLE
语法错误导致编译失败

### ISSUE THREAD

**Issue by SangeCoder** [vueComponent/ant-design-vue-pro#548]
**Describe the bug （描述 Bug）**

![image](https://user-images.githubusercontent.com/12948798/69615422-ce7e0100-106f-11ea-9ce8-35917fa4018a.png)

![image](https://user-images.githubusercontent.com/12948798/69615539-0422ea00-1070-11ea-90da-9fa9624a2870.png)

> 这里是语法错误，变量应该是首字母大写Tag

**解决方法**

如下：
![image](https://user-images.githubusercontent.com/12948798/69615641-33d1f200-1070-11ea-8d64-4dee240babc0.png)

**开发环境**

- 升级babel 到 7
- 加入插件jsx转换

**Comment by SangeCoder** [comment]
原因：小写的变量名会直接作为字符串编译

**Comment by SangeCoder** [comment]
参考语法： https://zhuanlan.zhihu.com/p/24672284

**Comment by SangeCoder** [comment]
加了jsx语法转换插件后，发现都是语法错误，懵逼了

**Comment by sendya** [comment]
#90

**Comment by sendya** [comment]
希望你能够提供完整的反馈内容，想到什么说什么  乱七八糟的，搞得我都想屏蔽邮箱消息了。
