### ISSUE TITLE
页面缩放的问题

### ISSUE THREAD

**Issue by hhxyjsj** [vueComponent/ant-design-vue-pro#55]
![a](https://user-images.githubusercontent.com/31506377/51098392-f58b6580-1804-11e9-9a0c-ab72d3929cb1.jpg)
如上图如果缩小页面，则显示/隐藏菜单的按钮消失，正常应该如下图所示：
![b](https://user-images.githubusercontent.com/31506377/51098413-223f7d00-1805-11e9-9ddb-b708c1a0e465.jpg)

**Comment by sendya** [comment]
重复问题。 ref #54
