### ISSUE TITLE
分布对话框当前步骤的序号 字体颜色不正确

### ISSUE THREAD

**Issue by OldsixShang** [vueComponent/ant-design-vue-pro#550]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
最新 master ?

**Comment by SangeCoder** [comment]
![image](https://user-images.githubusercontent.com/12948798/69687704-da64d400-10fe-11ea-8e02-e4f9d087b5c5.png)

**Comment by OldsixShang** [comment]
没错呢，我是看了官方的demo发现哒

**Comment by OldsixShang** [comment]
.ant-steps-item-process .ant-steps-item-icon>.ant-steps-icon  这个样式导致的

**Comment by sendya** [comment]
#284

**Comment by kasnet** [comment]
分步表单序号不显示的问题  我也碰到了, tag:2.0.2版本 @sendya
