### ISSUE TITLE
aUpload组件beforeUpload压缩图片为blob上传报错

### ISSUE THREAD

**Issue by jiaqunying** [vueComponent/ant-design-vue-pro#552]
**Question （问题描述）**
aUpload组件beforeUpload压缩图片为blob上传报错

**Describe the solution you'd like （你期待的是什么？）**
 <a-upload
    name="avatar"
    listType="picture-card"
    class="avatar-uploader"
    :showUploadList="false"
    action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
    :beforeUpload="beforeUpload"
    @change="handleChange"
  >
    <img v-if="imageUrl" :src="imageUrl" alt="avatar" />
    <div v-else>
      <a-icon :type="loading ? 'loading' : 'plus'" />
      <div class="ant-upload-text">Upload</div>
    </div>
  </a-upload>

 beforeUpload (file) {
      return new Promise((resolve, reject) => {
        const isJPEG = file.type === 'image/jpeg';
        const isJPG = file.type === 'image/jpg';
        const isPNG = file.type === 'image/png';
        const isBMP = file.type === 'image/bmp';
        const isLt2M = file.size / 1024 / 1024 < 2;
        if (!isJPEG && !isJPG && !isPNG && !isBMP) {
          this.$message.error('上传图片必须是JPEG/JGP/PNG/BMP 格式!');
        }
        if (isLt2M) {
          resolve(res)
        }else{
          console.log(file.size / 1024 / 1024)
          imageConversion.compress(file, 0.6).then(res => { 
            console.log(res,file,res.size / 1024 / 1024)
            resolve(res)
          })
       }
        
      })
    }

**Additional context（附加信息）**
![13313](https://user-images.githubusercontent.com/31029570/69700210-dc418e00-1124-11ea-85ed-b7d3d025e572.png)

**Comment by sendya** [comment]
https://codesandbox.io/s/vue-antd-template-e22bh

用这个提供可运行复现

**Comment by jiaqunying** [comment]
> https://codesandbox.io/s/vue-antd-template-e22bh
> 
> 用这个提供可运行复现



请上传2M以上图片（2M图片以上开始压缩）

**Comment by jiaqunying** [comment]
> https://codesandbox.io/s/vue-antd-template-e22bh
> 
> 用这个提供可运行复现

因为上传地址涉及真实的，已私发QQ

**Comment by jiaqunying** [comment]
> https://codesandbox.io/s/vue-antd-template-e22bh
> 
> 用这个提供可运行复现

https://codesandbox.io/embed/vue-antd-template-v9ero?fontsize=14&hidenavigation=1&theme=dark
