### ISSUE TITLE
顶部导航模式，告警数字角标显示bug

### ISSUE THREAD

**Issue by OldsixShang** [vueComponent/ant-design-vue-pro#555]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/15935487/69841254-74f91a80-1299-11ea-8259-afc5cba62220.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by kokoroli** [comment]
已修复 9b7a06726514b2
