### ISSUE TITLE
打包后改变主题失效

### ISSUE THREAD

**Issue by lhp15575865420** [vueComponent/ant-design-vue-pro#557]
通过npm run build打包后，部署dist，发现切换主题颜色的功能失效了。

**Comment by sendya** [comment]
打包后不提供主题更换功能。如一定需要，请按照 preview 打包形式打包

**Comment by lhp15575865420** [comment]
我修改了defaultSettings.js里面的颜色值为红色，打包后运行还是显示默认的蓝色，设置导航栏显示在左边或者右边是有效的，颜色失效

**Comment by sendya** [comment]
直接在 vue.config.js 中修改颜色，谢谢
