### ISSUE TITLE
我修复了一个bug

### ISSUE THREAD

**Issue by ch656409110** [vueComponent/ant-design-vue-pro#56]
你好，我修复了一个bug。
在分页列表非第一页的情况删除当前页面所有数据，会导致上一页显示无数据。
![1](https://user-images.githubusercontent.com/32993363/51098366-c2e16d00-1804-11e9-8b0a-94f3491e6b0e.jpg)
![2](https://user-images.githubusercontent.com/32993363/51098367-c2e16d00-1804-11e9-9b11-7bb6c21a3d97.jpg)

代码：
在src\components\table\index.js 115行加上
`

                    if (r.data.length == 0 && that.localPagination.current != 1) {
                        that.localPagination.current--;
                        that.loadData();
                        return;
                    }
`

**Comment by sendya** [comment]
thanks. 



> 另外，如果已知如何修正问题，非常欢迎发起 `Pull Request`
