### ISSUE TITLE
axios.js下的这段代码Vue.axios = instance是起到什么作用?

### ISSUE THREAD

**Issue by iJay** [vueComponent/ant-design-vue-pro#561]
**Question （问题描述）**
axios.js下的这段代码Vue.axios = instance有什么意义吗?

**Describe the solution you'd like （你期待的是什么？）**
既然在Vue的原型下增加了axios属性,为什么要在Vue的构造函数上添加axios属性,感觉没有必要吧

**Additional context（附加信息）**
在项目中该代码遇到这里,没想明白用途或作用,请教一下

**Comment by sendya** [comment]
可能写重复了吧
