### ISSUE TITLE
页面刷新，页签保留

### ISSUE THREAD

**Issue by kkrout** [vueComponent/ant-design-vue-pro#563]
![image](https://user-images.githubusercontent.com/37602470/70012837-a41cce00-15b0-11ea-8937-1e3c26058879.png)
刷新前，如上
![image](https://user-images.githubusercontent.com/37602470/70012859-b26aea00-15b0-11ea-816c-5aae77e6a577.png)
刷新后，如上

**Comment by sendya** [comment]
默认无法实现，也不属于 bug。请自行改造。
