### ISSUE TITLE
ant design 如何引入静态html文件？

### ISSUE THREAD

**Issue by MiyaHeGH** [vueComponent/ant-design-vue-pro#564]
![image](https://user-images.githubusercontent.com/41277143/70021834-008de680-15cd-11ea-9c36-8b84c42a397b.png)
![image](https://user-images.githubusercontent.com/41277143/70021901-3501a280-15cd-11ea-89b6-f413e210789b.png)
地址是对的,但一直报错，好像是路由问题，请大神指教

**Comment by sendya** [comment]
vue 不存在引入静态 html 文件之说。你这只是普通的访问静态文件，具体 mdn 或者百度查怎么访问静态资源。pro 不对这些做处理

**Comment by MiyaHeGH** [comment]
那怎么可以访问静态html文件呢，用vue-cli搭建的脚手架，同样的写法是可以访问的，这里的报错是路由拦截或限制了什么吗？

**Comment by sendya** [comment]
你用的什么路由模式

**Comment by MiyaHeGH** [comment]
history模式，静态文件是放在public下，路径用的public下的绝对路径

**Comment by sendya** [comment]
不行吧，会被 vue-router 当作是路由。用 hash 模式

**Comment by MiyaHeGH** [comment]
解决了，非常感谢！
