### ISSUE TITLE
STable 如何让表格跳转到指定页

### ISSUE THREAD

**Issue by csnan** [vueComponent/ant-design-vue-pro#566]

**Comment by csnan** [comment]
就我想让 tab 切换表格的时候让表格回到第一页

**Comment by sendya** [comment]
https://pro.loacg.com/components/s-table

![image](https://user-images.githubusercontent.com/5404542/70106643-27a4f080-167f-11ea-90c6-63640dd0d5ef.png)

----

如果要重载时，控制参数，请自行你自己的 loadData 中 ajax 请求带上参数
