### ISSUE TITLE
MultiTab组件同一个路由，带不同参数就会新开一个tab标签页

### ISSUE THREAD

**Issue by RunningV** [vueComponent/ant-design-vue-pro#568]
**Question （问题描述）**
MultiTab组件同一个路由  ```/baseinfo/person-info-detail?id=123```,只要id不同就会新增一个tab标签页

**Describe the solution you'd like （你期待的是什么？）**
这个组件这样实现也没问题，但是我想点列表页进详情传不同的参数，只保留一个详情页tab标签，这样的需求场景也是很常见的，不然列表页不是有多少条，就打开多少详情页tab标签吗？

**Comment by sendya** [comment]
不在提供 multi-tab 新功能维护，请自行处理
