### ISSUE TITLE
页面缩放后，confirm显示不正常

### ISSUE THREAD

**Issue by hhxyjsj** [vueComponent/ant-design-vue-pro#57]
如题，当缩放页面宽度小于750px时
<img width="1438" alt="a" src="https://user-images.githubusercontent.com/31506377/51229429-64002d00-1997-11e9-9edf-1f8d7f7699cf.png">

**Comment by sendya** [comment]
confirm 的什么地方 显示不正常

**Comment by sendya** [comment]
应该是识别到 Grid `sm` 栅格为手机模式。自动拉伸到全屏了把。不影响
