### ISSUE TITLE
table组件修改展开图标expandIcon不起效果

### ISSUE THREAD

**Issue by lovehebe330** [vueComponent/ant-design-vue-pro#570]
**Question （问题描述）**
How to use component `s-table` paging
![gaitubao_expandIcon_jpg](https://user-images.githubusercontent.com/20655248/70302805-ee17e500-1838-11ea-9e64-bff364bc2d04.jpg)

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
@expandIcon 事件？？

**Comment by lovehebe330** [comment]
> @expandIcon 事件？？

奥改了上面是:expandIcon="expandIcon"  底下是
expandIcon (props) {
      return ( <a-icon type="right" /> )
  },
但改了之后展开事件不生效了？？？

**Comment by sendya** [comment]
https://codesandbox.io/s/antd-table-expandicon-7m8sm

**Comment by lovehebe330** [comment]
> https://codesandbox.io/s/antd-table-expandicon-7m8sm

![image](https://user-images.githubusercontent.com/20655248/70313776-33481100-1851-11ea-8ff9-4e5e75f28ef9.png)
但是onExpand目测会覆盖上面的expand展开图标的事件，展开的时候没看到接口调用。

**Comment by lovehebe330** [comment]
> https://codesandbox.io/s/antd-table-expandicon-7m8sm

想要在这个onExpand事件里做一些其它的事情，比如调用接口，但发现如果覆盖原来的onExpandshi j事件的话点击图标的话就展不开了，怎么覆盖了onExpand事件之后触发展开的事件呢？
![gaitubao_expand_jpg](https://user-images.githubusercontent.com/20655248/70504007-b1f9c280-1b5f-11ea-9d56-3afd72b44d65.jpg)
