### ISSUE TITLE
去除登录页面和相关的路由,为什么会报错?

### ISSUE THREAD

**Issue by zhichao8756** [vueComponent/ant-design-vue-pro#571]
项目不需要登录页面,我把登录相关的路由配置信息注释:
![image](https://user-images.githubusercontent.com/24514251/70409754-e0a46a00-1a87-11ea-8b87-4bc8790c3ec8.png)
是不是进入了一个死循环,页面报错如下:
![image](https://user-images.githubusercontent.com/24514251/70409775-f3b73a00-1a87-11ea-8f51-4a7cff35bd2a.png)

**Comment by sendya** [comment]
https://pro.loacg.com/docs/remove-authority-management

**Comment by zhichao8756** [comment]
已解决,是权限的问题
