### ISSUE TITLE
s-table 组件@expand 事件无效

### ISSUE THREAD

**Issue by keroes000** [vueComponent/ant-design-vue-pro#572]
**Question （问题描述）**
How to use component `s-table` paging

在S-TABLE组件使用@Expand无效

**Describe the solution you'd like （你期待的是什么？）**

沿用a-table组件的事件

**Additional context（附加信息）**

`    <s-table
      size="default"
      :columns="columns"
      :data="loadData"
      @expand="expand"
    >`
`   expand () {
      alert(1)
    }`

**Comment by sendya** [comment]
复杂功能建议直接使用 a-table
