### ISSUE TITLE
ant-design-pro-vue 如何关闭 eslint

### ISSUE THREAD

**Issue by tgy3300** [vueComponent/ant-design-vue-pro#573]
error found.
error potentially fixable with the `--fix` option.

动不支就出现这错误，能不能闭关 eslint

**Comment by sendya** [comment]
https://segmentfault.com/a/1190000019674350

[Search: cn.bing.com/search?q=vue-cli3关闭eslint](https://cn.bing.com/search?q=vue-cli3+%E5%85%B3%E9%97%AD+eslint&form=ANNNB1&refig=c27f348936bf49a4b4094d728e83fb2b&mkt=zh-cn&sp=-1&pq=vue-cli3+%E5%85%B3%E9%97%AD&sc=0-11&qs=n&sk=&cvid=c27f348936bf49a4b4094d728e83fb2b)

**Comment by tgy3300** [comment]
> https://segmentfault.com/a/1190000019674350
> 
> [Search: cn.bing.com/search?q=vue-cli3关闭eslint](https://cn.bing.com/search?q=vue-cli3+%E5%85%B3%E9%97%AD+eslint&form=ANNNB1&refig=c27f348936bf49a4b4094d728e83fb2b&mkt=zh-cn&sp=-1&pq=vue-cli3+%E5%85%B3%E9%97%AD&sc=0-11&qs=n&sk=&cvid=c27f348936bf49a4b4094d728e83fb2b)

我关了，还是会出现，但没有那么严格，，我代码缩进4   5   个空格就会出现这错误

**Comment by brave2017** [comment]
删除.eslintrc.js 文件中的 @vue/standard
