### ISSUE TITLE
多tab模式下，某个路由页面如何多开？

### ISSUE THREAD

**Issue by xs06974** [vueComponent/ant-design-vue-pro#574]
在多tab模式下，有一个常见多应用场景就是有一个路由/list到列表页， 列表页点击每一行， 就路由到/item?itemId=xxx，新开一个tab页展示详情，这在企业管理平台是很常见多一个需求；但我实测下来发现，详情页只会第一次执行初始化，获取this.$route.query.xxxId, 然后初始化详情数据； 后续打开的详情页tab不再执行初始化。这个如何解决？

**Comment by sendya** [comment]
无法支持，目前也没规划继续支持 multi-tab 组件的更新。麻烦请自行设计该组件
