### ISSUE TITLE
如何取消构建版本请求cdn

### ISSUE THREAD

**Issue by chy89310** [vueComponent/ant-design-vue-pro#575]
**Question （问题描述）**
使用 npm run build 之后运行 dist 目录下的网站，vue.min.js 请求的是 cdn 的路径，但我的应用是部署在内网环境的，想问怎么取消这个 cdn 的设定？

**Describe the solution you'd like （你期待的是什么？）**
不请求 cdn 路径，只使用 dist 内的静态文件

**Additional context（附加信息）**
我尝试过删除 vue.config.js 以下的代码，但不知道为什么还是请求 cdn 的路径
```
if (isProd()) {
  config.plugin('html').tap(args => {
    args[0].cdn = assetsCDN
    return args
  })
}
```

**Comment by edenleung** [comment]
你可能要修改下
https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L38

```js
  //  externals: isProd ? assetsCDN.externals : {}
  externals: {}
```

**Comment by sendya** [comment]
还有这个
https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L61-L68

**Comment by chy89310** [comment]
> 你可能要修改下
> https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L38
> 
> ```js
>   //  externals: isProd ? assetsCDN.externals : {}
>   externals: {}
> ```

解决我的问题了！谢谢

**Comment by happydele** [comment]
请问如果想彻底去除cdn, 应该修改哪些文件
