### ISSUE TITLE
我参看了iview admin pro,觉得那样的排版好看一些，作者可以参考一下

### ISSUE THREAD

**Issue by pony5551** [vueComponent/ant-design-vue-pro#576]
我自己先调理了一下，不是太理想

![QQ图片20191212020856](https://user-images.githubusercontent.com/36391163/70647643-642aaa80-1c84-11ea-8472-3790713564cb.png)

**Comment by pony5551** [comment]
我觉得这个好看

![QQ图片20191212021032](https://user-images.githubusercontent.com/36391163/70647732-9b00c080-1c84-11ea-9067-e9225e7e1d42.png)

**Comment by pony5551** [comment]
多页签也可以固定

**Comment by sendya** [comment]
本项目是按照 react antd 的布局开发的，并保持界面样式同步。人手不足暂不考虑其他方案。你可以自行修改使用
