### ISSUE TITLE
缺少eslintric.js文件， 导致项目无法运行

### ISSUE THREAD

**Issue by lm356536** [vueComponent/ant-design-vue-pro#579]
**Describe the bug （描述 Bug）**

新克隆一个项目，没法跑起来

**To Reproduce （重现步骤）**
项目克隆好后
1. git clone https://github.com/sendya/ant-design-pro-vue.git 
2. yarn install
3. yarn  run serve

**Expected behavior（你期待的是什么?）**
页面正常显示

**Screenshots（截图）**

```
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
```

**Desktop (please complete the following information):**

 - OS: macOs 10.15.2
 - Browser:  chrome
 - Version: 79.03

**Additional context（附加信息）**
由于克隆下来的项目缺少eslintrc.js文件，导致项目启动不了

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/.eslintrc.js 不是有吗？

**Comment by lm356536** [comment]
尴尬， 昨天用命令和用工具克隆都没有把eslintrc.js克隆下来。 今天又好了。
