### ISSUE TITLE
关于.js和.vue文件格式化的问题 

### ISSUE THREAD

**Issue by xiaopengRUNNING** [vueComponent/ant-design-vue-pro#582]
没有做任何修改，在格式化.js文件的时候函数 test (ttt) {}会变成 test(ttt) {} 并且报错，添加空格后错误消失，.vue文件格式化就会有的标签末尾会多出一个空格和/ `<count-down
        style="font-size: 2rem"
        :target="new Date().getTime() + 3000000"
        :on-end="onEndHandle">
      </count-down>`这样的代码会变成一排，页面报错

**Comment by sendya** [comment]
格式化问题请自行处理，每个人用的 IDE 并不统一，只要按照 eslint 的格式化规范来即可。相关请自行百度
