### ISSUE TITLE
i18n 国际化实现

### ISSUE THREAD

**Issue by yorcent** [vueComponent/ant-design-vue-pro#585]
** 官网给出的国际化方案中，lang分支的地址不存在。在git 仓库中找到了feat/i18n的分支，但是没有merge，大致浏览了一下diff的代码，猜想应该是还没有实现。
想请问下，i18n国际化的分支或者说功能还会进一步实现吗？
@sendya

**Comment by witterlee** [comment]
i18nfeat/i18n分支展示的很清晰了，剩下不就是对文本进行vuei18n的使用吗？  $t("messageKey")，自已组合多语言文件定义就可以了。
