### ISSUE TITLE
router-view-table分支登录不上去

### ISSUE THREAD

**Issue by shen278007970** [vueComponent/ant-design-vue-pro#586]
**Describe the bug （描述 Bug）**
router-view-table分支登录
Proxy error: Could not proxy request /api/auth/login from localhost:8080 to https://mock.ihx.me/mock/5baf3052f7da7e07e04a5116/antd-pro (ETIMEDOUT).

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
按照主分支修改 vue.config 里的 devServer 配置，并且引入一份 src/mock 即可
