### ISSUE TITLE
EN translation not working.

### ISSUE THREAD

**Issue by parfumix** [vueComponent/ant-design-vue-pro#588]
**Describe the bug （描述 Bug）**

By accessing documentation in english I got error.

**To Reproduce （重现步骤）**

1. Go to 'https://pro.loacg.com/docs/new-page'
2. Click on 'English'

**Screenshots（截图）**
![Screenshot 2019-12-18 at 14 28 54](https://user-images.githubusercontent.com/6368534/71086604-f8c06b80-21a2-11ea-8de6-9a3a18df59a2.png)

**Comment by Acris** [comment]
文档尚未完成，欢迎PR。

**Comment by Acris** [comment]
The document isn't completed yet, all contributions are welcome.

**Comment by jjandxa** [comment]
This is not completed document. please contributions pull requests.
