### ISSUE TITLE
日期选择组件，带时分秒的，实际数据：小时不准

### ISSUE THREAD

**Issue by nbin2008** [vueComponent/ant-design-vue-pro#591]
```
<a-date-picker showTime v-model="quotation_time" />
```
使用日期组件，带时分秒，用v-model这种方式获取的，页面显示正常，但是实际拿到的数据，小时数据不准，是否是不支持 v-model 这种方式？
比如：我选择的是：2019-12-19 17:32:45
但quotation_time实际的是：Fri Dec 20 2019 01:32:45 GMT+0800 (中国标准时间)

**Comment by sendya** [comment]
没有你说的问题
![image](https://user-images.githubusercontent.com/5404542/71222150-620ebe80-230a-11ea-91a5-2e3bc11d6c90.png)

https://codesandbox.io/s/sparkling-cache-v4plt

 另外， 你的 issue 发错 repo 了

**Comment by nbin2008** [comment]
> 没有你说的问题
> ![image](https://user-images.githubusercontent.com/5404542/71222150-620ebe80-230a-11ea-91a5-2e3bc11d6c90.png)
> 
> https://codesandbox.io/s/sparkling-cache-v4plt
> 
> 另外， 你的 issue 发错 repo 了

参考了demo，仔细对比了下代码，对不起，实在抱歉，我之前的format写的是'YYYY-MM-DD h:mm:ss'，少了一个h，天坑，打扰了 。。。
