### ISSUE TITLE
异步获取路由匹配不上基础页面 layout  (generator-routers.js)

### ISSUE THREAD

**Issue by shen278007970** [vueComponent/ant-design-vue-pro#592]
**Question （问题描述）**
import { BasicLayout, RouteView, BlankLayout, PageView } from '@/layouts'
console.log(BasicLayout, '==>BasicLayout', BlankLayout, '===>BlankLayout')

打印结果为:
undefined "==>BasicLayout" {name: "BlankLayout", staticRenderFns: Array(0), _compiled: true, _scopeId: "data-v-5291c0af", render: ƒ, …}name: "BlankLayout"render: ƒ ()staticRenderFns: []_compiled: true_scopeId: "data-v-5291c0af"beforeCreate: [ƒ]beforeDestroy: [ƒ]__file: "src/layouts/BlankLayout.vue"__proto__: Object "===>BlankLayout"

**Describe the solution you'd like （你期待的是什么？）**
不明白这里有的layout为什么会是undefind

**Additional context（附加信息）**
 */
export const generatorDynamicRouter = (token) => {
  console.log(constantRouterComponents, 'constantRouterComponents')
  return new Promise((resolve, reject) => {
    loginService.getCurrentUserNav(token).then(res => {
      const result = res.data
      const menuNav = []
      const childrenNav = []
      //      后端数据, 根级树数组,  根级 PID
      listToTree(result, childrenNav, 0)
      rootRouter.children = childrenNav
      menuNav.push(rootRouter)
      console.log('menuNav', menuNav)
      const routers = generator(menuNav)
      routers.push(notFoundRouter)
      console.log('routers', routers)
      resolve(routers)
    }).catch(err => {
      reject(err)
    })
  })
}

调用接口时我打印constantRouterComponents
{BasicLayout: undefined, BlankLayout: {…}, RouteView: undefined, PageView: undefined, 403: ƒ, 404: ƒ, 500: ƒ, Workplace: ƒ, …}403: ƒ _()404: ƒ _()500: ƒ _()BasicLayout: undefinedBlankLayout: {name: "BlankLayout", staticRenderFns: Array(0), _compiled: true, _scopeId: "data-v-5291c0af", render: ƒ, …}RouteView: undefinedPageView: undefinedWorkplace: ƒ Workplace()Analysis: ƒ Analysis()BasicForm: ƒ BasicForm()StepForm: ƒ StepForm()AdvanceForm: ƒ AdvanceForm()TableList: ƒ TableList()StandardList: ƒ StandardList()CardList: ƒ CardList()SearchLayout: ƒ SearchLayout()SearchArticles: ƒ SearchArticles()SearchProjects: ƒ SearchProjects()SearchApplications: ƒ SearchApplications()ProfileBasic: ƒ ProfileBasic()ProfileAdvanced: ƒ ProfileAdvanced()ResultSuccess: ƒ ResultSuccess()ResultFail: ƒ ResultFail()Exception403: ƒ Exception403()Exception404: ƒ Exception404()Exception500: ƒ Exception500()AccountCenter: ƒ AccountCenter()AccountSettings: ƒ AccountSettings()BaseSettings: ƒ BaseSettings()SecuritySettings: ƒ SecuritySettings()CustomSettings: ƒ CustomSettings()BindingSettings: ƒ BindingSettings()NotificationSettings: ƒ NotificationSettings()__proto__: Object "constantRouterComponents"

这里undefind导致动态匹配路由一直失败,有没有大佬遇到过,能帮忙解决下,谢谢!

**Comment by sendya** [comment]
我也不明白你这个 console.log 是什么意思
能否提供复现？
或者描述清楚，这么做是为了什么

**Comment by shen278007970** [comment]
> 我也不明白你这个console.log是什么意思
> 能否提供复现？
> 或者描述清楚，这样做是为了什么

因为在构建路由是要匹配对应的component   但是constantRouterComponents[item.component || item.key],这里匹配的一直是undefind  在构建constantRouterComponents这个对象时,基本layout属性的值一直是undefind
export const generator = (routerMap, parent) => {
  return routerMap.map(item => {
      name: item.name || item.key || '',
      // 该路由对应页面的 组件 :方案1
      component: constantRouterComponents[item.component || item.key],
      // 该路由对应页面的 组件 :方案2 (动态加载)
      // component: constantRouterComponents[item.component || item.key] || () => import(`@/views/${item.component}`),

      // meta: 页面标题, 菜单图标, 页面权限(供指令权限用，可去掉)
      meta: { title: title, icon: icon || undefined, hiddenHeaderContent: hiddenHeaderContent, target: target, permission: item.name }
    }

**Comment by shen278007970** [comment]
> 我也不明白你这个 console.log 是什么意思
> 能否提供复现？
> 或者描述清楚，这么做是为了什么
我发现当我修改了右上角UserMenu.vue文件以后,上面我说的引入layout就会出错
这是我修改后的内容
`<template>
  <div class="user-wrapper">
    <div class="content-box">
      
      
      
      
      
      
      <a-dropdown>
        <span class="action ant-dropdown-link user-dropdown-menu" >
          <a-avatar class="avatar" size="small" :src="avatar()"/>
          <span>{{ nickname() }}</span>
        </span>
        <a-menu slot="overlay" class="user-dropdown-menu-wrapper">
          <a-menu-item key="0">
            <a href="javascript:;" @click="showModal('password')">
              <span>修改密码</span>
            </a>
          </a-menu-item>
          <a-menu-item key="1">
            <a href="javascript:;" @click="showModal('passphrase')">
              <span>修改口令</span>
            </a>
          </a-menu-item>
          <a-menu-item key="3">
            <a href="javascript:;" @click="handleLogout">
              <span>退出登录</span>
            </a>
          </a-menu-item>
        </a-menu>
        <a-modal
          :title="title"
          :visible="Boolean(title)"
          :confirmLoading="confirmLoading"
          destroyOnClose
          @cancel="handleCancel"
          @ok="handleOk"
        >
          <a-spin :spinning="confirmLoading">
            <a-form :form="form" v-if="title==='修改密码'">
              <a-form-item
                label="原密码"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入原密码"
                  v-decorator="['password',
                                {
                                  rules: [
                                    { required: true, message: '请输入原密码' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="新密码"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入8-20位数字和字母的组合"
                  v-decorator="['new_password',
                                {
                                  rules: [
                                    { required: true, message: '请输入新密码' },
                                    {pattern: /^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,20}$/,message: '密码格式不正确' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="确认密码"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请再次输入密码"
                  v-decorator="['affirmPassword',
                                {
                                  rules: [
                                    { required: true, message: '请确认新密码' },
                                    { validator: validPassword },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
            </a-form>
            <a-form :form="form" v-if="title==='修改口令'">
              <a-form-item
                label="原口令"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入原口令"
                  v-decorator="['oldPassphrase',
                                {
                                  rules: [
                                    { required: true, message: '请输入原口令' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="新口令"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入4位数字新口令"
                  v-decorator="['newPassphrase',
                                {
                                  rules: [
                                    { required: true, message: '请输入新口令' },
                                    {pattern: /^\d{4}$/,message: '口令格式不正确' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="确认口令"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请再次输入口令"
                  v-decorator="['affirmPassphrase',
                                {
                                  rules: [
                                    { required: true, message: '请确认新口令' },
                                    { validator: validPassphrase },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
            </a-form>
          </a-spin>
        </a-modal>
      </a-dropdown>
    </div>
  </div>
</template>

<script>
import NoticeIcon from '@/components/NoticeIcon'
// import userModal from './userModal'
import { mapActions, mapGetters } from 'vuex'
import { userPasswordEdit, userCommandEdit } from '@/api/login'

export default {
  name: 'UserMenu',
  components: {
    NoticeIcon
  },
  data () {
    return {
      loading: '',
      formItemLayout: {
        labelCol: {
          span: 6
        },
        wrapperCol: {
          span: 16
        }
      },
      visible: false,
      confirmLoading: false,
      form: this.$form.createForm(this),
      title: ''
    }
  },
  methods: {
    ...mapActions(['Logout']),
    ...mapGetters(['nickname', 'avatar']),
    handleLogout () {
      const that = this

      this.$confirm({
        title: '提示',
        content: '真的要注销登录吗 ?',
        onOk () {
          that.Logout().then(() => {
            that.$router.push({ name: 'login' })
          })
        },
        onCancel () {
        }
      })
    },
    showModal (type) {
      this.visible = true
      if (type === 'password') {
        this.title = '修改密码'
      } else if (type === 'passphrase') {
        this.title = '修改口令'
      }
    },
    handleCancel () {
      this.title = ''
      this.confirmLoading = false
    },

    handleOk (e) {
      const { form: { validateFields }, title } = this
      validateFields((errors, values) => {
        if (!errors) {
          this.confirmLoading = true
          if (title === '修改密码') {
            const data = { ...values }
            // userPasswordEdit(data)
            //   .then((res) => {
            //     this.$message.success(res.msg)
            //     /* 退出登录 */
            //     this.Logout().then(() => {
            //       this.$router.push({ name: 'login' })
            //     })
            //   })
            //   .catch(err => console.log(err))
            //   .finally(() => {
            //     this.confirmLoading = false
            //   })
          }
          if (title === '修改口令') {
            const data = { ...values }
            // userCommandEdit(data)
            //   .then((res) => {
            //     this.$message.success(res.msg)
            //     /* 退出登录 */
            //     this.Logout().then(() => {
            //       this.$router.push({ name: 'login' })
            //     })
            //   })
            //   .catch(err => console.log(err))
            //   .finally(() => {
            //     this.confirmLoading = false
            //   })
          }
        } else {
          console.log(errors)
        }
      })
    },
    /* 验证确认密码 */
    validPassword (rule, value, callback) {
      const new_password = this.form.getFieldValue('new_password')
      if (value) {
        /* 发请求验证是否为唯一账户 */
        if (!new_password) {
          callback('请先输入新密码')
        }
        if (new_password !== value) {
          callback('确认密码与新密码不一致!')
        }
      }
      callback()
    },
    /* 验证确认口令 */
    validPassphrase (rule, value, callback) {
      const newPassphrase = this.form.getFieldValue('newPassphrase')
      if (value) {
        /* 发请求验证是否为唯一账户 */
        if (!newPassphrase) {
          callback('请先输入新口令')
        }
        if (newPassphrase !== value) {
          callback('确认口令与新口令不一致!')
        }
      }
      callback()
    }
  }
}
</script>
`

**Comment by shen278007970** [comment]
<template>
  <div class="user-wrapper">
    <div class="content-box">
      
      
      
      
      
      
      <a-dropdown>
        <span class="action ant-dropdown-link user-dropdown-menu" >
          <a-avatar class="avatar" size="small" :src="avatar()"/>
          <span>{{ nickname() }}</span>
        </span>
        <a-menu slot="overlay" class="user-dropdown-menu-wrapper">
          <a-menu-item key="0">
            <a href="javascript:;" @click="showModal('password')">
              <span>修改密码</span>
            </a>
          </a-menu-item>
          <a-menu-item key="1">
            <a href="javascript:;" @click="showModal('passphrase')">
              <span>修改口令</span>
            </a>
          </a-menu-item>
          <a-menu-item key="3">
            <a href="javascript:;" @click="handleLogout">
              <span>退出登录</span>
            </a>
          </a-menu-item>
        </a-menu>
        <a-modal
          :title="title"
          :visible="Boolean(title)"
          :confirmLoading="confirmLoading"
          destroyOnClose
          @cancel="handleCancel"
          @ok="handleOk"
        >
          <a-spin :spinning="confirmLoading">
            <a-form :form="form" v-if="title==='修改密码'">
              <a-form-item
                label="原密码"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入原密码"
                  v-decorator="['password',
                                {
                                  rules: [
                                    { required: true, message: '请输入原密码' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="新密码"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入8-20位数字和字母的组合"
                  v-decorator="['new_password',
                                {
                                  rules: [
                                    { required: true, message: '请输入新密码' },
                                    {pattern: /^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,20}$/,message: '密码格式不正确' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="确认密码"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请再次输入密码"
                  v-decorator="['affirmPassword',
                                {
                                  rules: [
                                    { required: true, message: '请确认新密码' },
                                    { validator: validPassword },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
            </a-form>
            <a-form :form="form" v-if="title==='修改口令'">
              <a-form-item
                label="原口令"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入原口令"
                  v-decorator="['oldPassphrase',
                                {
                                  rules: [
                                    { required: true, message: '请输入原口令' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="新口令"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请输入4位数字新口令"
                  v-decorator="['newPassphrase',
                                {
                                  rules: [
                                    { required: true, message: '请输入新口令' },
                                    {pattern: /^\d{4}$/,message: '口令格式不正确' },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
              <a-form-item
                label="确认口令"
                v-bind="formItemLayout"
                hasFeedback
              >
                <a-input
                  type="password"
                  placeholder="请再次输入口令"
                  v-decorator="['affirmPassphrase',
                                {
                                  rules: [
                                    { required: true, message: '请确认新口令' },
                                    { validator: validPassphrase },
                                  ]
                                }
                  ]"
                />
              </a-form-item>
            </a-form>
          </a-spin>
        </a-modal>
      </a-dropdown>
    </div>
  </div>
</template>

<script>
import NoticeIcon from '@/components/NoticeIcon'
// import userModal from './userModal'
import { mapActions, mapGetters } from 'vuex'
import { userPasswordEdit, userCommandEdit } from '@/api/login'

export default {
  name: 'UserMenu',
  components: {
    NoticeIcon
  },
  data () {
    return {
      loading: '',
      formItemLayout: {
        labelCol: {
          span: 6
        },
        wrapperCol: {
          span: 16
        }
      },
      visible: false,
      confirmLoading: false,
      form: this.$form.createForm(this),
      title: ''
    }
  },
  methods: {
    ...mapActions(['Logout']),
    ...mapGetters(['nickname', 'avatar']),
    handleLogout () {
      const that = this

      this.$confirm({
        title: '提示',
        content: '真的要注销登录吗 ?',
        onOk () {
          that.Logout().then(() => {
            that.$router.push({ name: 'login' })
          })
        },
        onCancel () {
        }
      })
    },
    showModal (type) {
      this.visible = true
      if (type === 'password') {
        this.title = '修改密码'
      } else if (type === 'passphrase') {
        this.title = '修改口令'
      }
    },
    handleCancel () {
      this.title = ''
      this.confirmLoading = false
    },

    handleOk (e) {
      const { form: { validateFields }, title } = this
      validateFields((errors, values) => {
        if (!errors) {
          this.confirmLoading = true
          if (title === '修改密码') {
            const data = { ...values }
            // userPasswordEdit(data)
            //   .then((res) => {
            //     this.$message.success(res.msg)
            //     /* 退出登录 */
            //     this.Logout().then(() => {
            //       this.$router.push({ name: 'login' })
            //     })
            //   })
            //   .catch(err => console.log(err))
            //   .finally(() => {
            //     this.confirmLoading = false
            //   })
          }
          if (title === '修改口令') {
            const data = { ...values }
            // userCommandEdit(data)
            //   .then((res) => {
            //     this.$message.success(res.msg)
            //     /* 退出登录 */
            //     this.Logout().then(() => {
            //       this.$router.push({ name: 'login' })
            //     })
            //   })
            //   .catch(err => console.log(err))
            //   .finally(() => {
            //     this.confirmLoading = false
            //   })
          }
        } else {
          console.log(errors)
        }
      })
    },
    /* 验证确认密码 */
    validPassword (rule, value, callback) {
      const new_password = this.form.getFieldValue('new_password')
      if (value) {
        /* 发请求验证是否为唯一账户 */
        if (!new_password) {
          callback('请先输入新密码')
        }
        if (new_password !== value) {
          callback('确认密码与新密码不一致!')
        }
      }
      callback()
    },
    /* 验证确认口令 */
    validPassphrase (rule, value, callback) {
      const newPassphrase = this.form.getFieldValue('newPassphrase')
      if (value) {
        /* 发请求验证是否为唯一账户 */
        if (!newPassphrase) {
          callback('请先输入新口令')
        }
        if (newPassphrase !== value) {
          callback('确认口令与新口令不一致!')
        }
      }
      callback()
    }
  }
}
</script>

**Comment by pylixm** [comment]
+1  @since2006  求解决思路或问题
