### ISSUE TITLE
帮助文档，移动端无法正常浏览

### ISSUE THREAD

**Issue by witterlee** [vueComponent/ant-design-vue-pro#594]
**Is your feature request related to a problem? Please describe.**
做的很赞，感谢开源贡献。 目前在移动端看文档时，文档内容被菜单挡住，菜单没有折叠功能导致内容无法阅读

**Describe the solution you'd like**
期望增加移动端支持，增加一个菜单折叠即可
**Describe alternatives you've considered**

**Additional context**

**Comment by sendya** [comment]
目前不支持移动端访问

**Comment by witterlee** [comment]
了解了，感谢回复。期待未来能支持
