### ISSUE TITLE
该路由对应页面的 组件 :方案2 (动态加载)

### ISSUE THREAD

**Issue by ipanocloud** [vueComponent/ant-design-vue-pro#595]
// 该路由对应页面的 组件 :方案2 (动态加载)
      component: constantRouterComponents[item.component || item.key] || () => import(`@/views/${item.component}`),

组件动态加载注释去掉后,貌似编译时大量报错  是不是语法有问题

**Comment by sendya** [comment]
请问 大量报什么错

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/commit/0f096d4e5f3ebd050c2113fddf184cb6f0eb6570
