### ISSUE TITLE
二级路由页面@onclick跳转到三级菜单

### ISSUE THREAD

**Issue by ipanocloud** [vueComponent/ant-design-vue-pro#598]
**Question （问题描述）**
二级路由页面@onclick跳转到三级菜单(隐藏)时,url以及导航面包屑发生变化,但是content仍然是二级菜单content
[![lia6wF.md.png](https://s2.ax1x.com/2019/12/25/lia6wF.md.png)](https://imgchr.com/i/lia6wF)

[![liax6P.md.png](https://s2.ax1x.com/2019/12/25/liax6P.md.png)](https://imgchr.com/i/liax6P)

**Comment by ipanocloud** [comment]
@sendya

**Comment by sendya** [comment]
放到同级

**Comment by sendya** [comment]
或者二级路由页面有 router-view 。没 router-view 怎么显示页面？具体自行查询 vue-router 官方文档

**Comment by Nicky213Zhang** [comment]
> 放到同级

也碰到类似的问题，之前一直是放在同级的，也试过添加router-view组件。同级的问题就是面包屑无法满足上下级样式，作者能不能给一个完美的方案
