### ISSUE TITLE
请问一下有没有后端接口是用的graphql

### ISSUE THREAD

**Issue by xiaopengRUNNING** [vueComponent/ant-design-vue-pro#599]
**Question （问题描述）**
我现在的问题是通过graphql能够查询到数据，并且能够在`<a-table>`标签中显示，但是经过封装的`<s-table>`标签中不知道如何显示，这个问题想了好久了。

期待回复

感谢

**Comment by sendya** [comment]
没有，你可以自己封装
也可以选择不用 stable，本来就是可选的强业务定制组组件

**Comment by xiaopengRUNNING** [comment]
那我试试

感谢
