### ISSUE TITLE
request.js 文件依赖import store from '@/store'，会导致编译循环依赖RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by BarronLin** [vueComponent/ant-design-vue-pro#6]
比如把这个import { getRoleList, getServiceList } from '@/api/manage' 放到任何一个vue文件引用，都会报错。

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/commit/06303db3850802290730fb122ee26f30517df637

https://github.com/vuejs/vue-cli/issues/2463

**Comment by sendya** [comment]
经测试没有你描述的问题发生，你可以看一下提交内容。确实有引用到这两个方法，并且这个两个方法的引用在 TableList.vue 也用到了。

https://github.com/sendya/ant-design-pro-vue/commit/72822645a48e422286a788979f9e1ea7bb38ecb8#diff-ff155d4a440197a6f84e8714fd6374e9R153

**Comment by BarronLin** [comment]
> 经测试没有你描述的问题发生，你可以看一下提交内容。确实有引用到这两个方法，并且这个两个方法的引用在 TableList.vue 也用到了。
> 
> [7282264#diff-ff155d4a440197a6f84e8714fd6374e9R153](https://github.com/sendya/ant-design-pro-vue/commit/72822645a48e422286a788979f9e1ea7bb38ecb8#diff-ff155d4a440197a6f84e8714fd6374e9R153)

import { getRoleList, getServiceList } from '@/api/manage' 你可以放到其他page文件，比如workplace.vue 就会编译出上面错误的，作者大大有联系方式可以交流下吗？

**Comment by sendya** [comment]
这是测试代码

https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/dashboard/Workplace.vue#L120

![20181108165652](https://user-images.githubusercontent.com/5404542/48188021-99751280-e377-11e8-8bf0-d3fc08546f46.png)

**Comment by BarronLin** [comment]
> 这是测试代码
> 
> https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/dashboard/Workplace.vue#L120
> 
> ![20181108165652](https://user-images.githubusercontent.com/5404542/48188021-99751280-e377-11e8-8bf0-d3fc08546f46.png)

这是注释掉“你也可以尝试在 request.js 里去掉 import store from '@/store' 以及 21 行的”之后尝试的吗

**Comment by sendya** [comment]
没注释哦，你可以拉完整代码在你本地跑试试
