### ISSUE TITLE
请问下如何能够antv相关依赖

### ISSUE THREAD

**Issue by Xiaohantx** [vueComponent/ant-design-vue-pro#602]
打包后js文件过大，用可视化分析了下好像antv相关依赖很大，但是没有用到这些，所以想请问下如何移除这个依赖，直接卸载会报错...

![](https://cdn.markone.xyz/images/20191226165443.png)

**Comment by sendya** [comment]
`yarn remove @antv/data-set viser-vue` 
or
`npm remove @antv/data-set viser-vue --save`

然后重启，看哪里报错删哪里
