### ISSUE TITLE
采取动态路由时问题

### ISSUE THREAD

**Issue by LiHaodong888** [vueComponent/ant-design-vue-pro#603]
后端生成路由返回给前端,菜单需要点击二次才可以激活,第一次点击没有激活,菜单栏没有激活颜色

**Comment by sendya** [comment]
有代码吗？

**Comment by LiHaodong888** [comment]
按照官网提供的案例进行生成的路由

**Comment by sendya** [comment]
官网提供的案例没有你描述的问题，请提供代码

**Comment by EmiyaYang** [comment]
可能是在路由配置采用相对路径导致的, 我另提一个issue https://github.com/sendya/ant-design-pro-vue/issues/662
