### ISSUE TITLE
能否升级到vue-cli4？

### ISSUE THREAD

**Issue by PineSongCN** [vueComponent/ant-design-vue-pro#604]
vue-cli4已出来一段时间，是否可以升级一下，谢谢

**Comment by sendya** [comment]
你的认知里 vue-cli3 和 vue-cli4 的区别是什么？

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/71503093-bee01b00-28ae-11ea-9c70-45da09c19502.png)


10月21就升级上去了

**Comment by PineSongCN** [comment]
打扰，我的错，我下载代码用了vue upgrade后，某些功能报错，还以为是没适配vue-cli4的原因。
