### ISSUE TITLE
求替换mock的后台demo

### ISSUE THREAD

**Issue by lihua123569** [vueComponent/ant-design-vue-pro#606]
**Question （问题描述）**
mock的数据看不懂，我是个后台开发人员，只能把登录弄出来，那个nav就没看懂了
**Describe the solution you'd like （你期待的是什么？）**
求替换mock的后台demo
**Additional context（附加信息）**
求替换mock的后台demo

**Comment by sendya** [comment]
没有。
看不懂就学着看一下，没什么难度

**Comment by lihua123569** [comment]
我把mock去掉了，用的java后台，登录ok的，这个菜单是会调用下面的方法吗，我断点，没看到调用吗

export function getCurrentUserNav (token) {
  return axios({
    url: '/user/json/nav',
    method: 'get'
  })
}

下面这个方法也没进
/**
 * 动态生成菜单
 * @param token
 * @returns {Promise<Router>}
 */
export const generatorDynamicRouter = (token) => {
	debugger
  return new Promise((resolve, reject) => {
		debugger
    loginService.getCurrentUserNav(token).then(res => {
      console.log('res', res)
      const { result } = res

能给指导个方向吗

**Comment by sendya** [comment]
https://pro.loacg.com/docs/authority-management

**Comment by playsunseek** [comment]
> https://pro.loacg.com/docs/authority-management

请问一下 如果使用动态加载菜单  v-action 和$auth 是不是就不能用了

**Comment by Jovan-Cheng** [comment]
昨天刚拉了新版本的代码，换了Java后台，现已调通，改了几个地方

**Comment by sendya** [comment]
> > https://pro.loacg.com/docs/authority-management
> 
> 请问一下 如果使用动态加载菜单 v-action 和$auth 是不是就不能用了

动态菜单跟权限指令没什么太大关系，没有规定不能使用

**Comment by playsunseek** [comment]
> > > https://pro.loacg.com/docs/authority-management
> > 
> > 
> > 请问一下 如果使用动态加载菜单 v-action 和$auth 是不是就不能用了
> 
> 动态菜单跟权限指令没什么太大关系，没有规定不能使用

指令中看有使用store user下的roles.permissions来鉴权
如果使用动态菜单  假如获取的用户信息中没有role.permissions的信息了（因为使用动态的菜单就不需要根返回的role信息来生成菜单了） 使用接口来获取userNav生成菜单   store中./modules/user.js 中保存的role 也没有了 鉴权的时候就查不到数据。 我的意思是如果使用动态菜单 去掉了用户信息中的role  动态获取菜单的时候是否要把role.permissions 写入到store 下的user.js 中的roles 中 谢谢解答
