### ISSUE TITLE
配置多个代理无法使用

### ISSUE THREAD

**Issue by kuailingmin** [vueComponent/ant-design-vue-pro#607]
**配置多个代理无法使用**

在vue.config文件中配置proxy 里面设置多个地址，但是第一个能调通，第二个就无法调通，一直报404，我用jquery方式调能调通接口 请问这是怎么回事

**To Reproduce （重现步骤）**

1. 进入vue.config.js中找到devServer
2. 在devServer中proxy设置多个系统地址链接
proxy: {
      '/api': {
        target: 'http://....',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      },
      '/yc': {
        target: 'http://...',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/yc': ''
        }
      }
    }

4. Uncaught (in promise) Error: Request failed with status code 404 是不是这样配置，其域名还是走第一个 所以报404，其他路径都是对的，维度这样使用就404

**Expected behavior（你期待的是什么?）**
因为我们业务场景调多个系统接口，接口域名端口等都不一样，所以都能调通

**Screenshots（截图）**

**Desktop (please complete the following information):**
我们使用的pc端项目

**Comment by sendya** [comment]
API 调不通请自行处理，接口我都没办法看，也没办法帮你判断是什么问题

**Comment by Niannian512** [comment]
> API 调不通请自行处理，接口我都没办法看，也没办法帮你判断是什么问题

遇到了同样的问题，在vue.config.js中更换下代理的顺序就好了，不知道是啥原因。。。
