### ISSUE TITLE
首次进入界面时间太久了！

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#61]
大佬， 首次进入界面虽然有加载动画， 可是感觉还是太久了。 可不可以修改成首次进入只加载菜单以及框架最外层的静态文件， 其他都等菜单和整体框框加载完毕， 再加载。

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/docs/load-on-demand.md


然后就是把基础通用依赖提取出来用 CDN
实际上我的 `pro` demo 正常网速基本上就是 2 秒内加载完毕（完全没开启按需加载）
