### ISSUE TITLE
table 集成 vue-draggable-resizable 来实现可伸缩列 错误

### ISSUE THREAD

**Issue by luoliyi** [vueComponent/ant-design-vue-pro#610]
**Question （问题描述）**
在table 集成 vue-draggable-resizable 来实现可伸缩列时，报错Argument name clash 

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
![S9(X$)V$AT4`G9BRUKPDU7I](https://user-images.githubusercontent.com/38175117/71653589-35c25b80-2d68-11ea-9ace-84bd8f84ca84.png)

**Comment by sendya** [comment]
请提供代码

**Comment by luoliyi** [comment]
Module parse failed: Argument name clash (70:29)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   name: "ResizeableTitle",
|   functional: true,
>   render: function render(h, h, props, children) {
|     var thDom = null;
|

 @ ./src/views/indexPage/Index.vue?vue&type=script&lang=js& 1:0-321 1:337-340 1:342-660 1:342-660
 @ ./src/views/indexPage/Index.vue
 @ ./src/config/router.config.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.8.8.128:8000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by TowerLiuFan** [comment]
我也碰到了这个问题，你解决了吗

**Comment by ethan666** [comment]
我也遇到这个问题，报一样的错误

**Comment by luoliyi** [comment]
> 我也碰到了这个问题，你解决了吗

我换了一种实现方式

**Comment by luoliyi** [comment]
> 我也遇到这个问题，报一样的错误

我换了一种实现方式

**Comment by ethan666** [comment]
> > 我也遇到这个问题，报一样的错误
> 
> 我换了一种实现方式

是用 vue-draggable-resizable 吗？

**Comment by luoliyi** [comment]
> > > 我也遇到这个问题，报一样的错误
> > 
> > 
> > 我换了一种实现方式
> 
> 是用 vue-draggable-resizable 吗？

你可以试试vue-easytable

**Comment by ethan666** [comment]
> > > > 我也遇到这个问题，报一样的错误
> > > 
> > > 
> > > 我换了一种实现方式
> > 
> > 
> > 是用 vue-draggable-resizable 吗？
> 
> 你可以试试vue-easytable

好的，多谢

**Comment by ethan666** [comment]
猜测是babel, webpack配置引发的问题。

比较完美的实现：
https://codesandbox.io/s/exciting-sea-d5zsf

有缺陷的实现（table的排序用不了）：
https://www.cnblogs.com/gg_lihui/p/12195778.html?tdsourcetag=s_pctim_aiomsg

**Comment by rockfang** [comment]
同问
