### ISSUE TITLE
页签标题怎么修改

### ISSUE THREAD

**Issue by 772620023** [vueComponent/ant-design-vue-pro#613]
怎么把页签标题修改 或者去掉

**Comment by wugy11** [comment]
![image](https://user-images.githubusercontent.com/3353835/71759308-43055480-2ee6-11ea-866a-308cfcdcd738.png)
这里怎么去掉？

**Comment by sendya** [comment]
https://pro.loacg.com/docs/router-and-nav

**Comment by liuning9** [comment]
楼上的方法就连面包屑也去掉了..1. <page-view :title="false"> 2.简单粗暴 去pageView里修改下代码..
