### ISSUE TITLE
如何在已有的 ant design of vue 项目中使用 ant design pro of vue ?

### ISSUE THREAD

**Issue by Kavf** [vueComponent/ant-design-vue-pro#615]
**Question （问题描述）**
如何在已有的 ant design of vue 项目中使用 ant design pro of vue ?

**Describe the solution you'd like （你期待的是什么？）**
我现在有一个 vue 项目前端已经完成，现在要加入后台界面，想使用 ant design pro of vue，要怎么搞？

**Additional context（附加信息）**
None

**Comment by sendya** [comment]
不清楚你的项目结构，你可以直接把 pro clone 下来，根据你的需要，删除不需要的部分文件即可

**Comment by Kavf** [comment]
哦，果然，我还是不会。。。
