### ISSUE TITLE
s-table使用问题求助

### ISSUE THREAD

**Issue by lijiuhui** [vueComponent/ant-design-vue-pro#616]
**Question （问题描述）**
![image](https://user-images.githubusercontent.com/20593385/71760762-a77fde00-2efd-11ea-818b-524e5de66e35.png)
如上图，如何在左侧分类加载完成之后再请求表格数据？求一个示例，谢谢各位大佬
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
```
load().then(() => {
  this.loadData = // loadTable 的方法
})
```

**Comment by lijiuhui** [comment]
> ```
> load().then(() => {
>   this.loadData = // loadTable 的方法
> })
> ```

早上这样尝试了一波，但是没有效果，并没有重新发起请求

**Comment by lijiuhui** [comment]
> > ```
> > load().then(() => {
> >   this.loadData = // loadTable 的方法
> > })
> > ```
> 
> 早上这样尝试了一波，但是没有效果，并没有重新发起请求

我给loadData赋值了一个匿名函数，但是没起作用

**Comment by sendya** [comment]
那就用 a-table 不要用 s-table

**Comment by qhj1990** [comment]
> > 
> > load().then(() => {
> >   this.loadData = // loadTable 的方法
> > })
> > ```
> 
> 早上这样尝试了一波，但是没有效果，并没有重新发起请求

试一下这个
```
const that = this
load().then(() => {
  that.loadData = // loadTable 的方法
})
```
或者是
this.$refs.table.refresh(true)

**Comment by lijiuhui** [comment]
> > > load().then(() => {
> > > this.loadData = // loadTable 的方法
> > > })
> > 
> > 
> > 早上这样尝试了一波，但是没有效果，并没有重新发起请求
> 
> 试一下这个
> 
> ```
> const that = this
> load().then(() => {
>   that.loadData = // loadTable 的方法
> })
> ```
> 
> 或者是
> this.$refs.table.refresh(true)

谢谢，我已经解决了，解决方法如下：
load.then(() => {
this.loadData = ()=>{....}
})
this.$nextick(()=>{
this.$refs.table.refresh(true)
})
