### ISSUE TITLE
请求帮助：动态加载菜单遇到import导入内容未正常初始化问题

### ISSUE THREAD

**Issue by witterlee** [vueComponent/ant-design-vue-pro#617]
**Question （问题描述）**
在尝试使用动态路由时，generator-routers内部

`import { BasicLayout, BlankLayout, PageView, RouteView } from '@/layouts'
// 前端路由表

const constantRouterComponents = {  
  // 基础页面 layout 必须引入    
  BasicLayout: BasicLayout,  
  BlankLayout: BlankLayout,  
  RouteView: RouteView,  
  PageView: PageView,  
  '403': () => import(/* webpackChunkName: "error" */ '@/views/exception/403'),  
  '404': () => import(/* webpackChunkName: "error" */ '@/views/exception/404'),  
  '500': () => import(/* webpackChunkName: "error" */ '@/views/exception/500')  
}`

![image](https://user-images.githubusercontent.com/4479969/71767830-76c69580-2f4b-11ea-9a4c-cda76e014163.png)
出现一个问题是：都是从layouts导入的，为什么有部分是undefined；（使用官方clone的，在这里加入console,也同样存在这个问题，我不知道是什么导致的）
**Describe the solution you'd like （你期待的是什么？）**
期待应该都是非undefined

**Additional context（附加信息）**
之前尝试多语言时，在locals/index里有一个export const defaultLang=‘zh-CN’，也是类似上边的问题，在其它js文件中import {defaultLang} from  '@/locals/index' 得到的defaultLang 也是undefined.
后来采用了改写为
`export function defaultLang () {
  return 'zh-CN'
}`
的方式解决了。
我不知道这个是什么异常，之前没遇到过这样的问题. 大家有者遇到这样的问题，请帮助给一下大家的处理方式。感谢各位

**Comment by eminoda** [comment]
你可以用 [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin) 在 webpack 构建的时候查看模块之间的依赖问题。

大概是 A import B，B import C，C 又 import A ，在 webpack 构建的时候，这种循环依赖导致拿到 A 引用为空（undefined）。
