### ISSUE TITLE
关于国际化,菜单栏,子菜单的中英文切换是怎么设置的,

### ISSUE THREAD

**Issue by szh941002** [vueComponent/ant-design-vue-pro#618]
直接拉下来feat/i18n分支,我多添加一个子菜单的语言切换,也是设置不了的,

**Comment by witterlee** [comment]
最近刚做了一个支持菜单切换的，分享下经验。 addRouters是存在state的，menu是根据这个数据重新加载的，因此，点击切换语言时，从新生成对应语言的addRouters，在menu component里做一个watch监视这个数据变化，从新load 菜单数据就可以了
