### ISSUE TITLE
打包之后，启动不了。

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#62]
npm run build之后， 打包之后的文件启动不了。

**Comment by java8site** [comment]
我安装yarn之后， 用yarn install 都成功不了。 我试试能正常使用npm install, npm install serve

**Comment by sendya** [comment]
nodejs 环境问题你可能要自己想办法解决。 
yarn 网络好一般没见到失败的。
npm 不建议使用，本项目没提供 npm package.lock 可能 install 会引入到最新依赖导致不能运行，比如最新的 webpack 4.29 就有 bug 会导致整个项目不能 build

**Comment by sendya** [comment]
还有，如果可以的话。issue 请尽量完整提供运行环境信息 log 等。不然你提个问题，我也只能靠猜
