### ISSUE TITLE
antd pro vue 配合 vue-cli-plugin-electron-builder 插件开发桌面应用，成功打包，但运行软件报错

### ISSUE THREAD

**Issue by tgy3300** [vueComponent/ant-design-vue-pro#620]
报错如下：
Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'

**Comment by sendya** [comment]
本项目没对 electron 进行兼容测试，请自行解决

**Comment by tgy3300** [comment]
> 本项目没对 electron 进行兼容测试，请自行解决

求大佬帮忙，，卡在这了，实在不知问题出在哪

**Comment by Neal-Wei** [comment]
> > 本项目没对 electron 进行兼容测试，请自行解决
> 
> 求大佬帮忙，，卡在这了，实在不知问题出在哪

移除antv, 配置webpack-bundle-analyzer查看antv是否被移除，然后用electron打包，至于不能登录，自己找办法
