### ISSUE TITLE
TreeSelect 控件，勾选多个节点时，存在排序错乱问题。

### ISSUE THREAD

**Issue by lizhihui19871127** [vueComponent/ant-design-vue-pro#621]
TreeSelect 控件，勾选多个节点时，存在排序错乱问题。

![image](https://user-images.githubusercontent.com/19592656/71808714-7ba15b80-30a9-11ea-89b0-1fde91a160d5.png)

![image](https://user-images.githubusercontent.com/19592656/71808850-c4f1ab00-30a9-11ea-9fb4-543bfb378898.png)

**Comment by sendya** [comment]
我不知道是否存在这样的问题，请直接前往 https://github.com/vueComponent/ant-design-vue 反馈
