### ISSUE TITLE
当前配置 vue 的相关组件默认使用 CDN

### ISSUE THREAD

**Issue by lwQin** [vueComponent/ant-design-vue-pro#622]
**Question （问题描述）**
当前配置 vue 的相关组件默认使用 CDN，部分仅内网使用系统打包使用会因无法联网导致无法使用。建议默认打包 vue 的相关组件

**Comment by sendya** [comment]
自己屏蔽 CDN 配置即可。本项目确定默认使用 CDN 不做更改
