### ISSUE TITLE
添加完动态路由后，next方法匹配不到路由会白屏不会匹配到*跳转404

### ISSUE THREAD

**Issue by xiaolisheng** [vueComponent/ant-design-vue-pro#624]
**Describe the bug （描述 Bug）**
添加完动态路由后，next方法匹配不到路由会白屏不会匹配到*跳转404

**To Reproduce （重现步骤）**
1、登录跳转push一个不存在的路由
2、接着就会白屏

**Code Here**
原作者代码
```javascript
if (to.path === redirect) {
  // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
  next({ ...to, replace: true });
} else {
  // 跳转到目的路由
  next({ path: redirect });
}
```
更改后代码
```javascript
router.push({path:redirect})
```

**Expected behavior（你期待的是什么?）**
期待作者能解释一下next方法和push方法的区别，我没看过源码，也不知道为什么next方法匹配不到而push方法可以匹配的到。

**Comment by sendya** [comment]
master 仓库的代码是会跳转到 404 的哦。
至于 next 和 push 的区别，请直接去看 vue-router 官方文档即可，描述肯定比我口述来的准确
