### ISSUE TITLE
有没有Ant Design Pro的基础版本呢？方便二次开发

### ISSUE THREAD

**Issue by happydele** [vueComponent/ant-design-vue-pro#627]
你好，wind哥

请问有考虑出一个基础版本吗？Ant Design Pro相当于一个集合方案，用到什么功能直接从中复制过来就行，基础版本适合开发人员直接上手，不用太多去做一些实际项目无关功能组件的删除动作。

类似于vue-template-admin 和 vue-admin-template

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-layout

**Comment by sendya** [comment]
也就删除几个文件，两三分钟的事情，还能顺便理解结构。 何乐而不为

**Comment by happydele** [comment]
好的 wind大大所言极是
