### ISSUE TITLE
请问怎么移除eslint啊这个eslint校验太烦人了

### ISSUE THREAD

**Issue by EForinaJ** [vueComponent/ant-design-vue-pro#628]
![image](https://user-images.githubusercontent.com/22424208/72636371-e0a65c80-3999-11ea-81c7-9b958846363f.png)
不想用eslint，大佬给个移除方案

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/72673108-a8d60c80-3aa0-11ea-9e0f-897b2528f0f3.png)

其余的自行百度
