### ISSUE TITLE
s-table列数过多时，增加:scroll= { x: 1200 }时，页面的搜索文本框输入卡顿

### ISSUE THREAD

**Issue by esinee** [vueComponent/ant-design-vue-pro#631]
**Question （问题描述）**
当页面中s-table组件的列比较多时，加入横向滚动时（左边第一列固定，最右侧两列固定）时，该页面上的搜索框输入文字时会出现卡顿现象，同时页面中弹出的modal表单页的文本框输入内容时也会卡顿；如果把列数减少，卡顿消失。

**Describe the solution you'd like （你期待的是什么？）**
加入横向滚动条时，输入文本框不卡顿

**Additional context（附加信息）**

**Comment by sendya** [comment]
无法解决。请自行想办法，比如懒加载列。减少组件
