### ISSUE TITLE
[i18n] needing i18n when .setDocumentTitle() 

### ISSUE THREAD

**Issue by YogaZong** [vueComponent/ant-design-vue-pro#635]
**Describe the bug （描述 Bug）**

Branch: feat/i18n
There needs globalization when setting title of document 
proposal : `setDocumentTitle(${i18nRender(to.meta.title)} - ${domTitle}`

**Expected behavior（你期待的是什么?）**
As the title

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/App.vue#L18
