### ISSUE TITLE
多选项卡标题栏，方便菜单切换，单页看上去不太符合PC的后管风格

### ISSUE THREAD

**Issue by tkggusraqk** [vueComponent/ant-design-vue-pro#637]
![image](https://user-images.githubusercontent.com/5164663/73652756-8eb44500-46c2-11ea-9ac1-6ce6bc3cda09.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/73823621-a232ed80-4833-11ea-885c-997f76027433.png)
