### ISSUE TITLE
vendor 体积过大

### ISSUE THREAD

**Issue by mcxzyang** [vueComponent/ant-design-vue-pro#639]
从 master 分支拉下来的新代码，直接 yarn build 以后，发现 vendor 目录还有 2.8M 左右，但是我看官网的 vendor 只有 800多K，想请教下是进行什么优化了吗？

**Comment by sendya** [comment]
gzip

**Comment by q27488** [comment]
回答上楼，gzip只能打包出gz文件，虽然是压缩了体积。但是需要做服务端兼容。  本质上还是没解决vendor.js过大的问题！
