### ISSUE TITLE
内联编辑表格，编辑失效

### ISSUE THREAD

**Issue by feifeijin** [vueComponent/ant-design-vue-pro#64]
https://pro.loacg.com/list/edit-table

不能编辑。
实际使用中，是可以感受到变化的。
但最终值被还原了。

**Comment by sendya** [comment]
demo 不提供任何真实修改功能

**Comment by feifeijin** [comment]
> demo 不提供任何真实修改功能

数据并没有和服务器端进行交互。在页面上进行更改时，会有一个变化的过程。大概一帧的时间，然后在页面上面值就被重置了。
