### ISSUE TITLE
如何设置一个兜底图标?

### ISSUE THREAD

**Issue by mogody** [vueComponent/ant-design-vue-pro#640]
**Question （问题描述）**
我们目前的需求是根据用户上传的不同文件类型显示不同的图标, 这个图标都是icon引入的, 由于不可能涵盖全部文件类型, 所以我们有设计的一个默认图标, 但是如何判断我们引入的图标里面, 没有我们想要的?

**Describe the solution you'd like （你期待的是什么？）**
判断icon引入的图标是否有我们需要的, 如果么有显示一个默认图标

**Additional context（附加信息）**
```
const IconFont = Icon.createFromIconfontCN({
  scriptUrl: 'https://at.alicdn.com/t/font_1518964_azk783rcmsd.js'
})

Vue.component('icon-font', IconFont)

<icon-font :type="icon-jpg" :style="{ fontSize: '48px' }" />
```
以上是我们图标的引入方式, 假如说没有 'icon-jpg' 这个图标(icon组件的默认方式是没有的话显示一片空白), 要求显示一个默认的通用文件图标, 这个该怎么实现?

**Comment by sendya** [comment]
你自己引入的东西，你都没办法知道有什么，那我们就更不可能知道有什么了。

你自己引入的 icons 你自己肯定知道有几个 icons ，你要做就是判断一下 icon 在 icons 里有没有，然后分个逻辑去显示你想显示的东西，而不是考虑到我们提供的通用组件上
