### ISSUE TITLE
关于日期组件,编辑回填值绑定v-model无效,问题

### ISSUE THREAD

**Issue by szh941002** [vueComponent/ant-design-vue-pro#641]
关于日期组件,编辑回填值绑定v-model无效,问题

  <a-date-picker @change="handleChange" style="width:100%;" format="YYYY-MM-DD" v-model="left.linewaybillTime">
  </a-date-picker>

TypeError: value.locale is not a function
    at a.render (createPicker.js?fbc9:169)
    at a.e._render (vue.min.js:6)
    at a.r (vue.min.js:6)
    at fn.get (vue.min.js:6)
    at fn.run (vue.min.js:6)
    at un (vue.min.js:6)
    at Array.<anonymous> (vue.min.js:6)
    at qe (vue.min.js:6)

编辑回显,无法回填  查看文档需要使用到moment ,这个具体用法怎么去处理的,求大佬们指导一波

**Comment by sendya** [comment]
import moment from 'moment'

data:   val: moment('2019')
v-modal= val

**Comment by szh941002** [comment]
<a-date-picker @change="handleChange" style="width:100%;" format="YYYY-MM-DD" v-model="linewaybillTime">
            </a-date-picker>

this.linewaybillTime = moment(this.left.linewaybillTime)

这样子的赋值不行,请求回来的的数据回填不了,直接是  invalid date 无穷大勒

> 从“瞬间”导入瞬间
> 
> 数据：val：moment（'2019'）
> v-modal = val


![Uploading image.png…]()

**Comment by sendya** [comment]
你还是学学 Vue 基础去把
