### ISSUE TITLE
富文本在表单里使用的报错

### ISSUE THREAD

**Issue by hepeichun** [vueComponent/ant-design-vue-pro#643]
我引用了  components/Editor/WangEditor  组件 然而在配合form去使用的时候报错

尝试了好几种办法依旧不行
![image](https://user-images.githubusercontent.com/13855247/74359893-0db22780-4dff-11ea-9a1d-b37e011099f6.png)

![image](https://user-images.githubusercontent.com/13855247/74359752-d04d9a00-4dfe-11ea-8e61-d333862c21fc.png)

这个我是直接赋值的,其中json来回转换是为了解决变量复制的问题.
导致如下报错
![image](https://user-images.githubusercontent.com/13855247/74359599-8bc1fe80-4dfe-11ea-8820-c72f8c869d51.png)

随后我换成标准写法
![image](https://user-images.githubusercontent.com/13855247/74359945-24f11500-4dff-11ea-9cfd-25bbbd0dfc52.png)

这次依旧不行
![image](https://user-images.githubusercontent.com/13855247/74360062-5833a400-4dff-11ea-8de2-017fd3828a0a.png)

对此有疑问,求如何解决这个问题

**Comment by sendya** [comment]
没有问题，另外这个报错说明你在表单还没创建的时候，进行了赋值等操作

https://codesandbox.io/embed/loving-jang-6m06y?fontsize=14&hidenavigation=1&theme=dark

**Comment by hepeichun** [comment]
> 没有问题，另外这个报错说明你在表单还没创造的时候，进行了赋值等操作
> 
> https://codesandbox.io/embed/loving-jang-6m06y?fontsize=14&hidenavigation=1&theme=dark

谢谢
