### ISSUE TITLE
后端程序员，ui很适合大众的审美观念，就是入门的路线不清晰

### ISSUE THREAD

**Issue by cheapWhite** [vueComponent/ant-design-vue-pro#644]
**Question （问题描述）**
How to use component `s-table` paging
我很想把这个前端功能用在我的项目上，但是对于这个pro4认识有没有一个循序渐进的学习路线咧？
**Describe the solution you'd like （你期待的是什么？）**
有没有什么新的付费的视频教程？或者相关详细的pro4的教程文档
**Additional context（附加信息）**

**Comment by sendya** [comment]
没有，请先学习 vue 基础。然后在看本项目文档

**Comment by cheapWhite** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言肆"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午4:49
收件人:&nbsp;"sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com&gt;;
抄送:&nbsp;"彼岸遇到你"<826060463@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sendya/ant-design-pro-vue] 后端程序员，ui很适合大众的审美观念，就是入门的路线不清晰 (#644)




没有，请先学习 vue 基础。然后在看本项目文档
