### ISSUE TITLE
动态路由开启报异常？

### ISSUE THREAD

**Issue by zwtlong** [vueComponent/ant-design-vue-pro#645]
开启动态路由报异常，不清楚是否配置错误？
// default router permission control
//import permission from './modules/permission'

// dynamic router permission control (Experimental)
import permission from './modules/async-router'
  
以上操作后报错：
 error  in ./src/router/generator-routers.js

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting E:\java_project\vue_work\ant-design-pro-vue\src\router\generator-routers.js:121

是我哪里没有配置好吗？ 

=====================================
问题已解决，是未初始化成功导致

**Comment by zwtlong** [comment]
问题已解决，是未初始化成功导致

**Comment by cxp1539** [comment]
> ，是未初始化成功导致

怎么解决的，方便说一下吗？

**Comment by sammyke** [comment]
@zwtlong 怎么解决的？什么未初始化？方便贴个代码吗？

**Comment by zhoulin00** [comment]
@zwtlong 老铁，是怎么解决的~~，没看懂啊
