### ISSUE TITLE
如何配置一个菜单，点击在新窗口弹出，并且不带有左侧的菜单栏

### ISSUE THREAD

**Issue by murongqingsi** [vueComponent/ant-design-vue-pro#646]
**Question （问题描述）**
菜单里面有父级菜单【A】,父级菜单【A】下面有子级菜单【B】,【C】
1、点击【B】,期望在当前页面刷新右侧区域，没有问题
2、点击【C】,期望弹出新窗口（现有项目可以实现），并且弹出的页面不带有左侧菜单栏，只有【C】页面内容（无法实现）
菜单层级关系不能改变，不能单独拆分【C】出去，不能使用白名单过滤，因为C菜单也是动态配置，也需要权限

**Describe the solution you'd like （你期待的是什么？）**
期望   能实现某个子菜单的弹出不携带左侧菜单功能
菜单层级关系不能改变，不能单独拆分【C】出去，不能使用白名单过滤，因为C菜单也是动态配置，也需要权限
**Additional context（附加信息）**
版本 vue-antd-pro   2.0.0

**Comment by sendya** [comment]
自己做一个 layout 居然参考 src/layouts 下的基础 layout

**Comment by murongqingsi** [comment]
我是有自己做layout  但是您的项目路由规范是默认所有路由都是一个路由的子路由，而这个顶级路由时basiclayout,我在里面新建其他路由没有效果了

**Comment by cjywoo** [comment]
> 我是有自己做layout 但是您的项目路由规范是默认所有路由都是一个路由的子路由，而这个顶级路由时basiclayout,我在里面新建其他路由没有效果了

你可以在A菜单下新建一个菜单，类似于下方的配置

{
            path: '/blank',
            name: 'blank',
            redirect: '/blankR/redirect',
            meta: { title: '外部空白无菜单的页面', target: '_blank' }
}

然后在根路径下，新建一个路由，component用空白的layout即可，参考
{
    path: '/blankR',
    component: BlankLayout,
    hidden: true,
    children: [
      {
        path: 'redirect',
        name: blankR',
        component: () => import('你C页面的view')
      }
    ]
  }
我之前也有这样的需求，就是这么实现的

**Comment by murongqingsi** [comment]
明白了，的确这样可以
