### ISSUE TITLE
列表页面的输入库输入或者回车删除卡顿问题

### ISSUE THREAD

**Issue by murongqingsi** [vueComponent/ant-design-vue-pro#647]
**Question （问题描述）**
How to use component `s-table` paging
一个普通页面，上面有一个input搜索框，一个新增按钮，新增按钮会弹出一个form表单，下面有个table,是个树形结构的table,父级子级数据一共200条，顶级有10几条，结果页面加载完毕，发现上面的输入库，输入数据有明显的卡顿，长按回车删除，也是会卡顿；
点击新增，弹出form表单，如果表单开启了this.$form.createForm 校验，也会卡顿
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
版本2.0.0

**Comment by sendya** [comment]
分离表单和 table 不要在同一个组件内

**Comment by murongqingsi** [comment]
form表单是用a-modal 组件弹出的，这不已经是分离组件了吗，因为ant 官网组件a-modal 有说明【需要用户处理事务，又不希望跳转页面以致打断工作流程时，可以使用 Modal 在当前页面正中打开一个浮层，承载相应的操作。】因此弹层里面实现新增编辑，就不用跳转新页面了

**Comment by edenleung** [comment]
> form表单是用a-modal 组件弹出的，这不已经是分离组件了吗，因为ant 官网组件a-modal 有说明【需要用户处理事务，又不希望跳转页面以致打断工作流程时，可以使用 Modal 在当前页面正中打开一个浮层，承载相应的操作。】因此弹层里面实现新增编辑，就不用跳转新页面了

官方说的没错，但如果你的表单项多了，就会引起这卡顿问题。

尝试以下方式
```vue
App.vue

<template>
  <div>
     <custom-form />
  </div>
</template>
<script>
import Form from './CustomForm'

export default {
  components: { CustomForm }
}
</script>
```
