### ISSUE TITLE
在route.config.js中无法为PageView页面配置keep-alive

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/ant-design-vue-pro#649]
**Describe the bug （描述 Bug）**

在route.config.js中无法为PageView页面配置keep-alive

**To Reproduce （重现步骤）**

1. 打开[表单示例页面](https://preview.pro.loacg.com/form/step-form)
2. 在表单输入内容
3. 切换至其他页面
4. 再切换回来，输入的内容没了

在示例页面中的表单页面router配置中，用了PageView，keep-alive为true
```
      // forms
      {
        path: '/form',
        redirect: '/form/base-form',
        component: PageView,
        meta: { title: '表单页', icon: 'form', permission: [ 'form' ] },
        children: [
          {
            path: '/form/base-form',
            name: 'BaseForm',
            component: () => import('@/views/form/BasicForm'),
            meta: { title: '基础表单', keepAlive: true, permission: [ 'form' ] }
          }
      }
```

在RouterView中，组件接受keepAlive传参来控制是否缓存页面
但在PageView.vue中，没有接收keepAlive，只有在multiTab开启的情况下keep-alive

**Expected behavior（你期待的是什么?）**

keep-alive 生效

**Desktop (please complete the following information):**

 - OS: win10
 - Browser chrome 79.0.3945.130
 - Version  v2.0.2

**Comment by sendya** [comment]
keep-alive 需要全页面均开启 或者均关闭。否则无法分离缓存。
或者自己实现一套 keep-alive

**Comment by candy-Tong** [comment]
从源码中看，RouterView是可以单独开启keep-alive。从官方文档中，并没有说明keep-alive 需要全页面均开启 或者均关闭，也并没有说明keep-alive只能用于RouterView。
![image](https://user-images.githubusercontent.com/20377280/74822630-65411d80-5340-11ea-9dbd-6c4206db780f.png)

文档中没说明PageView不能使用KeepAlive，应该就可以认为，这个应该是能够使用的。所以我认为这是一个bug。

另外，在表单页示例页面的源代码中，使用keepAlive了却没有生效，我认为这是一个keepAlive的错误示范。
```
      // forms
      {
        path: '/form',
        redirect: '/form/base-form',
        component: PageView,
        meta: { title: '表单页', icon: 'form', permission: [ 'form' ] },
        children: [
          {
            path: '/form/base-form',
            name: 'BaseForm',
            component: () => import('@/views/form/BasicForm'),
            meta: { title: '基础表单', keepAlive: true, permission: [ 'form' ] }
          }
      }
```

**Comment by sendya** [comment]
无法解决  请自行处理

**Comment by sendya** [comment]
不过可以给你一个提示， 自己实现一套 vue 的 keep-alive 。因为下个版本要移除 multi-tab 所以不会继续提供该功能支持
