### ISSUE TITLE
storageOptions配置为session后自动登录无效，看了下登录页面的代码好像没对自动登录做处理

### ISSUE THREAD

**Issue by tanwenchao** [vueComponent/ant-design-vue-pro#65]

**Comment by tanwenchao** [comment]
那如果是配置为session 自动登录就该屏蔽了？觉得这种定死了存一个地方有点不科学，可能是我没仔细看过vue-ls

**Comment by sendya** [comment]
储存位置这个不是强制要求，你可以按照自己的储存方案处理，甚至放在 Cookie 也是可行的。
但是如果你硬要放到 session 这种会话级别的储存，那么理应知道关闭浏览器会清除登陆状态。
而针对设计的登录页等一系列自动登陆的地方都应当做相应处理。

**Comment by sendya** [comment]
并且 我不可能知道使用本项目的开发者会用什么样的储存，本项目的配置均提供修改。
但是修改后也要对修改功能有关联的地方做处理，如果说 我把配置项做判断进行动态的页面隐藏显示 你所说的 `自动登陆` 等选项。那么这些代码就过于累赘。 因为该项目面向 `开发者` 的，开发者应当处理这些问题。
