### ISSUE TITLE
/deep/, >>>, ::shadow 已经弃用，修改组件内样式需要使用新方式

### ISSUE THREAD

**Issue by liudonghua123** [vueComponent/ant-design-vue-pro#650]
**Describe the bug （描述 Bug）**

通过 /deep/, >>>, ::shadow 等方式在外部修改 shadow dom 里面的样式现在已经逐渐不可用了，我翻看 antd, antd pro, antv 的样式或主题方面的文档，都已经慢慢迁移到使用CSS variables。

https://stackoverflow.com/questions/37352637/shadow-dom-styling-from-the-outside
https://stackoverflow.com/questions/35741722/whats-the-substitute-for-shadow-and-deep#
https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/
https://pro.ant.design/docs/theme-cn/
https://ant.design/docs/react/customize-theme-cn
https://antdv.com/docs/vue/customize-theme-cn/

所以这部分的文档可能需要更新
https://pro.loacg.com/docs/style
```vue
<template>
    <div class="test-wrapper">
        <a-select>
            <a-select-option value="1">Option 1</a-select-option>
            <a-select-option value="2">Option 2</a-select-option>
            <a-select-option value="3">Option 3</a-select-option>
        </a-select>
    </div>
</template>

<script>
export default {

}
</script>
<style lang="less" scoped>
// 使用 css 时可以用 >>> 进行样式穿透
.test-wrapper >>> .ant-select {
    font-size: 16px;
}

// 使用 scss, less 时，可以用 /deep/ 进行样式穿透
.test-wrapper /deep/ .ant-select {
    font-size: 16px;
}
</style>
```

**Comment by sendya** [comment]
在 vue 中 webpack 的 css 处理插件会自动编译成全局的样式，不受影响 另外这个和你说的 CSS variables 好像没有太大关系？  我没看出来怎么解决覆盖样式的问题。
不如来个 PR ?

**Comment by liudonghua123** [comment]
嗯，我再详细看看css预处理是怎么处理/deep/, >>> 的，我今天在一个svg中想通过这种方式修改 shadow dom里面的样式发现修改不了，才看了一下这方面的文档，发现纯css已经不可以了，可能预处理器会有特殊的处理，直接在shadow dom里面添加或修改style。

**Comment by sendya** [comment]
我不明白为什么会跟 CSS variables 扯上关系。
我给你解释一下 vue 中的 css 吧

vue 组件编译出来的 css scoped  和 html 元素是呈现这样
```css
.classname[data-v-9c918b40] {
   font-size: 12px;
}
```

```vue
<div data-v-9c918b40>abc</div>
```

当你要为嵌套的组件覆盖样式

`scpoed`
```css
.classname[data-v-9c918b40] {
   font-size: 12px;
}
.a-select[data-v-9c918b40] {

}
```

```vue
<select class="a-select"></select>
<div data-v-9c918b40>
</div>
```

这个 `.a-select[data-v-9c918b40]` 不会被应用到 a-select 这个组件上

文档的教程是为了能够覆盖组件的样式。 并不跟你描述的 CSS variables 有什么关系

**Comment by liudonghua123** [comment]
嗯，只要组件没有渲染在shadow dom里面，这种方式是没有问题的

**Comment by liudonghua123** [comment]
> 嗯，只要组件没有渲染在shadow dom里面，这种方式是没有问题的

好像目前vue暂时没用到shadow dom。 

https://github.com/vuejs/vue/issues/7385#issuecomment-355565288_
