### ISSUE TITLE
多角色管理系统中，每个角色具有不同的首页问题

### ISSUE THREAD

**Issue by cjywoo** [vueComponent/ant-design-vue-pro#651]
**Is your feature request related to a problem? Please describe.**
目前对于以下两种情况，页面登陆之后会出现404页面，原因是路由问题
1. 存在这么一种情况，一个用户登陆之后，访问了某个页面，路由假设是/a，然后退出登陆，此时路径中的redirect会把/a路径带上，这是登陆另外一个账号，但是这个账号不具有访问/a路径菜单的permission，此时就会出现404页面，这样体验貌似不太友好，可能我换一个账号登陆时，应该能够重新定向到我的首页。

2. 存在这么一种情况，我系统内存在多个角色，且每个角色的首页不同，现首页的根路径会redirect到一个路由地址里，如果这个地址某个角色没有permission的话，还是会存在登陆报404的情况

**Describe the solution you'd like**
针对上述问题，我的建议有以下修改点，
1. 是否可以在用户登陆之后，返回一个Homepath参数，使用户登陆之后跳转到每个角色的home页面？
2  在permision.js方法中，需要判断是否是登陆界面跳转，如果是登陆界面跳转，则不使用redirect地址，而是使用角色的home地址进行跳转，防止上一个用户登陆退出，下一个用户没有这个路由的权限问题

**Comment by sendya** [comment]
请自行实现。本项目的业务功能均作参考以供思路。

**Comment by cjywoo** [comment]
好的，谢谢作者
