### ISSUE TITLE
ant提供图标太少，需要在菜单栏引入自定义图标（svg格式），不知道该如何引用

### ISSUE THREAD

**Issue by murongqingsi** [vueComponent/ant-design-vue-pro#653]
**Question （问题描述）**
How to use component `s-table` paging
本地路由，可以按照demo里面提供的方式新图标，但是，我们的路由都是后台返回的，图标也是后台配置的，不知道该如何配置

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
版本2.0.0

**Comment by kokoroli** [comment]
[自定义图标](https://www.antdv.com/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-font-%E5%9B%BE%E6%A0%87)
参考antd-vue 组件库中，自定义icon文档
