### ISSUE TITLE
如何关闭eslint

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue-pro#654]
这个错误提示太烦了
如何关了他

**Comment by sendya** [comment]
https://www.baidu.com/s?wd=vue-cli3%20%E5%85%B3%E9%97%AD%20eslint&rsv_spt=1&rsv_iqid=0xaa1ed3e000055be6&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=ib&rsv_n=2&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=246&rsv_sug4=246


参考一下。
另外 不推荐关闭
