### ISSUE TITLE
如何通过antd官方组件来使用需要的组件

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue-pro#656]
官方文档是react的
这个是vue的
我不知道如何来使用
目前只能通过vue antd的现有的来拷贝使用
那如果没参考的demo就不知道如何来使用

**Comment by sendya** [comment]
没看懂你说的官方文档是 react 是什么

是想要这个吗 https://vue.ant.design/

**Comment by ghost** [comment]
> 没看懂你说的官方文档是 react 是什么
> 
> 是想要这个吗 https://vue.ant.design/

谢谢
