### ISSUE TITLE
在IE11中，Select和DatePicker组件点击后闪烁

### ISSUE THREAD

**Issue by F-oldwest** [vueComponent/ant-design-vue-pro#657]
Version
1.4.11

Environment
Windows10，IE11

Reproduction link
https://github.com/TTcom/tree-demo

Steps to reproduce
在项目运行后，DatePicker组件点击后和Select组件点击后

What is expected?
DatePicker和Select不会闪烁

What is actually happening?
DatePicker组件点击后，会显示在左上角，随后消失，出现在正确的位置。
Select组件点击后，会在正确的位置上出现两次。

**Comment by F-oldwest** [comment]
https://preview.pro.loacg.com/form/base-form

pro项目预览地址也有此问题出现

**Comment by sendya** [comment]
这属于基础库问题，目前 pro 上无法修正。请等待基础库更新

**Comment by F-oldwest** [comment]
> 这属于基础库问题，目前pro上无法修正。请等待基础库更新

请问。目前有其它补救方法吗？

**Comment by sendya** [comment]
> 请问。目前有其它补救方法吗？  

不使用 IE，推荐用其他现代浏览器算吗？

**Comment by mynuolr** [comment]
自己修正 基础库

**Comment by sendya** [comment]
ref vueComponent/ant-design-vue/issues/1833
