### ISSUE TITLE
yarn install 报错

### ISSUE THREAD

**Issue by hugokchen-hh** [vueComponent/ant-design-vue-pro#659]
**Question （问题描述）**
error  in /data/deploy/nodeModulesTmp/xmail_statistics/xmdatamgr/node_modules/ant-design-vue/es/modal/style/index.less

Module build failed (from /data/deploy/nodeModulesTmp/xmail_statistics/xmdatamgr/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /data/deploy/nodeModulesTmp/xmail_statistics/xmdatamgr/node_modules/ant-design-vue/es/modal/style
    at config.load.then (/data/deploy/nodeModulesTmp/xmail_statistics/xmdatamgr/node_modules/postcss-load-config/src/index.js:55:15)

 @ /data/deploy/nodeModulesTmp/xmail_statistics/xmdatamgr/node_modules/ant-design-vue/es/modal/style/index.less 4:14-207
 @ /data/deploy/nodeModulesTmp/xmail_statistics/xmdatamgr/node_modules/ant-design-vue/es/modal/style/index.js
 @ ./src/core/lazy_lib/components_use.js
 @ ./src/core/lazy_use.js
 @ ./src/main.js
 @ multi ./src/main.js
![image](https://user-images.githubusercontent.com/60635918/75612722-3eb18c80-5b61-11ea-9448-75e69b08cb54.png)

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
请提供你的完整环境信息

**Comment by hugokchen-hh** [comment]
warning @tencent/deploy-client > socket.io-client > socket.io-parser > json3@3.3.2: Please use the native JSON object instead of JSON 3
error fsevents@1.2.11: The platform "linux" is incompatible with this module.
error Found incompatible module.

**Comment by sendya** [comment]
请按照 #91 提供任何可提供信息，否则无法判断是否为本项目代码所致出错

**Comment by hugokchen-hh** [comment]
linux环境

**Comment by hugokchen-hh** [comment]
![image](https://user-images.githubusercontent.com/60635918/76328274-14608b80-6326-11ea-88de-bc83d1dbb57f.png)

**Comment by hugokchen-hh** [comment]
> 请按照 #91 提供任何可提供信息，否则无法判断是否为本项目代码所致出错

后端写前端不知道怎么沟通

**Comment by sendya** [comment]
不好意思，按照 https://github.com/sendya/ant-design-pro-vue/issues/90 格式提供
