### ISSUE TITLE
vscode下仅.vue智能语法提示失效vuter

### ISSUE THREAD

**Issue by nongzhenli** [vueComponent/ant-design-vue-pro#660]
**Question （问题描述）**
感谢提供开源组件、我在拉取最新 release 版本进行本地开发时，发现vscode的只能代码提示功能失效了（可能具体说是 vuter插件失效）
--
1、经过测试发现，放个打开vscode的时候（2s、3s）代码只能提示还是可以的！
2、且仅在.vue文件失效，.js文件还是生效的
--
疑惑：会不会是eslint的配置冲突，会是哪个rules规则呢？

**Describe the solution you'd like （你期待的是什么？）**
成功恢复vscode只能语法提示，解决冲突！

**Additional context（附加信息）**

**Comment by sendya** [comment]
本项目不会影响你的 智能代码提示，请自行检查你的环境问题

**Comment by nongzhenli** [comment]
> 本项目不会影响你的 智能代码提示，请自行检查你的环境问题

谢谢给予答复！我测试了下，没npm install 之前是可以的，之后马上就不行了。应该是某些包和vscode的插件冲突了，难搞。
