### ISSUE TITLE
项目在本地正常，但是上线之后报错：vue We're sorry but vue-antd-pro doesn't work properly without JavaScript enabled. Please enable it

### ISSUE THREAD

**Issue by SidselLoong** [vueComponent/ant-design-vue-pro#661]
**Describe the bug （描述 Bug）**

项目在本地的时候一切正常，但是上线之后报错，vue We're sorry but vue-antd-pro doesn't work properly without JavaScript enabled. Please enable it。根据网上把mood:'history'改成'hash'之后首页一直刷新

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
请按照 #90 提供详细信息
