### ISSUE TITLE
发布到测试环境之后页面一直刷新，控制台一直报错，在本地的时候正常

### ISSUE THREAD

**Issue by SidselLoong** [vueComponent/ant-design-vue-pro#663]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/38250412/75853326-d09eeb00-5e28-11ea-9735-c1184f2ec800.png)
![image](https://user-images.githubusercontent.com/38250412/75853421-004df300-5e29-11ea-8a45-82a79dfca653.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
这些错误好像都不是 pro 有的东西，请自行查一下用了什么依赖，用错了导致的
