### ISSUE TITLE
最新代码的右侧设置不再展示了

### ISSUE THREAD

**Issue by yangjuncheng** [vueComponent/ant-design-vue-pro#667]
**Describe the bug （描述 Bug）**

最新代码的右侧设置不再展示了

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
#668
