### ISSUE TITLE
文档勘误

### ISSUE THREAD

**Issue by lymanlai** [vueComponent/ant-design-vue-pro#675]
https://pro.loacg.com/docs/new-page#%E4%B8%89%E3%80%81%E6%96%B0%E5%A2%9E%20model

最底部, 应该不是 model, 而是 module 吧?

**Comment by sendya** [comment]
也许 理解偏差吧？

model 数据模型，没什么毛病，module 是开发规范中的模块统称 与 MVVM 中的 Model 没什么关系

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/76277016-77203b80-62c2-11ea-9d05-8e53810eec03.png)
