### ISSUE TITLE
table组件 pagination报错

### ISSUE THREAD

**Issue by HappyLilyWen** [vueComponent/ant-design-vue-pro#677]
操作过程如下：
第一次请求从后端拿到数据为空
返回的分页数据是
pageNo: 1
pageSize: 10
totalCount: 0
totalPage: 0

第二次请求返回了数据，这时候报错“custom validator check failed for prop ‘pagination’”
请问下有遇到过这种情况吗，怎么解决的？

**Comment by sendya** [comment]
版本?

**Comment by HappyLilyWen** [comment]
1.4.0

**Comment by sendya** [comment]
src/compoents/Table 代码更新到最新

**Comment by HappyLilyWen** [comment]
问题解决了，万分感谢
