### ISSUE TITLE
树形选择框和树形表格有计划实现吗？

### ISSUE THREAD

**Issue by iisquare** [vueComponent/ant-design-vue-pro#679]
树形表格（TreeGrid）：http://www.jeasyui.net/demo/578.html
树形选择框（CheckBox Tree）：http://www.jeasyui.net/demo/573.html

**Comment by iisquare** [comment]
EasyUI中还有一种属性网格，虽然可以通过组合现有组件实现，但如果能提供原生支持，就再好不过了。
属性网格（PropertyGrid）：http://www.jeasyui.net/demo/384.html
如果上述三种组件都能支持良好，就可以彻底告别EasyUI了，作者们加油！

**Comment by sendya** [comment]
这不就是普通的 table 和普通的 tree 而已吗

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/76434724-0297ea80-63f1-11ea-8287-e0de0b45ce63.png)

![image](https://user-images.githubusercontent.com/5404542/76434756-0f1c4300-63f1-11ea-836e-f83fbf90cc96.png)

**Comment by iisquare** [comment]
树形表格是保持表头一致，树形结构列可以多级展开，而不是单行展开手风琴面板。

**Comment by iisquare** [comment]
重新翻了下Ant Design of Vue的文档，是支持的，🤣是我文档没看仔细。属性网格（PropertyGrid）如果能直接支持就好了，不过通过组合现有组件自定义实现可能会更灵活一些。结贴，多谢回复！
