### ISSUE TITLE
日期控件问题-设置的是zh_CN,但是日期控件显示英文

### ISSUE THREAD

**Issue by snryang** [vueComponent/ant-design-vue-pro#68]
尝试过升级ant-design-vue，版本号，与ant-design-vue无关。尝试过设置moment的默认语言，都无法解决，https://pro.loacg.com/ 示例中的日期控制也存在这个问题。

**Comment by sendya** [comment]
去掉这里 https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L27
或者手动引入中文日期语言文件
或者去参考 https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

**Comment by snryang** [comment]
> 去掉这里 https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L27
> 或者手动引入中文日期语言文件
> 或者去参考 https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

谢谢，注释// new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/), 解决问题了。

**Comment by snryang** [comment]
> 去掉这里 https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L27
> 或者手动引入中文日期语言文件
> 或者去参考 https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

谢谢，注释// new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/), 解决问题了。
之前尝过在main.js中使用以下代码，解决不了问题
```
import moment from 'moment';
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
```
