### ISSUE TITLE
ant-design-vue 1.5.0-alpha.1 中a-tree和a-tree-select无法正常使用

### ISSUE THREAD

**Issue by 5202m** [vueComponent/ant-design-vue-pro#681]
项目使用了 ant-design-vue 1.5.0-alpha.1 版本
但是在使用a-tree和a-tree-select时无法正常使用
Unknown custom element: <a-tree> - did you register the component correctly? For recursive components, make sure to provide the "name" option

Unknown custom element: <a-tree-select> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

请问是在这个版本中弃用了吗？

**Comment by Gardent** [comment]
[参考这个试下，#546](https://github.com/sendya/ant-design-pro-vue/issues/546)

**Comment by sendya** [comment]
请自行引入需要的组件

**Comment by 5202m** [comment]
感谢回复，问题已解决
