### ISSUE TITLE
页面表单输入卡顿

### ISSUE THREAD

**Issue by murongqingsi** [vueComponent/ant-design-vue-pro#682]
**Describe the bug （描述 Bug）**

再提供的demo 地址https://preview.pro.loacg.com/form/advanced-form   
底部新增成员功能，新增4，5行数据，再在输入框输入数据会感到明显卡顿，长按backspace也会有明显卡顿效果，该demo已经是组件化开发了。

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
给表单增加 `selfUpdate` 具体查阅 [https://antdv.com](https://antdv.com)

另外，由于 demo 是纯数据 mock ，有非常多的对象遍历操作，这并不是生产环境代码会有的。正常不会存在你说的问题
