### ISSUE TITLE
左侧菜单mode改为vertical,收起时鼠标放上去没有滑出子菜单，点击菜单在收缩状态向下展开

### ISSUE THREAD

**Issue by aha-li** [vueComponent/ant-design-vue-pro#684]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
antd pro 左侧菜单不支持该功能，如需自定义，请自行实现。
