### ISSUE TITLE
表格scoll的一个BUG

### ISSUE THREAD

**Issue by forever-thinker** [vueComponent/ant-design-vue-pro#687]
GIT提取的最新版本。S-TABLE（TableInnerEditList.vue）设置滚动（scroll）属性，然后表格标题栏点击排序字段（服务调用次数）console会报异常。S-TREE则没有这个问题。
![操作界面](https://user-images.githubusercontent.com/56533456/76691972-5faecd00-668b-11ea-85cf-635f0126b4bf.png)
![代码属性设置](https://user-images.githubusercontent.com/56533456/76691977-6d645280-668b-11ea-9c8e-fe3da075a895.png)
![异常](https://user-images.githubusercontent.com/56533456/76691981-76edba80-668b-11ea-80ed-6c15ec9bf0e7.png)

<s-table
      ref="table"
      size="default"
      :columns="columns"
      :data="loadData"
      :alert="{ show: true, clear: true }"
      :scroll="{x: 'max-content', y: 'calc(100vh - 400px)'}"
      :rowSelection="{ selectedRowKeys: this.selectedRowKeys, onChange: this.onSelectChange }"
    >

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'scrollTop' of undefined"

found in

**Comment by sendya** [comment]
复杂应用请使用  a-table，s-table 仅作为业务封装 table
