### ISSUE TITLE
Unknown custom element: <a-carousel>

### ISSUE THREAD

**Issue by linaaaqi** [vueComponent/ant-design-vue-pro#689]
**Question （问题描述）**
系统环境：macOS 10.15.3
浏览器版本：Chrome 80.0.3987.132（正式版本） （64 位）
Ant design pro vue 2.1.0
错误提示：
```
[Vue warn]: Unknown custom element: <a-carousel> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Home> at src/views/Home.vue
       <BlankLayout> at src/layouts/BlankLayout.vue
         <ALocaleProvider>
           <Anonymous>
             <AConfigProvider>
               <App> at src/App.vue
                 <Root>
warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620
```

**Describe the solution you'd like （你期待的是什么？）**
正常使用跑马灯组件

**Additional context（附加信息）**
重新拉取了也不行

**Comment by Gardent** [comment]
[参考这个试下，#546](https://github.com/sendya/ant-design-pro-vue/issues/546)
或者
`import { Carousel } from 'ant-design-vue'

  components: {
    [Carousel.name]: Carousel
  },
`

**Comment by losgif** [comment]
可以通过以下的按需加载方式载入，这个算不算BUG？
```
import Carousel from 'ant-design-vue/es/carousel'
import 'ant-design-vue/lib/carousel/style'

export default {
  name: 'List',
  components: {
    [Carousel.name]: Carousel
  }
}
```

**Comment by linaaaqi** [comment]
> [参考这个试下，#546](https://github.com/sendya/ant-design-pro-vue/issues/546)
> 或者
> `import { Carousel } from 'ant-design-vue'
> 
> components: {
> [Carousel.name]: Carousel
> },
> `

明白了，lazy_use 没有全局引入。
