### ISSUE TITLE
ant-design的控件样式在自定义控件重写后，会影响到其他控件的样式。

### ISSUE THREAD

**Issue by intellijboy** [vueComponent/ant-design-vue-pro#691]
**Question （问题描述）**
How to use component `s-table` paging
我自定义了一个头部导航组件，我在global中添加了自己的样式，但是影响到了管控台的菜单栏的样式（比如我的情况是：图标都变大了）；而 如果在单独的控件中添加样式，发现刷新后，样式不会立即应用到组件。
**Describe the solution you'd like （你期待的是什么？）**
我希望在单独的控件中写样式覆盖ant的默认控件样式，并前端路由转发后立即能看到效果。
**Additional context（附加信息）**
None.

**Comment by sendya** [comment]
https://github.com/kokoroli/antd-awesome/blob/master/docs/%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E8%A6%86%E7%9B%96.md

**Comment by intellijboy** [comment]
谢谢，我回头试一下，应该是我想要的
