### ISSUE TITLE
Uncaught SyntaxError: Identifier 'pleaseLetJsLoaded' has already been declared

### ISSUE THREAD

**Issue by Wangrong23** [vueComponent/ant-design-vue-pro#692]
**Describe the bug （描述 Bug）**

console报此错误，路由每跳转一次都会报一遍这个错误

**To Reproduce （重现步骤）**

最新版Chrome F12打开控制台就可以看到此错误输出

**Expected behavior（你期待的是什么?）**
不输出此错误 此错误产生的原因

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/24642975/76914554-a4d63780-68f5-11ea-8a5b-6f9810e3801b.png)

**Desktop (please complete the following information):**

 - OS: windows10 1903
 - Browser  chrome
 - Version 80.0.3987.149

**Comment by sendya** [comment]
无法复现你说的问题，请提供复现代码，请描述清楚做了什么改动。 按照 #90 进行编写 issue

**Comment by Wangrong23** [comment]
我这边查看预览环境（[https://preview.pro.loacg.com/](https://preview.pro.loacg.com/)）同样会出现这个错误,且只在chrome下输出
经测试使用无痕窗口访问不会输出此错误

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/76916461-7196a700-68fb-11ea-9424-11e810e81c45.png)

同样没有，是否你自己装了什么浏览器插件导致的

**Comment by Wangrong23** [comment]
确实，禁用FeHelper此错误消失，谢谢回复
