### ISSUE TITLE
一级菜单如何添加面包屑

### ISSUE THREAD

**Issue by wushunqing** [vueComponent/ant-design-vue-pro#693]
**Question （问题描述）**
How to use component `s-table` paging
面包屑目前在二级菜单时，最外层component : PageView，里面的二级菜单直接import就有面包屑功能，但是如果一级菜单想要使用确没有，目前只能手动在一级页面添加   <page-view>组件。
**Describe the solution you'd like （你期待的是什么？）**
请问有没有什么设置途径，可以直接一级菜单就可以方便使用面包屑.
**Additional context（附加信息）**

**Comment by sendya** [comment]
可以尝试 faeture/v3 或者参照 pro-layout 的 PageHeaderWrapper 自行封装
