### ISSUE TITLE
色弱模式下SettingDrawer没有正确隐藏

### ISSUE THREAD

**Issue by iisquare** [vueComponent/ant-design-vue-pro#694]
**Describe the bug （描述 Bug）**

SettingDrawer选中“色弱模式”，关闭后没有正确隐藏，通过拖动底部滚动条，在页面右部可以看到，取消“色弱模式”页面恢复正常。

**To Reproduce （重现步骤）**

1. 点击SettingDrawer设置按钮
2. 选中“色弱模式”
3. 关闭SettingDrawer
4. 此时页面底部出现滚动条，拖动后在页面右侧可看到SettingDrawer面板

**Desktop (please complete the following information):**

 - OS: Mac & Windows10
 - Browser [chrome 80.0.3987.132（正式版本） （64 位）]
 - Version [master]

**Comment by sendya** [comment]
`filter: invert` 导致 transform 被覆盖，目前无法解决。所以我参考了 react antd pro 的做法，反色挂在 #app 下。
只不过这样会导致 dialog , model 等各系列弹窗颜色不会被反色，如有需要 请自行处理
