### ISSUE TITLE
请问老师，后端返回路由列表，那个列表数据是在哪里生成传给后端的？谢谢

### ISSUE THREAD

**Issue by Thlq** [vueComponent/ant-design-vue-pro#695]
![image](https://user-images.githubusercontent.com/21211777/77286590-8d8cb500-6d0e-11ea-842a-56c5c1f96d96.png)

**Comment by sendya** [comment]
> 后端返回路由列表，那个列表数据是在哪里生成传给后端的？

没看懂什么意思， 是说截图的这个权限列表吗？

**Comment by Thlq** [comment]
是的，我理解的是截图的这个列表，应该由前端在设置角色分配权限的时候传给服务端，然后用户登录根绝角色获取权限的时候再返给前端，我想知道的是角色分配设置权限在哪里设置的，谢谢老师

**Comment by sendya** [comment]
本库不提供这种东西，只有一个 demo 列表 https://preview.pro.loacg.com/other/list/role-list
，请自行设计

**Comment by Thlq** [comment]
好的，谢谢
