### ISSUE TITLE
checkbox组如何能够动态勾选上

### ISSUE THREAD

**Issue by Xiaohantx** [vueComponent/ant-design-vue-pro#699]
**Question （问题描述）**
采用的https://preview.pro.loacg.com/other/list/user-list这个页面的布局

```
      this.mdl.permissions.forEach(permission => {
        permission.actionsOptions = permission.actionEntitySet.map(action => {
          return { label: action.describe, value: action.action, defaultCheck: action.defaultCheck }
        })
      })
```
这里是处理代码，返回给到options上

defaultCheck没有钩上

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
![](https://cdn.markone.xyz/images/20200323161835.png)

**Comment by Xiaohantx** [comment]
在组件上添加默认值解决，return 中貌似无法设置

**Comment by sendya** [comment]
added https://github.com/sendya/ant-design-pro-vue/commit/685977e7f340eefc1dbfc23eeb07bcaff837cd48
