### ISSUE TITLE
如何获取s-table筛选后的全部列rows

### ISSUE THREAD

**Issue by watsonhaw5566** [vueComponent/ant-design-vue-pro#700]
**Question （问题描述）**
@saraka 大大您好，我在使用您封装的s-table之后有这样的一个需求，就是我通过params字段去筛选出需要的表格数据后，如何选中所有的rows信息，目前我只能通过传入`selectedRows`获取当前页的表格数据。
我的业务需求是导入符合筛选规则的全部数据表单生成相应的excel表格，excel表格后端写完了，但卡在了获取全部rows这里了。我找过了antd vue pro的文档和issue，没有找到相关的内容，所以发起了一个issue来向您提问，如果您有时间的话，烦请回复我一下，感谢您，谢谢你们付出的的antd vue pro。

**Describe the solution you'd like （你期待的是什么？）**
在`s-table`组件中可以选中所有分页中的列，而不止是当前分页中的列
**Additional context（附加信息）**
我想选中这全部‘未发货·的13张订单
![image](https://user-images.githubusercontent.com/4210367/77511061-3243f980-6eab-11ea-99da-5edb214e06ce.png)

**Comment by sendya** [comment]
定义一个 `totalSelectedRows` 每次 `onSelectChange` 的时候增量保存到这个变量里，`totalSelectedRows` 就成为不管怎么翻页，都存在的值 （请注意 下面 demo 只控制了往变量里增加的逻辑，并没有去除勾选的逻辑，请自行梳理实现 控制被去除的 rowKeys）

```
    onSelectChange (selectedRowKeys, selectedRows) {
      this.selectedRowKeys = selectedRowKeys
      this.selectedRows = selectedRows
      this.totalSelectedRows = [...this.totalSelectedRows, ...selectedRowKeys]
    },
```

**Comment by watsonhaw5566** [comment]
@sendya 谢谢您的回复，感动。

**Comment by dongpobaicai** [comment]
/**
     * 用户手动选择/取消选择某列的回调 
     */
    onSelect(record, selected, selectedRows, nativeEvent) {
      console.log(record, selected, selectedRows, nativeEvent)
    },
      /**
     * 用户手动选择/取消选择所有列的回调
     */
    onSelectAll(selected, selectedRows, changeRows) {
      console.log(selected, selectedRows, changeRows)
    },
  可以通过这个两个方法，更新totalSelectedRows
