### ISSUE TITLE
removeLoadingAnimate 方法在哪里调用的没找到，跳到第三方网站再调回来的时候，loading一直再

### ISSUE THREAD

**Issue by 0xleizhang** [vueComponent/ant-design-vue-pro#701]
**Question （问题描述）**
文档中的utils包中的方法 removeLoadingAnimate 方法在哪里调用的没找到

**Describe the solution you'd like （你期待的是什么？）**
 再源码中能找到主动调用 removeLoadingAnimate 方法的地方

**Additional context（附加信息）**
 removeLoadingAnimate 在antd-vue中也搜了没有调用

**Comment by sendya** [comment]
以前有用，但早就没有使用了。loading 在，跟这个方法目前没任何关系，自己看一下 public/index.html 文件结构吧

**Comment by 0xleizhang** [comment]
@sendya 
` <div id="loading-mask">
          <div class="loading-wrapper">
            <span class="loading-dot loading-dot-spin"><i></i><i></i><i></i><i></i></span>
          </div>
        </div>`
看到这段代码了，但是没看到在哪控制的这个div显示隐藏？你说神奇不神奇

**Comment by sendya** [comment]
> 看到这段代码了，但是没看到在哪控制的这个div显示隐藏？你说神奇不神奇

这有什么神奇的，只能说明你对 vue 的机制不了解而已。
vue 初始化之后会往 #app 挂载，挂载时会把虚拟 dom 全部挂上去，之前的任何 dom 都会被覆盖。一点也不神奇。就像你 dom.innerHtml = xx 一样

**Comment by 0xleizhang** [comment]
原来如此，这么神奇 
那就说明我从别的网站调回来的时候，vue没有重新挂载，导致loading一直都在
