### ISSUE TITLE
"2.1.0"

### ISSUE THREAD

**Issue by congxiaobai** [vueComponent/ant-design-vue-pro#703]
**Question （问题描述）**
尊敬的开发者您好，我正在学习本框架的源码。看到在动态生成菜单的时候，有这样一句源码：
文件路径为:  src\components\Menu\menu.js
![image](https://user-images.githubusercontent.com/20089891/77937796-6c682d80-72e7-11ea-88c8-fcd8b062c9d0.png)
这句代码实在看不懂，{...{props,on:on}}参数是怎么传递的呢？vModel又是什么呢？引用的‘'ant-design-vue/es/menu'组件中也确实没有看到相关的定义。

**Describe the solution you'd like （你期待的是什么？）**
您是否方便说一下这个实现的思路，或者指点一下方向，我自己去查找资料。

**Additional context（附加信息）**
版本："2.1.0"

**Comment by sendya** [comment]
https://zhuanlan.zhihu.com/p/37920151

https://github.com/vuejs/jsx
