### ISSUE TITLE
感觉权限判断和登录状态判断代码有点耦合

### ISSUE THREAD

**Issue by mogody** [vueComponent/ant-design-vue-pro#704]
如题，用户权限(permission)的判断是在 src/permission.js 里面判断的，而判断用户没登录(没有 token )的时候跳转到 /user/login 也是在这里面判断的，假如用户不需要权限控制模块，根据文档注释了 ./permission ，那么就会出现点击退出登录后，s虽然页面有一堆的401提示，但是依然在当前页面，而没有跳转到登录页面。

虽然说可以自己改造 permission.js 的业务逻辑来解决这个问题，而且也不难，但要是不熟悉的话会让人很手足无措，而且 **是否登录** 和 **用户权限** 本就是两码事，个人感觉不应该放到一起来处理

**Comment by sendya** [comment]
没有权限还要什么登录？

**Comment by sendya** [comment]
只要有登录 就属于权限控制了，不管你是否控制得多复制还是极简单的登录。校验，都属于权限管控的一环。 既然我文档给出的去除权限，就不再有登录操作了，因为没有意义。

如果你认为有必要存在一个登录。界面而不需要控制任何前置。后置条件，那么自行处理一下就好

**Comment by mogody** [comment]
我举一个场景：进入后台要登录，但是后台管理员不需要权限就可以操作资源(这里的权限是指对资源是否有操作能力，不是是否可不可以登录后台)，所有管理员都可以对资源进行操作(比如增删改)，这样的场景应该很常见。

我理解中的登录是指通过管理员帐号密码登录后台进行资源操作，权限只类似 RBAC 或者 ACL 等对资源是否有操作的权限。有帐号密码才能登录后台，有权限才能操作资源(假如没有权限，那么登录到后台之后也没啥意义)

而你们 permission.js 的实现，是把**登录功能**和**资源操作权限**耦合到一起判断，后台要有登录功能，那么就必须要给后台用户分配增删改查权限，如果直接注释掉 permission.js ，会使得后台的登录功能失效(这里的失效是狭义的，特指操作退出后或者TOKEN被清空无法跳转到登录页面)

当然这个话题解决方案也很简单，就是把 permission.js 中关于 GetInfo 这一块的判断去掉即可。

**Comment by mogody** [comment]
建议就是把 permission.js 里面的守卫拆分成两个，先A后B，A用来处理是否有登录态(可以理解为本地是否有TOKEN)，B用来处理是否对资源有操作权限，这样就可以完全解耦

**Comment by sendya** [comment]
你有更好的方案可以发出来，共享给大家。

**Comment by sendya** [comment]
我这边是不会继续对这个进行更改了，目前这样是比较好的一种方案， iview-admin, element-admin 等大部分 vue 集成后端均使用本方案

**Comment by mogody** [comment]
当然这只是一个建议，觉得不合适的话，可以保持原样，这个 issue 目的就是让有和我一样需求的人，可以有一个参考的解决方案

**Comment by Xiaohantx** [comment]
如果只需要登陆拦截，不需要用户权限组，可以参考以下修改（如果有好方案也可以提以下）

/src/router/index.js  14-19行 来跳过路由过滤
```vue
export default new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap.concat(asyncRouterMap)
})
```
/src/layouts/BasicLayout.vue  112行 created 替换以下代码，左侧菜单直接拿路由生成
```vue
this.menus = asyncRouterMap.find((item) => item.path === '/').children
this.collapsed = !this.sidebarOpened
```

/src/permission.js  `if (to.path === '/user/login') `的else判断里只留一句
```vue
next()
```

以上修改后会只拦截登陆，另外业务代码中改成了cookie中存token判断是否登陆，具体可以根据业务

**Comment by mogody** [comment]
@Xiaohantx 对,改造的话其实很简单不难, 只是个人觉得 **登录拦截** 和 **权限组** 是两个东西, 完全可以分开来处理, 而不应该都耦合到 permission.js 中处理, permission 应该只是处理权限相关, 登录拦截可以抽象到一个新的auth.js中, 到时候假如用户不需要权限, 直接注释permission.js即可

**Comment by we452366** [comment]
> @Xiaohantx 对,改造的话其实很简单不难, 只是个人觉得 **登录拦截** 和 **权限组** 是两个东西, 完全可以分开来处理, 而不应该都耦合到 permission.js 中处理, permission 应该只是处理权限相关, 登录拦截可以抽象到一个新的auth.js中, 到时候假如用户不需要权限, 直接注释permission.js即可

老哥说的是不是antd pro里authority那里的实现？我看vue改造的和react那里不太一样
