### ISSUE TITLE
VS Code 代码格式化问题

### ISSUE THREAD

**Issue by IMJacky** [vueComponent/ant-design-vue-pro#705]
**Question （问题描述）**
我fork下来项目之后，通过vs code查看代码并修改，然后习惯性的格式化代码，然后就编译不通过了，查找了相关资料要修改vetur.format、prettierrc以及eslint相关配置，这让我很困扰

**Describe the solution you'd like （你期待的是什么？）**
我想LZ你的代码已经是格式化之后的了吧，所以想问下你是怎么配置vs code开发ant design vue pro的环境的

**Additional context（附加信息）**
我是后端开发，表示对前端一些工程还不是很了解，谢谢~

**Comment by sendya** [comment]
eslint ，配置已经附带在项目根目录 `.eslintrc.js`
