### ISSUE TITLE
使用自带的权限功能，一个用户只能对应一个role吗？

### ISSUE THREAD

**Issue by doupengfei** [vueComponent/ant-design-vue-pro#706]
**Question （问题描述）**
我看了权限的介绍文档，里面写的后台用户信息的json是一个用于对应一个role，role这个字段是字符串吗？如果是一个用户对应多个role，是需要改代码吗？
`
 const userInfo = {
    'id': '4291d7da9005377ec9aec4a71ea837f',
    'name': '天野远子',
    'username': 'admin',
    'password': '',
    'avatar': '/avatar2.jpg',
    'status': 1,
    'telephone': '',
    'lastLoginIp': '27.154.74.117',
    'lastLoginTime': 1534837621348,
    'creatorId': 'admin',
    'createTime': 1497160610259,
    'merchantCode': 'TLif2btpzg079h15bk',
    'deleted': 0,
    'roleId': 'admin',//??????????????????????
    'role': {}
  }
`

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/store/modules/permission.js#L32
自行实现
