### ISSUE TITLE
有关构建工程时怎么不要使用cdn

### ISSUE THREAD

**Issue by xuzining** [vueComponent/ant-design-vue-pro#707]
工程打包后会自动引入vue等系列的cdn，如何不让项目访问cdn而是把vue等资源一起打包到工程里，这样再内网或者不能访问互联网时程序也可以正常使用。

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L38

https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L61
