### ISSUE TITLE
去除权限控制

### ISSUE THREAD

**Issue by jy-pwn** [vueComponent/ant-design-vue-pro#710]
按照官网的流程去除权限控制：
https://pro.loacg.com/docs/remove-authority-management
点击表格的权限按钮时，会报错。如下图
![image](https://user-images.githubusercontent.com/9392445/78588174-bbc2d680-7870-11ea-8438-12f6ac29ddbd.png)

如果我保留main.js中的：
import './permission' // permission control
就不会报错
不过这样好像又走回了权限判断了~~~

**Comment by sendya** [comment]
v-action 去掉
