### ISSUE TITLE
antd pro权限模块的vue实现

### ISSUE THREAD

**Issue by we452366** [vueComponent/ant-design-vue-pro#712]
**Question （问题描述）**
大佬，问个问题，看大佬源码好像是把antd pro的权限那块儿好像不太一样，antd pro的权限模块的authority实现大佬能给个思路吗？谢谢

**Comment by sendya** [comment]
都是 if 判断，在选择是否渲染

**Comment by we452366** [comment]
按照permission进入判断后，再进一步进行authority判断吧？我照着大佬的思路试试

**Comment by sendya** [comment]
vue 和 react 上从一开始风格就不同，没办法什么都照着 react 风格做，所以我做的方案是根据 element-admin 和 iview-admin 参考做的，在 vue 社区属于通用风格，用过以上任意 admin ，迁移的学习成本都很低，不可能为了 react 风格的授权在去做一份，即使做出来没技术难度。 其他用户的接受程度也无法估计。具体例子可以参考 antd vue 的 Form 组件。少了 v-model 一堆人有意见。

我说的 if 判断，在任何实现权限上，都是 if 判断。
最简单的  <component v-if="权限"  /> 都能用来控制权限
路由权限也一样。只要不加入到 vue-router 路由表就可以。
