### ISSUE TITLE
跳转页面这里为什么要next({ ...to, replace: true })，而不能直接next()

### ISSUE THREAD

**Issue by froggengoing** [vueComponent/ant-design-vue-pro#714]
**Question （问题描述）**
可能问题比较基础，但是搜了一圈也没找到答案，望大神解惑。
下面这段在permission中，大概流程是判断token-\>roles-\>动态获取router-\>跳转页面。
我的问题是跳转页面这里为什么要**next({ ...to, replace: true })，而不能直接next()。**
因为在这个地方一开始陷入了死循环，所以我就改成了next()。
但是只能跳转了constantRouterMap中的地址，新挂载的地址一直空白页面。然后这问题折腾了我两天。。。。。
而且next()没有再进入beforeEach()。
我的理解就是：动态获取router并挂载后->直接next()不能就是访问到已经挂载的路由吗？
所以是需要使用next(‘/’)，重新触发才能使用新的router吗？
```
      if (store.getters.roles.length === 0) {
        store
          .dispatch('GetInfo')
          .then(res => {
            const roles = res.result && res.result.role
            store.dispatch('GenerateRoutes', { roles }).then(() => {
              // 根据roles权限生成可访问的路由表
              // 动态添加可访问路由表
              router.addRoutes(store.getters.addRouters)
              // 请求带有 redirect 重定向时，登录自动重定向到该地址
              const redirect = decodeURIComponent(from.query.redirect || to.path)
              if (to.path === redirect) {
                // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
                next({ ...to, replace: true })
              } else {
                // 跳转到目的路由
                next({ path: redirect })
              }
            })
          })
```

**Comment by sendya** [comment]
// hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record

主要只是为了不让后退

**Comment by FyuNaru** [comment]
请问你解决了这个问题了吗

**Comment by FyuNaru** [comment]
没事了我已经知道了

**Comment by krislll** [comment]
请问是怎么解决的呢

**Comment by FyuNaru** [comment]
> 请问是怎么解决的呢

不好意思没有及时看到，可能你已经解决了这个问题了。但还是在这里说一下大致的原因，方便之后找到这里的人。陷入死循环的根本原因是这个嵌套的if-else的判断条件出了问题，可以仔细检查一下相关的条件判断对应的变量。由于已经过了一段时间了，代码有些不太记得了，具体是哪个变量忘记了，所以可以先自己尝试找下，如果还有疑问可以私信我一起看一下
