### ISSUE TITLE
请问table组件要自定义内容应该怎么写？官网文档api中给出的components属性以覆盖table中元素，那它内置的参数有哪些呢？

### ISSUE THREAD

**Issue by lijing1024** [vueComponent/ant-design-vue-pro#717]
官方文档给出table自定义内容可使用的属性说明
![image](https://user-images.githubusercontent.com/46262957/78983429-c6be8500-7b56-11ea-8963-777346c6de2d.png)
期望可以对table中的tr进行自定义，可结合vue-draggable插件实现对表格行进行拖拽效果

**Comment by sendya** [comment]
请查阅 ant design vue 官方文档

**Comment by lijing1024** [comment]
文档中并没有对table中的components作出细节说明，只说是用来覆盖table中的元素的，所以才请教您，可否将内置参数写明，感谢
![截屏2020-04-10 下午6 39 51](https://user-images.githubusercontent.com/46262957/78985317-09825c00-7b5b-11ea-9d3d-143a97b4933a.png)

**Comment by sendya** [comment]
components: { header, table, body }
这个属于 ant design vue 的库文档，这里是 pro 社区实现，请到对应仓库反馈
