### ISSUE TITLE
最新版本 <a-collapse>编译不通过

### ISSUE THREAD

**Issue by nongzhenli** [vueComponent/ant-design-vue-pro#719]
拉取最新的master，发现 <a-collapse> 使用不了，一看，标签元素并没有被编译，这是 antd vue 官方的Bug么
![image](https://user-images.githubusercontent.com/19389294/79165028-d79c1e80-7e14-11ea-9452-18cc38731289.png)
![image](https://user-images.githubusercontent.com/19389294/79165040-e08cf000-7e14-11ea-8ddc-9a21299c686a.png)

**Comment by nongzhenli** [comment]
我尝试将 antd vue 版本更改回1.5.0  问题还是存在 @sendya

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/79175247-c8769a00-7e2f-11ea-8c5d-6d8773b9557a.png)

你组件都没注册，不看错误提示的吗？这写得非常的明确了

**Comment by nongzhenli** [comment]
好的，我检查下！谢谢大佬、是不是master是组件按需加载的呀。我以为是全局引入、
