### ISSUE TITLE
devServer配置问题

### ISSUE THREAD

**Issue by hanzhenchaoGit** [vueComponent/ant-design-vue-pro#72]

**Comment by hanzhenchaoGit** [comment]
devServer: {
    proxy:{
      '/api':{
          target:'http://localhost:8080',
          changeOrigin: true
      }
    }
  },
后端已开放测试接口  但是请求后一直是502

**Comment by sendya** [comment]
https://webpack.js.org/configuration/dev-server/#devserver-proxy

**Comment by hanzhenchaoGit** [comment]
这个文档看过了  就是照着配置的  不知道哪里的问题

**Comment by sendya** [comment]
麻烦提供更详细的相关信息

**Comment by hanzhenchaoGit** [comment]
要改成真实的接口地址只要改成上面的配置应该就可以的吧  我现在是后端java开放了一个登陆接口 /api/auth/login  登陆的时候期望可以转发到我http://localhost:8080/api/auth/login这个接口上

**Comment by sendya** [comment]
本项目已经有提供 `devServer` 的配置用例 https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L63

请直接参考配置，如果还不能访问，请自行确认后端是否能正常访问。

**Comment by hanzhenchaoGit** [comment]
后端接口测试是可以的   先这样吧 谢谢了
