### ISSUE TITLE
这是一个Vue的框架,不明白为什么还要使用jsx语法

### ISSUE THREAD

**Issue by temuiphone** [vueComponent/ant-design-vue-pro#720]
很希望作者能够,统一技术栈,,这是一个Vue项目,然而却使用了React的jsx语法,对于没有React基础的,似乎很难去上手.

![image](https://user-images.githubusercontent.com/45486442/79177497-84869380-7e35-11ea-89d9-3eada9cae70a.png)

**Comment by temuiphone** [comment]
src / components / Search / GlobalSearch.jsx

`import { Select } from 'ant-design-vue'
import './index.less'

const GlobalSearch = {
  name: 'GlobalSearch',
  data () {
    return {
      visible: false
    }
  },
  mounted () {
    const keyboardHandle = (e) => {
      e.preventDefault()
      e.stopPropagation()
      const { ctrlKey, shiftKey, altKey, keyCode } = e
      console.log('keyCode:', e.keyCode, e)
      // key is `K` and hold ctrl
      if (keyCode === 75 && ctrlKey && !shiftKey && !altKey) {
        this.visible = !this.visible
      }
    }
    document.addEventListener('keydown', keyboardHandle)
  },
  render () {
    const { visible } = this
    const handleSearch = (e) => {
      this.$emit('search', e)
    }

    const handleChange = (e) => {
      this.$emit('change', e)
    }
    if (!visible) {
      return null
    }
    return (
      <div class={'global-search global-search-wrapper'}>
        <div class={'global-search-box'}>
          <Select
            size={'large'}
            showSearch
            placeholder="Input search text.."
            style={{ width: '100%' }}
            defaultActiveFirstOption={false}
            showArrow={false}
            filterOption={false}
            onSearch={handleSearch}
            onChange={handleChange}
            notFoundContent={null}
          >
          </Select>
          <div class={'global-search-tips'}>Open with Ctrl/⌘ + K</div>
        </div>
      </div>
    )
  }
}

GlobalSearch.install = function (Vue) {
  Vue.component(GlobalSearch.name, GlobalSearch)
}

export default GlobalSearch
`

**Comment by sendya** [comment]
JSX 是 Vue 有提供的语法支持。 什么叫 React 的语法？

https://github.com/vuejs/jsx
