### ISSUE TITLE
想看看动态菜单的实现，可是这个分支不见了呢？

### ISSUE THREAD

**Issue by tonyfud** [vueComponent/ant-design-vue-pro#722]
我看 issue 过往的记录，有提到这个分支，可是点进去 现在已经404 了，分支列表里也找不到了。
可以去哪里看相关的实例？

https://github.com/sendya/ant-design-pro-vue/blob/feature/dynamic-menu/src/utils/routerUtil.js

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/79218427-fafdb280-7e82-11ea-8279-8e517a2b595e.png)
https://pro.loacg.com/docs/authority-management

> 我更新一下文档

**Comment by tonyfud** [comment]
@sendya  谢谢，大致明白了.

mark，

看了一圈， 原来代码里面就有该功能了。 

修改 src/store/index.js

// default router permission control
// import permission from './modules/permission'

// dynamic router permission control (Experimental)
import permission from './modules/async-router'

使用了 async-router 后， permission -> generatorDynamicRouter -> loginService.getCurrentUserNav  就会请求 /user/nav 作者留好的 mock 数据
