### ISSUE TITLE
怎么样兼容到ie9，紧急求助

### ISSUE THREAD

**Issue by wxwebfeng** [vueComponent/ant-design-vue-pro#726]
**Question （问题描述）**
开发中发现兼容不了ie9，官方那边到ant-design-pro 配置上@babel/polyfill 、@babel/plugin-transform-runtime 上是可以兼容到ie9，但是我看了一下 这里到时候一直报错 matchMedia not present, legacy browsers require a polyfill; 引入用 matchmedia-polyfill 决解， 现在又Blob 未定义，请问这里应该怎么解决这个问题；

**Describe the solution you'd like （你期待的是什么？）**
能兼容到ie9

**Additional context（附加信息）**

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/79633221-bd589c80-8196-11ea-826b-4c7927cdbd1b.png)

本项目最低仅兼容至 IE10，再往下性能非常差不做兼容 ，并且下个版本仅兼容 IE11 以上。如需往下兼容，请自行移除不兼容的部分模块或者自己使用别的方案替代

**Comment by wxwebfeng** [comment]
感谢，(っ˘̩╭╮˘̩)っ伐开心要抱抱

**Comment by FrontEnd-Hub** [comment]
> 感谢，(っ˘̩╭╮˘̩)っ伐开心要抱抱

请问你解决了嘛? 我也遇到这个问题, 暂时排查不到Blob 是哪里引用到

**Comment by wxwebfeng** [comment]
> > 感谢，(っ˘̩╭╮˘̩)っ伐开心要抱抱
> 
> 请问你解决了嘛? 我也遇到这个问题, 暂时排查不到Blob 是哪里引用到
我这边就排查到 antd vue 的包里面，这个我这边没有去删，搞不定，搞定了 麻烦说一声，谢谢！
