### ISSUE TITLE
select组件的默认值只能是字符串类型，希望能支持数字类型

### ISSUE THREAD

**Issue by tjhyupo505** [vueComponent/ant-design-vue-pro#73]
### select组件的默认值只能是字符串类型，大多数情况服务器端返回的select的备选项都是数字类型的，希望能支持数字类型。

具体见如下两段代码

### 1、下面这种情况，select的默认值在页面上会显示为“1”，而不是“正常”.
<pre>
&#60;a-select
  :key="col"
  :value="status"
  style="margin: -5px 0"
  :placeholder="columns[i].title"
  @change="value =&#62; handleActionChange(value, record.index, col)"&#62;
  &#60;a-select-option value="1"&#62;正常&#60;/a-select-option&#62;
  &#60;a-select-option value="2"&#62;禁用&#60;/a-select-option&#62;
&#60;/a-select&#62;

export default {
data () {
  return {
    status: 1
    }
  }
}
</pre>

### 2、把status改为字符串类型就显示正确了，select的默认值在页面上会显示为“正常”.
<pre>
&#60;a-select
  :key="col"
  :value="status"
  style="margin: -5px 0"
  :placeholder="columns[i].title"
  @change="value =&#62; handleActionChange(value, record.index, col)"&#62;
  &#60;a-select-option value="1"&#62;正常&#60;/a-select-option&#62;
  &#60;a-select-option value="2"&#62;禁用&#60;/a-select-option&#62;
&#60;/a-select&#62;

export default {
data () {
  return {
    status: '1'
    }
  }
}
</pre>

**Comment by sendya** [comment]
`value="1"` 是 字符串
`:value="1"` 是 number
