### ISSUE TITLE
希望升级到1.5.x版本

### ISSUE THREAD

**Issue by leeyongyao** [vueComponent/ant-design-vue-pro#731]
官方vue版本目前1.5.3版本，新增了一些组件，希望能升级到1.5.x~

**Comment by sendya** [comment]
自行升级即可

**Comment by Bright0810** [comment]
把依赖全部更新了下 结果项目崩了····

**Comment by leeyongyao** [comment]
> 把依赖全部更新了下 结果项目崩了····

是的，我是个前端菜鸟。。。然后升级完不是崩就是没有新组件。。

**Comment by sendya** [comment]
`npm i ant-design-vue`
