### ISSUE TITLE
去除mock数据之后访问自己写的接口调试成功拿到数据， 但是跳不过去首页

### ISSUE THREAD

**Issue by DivinerSheep** [vueComponent/ant-design-vue-pro#735]
您好我想请问，接口请求成功以后，vue路由使用this.$router.push({path:'/'})跳不过去首页（dashboard/workplace）是什么原因，
场景如下：
去掉main.js里面的 import './mock'这一行，在login.vue页面中的loginSuccess方法直接接口请求成功以后用以上this.$router.push方法跳不过去首页是什么原因，其他均未改动！烦请大佬告知，前端不熟悉！
谢谢！

**Comment by labike** [comment]
兄弟 我也是去掉import mock之后登录就出现问题了，你登录成功后用框架封装Vue.ls.set()可以将token写入localStorage中吗, 另外在logSuccess(res)中能拿到res吗?

**Comment by sendya** [comment]
请先确定自己到底能不能请求到接口 并获取到数据，具体看 permission.js 如果不懂 就一步一步改，别一下子就把 mock 去掉了

**Comment by DivinerSheep** [comment]
> 请先确定自己到底能不能请求到接口 并获取到数据，具体看 permission.js 如果不懂 就一步一步改，别一下子就把 mock 去掉了

好的谢谢，刚学不好意思~打扰了

**Comment by DivinerSheep** [comment]
> 兄弟 我也是去掉import mock之后登录就出现问题了，你登录成功后用框架封装Vue.ls.set()可以将token写入localStorage中吗, 另外在logSuccess(res)中能拿到res吗?
没注意你说的set是什么方法，我用sessionStorage.set是可以写入和拿到token的，另外我的res是可以的，你把上面登录那块加密的代码去掉试试，直接存进去，然后进这个logSuccess方法看看

**Comment by labike** [comment]
@zfboy 你没用框架封装的vue.ls.set()这个方法将数据存到localStorage中吗, 我是这样子的
```
Login ({ commit }, userInfo) {
      return new Promise((resolve, reject) => {
        login(userInfo).then(response => {
          console.log('response is:', response)
          const result = response.data
          // 到这一步Vue.ls.set()的时候存不进去
          Vue.ls.set(ACCESS_TOKEN, result.access_token, 1 * 1 * 60 * 60 * 1000)

          commit('SET_TOKEN', result.access_token)
          resolve()
        }).catch(error => {
          reject(error)
        })
      })
    },
```
然后resolve()之后promise.then()的时候就拿不到response了, 我知道了你没用
```
          Vue.ls.set(ACCESS_TOKEN, result.access_token, 1 * 1 * 60 * 60 * 1000)
```
我之前也尝试了直接用localStorage.setItem('token', '132')这种写法, 请求成功后无法跳转到dashboard首页
目前还没整明白啥原因不能跳转

**Comment by DivinerSheep** [comment]
我没有用你说的这个set，大概率是你在前面没有成功use到这个系统的set，还有，我目前什么都没有存，就是确定接口请求成功了，然后我就直接push跳页面跳不过去，我卡在这，建议你也先用我这些办法先跳通页面，再考虑存值传值呃呃呃问题，不然啥都白瞎😂😂😂



---原始邮件---
发件人: "labike"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 晚上8:51
收件人: "sendya/ant-design-pro-vue"<ant-design-pro-vue@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Agoni"<1849748550@qq.com&gt;;
主题: Re: [sendya/ant-design-pro-vue] 去除mock数据之后访问自己写的接口调试成功拿到数据， 但是跳不过去首页 (#735)




 
@zfboy 你没用框架封装的vue.ls.set()这个方法将数据存到localStorage中吗, 我是这样子的
 Login ({ commit }, userInfo) {       return new Promise((resolve, reject) =&gt; {         login(userInfo).then(response =&gt; {           console.log('response is:', response)           const result = response.data           // 到这一步Vue.ls.set()的时候存不进去           Vue.ls.set(ACCESS_TOKEN, result.access_token, 1 * 1 * 60 * 60 * 1000)           commit('SET_TOKEN', result.access_token)           resolve()         }).catch(error =&gt; {           reject(error)         })       })     },  
然后resolve()之后promise.then()的时候就拿不到response了, 我知道了你没用
           Vue.ls.set(ACCESS_TOKEN, result.access_token, 1 * 1 * 60 * 60 * 1000)  
我之前也尝试了直接用localStorage.setItem('token', '132')这种写法, 请求成功后无法跳转到dashboard首页
 目前还没整明白啥原因不能跳转

**Comment by labike** [comment]
@zfboy 我找到我一下调了三个接口的原因了 其实登录成功后我已经写到localStorage中了 跳转到'/'的时候被beforeEach拦截了, 然后去获取getInfo, 但是getInfo返回的数据没有role, 导致进了catch, 最后调了logout接口,localStorage中的数据又被清除了.

跳转不过去的最大可能就是beforeEach拦截的问题

**Comment by githwc** [comment]
我在src/store/modules/user.js 55行 也就是GetInfo方法回调中
添加以下代码解决(其实就是写死权限了,  我系统比较简单不需要菜单鉴权)
`result.role = { id: 'admin', name: '管理员', permissions: [ { 'roleId': 'admin', 'permissionId': 'admin' } ] }`

**Comment by labike** [comment]
@githwc 我试了你的写法。全局beforeEach哪里拦截的时候你的能过去吗？

**Comment by githwc** [comment]
> @githwc 我试了你的写法。全局beforeEach哪里拦截的时候你的能过去吗？

当然过的去

**Comment by labike** [comment]
@githwc 
```
GetInfo ({ commit }) {
      return new Promise((resolve, reject) => {
        getInfo().then(response => {
          // console.log('response is:', response)
          const result = response.data

          result.role = { id: 'admin', name: '管理员', permissions: [ { 'roleId': 'admin', 'permissionId': 'admin' } ] }

          if (result.role && result.role.permissions.length > 0) {
            const role = result.role
            role.permissions = result.role.permissions
            role.permissions.map(per => {
              if (per.actionEntitySet != null && per.actionEntitySet.length > 0) {
                const action = per.actionEntitySet.map(action => { return action.action })
                per.actionList = action
              }
            })
            role.permissionList = role.permissions.map(permission => { return permission.permissionId })
            commit('SET_ROLES', result.role)
            commit('SET_INFO', result)
          } else {
            reject(new Error('getInfo: roles must be a non-null array !'))
          }

          commit('SET_NAME', { name: result.name, welcome: welcome() })
          commit('SET_AVATAR', result.avatar)

          resolve(response)
        }).catch(error => {
          reject(error)
        })
      })
    }
```

```
if (Vue.ls.get(ACCESS_TOKEN)) {
    /* has token */
    if (to.path === '/user/login') {
      next({ path: defaultRoutePath })
      NProgress.done()
    } else {
      if (store.getters.roles.length === 0) {
        store
          .dispatch('GetInfo')
          .then(res => {
          // 到这里生成动态路由的时候你是怎么过去的
            const roles = res.result && res.result.role
            store.dispatch('GenerateRoutes', { roles }).then(() => {
              // 根据roles权限生成可访问的路由表
              // 动态添加可访问路由表
              router.addRoutes(store.getters.addRouters)
              // 请求带有 redirect 重定向时，登录自动重定向到该地址
              const redirect = decodeURIComponent(from.query.redirect || to.path)
              if (to.path === redirect) {
                // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
                next({ ...to, replace: true })
              } else {
                // 跳转到目的路由
                next({ path: redirect })
              }
            })
          })
```

**Comment by labike** [comment]
@githwc 
```
function filterAsyncRouter(routerMap, roles) {
  var accessedRouters = routerMap.filter(function (route) {
    if (hasPermission(roles.permissionList, route)) {
      if (route.children && route.children.length) {
        route.children = filterAsyncRouter(route.children, roles);
      }

      return true;
    }

    return false;
  });
  return accessedRouters;
}
```

TypeError: roles is undefined

**Comment by githwc** [comment]
> @githwc
> 
> ```
> GetInfo ({ commit }) {
>       return new Promise((resolve, reject) => {
>         getInfo().then(response => {
>           // console.log('response is:', response)
>           const result = response.data
> 
>           result.role = { id: 'admin', name: '管理员', permissions: [ { 'roleId': 'admin', 'permissionId': 'admin' } ] }
> 
>           if (result.role && result.role.permissions.length > 0) {
>             const role = result.role
>             role.permissions = result.role.permissions
>             role.permissions.map(per => {
>               if (per.actionEntitySet != null && per.actionEntitySet.length > 0) {
>                 const action = per.actionEntitySet.map(action => { return action.action })
>                 per.actionList = action
>               }
>             })
>             role.permissionList = role.permissions.map(permission => { return permission.permissionId })
>             commit('SET_ROLES', result.role)
>             commit('SET_INFO', result)
>           } else {
>             reject(new Error('getInfo: roles must be a non-null array !'))
>           }
> 
>           commit('SET_NAME', { name: result.name, welcome: welcome() })
>           commit('SET_AVATAR', result.avatar)
> 
>           resolve(response)
>         }).catch(error => {
>           reject(error)
>         })
>       })
>     }
> ```
> 
> ```
> if (Vue.ls.get(ACCESS_TOKEN)) {
>     /* has token */
>     if (to.path === '/user/login') {
>       next({ path: defaultRoutePath })
>       NProgress.done()
>     } else {
>       if (store.getters.roles.length === 0) {
>         store
>           .dispatch('GetInfo')
>           .then(res => {
>           // 到这里生成动态路由的时候你是怎么过去的
>             const roles = res.result && res.result.role
>             store.dispatch('GenerateRoutes', { roles }).then(() => {
>               // 根据roles权限生成可访问的路由表
>               // 动态添加可访问路由表
>               router.addRoutes(store.getters.addRouters)
>               // 请求带有 redirect 重定向时，登录自动重定向到该地址
>               const redirect = decodeURIComponent(from.query.redirect || to.path)
>               if (to.path === redirect) {
>                 // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
>                 next({ ...to, replace: true })
>               } else {
>                 // 跳转到目的路由
>                 next({ path: redirect })
>               }
>             })
>           })
> ```

src/permission.js 不用管
这是我的src/store/modules/user.js
`// 登录
    Login ({ commit }, userInfo) {
      return new Promise((resolve, reject) => {
        login(userInfo).then(response => {
          const result = response.data
          Vue.ls.set(ACCESS_TOKEN, result.token, 7 * 24 * 60 * 60 * 1000)
          commit('SET_TOKEN', result.token)
          resolve()
        }).catch(error => {
          reject(error)
        })
      })
    },

    // 获取用户信息
    GetInfo ({ commit }) {
      return new Promise((resolve, reject) => {
        getInfo().then(response => {
          const result = response.data
          result.role = { id: 'admin', name: '管理员', permissions: [ { 'roleId': 'admin', 'permissionId': 'admin' } ] }
          if (result.role && result.role.permissions.length > 0) {
            const role = result.role
            role.permissions = result.role.permissions
            role.permissions.map(per => {
              if (per.actionEntitySet != null && per.actionEntitySet.length > 0) {
                const action = per.actionEntitySet.map(action => { return action.action })
                per.actionList = action
              }
            })
            role.permissionList = role.permissions.map(permission => { return permission.permissionId })
            commit('SET_ROLES', result.role)
            commit('SET_INFO', result)
          } else {
            reject(new Error('getInfo: roles must be a non-null array !'))
          }

          commit('SET_NAME', { name: result.name, welcome: welcome() })
          commit('SET_AVATAR', '/avatar2.jpg')

          resolve(response)
        }).catch(error => {
          reject(error)
        })
      })
    }`

**Comment by githwc** [comment]
@labike 刚看了下 src/permission.js  有个别代码我动过
29行  const roles = res.result && res.result.role  -> const roles = res.data && res.data.role
匹配了自己的返回格式

**Comment by githwc** [comment]
@labike 
整体改动的地方包括以下几处:

1. src/main.js -> 去除mock
2. src/permission.js 
`29行 const roles = res.result && res.result.role -> const roles = res.data && res.data.role`

3. src/views/user/Login.vue
`147行去除前端md5加密(个人不需要,根据自身情况而定)` 
4. src/store/modules/user.js
`40行  const result = response.result - > const result = response.data`
`根据自身json格式修改`
`54,55行 `
`const result = response.data  -根据自身json格式修改`
` result.role = { id: 'admin', name: '管理员', permissions: [ { 'roleId': 'admin', 'permissionId': 'admin' } ] }`
5. src/config/router.config.js
`路由权限控制改为admin  permission: [ 'admin' ]  --根据自身情况修改`
6. src/api/index.js
`修改api请求地址为个人后端地址`

**Comment by labike** [comment]
@githwc 非常感谢 我试试 有啥不懂得再来请教你

**Comment by labike** [comment]
@githwc 
```
{
	"code": 1,
	"message": "查询成功",
	"data": {
		"id": 1,
		"name": "ce",
		"phone": "18629329082",
		"qq": "",
		"balance": "0.00",
		"menu": [
			{
				"id": 118,
				"type": 2,
				"is_show": 1,
				"name": "主页",
				"parent_id": 0,
				"app": "",
				"controller": "",
				"action": "",
				"icon": "",
				"remark": "",
				"create_time": "2020-04-23 14:50:39",
				"update_time": "2020-04-23 14:50:39",
				"delete_time": 0,
				"order": 0
			},
			{
				"id": 119,
				"type": 2,
				"is_show": 1,
				"name": "平台公告",
				"parent_id": 0,
				"app": "",
				"controller": "",
				"action": "",
				"icon": "",
				"remark": "",
				"create_time": "2020-04-23 14:50:54",
				"update_time": "2020-04-23 14:50:54",
				"delete_time": 0,
				"order": 0
			},
    ]
}
```
像后端返回的这种数据不涉及权限处理的该怎么动态生成菜单树呢?

**Comment by labike** [comment]
@zfboy 老哥 跳转好了没

**Comment by labike** [comment]
@githwc 老哥 按照你上面的改完后 redirect='/404' 登录完后直接跳转到404了 该怎么处理这个问题
![redirect404](http://img.labike.site/ant-design-redirect.png)

**Comment by githwc** [comment]
路由里的菜单权限配置的是否正确?

**Comment by labike** [comment]
@githwc 已解决

**Comment by huanglou** [comment]
> @githwc 已解决

大佬您好！小白一枚。请问路由里的菜单权限是怎么配置的，我用的是最新的2.0.3版本，在里面加上这个authority: ['admin'],登录成功后还是跳不了首页，请指教，感谢。

**Comment by huanglou** [comment]
> 路由里的菜单权限配置的是否正确?

大佬您好！小白一枚。请问路由里的菜单权限是怎么配置的，我用的是最新的2.0.3版本，在里面加上这个authority: ['admin'],登录成功后还是跳不了首页，请指教，感谢。

**Comment by arraycto** [comment]
@labike @githwc   我的一直跳转404 ，后来调整路由器菜单api的数值，现在一直【http://127.0.0.1:8000/dashboard/workplace】白屏，浏览器的这个界面一片空白，控制台不报错，请问大佬，思路。

**Comment by devotion987** [comment]
@labike 我的logSuccess中拿不到res，请问这是为啥？
