### ISSUE TITLE
List <s-table/>组件 能否增根据分页显示序号功能？

### ISSUE THREAD

**Issue by DaskV** [vueComponent/ant-design-vue-pro#737]

**Comment by kokoroli** [comment]
定制化需求，可自行使用 a-table 封装

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/views/list/TableList.vue#L90 

配合 stable 的 load 方法回调，自己纪录当前分页数
