### ISSUE TITLE
生产环境为什么控制台没有console.log打印了?

### ISSUE THREAD

**Issue by zhichao8756** [vueComponent/ant-design-vue-pro#739]
开发环境:
![image](https://user-images.githubusercontent.com/24514251/80332022-45683180-887c-11ea-96ad-db4f312f4a2f.png)
生产环境:
![image](https://user-images.githubusercontent.com/24514251/80332032-5153f380-887c-11ea-8251-0f623a691d0a.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/babel.config.js#L5
