### ISSUE TITLE
使用FormModel报错

### ISSUE THREAD

**Issue by chenqq86** [vueComponent/ant-design-vue-pro#740]
**Question （问题描述）**
使用FormModel报错，console里报Unknown custom element: <a-form-model> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Describe the solution you'd like （你期待的是什么？）**
没报错

**Additional context（附加信息）**

**Comment by sendya** [comment]
升级 antd 版本，自行注册组件
