### ISSUE TITLE
Modal改写的dialog调用时回调信息

### ISSUE THREAD

**Issue by mingzaily** [vueComponent/ant-design-vue-pro#741]
**Question （问题描述）**
希望能够调用dialog时回调信息
![企业微信截图_15879624774513.png](https://i.loli.net/2020/04/27/YzV7SkroiyNUQp1.png)

**Describe the solution you'd like （你期待的是什么？）**
点击确定提交后，dialog关闭，页面刷新，或者有别的方式通知dialog按下确定还是取消

**Comment by sendya** [comment]
不是有 close 和 onOk 事件？

**Comment by mingzaily** [comment]
> 不是有 close 和 onOk 事件？

页面调用dialog组件的时候，组件的onOk()有效，但是不能回调给页面，就是想触发下刷新
场景：
1. 新增数据，按下确定，提示发布成功，组件消失（这一步有效）
![JHM88H.png](https://s1.ax1x.com/2020/04/29/JHM88H.png)
2. 就是想在resolve(true)的时候，返回给页面一个信息，让我能够刷新数据
![JHMcMn.png](https://s1.ax1x.com/2020/04/29/JHMcMn.png)

- 感谢作者，我是个前端新手，主要做后端，前端确实是第一次写，不太清楚

**Comment by yoder** [comment]
onOk如何触发表单的提交事件？

**Comment by mingzaily** [comment]
> onOk如何触发表单的提交事件？

```
this.$dialog(TaskForm,
    // component props
    {
        record: {},
        on: {
        ok () {
            console.log('ok 回调')
        },
        cancel () {
            console.log('cancel 回调')
        },
        close () {
            console.log('modal close 回调')
        }
        }
    },
    // modal props
    {
        title: '新增',
        width: 700,
        centered: true,
        maskClosable: false
    }
)
```
作者在后续版本补充了示例耶
https://github.com/vueComponent/ant-design-vue-pro/commit/e5d303a5a1eded524cdf08c4fdb33c0f7b01873a
在src/views/list/BasicList.vue下

**Comment by mingzaily** [comment]
> onOk如何触发表单的提交事件？

至于TaskForm如何触发提交
```
onOk () {
      return new Promise(resolve => {
        const { form: { validateFields } } = this
        validateFields((errors, values) => {
          if (!errors) {
            updatePassword(values).then(() => {
              this.$notification.success({
                message: '提示',
                description: '更新成功'
              })
              resolve(true)
            }).catch(() => { resolve(false) })
          } else resolve(false)
        })
      })
    },
    onCancel () {
      return new Promise(resolve => {
        resolve(true)
      })
    }
```
这是我的，也可以看看https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/views/list/modules/TaskForm.vue

**Comment by yoder** [comment]
> > 不是有 close 和 onOk 事件？
> 
> 页面调用dialog组件的时候，组件的onOk()有效，但是不能回调给页面，就是想触发下刷新
> 场景：
> 
> 1. 新增数据，按下确定，提示发布成功，组件消失（这一步有效）
>    ![JHM88H.png](https://camo.githubusercontent.com/248c160ff43fd984675220ebbc150b0aba0d7d87/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f32392f4a484d3838482e706e67)
> 2. 就是想在resolve(true)的时候，返回给页面一个信息，让我能够刷新数据
>    ![JHMcMn.png](https://camo.githubusercontent.com/79a60ee4ad79b21d57a7ebfe9fad8b6042af16df/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f32392f4a484d634d6e2e706e67)
> 
> * 感谢作者，我是个前端新手，主要做后端，前端确实是第一次写，不太清楚

所以其实你这个问题也是一样的。。。在this.$dialog调用的时候定义对应的**on: {ok() {//这里放刷新的代码即可}}**

**Comment by sendya** [comment]
modal 内部组件 emit 事件出来，或者 reject Promise 出去。

**Comment by wangz-code** [comment]
**子组件提交数据至父组件**

子组件提交数据

`
methods: {
    onOk () {
      this.$emit('ok', '子组件的数据')
    }
  }
`
------------------
父组件接收数据


` this.$dialog(TaskForm, {
          on: {
            ok (e) {
              console.log('ok 回调', e)
            }
          }
 }
`
------------------



子组件emit 数据传值 至 父组件的ok回调函数  特此记录一下
