### ISSUE TITLE
npm run build 后设置的主体颜色不起作用，其他选项正常，localstorage pro__DEFAULT_COLOR 也是对的。

### ISSUE THREAD

**Issue by luchaohui** [vueComponent/ant-design-vue-pro#746]
npm run build 后设置的主体颜色不起作用，其他选项正常，localstorage pro__DEFAULT_COLOR 也是对的。

**Comment by sendya** [comment]
颜色变量请直接在 vue.config.js 中 less 块进行配置覆盖主题色
