### ISSUE TITLE
麻烦配置一下支持多种环境

### ISSUE THREAD

**Issue by imhtang** [vueComponent/ant-design-vue-pro#75]
很喜欢你的这个项目，打算用于公司的后台管理系统中，因公司项目开发区分本地环境、测试环境和生产环境，按照官方文档 https://cli.vuejs.org/zh/guide/mode-and-env.html 配置后一直读取不到环境变量的值，由于首次使用yarn，不知道是否yarn的关系，能否在此项目里支持，以便我参考，非常感谢

**Comment by sendya** [comment]
1. 跟 yarn 无关系
2. vue 官方文档可正常使用，我亲测过
3. 如果有问题，可以提供一下使用/运行环境

Updated: _2019-02-17 PM 10:23_

![snipaste_2019-02-17_22-21-23](https://user-images.githubusercontent.com/5404542/52914403-ae602b00-3302-11e9-817f-4ed09dd16ae3.jpg)

> 当出现问题时，应当进行几次测试和与官方用例对比差异。而不是认为某一项东西导致的，除非网上有更多相同情况出现时

**Comment by sendya** [comment]
您好，过久未回复。将关闭该 issue
