### ISSUE TITLE
有一些疑问

### ISSUE THREAD

**Issue by nszbf** [vueComponent/ant-design-vue-pro#758]
**Question （问题描述）**
antdv 的版本还是1.5.0-rc.6 的情况下，为什么button等一些组件的border-radius变成了2px,
antdv 1.5.4却还是4px,也并没有看到global.less里面有改变，
还有现在里面把以前很多组件给隐藏了，是为什么，
进入vueCompment是意味着已经被官方纳入了吗？
名称也由 pro-vue 改成了 vue-pro ...

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
1. 目前任何版本都没修改 `border-radius` ，所有改动均为我本人喜好，在 antd 提供的自定义主题中，由 less-loader 处理掉了全局的变量，具体参阅 antd vue 官方文档。

2. 隐藏组件不为什么，单纯还没测试而已

3. 我很早就是 vueComponent 的组织成员
