### ISSUE TITLE
开发环境调试时，切换多页签模式，导致路由跳转报错

### ISSUE THREAD

**Issue by zhang1395hao** [vueComponent/ant-design-vue-pro#760]
**Describe the bug （描述 Bug）**

开发环境调试时，切换至多页签模式，导致路由跳转报错，每跳转一次，控制台就报一次错

![1](https://user-images.githubusercontent.com/37215660/81479996-4ffdd000-9259-11ea-8b88-a9dbdfaeeba2.png)

**Comment by sendya** [comment]
请提供有效错误信息

**Comment by zhang1395hao** [comment]
> 请提供有效错误信息
```
message: "Navigating to current location (XXX) is not allowed"
name: "NavigationDuplicated"
```

开启多页签模式，并打开浏览器控制台每次路由跳转都提示，影响调试

**Comment by sendya** [comment]
重复跳转相同 router，自己做个判断处理吧。 
大概在这个位置 https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/components/MultiTab/MultiTab.vue#L131

> multi-tab 性能极差已经不提供维护，请自行处理

**Comment by zhang1395hao** [comment]
> 重复跳转相同 router，自己做个判断处理吧。
> 大概在这个位置 https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/components/MultiTab/MultiTab.vue#L131
> 
> > multi-tab 性能极差已经不提供维护，请自行处理

这个判断怎么加？能给出提示吗？尝试好多次失败，感觉这里应该是死循环了，
