### ISSUE TITLE
官方pro-demo，查询表格- 二次封装的S-Table，选择存在分页Bug

### ISSUE THREAD

**Issue by zhang1395hao** [vueComponent/ant-design-vue-pro#761]
**Describe the bug （描述 Bug）**

官方pro-demo，查询表格- 二次封装的S-Table，选择存在分页Bug，

选择时，可输出 观察
console.log(this.selectedRows)
console.log(this.selectedRowKeys)

发现，当切换分页后，再次选择新current页，原来的this.selectedRows 会被替换，而不是追加，导致alert 部分的total错误，但是this.selectedRowKeys 又是正常的，会给人选择上的视觉错误，这部分代码看的很是头疼

![2](https://user-images.githubusercontent.com/37215660/81480145-4b85e700-925a-11ea-8dc4-f132b86b7dd8.png)

**Comment by sendya** [comment]
有考虑重新设计这个组件，如果不符合你的需求，请使用 a-table 来实现

**Comment by cwandev** [comment]
官网就不打算修复这个问题吗？

**Comment by sendya** [comment]
> 官网就不打算修复这个问题吗？

建议自行修改，或使用 a-table
