### ISSUE TITLE
a-anchor使用异常

### ISSUE THREAD

**Issue by alwayChina** [vueComponent/ant-design-vue-pro#765]
**项目中组件使用异常**
在使用Ant Design Vue的组件a-anchor时出现问题，组件引用成功，控制台也没报错，但是锚点就是不出来。麻烦看下是什么问题，蟹蟹
![image](https://user-images.githubusercontent.com/45747019/81539115-551a6680-93a2-11ea-9fb1-8e9301e67a38.png)
![image](https://user-images.githubusercontent.com/45747019/81539232-8abf4f80-93a2-11ea-8370-9ef71b29d65e.png)

**Comment by kokoroli** [comment]
componet: {
    aAnchor:Anchor,
    aAnchorLink: Anchor.Link
}
