### ISSUE TITLE
$auth 函数问题

### ISSUE THREAD

**Issue by whxcode** [vueComponent/ant-design-vue-pro#767]
**Describe the bug （描述 Bug）**
我觉得应该要改写一些地方，是代码强壮
![image](https://user-images.githubusercontent.com/44012914/81651274-25806280-9465-11ea-81c1-1d37ff7a1b8b.png)
如果不对 permissionList 返回值做验证，很难保证用户传入的参数有效性
![image](https://user-images.githubusercontent.com/44012914/81651108-08e42a80-9465-11ea-9082-db583ecdc15b.png)

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
你在开发的时候就应该对这些事情做处理，加以修改以适用你的项目。我们只提供一个实现思路
