### ISSUE TITLE
想在生产环境使用更换主题色的功能改怎么实现

### ISSUE THREAD

**Issue by xuzining** [vueComponent/ant-design-vue-pro#769]
我想在生产环境中把导航模式，主题色，整体风格等也能然让用户自定义，相当于提供一个自由的换肤功能，这个该怎么实现
![image](https://user-images.githubusercontent.com/16344817/81883354-93dd3600-95c7-11ea-9e62-2954f2c4d6cf.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/BasicLayout.vue#L56
