### ISSUE TITLE
多级菜单的问题 

### ISSUE THREAD

**Issue by XinJiangQingMang** [vueComponent/ant-design-vue-pro#77]
![image](https://user-images.githubusercontent.com/19700237/53025212-76d8b680-349b-11e9-88ef-16e9c81aff9a.png)

如图 【分析页3】下还有一个子页【分析页4】，如果【分析页4】设置属性隐藏  【分析页3】能否正常显示 

场景是这样的  如果 
![image](https://user-images.githubusercontent.com/19700237/53025465-ec448700-349b-11e9-8c35-3c19a7022c75.png)
【分析页3】是列表页，详情页【分析页4】点击table 的详情 跳转到【分析页4】分析页4不在左侧菜单栏显示 属于分析页3的子页 ，按照常理分析页3 可以点击为菜单  分析页4为隐藏菜单    点击详情的时候  依旧选中分析页3

**Comment by XinJiangQingMang** [comment]
谢谢大佬   项目很优秀

**Comment by sendya** [comment]
目前无法实现，也没思路 欢迎提供解决方案

**Comment by sendya** [comment]
提供了一个怎么用的 demo
ref https://github.com/sendya/ant-design-pro-vue/commit/5430878c2e75a904f9d6c3fa1a74c2509a825a50

路由文档： https://github.com/sendya/ant-design-pro-vue/blob/master/src/router/README.md

**Comment by XinJiangQingMang** [comment]
感谢大佬

**Comment by nuochong** [comment]
我也遇到同样的问题，同样的配置，但是还要正确的显示面包屑导航。
