### ISSUE TITLE
通过搜索列表子菜单切换时，页面Tab栏 active Tab 没有跟随路由变化

### ISSUE THREAD

**Issue by mx623303468** [vueComponent/ant-design-vue-pro#770]
**Describe the bug （描述 Bug）**

通过搜索列表子菜单切换时，页面Tab栏 active Tab 没有跟随路由变化

**To Reproduce （重现步骤）**

1. 点击菜单栏搜索列表的三个子菜单，（文章，应用，项目）
2. 页面Tab的高亮没有跟谁路由变化，但是通过点击Tab切换时，菜单高亮会跟随变化

**Expected behavior（你期待的是什么?）**
菜单切换和页面tab切换高亮(active tab)同步

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/36760861/81891992-9c8c3700-95dc-11ea-954a-6ec8b99a0f61.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
fixed a85c43808578a926cf6e52dbe37785e5431c0858
