### ISSUE TITLE
关于side bar滚动条晃动的解决方案

### ISSUE THREAD

**Issue by yoyo0926** [vueComponent/ant-design-vue-pro#774]
**Describe the bug （描述 Bug）**

sidebar固定了256，在鼠标碰触时，会出现滚动条，并且在各浏览器间样式不美观，关于此问题，暂提示小方案，供后来者借览，在侧边栏加两行CSS

  ::-webkit-scrollbar {
    display: none;
  }

暂时解决了

**Comment by sendya** [comment]
兼容性不好，不推荐使用

**Comment by sendya** [comment]
最好的做法是自己做一个滚动条，覆盖掉 任何浏览器自带的滚动条

**Comment by yoyo0926** [comment]
可以使用第三方滚动条插件吗？我之前考虑过这个方案来着
