### ISSUE TITLE
使用组件Tree

### ISSUE THREAD

**Issue by yoyo0926** [vueComponent/ant-design-vue-pro#775]
**Question （问题描述）**
使用官网antd pro vue的tree组件
`import STree from '@/components/Tree/Tree'
        <s-tree
          :dataSource="orgTree"
          :openKeys.sync="openKeys"
          :search="false"
          :ifNeedAdd="false"
          @click="handleTreeClick"
          @titleClick="handleTreeTitleClick">
          </s-tree>
`

在捕获handleTreeClick事件时，不仅仅想要获取key，还想要取当前node的其他字段，比如我另外添了level，cate_id，等，请问如何获取，比如我当前节点数据是这样的：
`"key": "1",
         "title": "江苏省",
         "icon": "folder",
         "group": true,
         "level": 2,
         "id": "1",`

**Describe the solution you'd like （你期待的是什么？）**
希望在handleTreeClick事件中，可以获取到group，id，level

**Additional context（附加信息）**

**Comment by sendya** [comment]
stree 是我随手封装的，不一定适合所有人的业务逻辑，源码都在里面，你可以自己修改。API 是基于 Menu
