### ISSUE TITLE
Timeline组件使用不生效？

### ISSUE THREAD

**Issue by YIXIANG0234** [vueComponent/ant-design-vue-pro#777]
**Question （问题描述）**
在自定义组件中使用Timeline组件样式没有生效，但是其他的antd组件可以正常使用，并且控制台有错误信息，错误信息如下：
![image](https://user-images.githubusercontent.com/33951809/82134687-c8056080-982c-11ea-86e2-ec0374cf22d1.png)
代码如下：
![image](https://user-images.githubusercontent.com/33951809/82134693-d489b900-982c-11ea-8cfb-fea6e6a47f33.png)
页面显示效果如下：样式没有生效，全都挨在一起了
![image](https://user-images.githubusercontent.com/33951809/82134707-f84cff00-982c-11ea-86c3-7e02da7dedd3.png)

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**
antd的其他组件都可以正常使用啊，目前就发型Timeline不可以，其他组件使用的使用也没有要引入呀，求解答。

**Comment by sendya** [comment]
没有引入组件，无效问题。请根据控制台说明自行处理

**Comment by YIXIANG0234** [comment]
但是其他vue组件用的时候也没有引入啊，比如Button使用的时候直接<a-button/>，并且不是在配置文件中配置了按需引入了吗？
