### ISSUE TITLE
网页预览版的 列表页中的标准列表中的编辑不能用

### ISSUE THREAD

**Issue by xiaozheqiu** [vueComponent/ant-design-vue-pro#778]
**Describe the bug （描述 Bug）**

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
fixed
