### ISSUE TITLE
主题

### ISSUE THREAD

**Issue by jiankian** [vueComponent/ant-design-vue-pro#78]

**Comment by jiankian** [comment]
最新版本，颜色没效果其它有

**Comment by sendya** [comment]
请详细提供您的运行环境，否则将无法为您排查和解决问题。

我在本地 和 服务器上的 demo 都进行了测试，均未发现你所描述的问题
![20190220091653](https://user-images.githubusercontent.com/5404542/53059016-57b84400-34f0-11e9-9dc5-2ae54bd4eb51.png)

**Comment by jiankian** [comment]
有时候选择的是固定左侧sidebar菜单 但是 复制出来的参数是 不固定的，得手动修改。
其次是颜色改了，复制到配置文件里是红色的，然后我清除浏览器缓存，重新启动项目，颜色还是蓝色。只有在侧边那个工具栏点颜色才切换颜色。默认的项目。没修改过

**Comment by sendya** [comment]
配置项仅供参考，具体颜色覆盖需要从 `vue.config.js` 覆盖。 sidebar 复制错来是错的这个问题我在排查一下
