### ISSUE TITLE
新版本pro不支持<a-tree>标签

### ISSUE THREAD

**Issue by seadonzhang** [vueComponent/ant-design-vue-pro#780]
新版本pro不支持a-tree标签
2.0.0版本可以.
提示未注册组件.
`[Vue warn]: Unknown custom element: <a-tree> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by shiyuanzheng** [comment]
注册一下就可以了

**Comment by sendya** [comment]
自行注册
