### ISSUE TITLE
下拉菜单的事件问题

### ISSUE THREAD

**Issue by kasnet** [vueComponent/ant-design-vue-pro#781]
**Describe the bug （描述 Bug）**

`<a-dropdown>
          <a-menu
            slot="overlay"
            v-decorator="[
              'component',
              {rules: [{ required: true, message: '请新增组件' }]}
            ]"
            @click="onClick()">
            <a-menu-item key="1"> <a-icon type="user" />1st menu item </a-menu-item>
            <a-menu-item key="2"> <a-icon type="user" />2nd menu item </a-menu-item>
            <a-menu-item key="3"> <a-icon type="user" />3rd item </a-menu-item>
          </a-menu>
          <a-button style="margin-left: 8px" @click="e => e.preventDefault()"> 组件 <a-icon type="down" /> </a-button>
        </a-dropdown>`
`methods: onClick (e) {
      console.log('click', e)
    }`
在a-menu上有个click事件, 选中其中一个a-menu-item应该可以返回选中的a-menu-item信息, 现在什么信息都没有
环境: tag:2.0.2版本

**Comment by sendya** [comment]
绑定事件写错了吧 onClick() ? 不应该是不带括号的吗

**Comment by kasnet** [comment]
是写错了, 没注意到
