### ISSUE TITLE
设置为多页面模式，ant design pro of vue 中自带的cdn 该怎么配置？

### ISSUE THREAD

**Issue by yanduhantan1991** [vueComponent/ant-design-vue-pro#783]
**Question （问题描述）**
vueConfig中按照webpack官网添加pages属性后，设置为多页面模式， 
会和这段代码冲突      
`config.plugin('html').tap(args => {
                args[0].cdn = assetsCDN
                return args
            })`     
要想使用多页面，该怎么配置呢

谢谢

**Comment by sendya** [comment]
没尝试过，你自己查下 webpack@4 资料吧

**Comment by clddup** [comment]
我按照vue-cli 配置pages后, 进不去我的页面了, 一直在loading @yanduhantan1991 老哥怎么做的
