### ISSUE TITLE
官网无法打开，要切换新版本吗？大概多久可以放出来？老版本迁移成本有多高？

### ISSUE THREAD

**Issue by MissSanSui** [vueComponent/ant-design-vue-pro#784]
**Question （问题描述）**
官网无法打开，要切换新版本吗？大概多久可以放出来？老版本迁移成本有多高？

**Describe the solution you'd like （你期待的是什么？）**
官网无法打开，要切换新版本吗？大概多久可以放出来？老版本迁移成本有多高？
**Additional context（附加信息）**
官网无法打开，要切换新版本吗？大概多久可以放出来？老版本迁移成本有多高？

**Comment by sendya** [comment]
时间暂定。 迁移成本看水平。
