### ISSUE TITLE
多环境配置问题

### ISSUE THREAD

**Issue by zhanghaiguo** [vueComponent/ant-design-vue-pro#785]
**Question （问题描述）**
我在`.env`和`.env.development`文件中增加配置项：`wsurl=ws://xxxx`，然后通过`process.env.wsurl`获取到的值为`undefined`，请问我应该怎么样才能获取到`wsurl`的值

**Comment by sendya** [comment]
https://cli.vuejs.org/guide/mode-and-env.html

请阅读 vue 和 vue 相关组件生态文档
