### ISSUE TITLE
组件Skeleton的使用方式

### ISSUE THREAD

**Issue by learnwritebug** [vueComponent/ant-design-vue-pro#786]
**Question （问题描述）**
怎么使用组件Skeleton 骨架屏呢？ 我看到分析页有骨架屏效果。但没找到骨架屏的相关代码。还请有空告知下。

**Describe the solution you'd like （你期待的是什么？）**
期望能找到骨架屏使用的相关的代码。比如分析页的骨架屏效果我没有找到相关代码。

**Additional context（附加信息）**
看文档是使用 `<a-skeleton />` 标签，但我全项目搜索没有搜到这个项目在哪里使用了。很好奇。但分析页 有骨架屏。  还请帮我解惑下，先感谢啦

**Comment by sendya** [comment]
a-card 自带功能

**Comment by sendya** [comment]
https://antdv.com/components/card-cn/#components-card-demo-loading-card
