### ISSUE TITLE
封装的 table如何使用动态渲染字段

### ISSUE THREAD

**Issue by mayuqi827** [vueComponent/ant-design-vue-pro#788]
**Question （问题描述）**
我自己封装了table组件ptable，columns从后台动态获取，原来a-table内是通过
`<span slot="username" slot-scope="text"> <b>{{text.username}} </b></span>`
来操作username的显示，现在需要使用ptable组件将text（行数据）传到父组件做中，我在原table中使用this.$slots循环，一直都无法将text传到我的父组件中去

**Describe the solution you'd like （你期待的是什么？）**
ant vue pro组件中封装的table使用render方法渲染，因为使用template写的组件，没有找到解决方法

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/components/Table/index.js#L305
