### ISSUE TITLE
新版本什么时候发布

### ISSUE THREAD

**Issue by magicpal** [vueComponent/ant-design-vue-pro#789]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IMJacky** [comment]
@sendya 
 有没有微信群，QQ群，钉钉群之类的，可以发一下嘛，想赞助一下都找到地方~

**Comment by sendya** [comment]
暂未安排新版发布时间，请直接用 master 或 release 发布版本。
新版与旧版不会做向下兼容，要兼容请自行动手。

没有群，要捐助请直接捐到 `ant-design-vue` 项目，本项目基于 `ant-design-vue`，没有她，就没有这个项目
