### ISSUE TITLE
输入框和按钮圆角问题

### ISSUE THREAD

**Issue by wangzhen-CHN** [vueComponent/ant-design-vue-pro#790]
Antd Vue PRO中 输入框和按钮组件的圆角都是2px，而官方的这些组件圆角都是4px，为什么会出现这个差异呢，感觉尖锐了很多
**Antd Vue PRO**
`.ant-input{
border-radius: 2px;
}
.ant-btn{
border-radius: 2px;
}`
**Antd Vue** 
`
.ant-input{
border-radius: 4px;
}
.ant-btn{
border-radius: 4px;
}`

**Comment by zkwolf** [comment]
大概是因为ant design v4规范里把圆角改成2px了吧

**Comment by wangzhen-CHN** [comment]
> 大概是因为ant design v4规范里把圆角改成2px了吧
嗯 可能是这个原因，但是我使用的不是v4版本~

**Comment by lvfangren** [comment]
建议拉取master分支最新代码，看下vue.config.js文件的79行

**Comment by lvfangren** [comment]
> > 大概是因为ant design v4规范里把圆角改成2px了吧
> > 嗯 可能是这个原因，但是我使用的不是v4版本~

**Comment by wangzhen-CHN** [comment]
> 建议拉取master分支最新代码，看下vue.config.js文件的79行

看到了  多谢指点

**Comment by wangzhen-CHN** [comment]
vue.config.js文件的79行
