### ISSUE TITLE
修改主题为“light”不生效

### ISSUE THREAD

**Issue by D-wuque** [vueComponent/ant-design-vue-pro#792]
**Describe the bug （描述 Bug）**

修改主题为“light”不生效

**To Reproduce （重现步骤）**

1. 修改src/config/defaultSettings.js文件中的17行
```
navTheme: 'light', // theme for nav menu
```

**Expected behavior（你期待的是什么?）**
希望将主题切换为light

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/49566928/82793113-f6c1ad80-9ea2-11ea-96d9-cd48800508fb.png)
![image](https://user-images.githubusercontent.com/49566928/82793213-22dd2e80-9ea3-11ea-953c-56e8d8710d7f.png)

****

**Desktop (please complete the following information):**

 - OS: [e.g. win]
 - Version [3.0.0]

**Comment by Dishone** [comment]
清除localStorage

**Comment by sendya** [comment]
fixed https://github.com/vueComponent/ant-design-vue-pro/commit/ff553bc13a7eee767371414eb86edea4381c0602
