### ISSUE TITLE
设置面板 Theme Color  切换成第一个蓝色不起作用

### ISSUE THREAD

**Issue by dargoner** [vueComponent/ant-design-vue-pro#796]
**Describe the bug （描述 Bug）**

设置面板 Theme Color  ，从蓝色切换成其他主题色，然后再切换成蓝色就不起作用

**To Reproduce （重现步骤）**

https://preview.pro.loacg.com/dashboard/workplace 官网演示地址

![image](https://user-images.githubusercontent.com/1793850/83087025-da03c080-a0c2-11ea-808f-17146d5203b7.png)

**Expected behavior（你期待的是什么?）**

切换成蓝色

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/1793850/83087075-f1db4480-a0c2-11ea-9488-2e62fe0553d8.png)

**Desktop (please complete the following information):**

 - OS: WIN10
 - Browser 360浏览器
 - Version 12

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by lvfangren** [comment]
在网站的预览里确实存在问题，但是本地跑的时候（运行于refactor/pro-v3分支）我这没重现，网站里的Build date: 2020-5-21 11:55:26

**Comment by sendya** [comment]
fixed https://github.com/vueComponent/ant-design-vue-pro/commit/ff553bc13a7eee767371414eb86edea4381c0602
