### ISSUE TITLE
mock数据不一致？

### ISSUE THREAD

**Issue by ofnhkb1** [vueComponent/ant-design-vue-pro#8]
项目中使用的mock数据是https://mock.ihx.me/mock/5baf3052f7da7e07e04a5116/antd-pro
如果直接切换成README.md中写的https://www.easy-mock.com/project/5b7bce071f130e5b7fe8cd7d则会提示错误
是否是实际使用的mock数据不一致？

**Comment by sendya** [comment]
测试没发现数据不一致

![20181115234822](https://user-images.githubusercontent.com/5404542/48564250-f9982580-e930-11e8-9a5a-fe3e34bd0ccb.png)

> 如果你说的是 step2-code 接口。这个接口本身就不存在
