### ISSUE TITLE
请紧急修复:PageHeader 页头 ==> 带面包屑页头 设置 breadcrumb 引发的三个bug 

### ISSUE THREAD

**Issue by chen00jian** [vueComponent/ant-design-vue-pro#802]
问题版本代码:@ant-design-vue\pro-layout 
 
  【node_modules\@ant-design-vue\pro-layout\es\components\PageHeaderWrapper\index.js】

bug:
1、PageHeader 设置breadcrumb 类型验证失败
2、itemRender缺失
3、Breadcrumb 面包屑 【和 browserHistory 配合】文档示例代码错误！

**Describe the bug （描述 Bug）**

需求：
在使用antd vue pro的时候，在使用菜单面包屑导航的时候因为是hash(#)的形式，需要改成 browserHistory 形式。

官方文档（https://www.antdv.com/components/breadcrumb-cn/#API） Breadcrumb 面包屑 【和 browserHistory 配合】

使用的是<a-breadcrumb />

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

package.json 版本

 {
  **"name": "vue-antd-pro",
  "version": "3.0.0",**
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint",
    "build:preview": "vue-cli-service build --mode preview",
    "lint:nofix": "vue-cli-service lint --no-fix"
  },
  "dependencies": {
    **"@ant-design-vue/pro-layout": "^0.2.11-0",**
    "@antv/data-set": "^0.10.2",
    "ant-design-vue": "1.6.0",

期望是将 hash改成browserHistory
![image](https://user-images.githubusercontent.com/3582728/83371056-cecad080-a3f3-11ea-923d-bf427568cf58.png)

**bug: 数据类型校验失败**

![image](https://user-images.githubusercontent.com/3582728/83371510-2fa6d880-a3f5-11ea-9969-aa51c5d3eca1.png)

![image](https://user-images.githubusercontent.com/3582728/83371768-06d31300-a3f6-11ea-8f4b-88b065ba1c8f.png)

代码位置： node_modules\@ant-design-vue\pro-layout\es\components\PageHeaderWrapper\index.js

bug：  breadcrumb: PropTypes.**oneOf**([PropTypes.object, PropTypes.bool]).def(true),
fixed bud:  breadcrumb: PropTypes.**oneOfType**([PropTypes.object, PropTypes.bool]).def(true),

**bug:itemRender无效**

页面代码
![image](https://user-images.githubusercontent.com/3582728/83372626-6b8f6d00-a3f8-11ea-821e-73a133c92b28.png)

![image](https://user-images.githubusercontent.com/3582728/83372747-cb861380-a3f8-11ea-9b0a-4b11f2cc271e.png)

**bug:文档使用错误（https://www.antdv.com/components/breadcrumb-cn/#API）=》  **paths**?**

![image](https://user-images.githubusercontent.com/3582728/83372489-03408b80-a3f8-11ea-9266-0c2bae14540e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by no1xsyzy** [comment]
看不懂这针线活，你可以重新组织语言、发 PR 或者发 patch 文件。

**Comment by sendya** [comment]
try use `@ant-design-vue/pro-layout` `0.3.0`

**Comment by WangGuanJie1** [comment]
我也遇到了这样的问题，renturn 回来的 router-link都是相同的path
