### ISSUE TITLE
能否添加滚动条组件, 或美化默认滚动条, 类似elementui那种

### ISSUE THREAD

**Issue by Lan-W** [vueComponent/ant-design-vue-pro#804]
在做一些大数据平台时,往往设计师会设计成暗黑主题, 浏览器默认的滚动条太扎眼了,自己引入第三方滚动条美化插件的话, 对于table或者select这些组件却无法设置, 很是烦恼呢

**Comment by sendya** [comment]
你可以去 react antd 的库里提 issue ，因为本项目只是实现 antd 是规范，并不会定制规范。你在那边被确定的规范 如果通过，这边也会同步

**Comment by Lan-W** [comment]
好的, 谢谢
