### ISSUE TITLE
如何根据不同的角色来动态设置侧边导航栏？

### ISSUE THREAD

**Issue by JaneyJso** [vueComponent/ant-design-vue-pro#805]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by JaneyJso** [comment]
需要动态设置导航栏的显示

**Comment by JaneyJso** [comment]
不用menu组件的动态菜单，有没有什么思路？望告知。

**Comment by sendya** [comment]
> 不用menu组件的动态菜单，有没有什么思路？望告知。

没有

**Comment by mynetfan** [comment]
文档中不是有说明如何从服务器动态加载导航菜单吗？

**Comment by codeliufan** [comment]
给导航栏路由加上权限吧，不同角色分配不同的权限
