### ISSUE TITLE
生产环境的主题换色

### ISSUE THREAD

**Issue by z0ffy** [vueComponent/ant-design-vue-pro#806]
**Question （问题描述）**
 为什么 需要增加 VUE_APP_PREVIEW 判断主题换色才可以生效

我尝试过在vue.config.js 中去掉if (process.env.VUE_APP_PREVIEW === 'true')  打包上线之后主题色失效

**Describe the solution you'd like （你期待的是什么？）**
希望大佬解答一下

**Comment by sendya** [comment]
由于换色功能性能极差，生产环境是默认禁用的。如果手动开启，请具备一定的问题处理能力并自己处理问题。否则请使用 vue.config.js 内的 less 样式变量覆盖功能对主题进行定制

**Comment by Mark24Code** [comment]
原来如此，也在纳闷，为啥要单独设置一个 VUE_APP_PREVIEW
