### ISSUE TITLE
运行 yarn run serve时报错。

### ISSUE THREAD

**Issue by java8site** [vueComponent/ant-design-vue-pro#809]
运行时候git-revision-webpack-plugin这个插件好像报错，我没用git，本地没安装git
以下为报错信息。
$ vue-cli-service serve
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 ERROR  Error loading vue.config.js:
 ERROR  Error: Command failed: git describe --always
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Error: Command failed: git describe --always
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at module.exports (D:\workspace\vue\admin-antd-vue\node_modules\git-revision-webpack-plugin\lib\helpers\run-git-command.js:25:34)
    at GitRevisionPlugin.version (D:\workspace\vue\admin-antd-vue\node_modules\git-revision-webpack-plugin\lib\index.js:65:10)

**Comment by java8site** [comment]
装完git之后报以下错。
yarn run v1.19.1
$ vue-cli-service serve
fatal: not a git repository (or any of the parent directories): .git
 ERROR  Error loading vue.config.js:
 ERROR  Error: Command failed: git describe --always
fatal: not a git repository (or any of the parent directories): .git

Error: Command failed: git describe --always
fatal: not a git repository (or any of the parent directories): .git

**Comment by sendya** [comment]
用 git clone 下载项目

**Comment by java8site** [comment]
> 用 git clone 下载项目

用git clone可以正常运行。
