### ISSUE TITLE
打包后的生产环境一直显示 正在切换主题 

### ISSUE THREAD

**Issue by usoaufo** [vueComponent/ant-design-vue-pro#811]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by ReyLiang** [comment]
vue.config.js里有一个判断
`if (process.env.VUE_APP_PREVIEW === 'true') {
             console.log('VUE_APP_PREVIEW', true)
              // add `ThemeColorReplacer` plugin to webpack plugins
             vueConfig.configureWebpack.plugins.push(createThemeColorReplacerPlugin())
}`
`vueConfig.configureWebpack.plugins.push(createThemeColorReplacerPlugin())`
它没有加载,所以会出现找不到主题,看你想怎么做了..要不然就把.env的VUE_APP_PREVIEW设置为true,要不然就自己加判断

**Comment by zhichao8756** [comment]
我也碰到了这个问题,请问解决了吗?

**Comment by y2282373181** [comment]
是部署到二级目录上吗，如果是的话：@ant-design-vue\pro-layout\es\utils\dynamicTheme.js，第20行有一个叫做**‘/’ + cssUrl**改成**process.env.BASE_URL + cssUrl**试试看
