### ISSUE TITLE
请问V3重构版本，怎么去掉国际化功能？

### ISSUE THREAD

**Issue by gowin520** [vueComponent/ant-design-vue-pro#812]
请问V3重构版本，怎么去掉国际化功能？

**Comment by sendya** [comment]
pro-layout props  `:i18n-render="(t) => t"`

**Comment by gowin520** [comment]
设置 :i18n-render="(t) => t" 后，国际化功能已经去掉，但是页面右上角国际化选择的小球图标还是在的哦

**Comment by gowin520** [comment]
> pro-layout props `:i18n-render="(t) => t"`

设置 :i18n-render="(t) => t" 后，国际化功能已经去掉，但是页面右上角国际化选择的小球图标还是在的哦

**Comment by sendya** [comment]
rightContentRender 自己定义
