### ISSUE TITLE
你好，main.js有一个文件的引入是没有的,请看图

### ISSUE THREAD

**Issue by Bamboo742** [vueComponent/ant-design-vue-pro#814]
```js
import themePluginConfig from '../config/themePluginConfig'
```
![image](https://user-images.githubusercontent.com/24216880/84016893-86418300-a9b0-11ea-8a63-cd7ce1650459.png)

**Comment by sendya** [comment]
仔细看看路径

**Comment by Bamboo742** [comment]
不好意思，不过项目直接下载来是报找不到这个主题配置文件的错。
