### ISSUE TITLE
尊敬的作者：关于V3版本去掉了系统的“多页签”模式

### ISSUE THREAD

**Issue by gowin520** [vueComponent/ant-design-vue-pro#815]
**Question （问题描述）**
以多年管理类系统开发的经验来说，（从业务角度来看）系统”多页签“模式其实用户是非常需要的，感谢作者之前提供了多页签的组件，升级到V3重构版本后，我还是将原来的multi-tab组件集成进去了。

**Describe the solution you'd like （你期待的是什么？）**
期待希望作者能像V2版本一样，有一个开关控制系统是否使用”多页签“模式

**Additional context（附加信息）**

**Comment by sendya** [comment]
由于该组件并不在 antd pro 的规范内，v3 不再提供该功能。如有需求，请自行实现。
