### ISSUE TITLE
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！

### ISSUE THREAD

**Issue by duzhenyi** [vueComponent/ant-design-vue-pro#817]
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！
刚更新这版不知道谁更新的，太操蛋了。跟老版本比对下，特色的组件竟然没了。搞笑呢吧！！！

**Comment by sendya** [comment]
是的
