### ISSUE TITLE
footer根据页面动态显示隐藏

### ISSUE THREAD

**Issue by cmaxiaojing** [vueComponent/ant-design-vue-pro#820]
**Question （问题描述）**
某些页面不显示底部，动态控制，请问有什么解决方案吗？

**Comment by sendya** [comment]
v-if

**Comment by cmaxiaojing** [comment]
底部不是页面初始化就加载好了吗，我执行函数触发不了
    this.$emit('footer', false)

**Comment by yajore** [comment]
vuex里面定义一个state变量去控制，或者改造一下route.config，在meta里面定义一个hideFooter也行，方法有很多

**Comment by kyuuta** [comment]
可以在路由原信息meta添加个boolean之类的 然后在footer 获取this.$route的信息判断是否隐藏
