### ISSUE TITLE
获取接口数据直接用proxy，其他不做处理，访问不到接口？是什么原因？？

### ISSUE THREAD

**Issue by JaneyJso** [vueComponent/ant-design-vue-pro#821]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by JaneyJso** [comment]
会出现404

**Comment by sendya** [comment]
贴代码，贴错误

**Comment by JaneyJso** [comment]
Uncaught (in promise) Error: Request failed with status code 404

**Comment by JaneyJso** [comment]
export function getResponse () {
  return request({
    url: '/api/platform-device/customer/response/list',
    method: 'get',
    params: {
      code_equal: 'mold'
    }
  })
}


 getSelect (item) {
      if (item === 'response') {
        getResponse().then(res => {
          this.searchItem[item].res = res.data.data
        })
      } else if (item === 'sale') {
        // selectSaleList('sale').then(res => {
        //   this.chargeList = res.data.data
        // })
      } else {
        // getListItem('area').then(res => {
        //   this.searchItem[item].res = res.data.data
        // })
      }
    },

**Comment by JaneyJso** [comment]
需要登录的权限，接口一直404。。。

**Comment by sendya** [comment]
你这样问问题 和贴问题过程，应该没人能帮你解决的了..
如果你不能提供完整的信息，那你就自行想办法处理吧

**Comment by JaneyJso** [comment]
缺了登录验证的请求头Authorization  ，这个不在浏览器显示
