### ISSUE TITLE
引入driver.js 之后。顶部和左侧提示不显示。如图所示

### ISSUE THREAD

**Issue by lhf1990729** [vueComponent/ant-design-vue-pro#822]
**Describe the bug （描述 Bug）**

![image](https://user-images.githubusercontent.com/12724642/84342443-23323500-abd8-11ea-984f-730af608d504.png)

**To Reproduce （重现步骤）**

**main.js**
import Driver from "driver.js" // import driver.js
import "driver.js/dist/driver.min.css" // import driver.js css

Vue.prototype.$driver = new Driver({  
  className: "scoped-class", // className to wrap driver.js popover
  doneBtnText: '完成',              // Text on the final button
  closeBtnText: '关闭',            // Text on the close button for this step
  // stageBackground: 'salmon',       // Background color for the staged behind highlighted element
  nextBtnText: '下一步',              // Next button text for this step
  prevBtnText: '上一步',          // Previous button text for this step
  animate: true, // Animate while changing highlighted element
  opacity: 0.75, // Background opacity (0 means only popovers and without overlay)
  padding: 10, // Distance of element from around the edges
  allowClose: true, // Whether clicking on overlay should close or not
  overlayClickNext: false, // Should it move to next step on overlay click
})

**Expected behavior（你期待的是什么?）**

希望能和driver.js官网的效果一样。目前看来是冲突了.

**Comment by sendya** [comment]
请自行兼容

**Comment by lhf1990729** [comment]
> 请自行兼容

你好，目前就是 调整了 很久样式。发现很难实现和官网一样的效果。

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/84505343-2587b280-acf0-11ea-8819-751475a40c3a.png)

没做任何样式调整，没改任何组件样式。  无任何问题
