### ISSUE TITLE
打开在线的地址时，在IE10 中报错 显示白屏

### ISSUE THREAD

**Issue by 120761701** [vueComponent/ant-design-vue-pro#823]
打开地址：https://preview.pro.antdv.com/user/login?redirect=%2F

浏览器 ie10 

报错内容：Set 未定义

**Comment by sendya** [comment]
你好 v3 开始，不兼容 IE11 以下的浏览器。因为要做 vue3 兼容，而 vue3 不兼容 IE11 以下的版本
