### ISSUE TITLE
request.js 中service.interceptors.response.use 想针对特定返回码做登录跳转

### ISSUE THREAD

**Issue by ShoXLi** [vueComponent/ant-design-vue-pro#824]
**Question （问题描述）**
想在src\utils\request.js [文件中针对相应拦截器做些操作]
![捕获](https://user-images.githubusercontent.com/22651760/84582646-51ef1c00-ae21-11ea-8763-2ad2479ffd57.PNG)

**Describe the solution you'd like （你期待的是什么？）**
返回5001时，可以跳转到登录页面，但是控制台会报错
如下图：
![捕获2](https://user-images.githubusercontent.com/22651760/84583168-494e1400-ae28-11ea-8a62-42c3d96622a8.PNG)

为什么是err undefined
最后，另外一个报错来看，好像是将原有的请求继续执行完了（原先的请求是会请求一个分页表格，我的理解是，但这个请求被路由到登录页面，返回值不带pageNo，最后报一个pageNo undefined）
![捕获3](https://user-images.githubusercontent.com/22651760/84583006-23277480-ae26-11ea-9a48-9f3ee47bfed0.PNG)

请问如何修复这两个报错呢（做后端的，前端勉强能做）

以下这个截图是后端重启后，前端未从新登录，点击这个页面报错
![捕获4](https://user-images.githubusercontent.com/22651760/84582950-6b926280-ae25-11ea-8fc8-048a265ff6af.PNG)

**Additional context（附加信息）**

**Comment by sendya** [comment]
try catch 或者保证接口一定是规范的返回结构
