### ISSUE TITLE
可以提供一个简化的后台模板吗？不引入国际化模块和其他页面模块，只保留几个菜单页面

### ISSUE THREAD

**Issue by hegphegp** [vueComponent/ant-design-vue-pro#825]
**Question （问题描述）**
我是Java后端，对ant-design-vue-pro不是很熟悉，我这个仓库代码比较庞大，可以提供一个简洁的后台管理模板吗？不要引入国际化模块和其他页面模块，只保留几个菜单页面

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-layout 可以基于这个依赖开发。

另外，没有足够的前端经验不推荐上手，请先学习基础知识后再进行

**Comment by hegphegp** [comment]
谢谢， 我前端比较菜，之前都是用jQuery，bootstrap开发管理系统的，没用过vue
