### ISSUE TITLE
run serve 体积大 页面卡顿

### ISSUE THREAD

**Issue by wxlzmt** [vueComponent/ant-design-vue-pro#827]
**为什么run serve时体积如此之巨大, 浏览器非常卡顿**

![antdpropacksize](https://user-images.githubusercontent.com/11326806/85087600-7b88b880-b210-11ea-8c23-6fe44efbd833.png)

对于浏览器而言, 30多兆的js就算是chrome也隐隐喘气扛不住.   
dev过程中, 页面审查元素非常非常卡顿.  css存在大量重复覆盖.

**可能是我修炼功力不够深厚, 没有找到问题原因和好的解决方案.  求路过大神分析一二.**

**环境以及版本**
Environment:
	Branche refactor/pro-v3
	commit 23996b3fe5d3625a30cff2ead280cf104da63cbd
	Commits on Jun 10, 2020
我一个字符都没改, 所以就不贴配置文件了. 仓库里面有对应分支和提交时间点.

**Comment by sendya** [comment]
请学习基础知识后在尝试使用本项目

另外开发环境少于 100M 都不算大，具体为什么，可以去查 webpack 资料
