### ISSUE TITLE
文档地址问题

### ISSUE THREAD

**Issue by lokkkk** [vueComponent/ant-design-vue-pro#829]
**Question （问题描述）**
https://pro.loacg.com/components/s-table 打开会跳转到 https://pro.antdv.com ，是旧的文档废弃了吗？

**Describe the solution you'd like （你期待的是什么？）**
想看下 s-table 相关文档

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://pro.antdv.com/components/s-table

都跳转过去了，你直接点组件看看不就好了
