### ISSUE TITLE
emmm,希望有那种标签页打开后tab在顶部,点击可以回到之前页面的那种

### ISSUE THREAD

**Issue by kiyosunsun** [vueComponent/ant-design-vue-pro#83]
点个star支持下

**Comment by sendya** [comment]
没明白说的是什么，能否详细描述一下

**Comment by kiyosunsun** [comment]
![Markdown](http://i1.bvimg.com/636875/80bc1dcfe6468f5a.png) @sendya

**Comment by sendya** [comment]
![20190222144431](https://user-images.githubusercontent.com/5404542/53224628-68171d00-36b0-11e9-964a-c3469e9b3610.png)

**Comment by kiyosunsun** [comment]
看到了。

**Comment by sendya** [comment]
> 看到了。

👍
