### ISSUE TITLE
打包成功后部署报错： Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by jhjade** [vueComponent/ant-design-vue-pro#830]
**Question （问题描述）**
How to use component `s-table` paging
publicPath:"/admin" 配置二级目录 
在开发模式下运行正常

执行 yarn build 构建成功后部署到nginx 就报错
```
Uncaught SyntaxError: Unexpected token '<'
```
配置成 / 又正常 
**Describe the solution you'd like （你期待的是什么？）**
 
- 有没有类似的解决方法经验
- 或者打包成非压缩的版本部署方式 便于找出报错原因

**Additional context（附加信息）**

**Comment by sendya** [comment]
请查阅 vue-cli 文档

**Comment by kasnet** [comment]
我也遇到这个问题了, 怎么解决啊?
