### ISSUE TITLE
Input组件allow-clear图标color未生效

### ISSUE THREAD

**Issue by lanrenbulan** [vueComponent/ant-design-vue-pro#831]
**Question （问题描述）**

在Pro中，使用 allow-clear 允许清除时，clear图标的颜色未生效
![image](https://user-images.githubusercontent.com/9604624/85276994-39cc6c00-b4b5-11ea-8010-6cd1fc79a49f.png)

**Describe the solution you'd like （你期待的是什么？）**

目前clear图标颜色为黑色，希望保持组件原样(灰色)

**Additional context（附加信息）**

Input组件的allow-clear，是否可以新增鼠标hover时才显示clear图标的prop

**Comment by sendya** [comment]
自行样式覆盖

**Comment by lanrenbulan** [comment]
> 自行样式覆盖

这是什么原因导致的呢？我看到样式有大量的chunk-*.css的样式覆盖，比如.anticon

**Comment by iczer** [comment]
尝试替换 ant-design-pro-vue/src/global.less 中这一行代码:
```diff
- @import '~ant-design-vue/es/style/themes/default.less'
+ @import '~ant-design-vue/dist/antd.less'
```
