### ISSUE TITLE
其它组件功能去哪儿了

### ISSUE THREAD

**Issue by jacksuc** [vueComponent/ant-design-vue-pro#832]
之前记得菜单中有个其它组件来，现在没看到啊。里面还是有很多实用的功能，不知道为什么要删掉！

**Comment by sendya** [comment]
没删掉！
https://github.com/vueComponent/ant-design-vue-pro/tree/refactor/pro-v3/src/views/other

**Comment by jacksuc** [comment]
> 没删掉！
> https://github.com/vueComponent/ant-design-vue-pro/tree/refactor/pro-v3/src/views/other

只是演示站点去掉了，是吧。
