### ISSUE TITLE
使用vuera引入React组件，在babel.config.js里面的plugins里面加入'transform-react-jsx'也是不生效

### ISSUE THREAD

**Issue by GuanLola** [vueComponent/ant-design-vue-pro#833]
问题描述：有个需求就是在改项目中使用react，于是上网去查找到vuera这个插件可以在vue项目中使用React，https://github.com/akxcv/vuera。
最后报的一个错是：
![WechatIMG1356](https://user-images.githubusercontent.com/37822389/85486273-ea915300-b5fc-11ea-8802-676f9f12e2a6.jpeg)

于是找到这个https://github.com/akxcv/vuera/issues/99，
在babel.config.js中配置如下：
![WechatIMG1357](https://user-images.githubusercontent.com/37822389/85486295-f3822480-b5fc-11ea-9eb7-36749b9c125e.jpeg)

还是会报同样的错，

请问一下是不是该项目在用vue的jsx写法的同时，不能使用react的jsx写法呢？ 各版本是"babel-plugin-transform-react-jsx": "^6.24.1","vue": "^2.6.10","vuera": "^0.2.7"

@sendya @kokoroli @hzsrc

**Comment by sendya** [comment]
这种极少数情况，请自己查资料看能不能解决。 我没尝试过这么用，也不会尝试

**Comment by GuanLola** [comment]
> 这种极少数情况，请自己查资料看能不能解决。 我没尝试过这么用，也不会尝试
我再上网查查，还是非常感谢

**Comment by CZU32** [comment]
你好，现在这个问题解决了吗，同样的需求我也遇到了这个问题

**Comment by GuanLola** [comment]
> 你好，现在这个问题解决了吗，同样的需求我也遇到了这个问题

上面在babel.config.js配置好，如上图，接着在layouts中的BasicLayout.vue文件把logoRender方法中的vue-jsx写法去掉就不会报h is not a function 的错误了。也就是说配置完react-jsx就不能再在vue里面写jsx了
