### ISSUE TITLE
关于Stable加载数据的方式

### ISSUE THREAD

**Issue by xuzining** [vueComponent/ant-design-vue-pro#834]
// 加载数据方法 必须为 Promise 对象
        loadData: parameter => {
          return this.$http.get('/service', {
            params: Object.assign(parameter, this.queryParam)
          }).then(res => {
            return res.result
          })
        },
这是markdown中的例子，既然工程中使用了axios为何还要多一个vue-resource，加载数据直接像ant的a-table那样直接使用数组多好，咱这里返回Promise对象是基于什么角度考虑的？

**Comment by sendya** [comment]
> 既然工程中使用了axios为何还要多一个vue-resource

不知道你从哪看到有 `vue-resource` 的



> 加载数据直接像ant的a-table那样直接使用数组多好  

![image](https://user-images.githubusercontent.com/5404542/85494411-30edae80-b60b-11ea-832a-34465a7612ae.png)

**Comment by xuzining** [comment]
上面的内容是我百度的，我对前端不太懂，我是后端，现在用这个S-table出了一些我不能解决问题，咱的例子中是这样加载数据的

我后端服务器挂掉了，前端应该响应超时，但是前端没有发生响应超时，它的表格一直在loading状态，没有数据，一直有个遮罩层在转圈圈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言肆"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 中午11:10
收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;;
抄送:&nbsp;"小提摩太"<1379540723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 关于Stable加载数据的方式 (#834)





  
既然工程中使用了axios为何还要多一个vue-resource
  
不知道你从哪看到有 vue-resource 的
  
加载数据直接像ant的a-table那样直接使用数组多好

**Comment by sendya** [comment]
请求出错没有做处理，请自行处理。 另外，搞不定就请个专门的前端工程师搞
