### ISSUE TITLE
refactor/pro-v3 分支, 点击退出跳到登录页面后, 控制台抛错Error in beforeDestroy hook: "TypeError: Cannot read property 'removeChild' of null"

### ISSUE THREAD

**Issue by hegphegp** [vueComponent/ant-design-vue-pro#835]
**Question （问题描述）**
refactor/pro-v3 分支, 点击退出跳到登录页面后, 控制台抛错Error in beforeDestroy hook: "TypeError: Cannot read property 'removeChild' of null"

**Additional context（附加信息）**
![image](https://user-images.githubusercontent.com/26202719/85938870-8e536980-b943-11ea-9ee3-8668b027f701.png)

**Comment by hb1707** [comment]
遇到同样问题，问题似乎来自Drawer组件，从有Drawer组件的页面退出并跳到其他页面时，会报这个错误

**Comment by hb1707** [comment]
刚刚使用npm-check -u
将包都升级到最新版，问题得到解决。

**Comment by hegphegp** [comment]
将包都升级到最新版，问题解决了。
