### ISSUE TITLE
Error in beforeDestroy hook: "TypeError: Cannot read property 'removeChild' of null"

### ISSUE THREAD

**Issue by wusuobuzai** [vueComponent/ant-design-vue-pro#836]
求帮助，组件打开Drawer关上的时候切换页面会报错
![11](https://user-images.githubusercontent.com/36450583/85943879-81477200-b965-11ea-9ddd-ac8d9bb93564.png)

**Comment by wusuobuzai** [comment]
升级到1.6.1好了

**Comment by dachengzi000** [comment]
> 升级到1.6.1好了

@wusuobuzai 你好，请问你所谓的升级到1.61是指的什么？
