### ISSUE TITLE
AvatarList 组件设置 maxLength 并且 size 为 “mini”时，显示多余数量的组件 size 异常.

### ISSUE THREAD

**Issue by jingguangyan** [vueComponent/ant-design-vue-pro#839]
**Describe the bug （描述 Bug）**

AvatarList 组件设置 maxLength 并且 size 为 “mini”时，显示多余数量的组件 size 异常;
并且多余数量应该为 (总数量 - maxLength), 而非 maxLength。

<img width="1316" alt="demo" src="https://user-images.githubusercontent.com/24221158/85983386-01c7aa80-ba1a-11ea-9709-ad27eb5d89e2.png">

**To Reproduce （重现步骤）**

<img width="527" alt="code" src="https://user-images.githubusercontent.com/24221158/85982825-0dff3800-ba19-11ea-9a13-e3edb5a04e9d.png">

**Expected behavior（你期待的是什么?）**

<img width="664" alt="demo2" src="https://user-images.githubusercontent.com/24221158/85984266-8666f880-ba1b-11ea-8336-a0800ec06cb0.png">

**Desktop (please complete the following information):**

 - OS: [macOS MoJava 10.14.6]
 - Browser [chrome 83.0.4103.116]

**Additional context（附加信息）**

基于当前最新 commit 4723fc5

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/85985253-0d68a080-ba1d-11ea-82be-03e2c4980c62.png)

`mini` 从官方 `Avatar` 组件属性中去除了，不要在使用了。
后续会跟进

**Comment by jingguangyan** [comment]
@sendya  已经提交pr，用于修复该问题。

**Comment by sendya** [comment]
这个组件准备重构，不准备按这种方式去处理了。谢谢提供 PR
