### ISSUE TITLE
三级菜单的keep-alive属性导致打开的url与实际组件不符

### ISSUE THREAD

**Issue by ajkx** [vueComponent/ant-design-vue-pro#84]
截图如下：
![image](https://user-images.githubusercontent.com/8744322/53225929-8c74f880-36b4-11e9-9253-b9df0c7c5487.png)

操作过程：
1. 先进入个人设置的安全设置页面
2. 点击个人中心菜单，进入里面
3. 再点击个人设置菜单，这时页面URL是/account/settings/base，但实际打开的页面却是安全设置的

发现取消了安全设置页面路由的keep-Alive属性则正常跳转回基本设置，请问keep-Alive为true时，上面操作怎样才能正常跳回基本设置。

非常感谢！

**Comment by sendya** [comment]
keepalive activated
