### ISSUE TITLE
yarn build 之后，部署dist文件夹时，访问接口404

### ISSUE THREAD

**Issue by IMJacky** [vueComponent/ant-design-vue-pro#841]
**Question （问题描述）**
您好，我本地测试的时候暂时没发现问题，不管是使用api-dev还是api，都可以正常访问。
但是发布之后，使用的是.env配置，接口baseurl就是/api，但是接口访问就404了，很奇怪，
应该和那个port没有关系吧？

**Describe the solution you'd like （你期待的是什么？）**
可以正常访问后端接口，后端是spring boot

**Additional context（附加信息）**
![vue-dist-404](https://user-images.githubusercontent.com/6263957/86082756-1f088180-bacb-11ea-8b80-daf1ef940559.png)

**Comment by sendya** [comment]
部署有什么流程推荐多看看别人的教程或文章

https://pro.antdv.com/docs/deploy

https://cli.vuejs.org/zh/guide/deployment.html

**Comment by IMJacky** [comment]
![vue-nginx](https://user-images.githubusercontent.com/6263957/86118895-184a3080-bb04-11ea-886e-0fd1959289ce.png)

就是看了部署的文章也没有解决才来问的，虽然不知道什么原因，但是在nginx的配置文件添加下面的配置就可以了。

`rewrite ^/api/(.*) /$1 break;  `

希望可以帮到其他遇到和我一样问题的同学~

**Comment by cxhello** [comment]
@IMJacky 和你遇到了同样的问题，使用了你的解决方案是可以的，后来又用了这样一种方法也是可以的，特此贴出来分享给大家，希望能帮助到大家
![image](https://user-images.githubusercontent.com/49056040/104080570-d09b2300-5263-11eb-8aa2-c2cd4cf48784.png)
