### ISSUE TITLE
全局引入组件或单独引用组件方法

### ISSUE THREAD

**Issue by vincent-dixin** [vueComponent/ant-design-vue-pro#845]
**Question （问题描述）**
`use.js?2e7e:19 Uncaught ReferenceError: Antd is not defined
    at eval (use.js?2e7e:19)
    at Module../src/core/use.js (app.js:1827)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (main.js:388)
    at Module../src/main.js (app.js:2089)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.1 (app.js:2306)
    at __webpack_require__ (app.js:854)`

`main.js` 引入 `import './core/use'`  报错

`<script>
import AutoComplete from 'ant-design-vue'
import { STable, Ellipsis } from '@/components'
import { getList } from '@/api/business'
import { find } from '@/api/customer'
import model from '../model'`

`export default {
  name: 'TableList',
  components: {
    STable,
    Ellipsis,
    AutoComplete
  },`

单独引用组件也报错

**Describe the solution you'd like （你期待的是什么？）**
全局引入组件或单独引用组件方法

**Additional context（附加信息）**

**Comment by sendya** [comment]
没看懂你要表达什么？能否整理一下语言表达？

另外这个不是这么写的
![image](https://user-images.githubusercontent.com/5404542/86250951-d5f82080-bbe3-11ea-8c7b-9cb131875523.png)
应该这样
`import { AutoComplete  } from 'ant-design-vue'`


最后，项目默认按需加载，是为了减少打包体积。
如果你要修改全部引入，你需要关掉 babel-import 插件

**Comment by vincent-dixin** [comment]
`Unknown custom element: <a-auto-complete> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

按照你这么写还是会报这个

**Comment by vincent-dixin** [comment]
![image](https://user-images.githubusercontent.com/5276216/86252216-8286d200-bbe5-11ea-8f62-978ed6fb340f.png)

**Comment by sendya** [comment]
如果你不会基础，那么请按照官方要求的引入方式 `Vue.use(AutoComplete)`  不要使用更高阶的方案来引入
