### ISSUE TITLE
如何关闭adobe广告

### ISSUE THREAD

**Issue by AndyLee1024** [vueComponent/ant-design-vue-pro#847]
打开项目就能看到广告
“
Limited time offer: Get 10 free Adobe Stock images.
ads via Carbon
”

![image](https://user-images.githubusercontent.com/3479173/86449734-28a01c80-bd4b-11ea-9a78-e6ba543508d6.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/layouts/BasicLayout.vue#L18
