### ISSUE TITLE
无法进入到忘记密码页面

### ISSUE THREAD

**Issue by fzlinjianhui** [vueComponent/ant-design-vue-pro#848]
**Question （问题描述）**
How to use component `s-table` paging
在 constantRouterMap 中加入的忘记密码的页面，在登录页却无法点击跳转过去，看现象应该是被拦截掉了，但是constantRouterMap这个不是无需权限就可以进入的页面么
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by fzlinjianhui** [comment]
解决了

**Comment by wxy1234567890** [comment]
遇到同样问题，怎么解决的
