### ISSUE TITLE
新加了忘记密码页面，为何没有登陆无法访问

### ISSUE THREAD

**Issue by fzlinjianhui** [vueComponent/ant-design-vue-pro#849]
Question （问题描述）
How to use component s-table paging
在 constantRouterMap 中加入的忘记密码的页面，在登录页却无法点击跳转过去，看现象应该是被拦截掉了，但是constantRouterMap这个不是无需权限就可以进入的页面么
Describe the solution you'd like （你期待的是什么？）

Additional context（附加信息）

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/permission.js#L13
