### ISSUE TITLE
好像列表页面和firefox，edge有兼容性问题

### ISSUE THREAD

**Issue by pangafu** [vueComponent/ant-design-vue-pro#85]
ie 11以下貌似进不了页面
firefox, edge一览页面貌似取不出数据
chrome和opera的最新版没有什么问题

建议支持一下firefox和edge，没有仔细调试，应该是小bug

**Comment by sendya** [comment]
fixed.  ref e3b0db19417128962e7d0e558011711dc14b9eae

**Comment by pangafu** [comment]
tested ok!
