### ISSUE TITLE
怎么去掉面包屑导航中的  ant-page-header-heading  ，去掉和侧边栏名一样的黑色粗体字

### ISSUE THREAD

**Issue by bruce-teng** [vueComponent/ant-design-vue-pro#850]
页面头部面包屑导航下边那 ，会有一个和左边路由一样的黑色粗体字，怎么能去掉   
我看他是封装在这个组件内的，这个组价有个 content ，但是不是这个值控制的
```vue
<page-header-wrapper
    :tab-list="tabList"
    :tab-active-key="tabActiveKey"
    :tab-change="handleTabChange"
  >
```

**Comment by sendya** [comment]
黑色粗体字 是指 当前页标题吗？
如果是，这个暂时无法被去除。 要么不用 page-wrapper 要么不许被去除

**Comment by bruce-teng** [comment]
是这个，这个链接图片里边的红框部分。

http://dev211.x2crm.cn/0/Snipaste_2020-07-07_15-52-33.jpg

**Comment by sendya** [comment]
这个暂时无法被去除。 要么不用 page-wrapper 要么不许被去除

**Comment by bruce-teng** [comment]
好的 多谢

**Comment by pangmer** [comment]
<page-header-wrapper :title="false" :breadcrumb="false">

将这两个属性设置为false即可

**Comment by pangmer** [comment]
`<page-header-wrapper :title="false" :breadcrumb="false">`

将这两个属性设置为false即可

**Comment by kbdancer** [comment]
`<page-header-wrapper :title="false"> `
即可隐藏下面那个标题大字

**Comment by FoggeOvO** [comment]
> <page-header-wrapper :title="false">

请问这个在哪里设置？
