### ISSUE TITLE
怎么删除左侧边栏中最上边的 logo 和标题

### ISSUE THREAD

**Issue by bruce-teng** [vueComponent/ant-design-vue-pro#851]
`BasicLayout`  里边嵌套了一个 `pro-layout`  这个怎么删除左侧边栏中最上边的 logo 和标题

**Comment by sendya** [comment]
`menuHeaderRender(logo,title)=>VNode` 或者 `logo`, `title` 属性自定义 不能删除，只能自定义。
如有必要，可以自己做一套 layouts

**Comment by bruce-teng** [comment]
好的 多谢
