### ISSUE TITLE
使用drawer抽屉时，点击关闭后切换会报错

### ISSUE THREAD

**Issue by wangf1121** [vueComponent/ant-design-vue-pro#854]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'removeChild' of null"

**Comment by hb1707** [comment]
遇到同样问题，点击关闭Drawer组件后，跳到其他页面时，会报这个错误

**Comment by hb1707** [comment]
刚刚使用npm-check -u
将包都升级到最新版，问题得到解决。
