### ISSUE TITLE
新增菜单后使用permission: [ 'userManager' ]时不显示，用已有的permission: [ 'dashboard' ]就能显示

### ISSUE THREAD

**Issue by QianYingCRM** [vueComponent/ant-design-vue-pro#855]
**Question （问题描述）**
如题
`新增完整代码`
`
      // userManager
      {
        path: '/userManager',
        name: 'userManager',
        redirect: '/userManager/list',
        component: RouteView,
        meta: { title: 'menu.userManager', keepAlive: true, icon: 'user', permission: [ 'userManager' ] },
        children: [
          {
            path: '/userManager/list/:pageNo([1-9]\\d*)?',
            name: 'List',
            component: () => import('@/views/userManager/List'),
            meta: { title: 'menu.userManager.list', keepAlive: true, permission: [ 'userManager' ] }
          }
        ]
      },
`

**Comment by sendya** [comment]
登录的用户信息有 `userManager` 这个权限吗

**Comment by lzdbh** [comment]
刚接触，跟题主一样，只修改router.config.js（其他任务代码无修改），添加类似的代码，其他地方不修改，没有显示，如：`{
       path: '/test',
       redirect: '/test',
       component: RouteView,
       meta: { title: '测试', icon: 'form', permission: [ 'test' ] },
       children: [
         {
           path: '/test',
           name: 'TestForm',
           component: () => import('@/views/test'),
           meta: { title: '测试表单', keepAlive: true, permission: [ 'test' ] }
         }
       ]
     }`
不能显示，把permission: [ 'test' ],改为permission: [ 'form' ]就可以显示。

小白请教，还需要修改哪里可以显示菜单？谢谢！！！

**Comment by sendya** [comment]
@lzdbh 你要确定自己有 `test` 这个权限才行啊

**Comment by 2-huang** [comment]
我也困在这里了，想知道怎么办

**Comment by yy-richard** [comment]
还要修改你mock的用户信息user.js文件，即给你登录的用户中加上userManager权限
