### ISSUE TITLE
为什么打包到生产环境一直提示正在切换主题

### ISSUE THREAD

**Issue by zhichao8756** [vueComponent/ant-design-vue-pro#857]
主题这块的代码没做过修改
![image](https://user-images.githubusercontent.com/24514251/87007081-3f83ba80-c1f4-11ea-8efe-79dbdb2f2619.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/layouts/BasicLayout.vue#L115

去除这一行即可

**Comment by zhichao8756** [comment]
> https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/layouts/BasicLayout.vue#L115
> 
> 去除这一行即可

感谢大佬~
