### ISSUE TITLE
 图表显示异常

### ISSUE THREAD

**Issue by codeliufan** [vueComponent/ant-design-vue-pro#859]
**Question （问题描述）**
自己的项目开启keep-alive和多标签时，切换页面并改变窗口尺寸，再切换回图表页面时，页面的图标显示异常。

在以前的antd pro版本中也有这个问题。

**Additional context（附加信息）**
![image](https://user-images.githubusercontent.com/16485762/87109749-08ff7b80-c298-11ea-9488-6c390c9c7566.png)

**Comment by sendya** [comment]
触发一下 window resize 事件
