### ISSUE TITLE
提供一个简洁版的分支

### ISSUE THREAD

**Issue by cn-src** [vueComponent/ant-design-vue-pro#86]
希望能提供一个简洁版的分支，没有样例的。

**Comment by jiankian** [comment]
同求，出个Skeleton

**Comment by sendya** [comment]
added 

ref https://github.com/sendya/ant-design-pro-vue/tree/lite

**Comment by sendya** [comment]
**需要注意的是，该分支今后不会进行维护，欲获取最新版基础架构，请自行从 `master` 删除无用组件和页面即可**
