### ISSUE TITLE
table的columns格式化render要怎么实现？

### ISSUE THREAD

**Issue by JaneyJso** [vueComponent/ant-design-vue-pro#860]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by jiangfen2018** [comment]
这么写没反应  
{ title: '类型',  dataIndex: 'status', className: 'columnSet',
        render:() => {
          return{
            formatter (text, row, index) {
             if(text==0){
               return '设备'
             }else{
               return '配件'
             }
           }
          }
          }  },

**Comment by JaneyJso** [comment]
这么写没效果
`  { title: '类型',  dataIndex: 'status', className: 'columnSet',
        render:() => {
          return{
            formatter (text, row, index) {
              console.log(text, row);
              
             if(text==0){
               return '设备'
             }else{
               return '配件'
             }
           }
          }
          }  },`

**Comment by sendya** [comment]
建议学习 antdv 的 table 相关文档，不要自己造 API 用法。

```jsx
const columns = [
  {
    title: '类型',
    dataIndex: 'status',
    customRender: (text, record, index) => (<span>{text == 0 && '设备' || '配件'}</span>)
  }
]
```

> 需要注意作用域和 `h` 注入问题
