### ISSUE TITLE
Pro 3.0.0-alpha1 不支持这种Vue.ls.get(ACCESS_TOKEN)？？大佬

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#863]
大佬，您好。
请问
Pro 3.0.0-alpha1 不支持这种Vue.ls.get(ACCESS_TOKEN)？？

还是说必须支持

storage.get(ACCESS_TOKEN)  这种？

上面这种跳转dashboard的时候白屏

**Comment by sendya** [comment]
请根据相应 API 使用
