### ISSUE TITLE
login.js问题不能触发后端的nav接口。跪求

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#864]
大佬您好，我的前端有些不太熟悉，打扰见谅。

代码如下： 

const userApi = {
  Login: '/login',
  Logout: '/logout',
  ForgePassword: '/auth/forge-password',
  Register: '/auth/register',
  twoStepCode: '/auth/2step-code',
  SendSms: '/account/sms',
  SendSmsErr: '/account/sms_err',
  // get my info
  UserInfo: '/rest/user/getInfo',
  UserMenu: '/rest/user/nav'    //修改了变成了后端的接口，但是无调用额。这个地方改了，不能触发后端的nav接口。login和rest/user/getInfo两个却可以触发。
}

**Comment by sendya** [comment]
这只是一个常量表，你贴这个出来对查 bug 没有任何帮助，提问能否表达清楚？

检查这一段代码的流程，自己跟踪，每行都能输出日志来跟踪你想知道的
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/permission.js#L27-L58

**Comment by sendya** [comment]
另外你还能看文档 https://pro.antdv.com/docs/authority-management
除此之外，没有任何能帮你的了。你可以找你现实生活中的前端开发帮你解决问题

**Comment by arraycto** [comment]
好的，提供思路就很感谢。方向对了就行
