### ISSUE TITLE
设置Theme Color 后，一刷新又恢复初始化状态，请问如何保存（除非清楚浏览器缓存才恢复初始化）

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#866]
设置Theme Color 后，一刷新又恢复初始化状态，请问如何保存（除非清楚浏览器缓存才恢复初始化）

版本：ant-design-vue-pro-3.0.0-alpha2

福星复现地址：https://preview.pro.antdv.com/dashboard/workplace

**Comment by goukuDev** [comment]
![image](https://user-images.githubusercontent.com/30975895/87655146-7294f380-c78a-11ea-87d8-38e2f82a8340.png)
修改src/config/defaultSettings.js 里面的primaryColor值

**Comment by goukuDev** [comment]
不知道你想要的是不是这个

**Comment by arraycto** [comment]
感谢亲，不是的，你的这个初始化的颜色可以变。没问题 ，如初始化红色，浏览器打开后设置为蓝色，一刷新又变成了红色。这是不对的，蓝色未保存。（没有清理cookie是
）

**Comment by sendya** [comment]
配置栏配置修改后，复制粘贴到配置文件内

**Comment by wxy1234567890** [comment]
修改src/config/defaultSettings.js 里面的primaryColor值为#1890FF后，打开页面，蓝色主题框未被勾选，why?

**Comment by wxy1234567890** [comment]
![1614069289(1)](https://user-images.githubusercontent.com/24424956/108819198-81cc0180-75f5-11eb-8700-3feecc4e12a0.jpg)

**Comment by wxy1234567890** [comment]
修改src/config/defaultSettings.js 里面的primaryColor值为#1890FF后，打开页面，蓝色主题框未被勾选，why?
![1614069289(1)](https://user-images.githubusercontent.com/24424956/108819252-95776800-75f5-11eb-8538-320b973436c8.jpg)

**Comment by wxy1234567890** [comment]
另一个问题，设置为黄色主题后，退出登录，刷新浏览器，页面又变成原始的蓝色，没有保存住设置的黄色主题，怎么解决？
