### ISSUE TITLE
日期中带有T和Z的时区小问题，大复杂：a-date-picker组件

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#867]
日期传递后台格式：updateTime: "2020-07-14T00:49:41.424Z"

目标格式：2020-07-14 08:49:41 

问题：日期中带有T和Z的时区，切少了8个小时属于UTC时间，其他input框显示正确，提交form表单，浏览器的network中参数不正确，如updateTime: "2020-07-14T00:49:41.424Z"

无效措施：
无效1：` <a-date-picker show-time style="width: 100%" v-decorator="['updateTime',{ initialValue: model==null?null:moment(model.updateTime, 'YYYY-MM-DD  HH:mm:ss')}]" placeholder="请选择日期" />`
由于script引入如下在template之后，报moment元素不识别的错误。

import moment from 'moment'
import 'moment/locale/zh-cn'

无效2： 单独定义一个isValue，依旧无效
```
isValue: {
        get () {
           if (this.model == null) {
             return null
        } else {
          return moment(this.model.updateTime, 'YYYY-MM-DD HH:mm:ss')
      }
        }
     }
```

解决：请问该如何解决？ 后台可以解决，但是想从前端源头解决，不知道前端支持么？

**Comment by sendya** [comment]
支持， 提交给后端前自行转换

**Comment by arraycto** [comment]
没找到对应的组件API能解决此的方法啊，大神给个链接，还是需要自定义函数处理。@sendya

**Comment by sendya** [comment]
你写代码都靠组件的话，是没办法做到的

**Comment by arraycto** [comment]
好的。还以为自己没找到地方额。我自己写一个函数。感谢大佬
