### ISSUE TITLE
求添加回多标签教程！！！

### ISSUE THREAD

**Issue by BerryWang1996** [vueComponent/ant-design-vue-pro#868]
**Question （问题描述）**
求添加回多标签教程！奈何本人前端菜鸟，求高手发出添加回多标签的教程，按照`multi-tabs.md`文件里的删除教程反推发现代码已经不一样了，没法反过来添加上

**Describe the solution you'd like （你期待的是什么？）**
添加回多标签的教程

**Additional context（附加信息）**
求添加回多标签教程

**Comment by sendya** [comment]
找个你觉得可以的地方，写入 <multi-tab /> 就好了
