### ISSUE TITLE
动态菜单。icon可以使用jpg/png这样的图片吗。因为不能确保后端返回的就是svg。请大佬们帮帮忙

### ISSUE THREAD

**Issue by goukuDev** [vueComponent/ant-design-vue-pro#870]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
不能

**Comment by goukuDev** [comment]
> 不能

好的，那只能限制上传svg了
