### ISSUE TITLE
关于动态创建菜单的问题。

### ISSUE THREAD

**Issue by goukuDev** [vueComponent/ant-design-vue-pro#873]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by goukuDev** [comment]
![image](https://user-images.githubusercontent.com/30975895/87740638-42466700-c815-11ea-9875-925199033a34.png)
现在后端返回的菜单里面有icon,不过只是个路径。想请教大佬这个要怎么构建icon啊。

**Comment by sendya** [comment]
svg 必须是前端存在的，否则无法引入。
如果要动态设置 svg，请当作 img 来使用，Pro-layout 不支持这么用，请自定义构建菜单

**Comment by goukuDev** [comment]
> svg必须是前端存在的，否则无法发布。
> 如果要动态设置svg，请考虑img来使用，Pro-layout不支持这么用，请自定义构建菜单

谢谢啊，已经解决了。我是用上面那样的路径重构了一个svg.
![image](https://user-images.githubusercontent.com/30975895/87766601-0084e300-c84c-11ea-942f-117c9bdbb637.png)
这里的svg-icon是用svg封装的一个组件。这样就可以显示了。
![image](https://user-images.githubusercontent.com/30975895/87766758-3cb84380-c84c-11ea-80d5-97996653f21d.png)

**Comment by brucethomaswayne6** [comment]
@syhITMAN  具体是怎么处理的呢？楼上看不太懂呢
