### ISSUE TITLE
打包后chunk-vendors文件很大，发现里边含有antv/g2占用1.73Mb，可以不把这个打包到chunk-wendors文件吗

### ISSUE THREAD

**Issue by dixiaoping** [vueComponent/ant-design-vue-pro#875]
**Question （问题描述）**
How to use component `s-table` paging
打包后chunk-vendors文件很大，发现里边含有antv/g2占用1.73Mb，可以不把这个打包到chunk-wendors文件吗
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
webpack (vue-cli) 自行配置 cdn 引入，构建时不打包而使用 cdn 文件
