### ISSUE TITLE
步骤条中的"process"状态下动态图标被覆盖

### ISSUE THREAD

**Issue by perpetrators** [vueComponent/ant-design-vue-pro#876]
**Describe the bug （描述 Bug）**
步骤条中的"process"状态下动态图标被覆盖
<a-step status="process" title="库存信息">
       <a-icon slot="icon" type="loading" />
</a-step>

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/35053260/87755720-17223e80-c83a-11ea-9558-8c42b974e76d.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/87756873-4639af80-c83c-11ea-8526-39bf3576a731.png)

#90

**Comment by perpetrators** [comment]
> ![图片](https://user-images.githubusercontent.com/5404542/87756873-4639af80-c83c-11ea-8526-39bf3576a731.png)
> 
> [＃90](https://github.com/vueComponent/ant-design-vue-pro/issues/90)
你把图标换成动态图标，动态图标，动态图标， <a-icon type="loading" />

**Comment by perpetrators** [comment]
> > ![图片](https://user-images.githubusercontent.com/5404542/87756873-4639af80-c83c-11ea-8526-39bf3576a731.png)
> > [＃90](https://github.com/vueComponent/ant-design-vue-pro/issues/90)
> > 你把图标换成动态图标，动态图标，动态图标，

type="loading"
