### ISSUE TITLE
发布上线时，无法隐藏主题设置

### ISSUE THREAD

**Issue by mouyong** [vueComponent/ant-design-vue-pro#877]
**Describe the bug （描述 Bug）**

按照代码提示进行配置后，发布上线时，无法隐藏主题设置

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

上线时能隐藏主题设置

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/10336437/88022644-426e9b80-cb62-11ea-9116-e3ed476175f1.png)
![image](https://user-images.githubusercontent.com/10336437/88022657-47334f80-cb62-11ea-9666-b4233221bed8.png
![image](https://user-images.githubusercontent.com/10336437/88022752-69c56880-cb62-11ea-88fe-9e00b1669347.png)

**Desktop (please complete the following information):**

 - Version [e.g. 22]83.0.4103.116

**Smartphone (please complete the following information):**

 - Device: [e.g. iPhone6] chrome 
 - OS: [e.g. iOS8.1] win10
 - Browser [e.g. stock browser, safari] chrome

**Additional context（附加信息）**

**Comment by sendya** [comment]
自己 v-if
