### ISSUE TITLE
tree菜单这个支持修改么？大佬

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#879]
![搜狗截图20年07月22日1316_1](https://user-images.githubusercontent.com/37463247/88137279-cc2f6f00-cc1d-11ea-8806-d889d8ded588.png)

组件位置：other/list/tree-list
问题：树形的左侧支持添加子节点，请问如何支持修改父节点。谢谢。如上图

**Comment by sendya** [comment]
自行改造 
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/components/Tree/Tree.jsx#L49-L57

**Comment by arraycto** [comment]
翡翠非常感谢
