### ISSUE TITLE
面包屑 首页path跳转 和 一级菜单展示无效连接404问题

### ISSUE THREAD

**Issue by zhaozhenghao1993** [vueComponent/ant-design-vue-pro#88]
![3y 98icl5rc4sjzwy 9xn_0](https://user-images.githubusercontent.com/33045226/53296918-45bc0580-3850-11e9-82db-8f0c7a329fcf.png)
**如果router.config.js 一级菜单不加redirect 会有点击面包屑跳转404**
`https://preview.pro.loacg.com/form`
**面包屑首页点击不跳转**
我本地修改是
![iu igg_ f7a0 ztvanq i](https://user-images.githubusercontent.com/33045226/53296948-b7944f00-3850-11e9-9467-3d49bb6ae1dd.png)

**Comment by sendya** [comment]
#ref f69a7c3c934af759d7ef1ca7d3ab21c9896bcb65
