### ISSUE TITLE
更新或者添加后，组件不能自动更新，必须F5刷新浏览器才可以。大佬如何解决，这是bug？

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#880]
如题：
为了更好的描述，举例说明【更新成功后，原来的form表单或者原来的list或者原来的table不刷新，按下电脑的F5刷新后，数据为最新的数据，不然还是之前的数据，不能动态感知】
例如：看下面的中文注释
```
 handleSubmit (e) {
      e.preventDefault()
      if (this.isView) {
        this.handleCancel()
        return
      }
      this.form.validateFields((err, values) => {
        if (!err) {
            updateSysMenu(values)
              .then(res => {
                this.handleCancel()
                this.$message.success('保存成功')
                this.$emit('refresh')    //更新成功后，原来的form表单或者原来的list或者原来的table不刷新，按下电脑的F5刷新后，数据为最新的数据，不然还是之前的数据
                this.$refs.tabs.refreshs()
              })
              .catch(() => {
                this.confirmLoading = false
              })
        }
      })
    },
```

**Comment by sendya** [comment]
不明白你在说什么，可否整理清楚来龙去脉？

包括你代码里这些什么　`this.$emit('refresh')`　这些都是干什么的？

**Comment by arraycto** [comment]
![搜狗截图20年07月22日2227_2](https://user-images.githubusercontent.com/37463247/88188563-9cf31f00-cc6a-11ea-9bd5-9c5cc59d1b87.png)


看上图，更新功能没问题，且成功后，期待左边效果立马变成【用户管理8】而不是原来的旧数据【用户管理】，但是左侧的没组件刷新（不知道该如何刷新），手动刷新浏览器后，原来的【用户管理】变成了【用户管理8】，每次都得刷新

**Comment by arraycto** [comment]
![搜狗截图20年07月22日2227_2](https://user-images.githubusercontent.com/37463247/88188963-18ed6700-cc6b-11ea-98cd-d6265491de48.png)
@sendya

**Comment by sendya** [comment]
你更新完，是你后端接口提交更新了而已，跟前端又没什么关系，你想要刷新，不应该是重新获取一次列表数据吗？

**Comment by sendya** [comment]
请自己思考

**Comment by arraycto** [comment]
框架本身不支持，需要自我实现是把？

**Comment by kokoroli** [comment]
HDM 请参考 webpack 文档自行修改
