### ISSUE TITLE
顶部消息提示框偏移

### ISSUE THREAD

**Issue by dongpobaicai** [vueComponent/ant-design-vue-pro#883]
**Describe the bug （描述 Bug）**

重复点击顶部消息弹框，偶尔出现偏移量不一样

**To Reproduce （重现步骤）**

1、点击消息铃铛
2、观察消息弹框左偏移量
3、重复点击十几次
4、会出现一两次偏移量不一样

**Expected behavior（你期待的是什么?）**

保持一致，如果 a-popover 位置是bottom，更加明显

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/16896249/88353157-03715d80-cd8f-11ea-95b3-7ec3d35d6e34.png)

![image](https://user-images.githubusercontent.com/16896249/88353172-12581000-cd8f-11ea-9355-e4eac83b7655.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
无法复现，我猜你在点开弹层后，改了浏览器窗口大小

**Comment by sendya** [comment]
![GIF](https://user-images.githubusercontent.com/5404542/88365895-0897d200-cdba-11ea-88ad-2db6df23e72c.gif)

**Comment by dongpobaicai** [comment]
是这样的，我git clone 仓库直接安装最新的脚手架代码，然后引入这个消息提示框。确实出现。
![question](https://user-images.githubusercontent.com/16896249/88381168-7a7f1400-cdd8-11ea-802d-779101fc7f4c.gif)

**Comment by sendya** [comment]
最新版没提供这个组件，如果是你自己引入进去的，出现兼容请自行处理一下哦
