### ISSUE TITLE
mixins的问题请教

### ISSUE THREAD

**Issue by goukuDev** [vueComponent/ant-design-vue-pro#884]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by syhITMAN** [comment]
目前做的项目里面用了table组件，还有分页组件。我就想把分页组件里面的两个方法j抽到mixins里面。结果提示找不到该方法。
![image](https://user-images.githubusercontent.com/30975895/88357732-e04eaa00-cd9e-11ea-8197-fdd61a4b6e22.png)
这两个方法在需要的组件里都已经引入了。如下图
![image](https://user-images.githubusercontent.com/30975895/88357818-2dcb1700-cd9f-11ea-99cc-ed4a99377c39.png)
![image](https://user-images.githubusercontent.com/30975895/88357857-5226f380-cd9f-11ea-9fe6-68ac7136d077.png)
有知道的朋友帮忙看看吧
