### ISSUE TITLE
有个问题，如果要使用ant pro的Authorized，在这个github资源的基础上应该如何改？

### ISSUE THREAD

**Issue by JaneyJso** [vueComponent/ant-design-vue-pro#885]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
本项目没有你说的 authorized

**Comment by JaneyJso** [comment]
没有authorized，那请问authority也是不能用吗，不能用这个那怎么配置不同角色的菜单呢？

**Comment by sendya** [comment]
不知道你在说什么，麻烦看文档
