### ISSUE TITLE
vue-pro很多样式都与antdesign不一致，全局css样式也没找到有修改的痕迹，你们用的是两套不同的antdesign-vue吗

### ISSUE THREAD

**Issue by zxuanhong** [vueComponent/ant-design-vue-pro#886]
**Describe the bug （描述 Bug）**
* 现在你们官方部署的或者以前发型的版本，很多css样式与antdesign-vue上的不一致，而且全局也没找到你们覆盖的地方。不明白你们难不成antdesign-vue发行是一套，vue-pro使用又是另一套吗？

* 比如，antdesign-vue按钮loading背景是蓝色，而vue-pro确是白色（个人觉得蓝色loading好看多了，白色真的很丑），vue-pro所有输入框border-radius是2，而antdesign-vue是4(2px能看出是圆角？？？？，如果看不到个人觉得有点多余。。。)
* 最后个人觉得vue-pro很多东西确实不错，但美观的细粒度上确实还是不足，虽然iview-admin-pro是模仿这边，但感觉那边美观确实不错(可惜费用不低，地址：https://adminpro.iviewui.com/form/basic-form)，希望官方加强下美观上的控制。希望打造更好的vue-pro

**Screenshots（截图）**
* antdesign-vue loading样式：
![image](https://user-images.githubusercontent.com/62740686/88472619-745b7580-cf47-11ea-840f-e924cfcec65a.png)

* vue-pro登录样式以及radius大小(官方演示站也一样):
![image](https://user-images.githubusercontent.com/62740686/88472631-8f2dea00-cf47-11ea-895f-ffecd8c04747.png)

**Desktop (please complete the following information):**

 - OS: mac
 - Browser chrome
 - Version 所有版本

**Comment by sendya** [comment]
你好，圆角问题你可以自行修改 https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/vue.config.js#L95
另外，之后的版本将一定是圆角了，所以任何样式上不喜欢的，完全可以自定义，并且官方也提供了自定义方案
附录
![image](https://user-images.githubusercontent.com/5404542/88473262-59403400-cf4e-11ea-80ac-af7b715abda3.png)

其余问题都是个人喜好问题，不会因为你的喜好，而改动设计稿

**Comment by Frankjunita** [comment]
那按钮点击时的波纹呢？在哪里还原？还有Loading时的背景
