### ISSUE TITLE
角色动态设置后：侧边导航栏不刷新问题

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#887]
背景前提：

角色来动态设置侧边导航栏，不同的角色显示不同的菜单数量和内容（已实现）
在router.config.js文件通过权限控制菜单

问题：
Bug或者问题复现步骤：
1）角色A，对应菜单A-1 （登录后没问题，菜单显示A-1，没问题，现在先登录后退出）
2）角色B，对应菜单B-1，B-2（登录正常，登录后左侧显示上一个用户的菜单A-1，必须刷新浏览器才能B-1，B-2恢复正常））

大佬，这种在什么地方修改一下？跪求
打扰你周末度假抱歉
  
浏览器：谷歌浏览器

**Comment by sendya** [comment]
你退出没清空原始菜单（初始化）吗

**Comment by arraycto** [comment]
懂了，解决，非常感谢

**Comment by caopengan** [comment]
我清空菜单了，但是还是需要重新刷新一下，菜单才能出来，请问你是怎么解决的？
