### ISSUE TITLE
为什么点击退出登录，没有正常跳转到login页面，反而提示login路由不存在

### ISSUE THREAD

**Issue by MySecret** [vueComponent/ant-design-vue-pro#890]
**Describe the bug （描述 Bug）**

在退出登录确认后，并没有跳转到login页面，虽然代码里面写的this.$router.push({name:'login'}),但是貌似没起到作用。

**To Reproduce （重现步骤）**

1.打开[preview url](https://preview.pro.antdv.com)
2. 使用账号"admin"和密码"admin"登录进去
3. 鼠标移动至右上角个人信息区域，点击“退出登录”
4. 点击确认按钮，发现页面并没有正常跳转至'login'页面

**Expected behavior（你期待的是什么?）**
我期待的是用户退出登录后，应该跳转到login页面去。

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/store/index.js#L7-L11

换刀默认的权限处理就行了。动态构建菜单的权限处理并没有加 logout 页面
