### ISSUE TITLE
s-table的页码自定义支持吗？

### ISSUE THREAD

**Issue by arraycto** [vueComponent/ant-design-vue-pro#891]
**Question （问题描述）**
![猎豹截图20200726203624](https://user-images.githubusercontent.com/37463247/88479351-1481c080-cf81-11ea-8c15-d395db896190.png)

1.问题描述：
    如上图表格的分页每页显示的页数没问题，分页正常，无法定义显示100页/page

2.复现地址：https://preview.pro.antdv.com/list/table-list  （右边下角分页）

3.期待的是什么？
       【旧】 原来分页每页条数下拉的10/page,20/page,30/page,40/page
       【新】 每页5/page  100/page两种。

ps：找了Stable的源代码和文档，没有找到设置页数的地方。atable可以实现。请问继续使用stable能实现么 

@Saraka

**Comment by sendya** [comment]
当然支持，和 antd 官方文档一致 pagination 属性

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/88479572-b229bf80-cf82-11ea-8ef0-af15c20a4ed4.png)
