### ISSUE TITLE
关于菜单生成

### ISSUE THREAD

**Issue by PrinceH** [vueComponent/ant-design-vue-pro#892]
**Question （问题描述）**
How to use component `s-table` paging
在开发环境下 现在菜单是mock那边拿数据 我想数据固定通过权限来增加和删除路由(就是不通过api拿到菜单 通过拿到用户的权限动态显示对应菜单)
**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

在开发环境下 现在菜单是mock那边拿数据 我想数据固定通过权限来增加和删除路由(就是不通过api拿到菜单 通过拿到用户的权限动态显示对应菜单)

**Comment by PrinceH** [comment]
我不明白 config/route.config.js是拿来干嘛的 我发现我把asyncRouterMap中的对象删除 菜单还是有的 所以菜单怎么才能跟asyncRouterMap是有关系的呢 不通过api拿到菜单

**Comment by sendya** [comment]
有两套权限和菜单生成逻辑
https://github.com/vueComponent/ant-design-vue-pro/blob/refactor/pro-v3/src/store/index.js#L7-L11
