### ISSUE TITLE
导航菜单在页面切换时的显示模式

### ISSUE THREAD

**Issue by hchungi** [vueComponent/ant-design-vue-pro#893]
**Question （问题描述）**
请问切换页面时导航菜单如何按以下方式实现
- 页面1 (使用sidemenu模式)
- 页面2 (使用sidemenu模式)
- 页面3 (使用sidemenu模式)
- 页面4 (使用topmenu模式)
- 页面5 (使用topmenu模式)

**Describe the solution you'd like （你期待的是什么？）**
浏览到不同页面时可以使用不同的导航菜单模式

**Additional context（附加信息）**

**Comment by sendya** [comment]
不支持，你可以考虑自己改 属性放在 route meta 里，然后 baselayout 做判断
