### ISSUE TITLE
退出登录无法正确跳转问题

### ISSUE THREAD

**Issue by MySecret** [vueComponent/ant-design-vue-pro#894]
**bug描述**

点击退出登录后，并没有正确跳转至登录页

**（重现步骤）**

1. 打开[Preview](https://preview.pro.antdv.com/)
2. 使用账号（admin）和密码(admin)登录
3. 鼠标移动至右上角，点击退出登录
4. 发现退出登录后并没有正确跳转至Login

**（你期待的是什么?）**
我期待退出登录后跳转至登录页面

**（截图）**

**桌面:**

 - OS: [windows 10]
 - Browser [chrome]
 - Version [83.0.4103.106]

**Comment by MySecret** [comment]
找到原因了，退出登录是在@/component/GlobalHeader/AvatarDropdown文件里面的handleLogout执行的；
这个方法会首先调用@/sotre/modules/user文件里面的action "Logout",调用成功后跳转login页面。问题就出在这个action 'Logout';作者把清除token等操作放在finally里面，导致resolve在清除操作之前完成，也就是跳转login页面的时候，token等信息还没有清除掉，然后匹配到@/permission.js里面的if (to.path === loginRoutePath) {
      next({ path: defaultRoutePath })
      NProgress.done()
    }
导致跳转至首页去了

**Comment by sendya** [comment]
ref #890
