### ISSUE TITLE
我打了个包发现dist文件4点多个MB，有没有优化打包配置的

### ISSUE THREAD

**Issue by LiuYuanZhe** [vueComponent/ant-design-vue-pro#895]
**Question （问题描述）**
我打了个包发现dist文件4点多个MB，有没有优化打包配置的

**Describe the solution you'd like （你期待的是什么？）**
有没有优化的方案啊

**Comment by sendya** [comment]
https://pro.antdv.com/docs/faq#%E7%BC%96%E8%AF%91%E5%90%8E%E4%BD%93%E7%A7%AF%E5%BE%88%E5%A4%A7%EF%BC%9F

**Comment by LiuYuanZhe** [comment]
> https://pro.antdv.com/docs/faq#%E7%BC%96%E8%AF%91%E5%90%8E%E4%BD%93%E7%A7%AF%E5%BE%88%E5%A4%A7%EF%BC%9F

多谢大哥
