### ISSUE TITLE
3.0版本中multiTab配置项去掉了，还能提供支持吗，后台系统还是很需要这个功能

### ISSUE THREAD

**Issue by rbj0820** [vueComponent/ant-design-vue-pro#897]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/tree/master/src/components/MultiTab
