### ISSUE TITLE
如何去掉 a-form-item 标签的冒号

### ISSUE THREAD

**Issue by hegphegp** [vueComponent/ant-design-vue-pro#900]
![image](https://user-images.githubusercontent.com/26202719/88926861-27f69980-d2a9-11ea-9c90-a895f9be6c51.png)

```
<a-form-item label="规则编号">
    <a-input v-model="queryParam.id" placeholder=""/>
</a-form-item>
```

**Comment by hegphegp** [comment]
好像是 ant-design-vue 控制的，不是pro控制的

**Comment by zkwolf** [comment]
a-form-item的colon prop设成false
