### ISSUE TITLE
如何关闭多标签

### ISSUE THREAD

**Issue by a827871781** [vueComponent/ant-design-vue-pro#902]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
本项目默认不提供 多标签，没有关闭一说

**Comment by a827871781** [comment]
不好意思，整错项目了。我想问的是在Ant Design Pro Vue Template使用单标签

**Comment by sendya** [comment]
vue template 单标签又是什么？

**Comment by amen943** [comment]
> 本项目默认不提供 多标签，没有关闭一说

请问会更新支持多标签页吗？
