### ISSUE TITLE
现在有获取token的api没有获取用户信息的api，我现在想根据登陆获取的token来跳转到首页(需要登陆)请问该怎么实现

### ISSUE THREAD

**Issue by zhangjiajia123** [vueComponent/ant-design-vue-pro#904]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://pro.antdv.com/docs/authority-management

![image](https://user-images.githubusercontent.com/5404542/89321968-2c122500-d6b6-11ea-9791-e5dcce8629b8.png)
