### ISSUE TITLE
a-table如何和a-badge一起使用,不使用s-table组件

### ISSUE THREAD

**Issue by zhangjiajia123** [vueComponent/ant-design-vue-pro#907]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
引入了直接用

**Comment by zhangjiajia123** [comment]
代码
<a-table
        :row-selection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
        :columns="columns"
        :data-source="valvedatas"
        rowKey="C2001_VALVE_ID"
        :customRow="onRow"
        showPagination="auto"
        :pagination="pagination"
        @change="handleTableChange"
      />
      <span slot="C2001_LIFT_STATUS" slot-scope="text">
        <a-badge :C2001_LIFT_STATUS="text | statusTypeFilter" :text="text | statusFilter" />
      </span>
const statusMap = {
  0: {
    C2001_LIFT_STATUS: 'success',
    text: '开启',
  },
  1: {
    C2001_LIFT_STATUS: 'error',
    text: '关闭',
  },
}

filters: {
    statusFilter(type) {
      return statusMap[type].text
    },
    statusTypeFilter(type) {
      return statusMap[type].C2001_LIFT_STATUS
    },
  },

**Comment by zhangjiajia123** [comment]
我想在table中的开启或者关闭前添加状态点,因为s-table对数据格式有要求,所以使用的a-table
