### ISSUE TITLE
a-table中根据数据状态显示不同的状态点

### ISSUE THREAD

**Issue by zhangjiajia123** [vueComponent/ant-design-vue-pro#908]
因为s-table对数据格式有要求，所以使用了a-table来实现
<a-table
        :row-selection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
        :columns="columns"
        :data-source="valvedatas"
        rowKey="C2001_VALVE_ID"
        :customRow="onRow"
        showPagination="auto"
        :pagination="pagination"
        @change="handleTableChange"
      />
      <span slot="C2001_LIFT_STATUS" slot-scope="text">
        <a-badge :C2001_LIFT_STATUS="text | statusTypeFilter" :text="text | statusFilter" />
      </span>

const statusMap = {
  0: {
    C2001_LIFT_STATUS: 'success',
    text: '开启',
  },
  1: {
    C2001_LIFT_STATUS: 'error',
    text: '关闭',
  },
}

filters: {
    statusFilter(type) {
      return statusMap[type].text
    },
    statusTypeFilter(type) {
      return statusMap[type].C2001_LIFT_STATUS
    },
  },

**Comment by zhangjiajia123** [comment]
使用a-table能达到这种效果吗

**Comment by sendya** [comment]
当然能，麻烦看 antd vue 的 table 文档
