### ISSUE TITLE
Table columns title 国际化切换语言不显示对应语言

### ISSUE THREAD

**Issue by 5202m** [vueComponent/ant-design-vue-pro#909]
**Question （问题描述）**
添加国际化切换语言时，table的columns title语言不会切换，只有刷新页面后才会显示对应的语言，还有个问题，请问为什么多标签页的设置丢掉了？

**Describe the solution you'd like （你期待的是什么？）**
期待切换语言后，table的title也能显示对应的语言

**Additional context（附加信息）**
columns: [
        {
          title: this.$t('table.serial'),
          scopedSlots: { customRender: 'serial' }
        }
]

**Comment by sendya** [comment]
`title: () => this.$t('table.serial'),`

没启用多标签，属性不会有任何作用
