### ISSUE TITLE
如果路由走接口，要在哪里设置才能保证是在登录后才调用的接口路由，而不是还没登录的时候就走了接口？GenerateRoutes？

### ISSUE THREAD

**Issue by JaneyJso** [vueComponent/ant-design-vue-pro#911]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by JaneyJso** [comment]
`
 GenerateRoutes ({ commit }, data) {
      return new Promise(resolve => {
        const { roles } = data
        let menuRouter2= []
        getMenu2().then((res)=>{
        menuRouter2.push(res.data)
        // menuRouter2 = res.data
        console.log('getMenu2',menuRouter2);

          const accessedRouters = filterAsyncRouter(menuRouter2)
          accessedRouters.forEach(v => {
            let isHidden = true
            if (v.children) {
              v.children.forEach(e => {
                if (!e.hidden) {
                  isHidden = false
                }
              })
              v.hidden = isHidden
            }
          })
          commit('SET_ROUTERS', accessedRouters)
          resolve(accessedRouters)
        
       })
     
      })
    }
`
这样就还没登录就进行路由判断，，，

**Comment by sendya** [comment]
https://pro.antdv.com/docs/authority-management

有问题先看文档
