### ISSUE TITLE
3.0.0版本的pro-layout如何重新支持multitab模式

### ISSUE THREAD

**Issue by liuyangscode** [vueComponent/ant-design-vue-pro#912]
3.0.0版本的pro-layout如何重新支持multitab模式

**Comment by sendya** [comment]
从 components 下面自行引入 multitab 然后在需要的地方使用，具体参考老版本用法

**Comment by xyfy** [comment]
@liuyangscode 

在 `src/layouts/basiclayout.vue`里`<router-view />`前添加 ` <multi-tab v-if="multiTab"></multi-tab>`
然后引入组件
`import MultiTab from '@/components/MultiTab'`
```
  components: {
    SettingDrawer,
    RightContent,
    GlobalFooter,
    MultiTab//ADD it
  },

..........

  computed: {
    ...mapState({
      // 动态主路由
      mainMenu: (state) => state.permission.addRouters,
      multiTab: (state) => state.app.multiTab  //ADD it
    })
  },

```
`config/defaultSettings.js`加入一行  `  multiTab: true,`

**Comment by xyfy** [comment]
这个做法有个问题在于keepAlive无效。。不知道怎么处理了
也就是tab切换的话，它会刷新切换到的tab，是不是不能启用路由的history模式？

**Comment by zzjjss** [comment]
> 这个做法有个问题在于keepAlive无效。。不知道怎么处理了
> 也就是tab切换的话，它会刷新切换到的tab，是不是不能启用路由的history模式？

无效是因为keepAlive 只针对于1，2级路由有效

**Comment by xyfy** [comment]
....我的就是一二级路由呀

**Comment by raythunder** [comment]
src/config/router.config.js

``` js
import { UserLayout, BasicLayout, BlankLayout, RouteView } from '@/layouts'   // 手动引入RouteView 
import { bxAnaalyse } from '@/core/icons'

//注释下面这部分
// const RouteView = {
//   name: 'RouteView',
//   render: (h) => h('router-view')
// }
```
src/layouts/RouteView.vue

我直接改成了根据路由的meta属性判断是否开启
``` js
// 若确实不需要，可改为 return meta.keepAlive ? inKeep : notKeep
return meta.keepAlive ? inKeep : notKeep
```
