### ISSUE TITLE
3.0语言切换setting不生效

### ISSUE THREAD

**Issue by zxuanhong** [vueComponent/ant-design-vue-pro#913]
**Describe the bug （描述 Bug）**
 3.0语言切换setting不生效，包括你们部署演示环境也是无效的

**To Reproduce （重现步骤）**

1. 点击右上角却换到中文
2. setting语言一直是英文

**Expected behavior（你期待的是什么?）**
全局语言切换setting应该也能切换

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/62740686/89772188-2e500580-db34-11ea-85e2-b1b9407bd4b6.png)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] mac
 - Browser [e.g. chrome, safari] 8.1
 - Version [e.g. 22] 3.0

**Comment by sendya** [comment]
只提供英语的内容，其余内容均无默认提供。如有需要请自己加翻译
