### ISSUE TITLE
把顶部导航和面包屑并排会不会香些，，面包屑旁边太空了

### ISSUE THREAD

**Issue by zxuanhong** [vueComponent/ant-design-vue-pro#915]
**Is your feature request related to a problem? Please describe.**
把顶部导航与面包屑并排会不会好些，，面包屑旁边太空了

**Describe the solution you'd like**
这样会不会好些
![image](https://user-images.githubusercontent.com/62740686/89847505-c5f63800-dbb6-11ea-9497-318816579649.png)
移动样式
![image](https://user-images.githubusercontent.com/62740686/89847685-284f3880-dbb7-11ea-8451-b53ebb159f5a.png)

**Comment by sendya** [comment]
我们按照 ant design pro 的设计稿做的，如果你觉得你不喜欢这种布局，可以通过提供的各项自定义 render 改成你自己想要的样子

**Comment by karainsun** [comment]
@sendya 请问调整面包屑位置从哪里入手呢，你提到通过自定义的render修改，有具体点儿的例子么

**Comment by sendya** [comment]
> @sendya 请问调整面包屑位置从哪里入手呢，你提到通过自定义的render修改，有具体点儿的例子么

各种 xxxRender 可以看 https://github.com/vueComponent/pro-components/tree/next/packages/pro-layout#api 要核对版本
