### ISSUE TITLE
你好 我的后台就给了个数组，我怎么配置权限 看文档没有看懂

### ISSUE THREAD

**Issue by wjing0904** [vueComponent/ant-design-vue-pro#916]
权限结构后端返回是个数组 ：
permissionList: ["test:perms:1", "test:perms:2"]

怎么配置？求大佬指导

**Comment by sendya** [comment]
我也看不懂， 你能说明你的数组结构吗

**Comment by wjing0904** [comment]
嗯 简单点就是后台返回的数组集合格式，每一项代表一个菜单的权限，有可能是一级，二级，也有是某个按钮的, PermissionList：[”test1“, "test2”...]

**Comment by sendya** [comment]
嗯 简单点就是照着葫芦画瓢，你可以把你这个结构转化成 demo 的结构。也可以修改 demo 的结构为适用你的结构，这个每个人每个公司的权限设计都不一样，所以没办法做公用，需要自己有一定的动手能力。
另外，权限不外乎 这么几个步骤，自己稍微动脑思考应该都能理解
![image](https://user-images.githubusercontent.com/5404542/89966705-5e0d2380-dc82-11ea-8e22-da89ed1fed60.png)

**Comment by wjing0904** [comment]
> 嗯 简单点就是照着葫芦画瓢，你可以把你这个结构转化成 demo 的结构。也可以修改 demo 的结构为适用你的结构，这个每个人每个公司的权限设计都不一样，所以没办法做公用，需要自己有一定的动手能力。
> 另外，权限不外乎 这么几个步骤，自己稍微动脑思考应该都能理解
> ![image](https://user-images.githubusercontent.com/5404542/89966705-5e0d2380-dc82-11ea-8e22-da89ed1fed60.png)

一脸蒙啊

**Comment by wjing0904** [comment]
怎么取到当前router.config里所有的路由？ 然后我自己过滤

**Comment by sendya** [comment]
import

**Comment by wjing0904** [comment]
.....好吧 谢谢你
