### ISSUE TITLE
在同一个页面使用两个a-table 如何在不影响另外一个table的情况下把其中一个table的选中状态取消,我尝试把selectedRowKeys设置为空,结果就把两个table的选中状态都取消了

### ISSUE THREAD

**Issue by zhangjiajia123** [vueComponent/ant-design-vue-pro#919]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
数据是你自己绑定的，你两个不同变量就不会互相影响。

**Comment by zhangjiajia123** [comment]
通过:row-selection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }绑定不同的变量就可以,谢谢
