### ISSUE TITLE
pro-layout组件左侧菜单上方的logo区域怎么自定义？ 看了文档用v-slot:menuHeaderRender会报错render: "TypeError: menuHeaderRender is not a function"

### ISSUE THREAD

**Issue by zyd750** [vueComponent/ant-design-vue-pro#920]
**Question （问题描述）**
How to use component `s-table` paging
我大概看了下源码menuHeaderRender处理插槽节点，节点返回的是个vnode数组，然后用menuHeaderRender函数去接收的，就报错了。
**Describe the solution you'd like （你期待的是什么？）**
这个插槽能不能用啊？
**Additional context（附加信息）**
可以把pro-layout写到component里面去吗？  方便自己定义，放到依赖里面真的不好自定义

**Comment by zyd750** [comment]
还有个问题呀，pro-layout组件里的header和footer区域怎么删掉。不需要那两块区域

**Comment by sendya** [comment]
1. 请确认自己的版本号，0.3.8 版本以上才有
2. 项目是开源的，你可以自己把 pro-layout 拉下来 npm link

**Comment by zyd750** [comment]
> 1. 请确认自己的版本号，0.3.8版本以上才有
> 2. 项目是开源的，你可以自己把pro-layout拉下来npm link
我是0.3.12版本的
![QQ图片20200817101608](https://user-images.githubusercontent.com/38484756/90351381-ae192b00-e072-11ea-9345-d3f6ee000131.png)
