### ISSUE TITLE
table中使用video，改变video src，video未实时更新

### ISSUE THREAD

**Issue by yafanisonya** [vueComponent/ant-design-vue-pro#921]
**Describe the bug （描述 Bug）**

table中使用video，改变video src，video未实时更新

**To Reproduce （重现步骤）**

1.在table组件中使用video预览视频
2.通过编辑按钮调用接口上传新视频
3. textarea显示视频路径
4. 视频上传成功，路径改变
5. table中视频未实时更新，刷新后为新上传视频

**Expected behavior（你期待的是什么?）**
上传视频后，table中可直接预览新视频

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/47240823/90330975-ba09dc00-dfe3-11ea-9ab7-afe5928c4246.png)

更改前src：
![更改前src](https://user-images.githubusercontent.com/47240823/90331108-c2164b80-dfe4-11ea-8fe8-ce0a0c583182.png)

更改后src：
![更改后src](https://user-images.githubusercontent.com/47240823/90331067-8085a080-dfe4-11ea-9d56-fcc2a3068199.png)

提交后video未变：
![提交后video未变](https://user-images.githubusercontent.com/47240823/90331157-0b669b00-dfe5-11ea-8190-e5ea4a217eaf.png)

刷新后video改变：
![刷新后video改变](https://user-images.githubusercontent.com/47240823/90331176-220cf200-dfe5-11ea-968e-e322dc716759.png)

**Desktop (please complete the following information):**

 - OS: [Windows10]
 - Browser [chrome 版本 84.0.4147.125]
  "dependencies": {
    "@ant-design-vue/pro-layout": "^0.3.4",
    "@antv/data-set": "^0.10.2",
    "ant-design-vue": "^1.6.2",

**Comment by sendya** [comment]
请确保你的接口数据是正确的
