### ISSUE TITLE
isMobile不能加括号

### ISSUE THREAD

**Issue by wevsmy** [vueComponent/ant-design-vue-pro#923]
https://github.com/vueComponent/ant-design-vue-pro/blob/91670fc511bf5aafbefb8e2aaad294b1ea81d0e1/src/views/role/RoleList.vue#L16

https://github.com/vueComponent/ant-design-vue-pro/blob/91670fc511bf5aafbefb8e2aaad294b1ea81d0e1/src/views/role/RoleList.vue#L20

**Comment by sendya** [comment]
已不再 pro 中体现该页面，所以没有处理老代码
