### ISSUE TITLE
关于动态路由的疑问！！

### ISSUE THREAD

**Issue by duliang123** [vueComponent/ant-design-vue-pro#925]
文档：https://pro.antdv.com/docs/authority-management

**Question （问题描述）**
根据文档中动态路由的介绍，尝试模拟了数据，文档中的eg  // 后端返回的 JSON 动态路由结构，完全跟源码中的结构不一样：

比如：vim src/permission.js 中
            const roles = res.result && res.result.role
            // generate dynamic router
            store.dispatch('GenerateRoutes', { roles }).then(() => {
              // 根据roles权限生成可访问的路由表
              // 动态添加可访问路由表
              router.addRoutes(store.getters.addRouters)

代码中res.result && res.result.role是父子层级，但文档JSON示例中并没有role的字段，感觉文档对【动态路由】的介绍跟源码中有出入

**Describe the solution you'd like （你期待的是什么？）**

希望作者能根据源码结构给出【动态路由】的示例，毕竟这块是刚需。 

**Additional context（附加信息）**
问了好多朋友，用的不是新的代码，都是自己改造的。本人才疏学浅望作者明示

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/mock/services/user.js#L24

**Comment by duliang123** [comment]
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/mock/services/user.js#L24

后端模拟user.js中json结构数据，可以登陆后台了，也可展指定的菜单。不过菜单权限控制这块如何精细？比如下方是对dashboard所有子菜单起用，如果我想对【分析页 /dashboard/analysis】这个菜单进行权限控制，如何设置？

'permissions': [{
      'roleId': 'admin',
      'permissionId': 'dashboard',
      'permissionName': '仪表盘',
      'actions': '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck":false,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': false
      }

**Comment by duliang123** [comment]
> https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/mock/services/user.js#L24

这个是默认的菜单的和权限方案数据（菜单是配置文件写死的，通过获取当前用户的权限去比对路由表，生成当前用户具有的权限可访问的路由表），不是动态菜单路由（动态生效菜单 并关联权限）。
