### ISSUE TITLE
ant-design-pro slot attritubes in slot element

### ISSUE THREAD

**Issue by brucemeteor** [vueComponent/ant-design-vue-pro#93]
thanks for this project,it helpful!!!
im  confused casue this  slot attritube in slot. i thought it's useless,but maybe it just i can't understand?
please note it.
首先非常高兴能够用到这个项目。对我的代码开发非常有用。
但是我在看到下面的代码的时候，非常困惑，我认为这是一个无用的属性slot。但是也许这是什么特殊的设置呢？
https://github.com/sendya/ant-design-pro-vue/blob/fbfd39b11ee7a2ad6ca238d966c6b4385d49e1e2/src/components/page/PageLayout.vue#L5

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/views/profile/advanced/Advanced.vue#L23

![20190225174649](https://user-images.githubusercontent.com/5404542/53328635-5db18900-3925-11e9-8ed1-12828b8339b6.png)

可以不用关注 `slot` 是否有用无用， `slot` 的存在是为了方便扩展

**Comment by brucemeteor** [comment]
slot 的存在既是为了扩展，或者说更加方便的预留接口。

至于预留的接口会不会被其他组件再次使用，就是实现的问题了。

不要去在意 slot 是否有无用，不然就失去了 slot 它本身的功能了
感谢~@sendya
