### ISSUE TITLE
栅格系统的100px 和auto的分割 不work 望fix

### ISSUE THREAD

**Issue by Kimi1020** [vueComponent/ant-design-vue-pro#931]
**Describe the bug （描述 Bug）**

代码用了如下：

`      <a-row type="flex">
        <a-col flex="100px">100px</a-col>
        <a-col flex="auto">auto</a-col>
      </a-row>`

但是好像不是100px 和auto的分割方式， 检查左边的盒子的width 没有100px

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
type 只有 type="flex" 没有 auto，如果不会使用请查看文档 https://antdv.com/components/grid-cn/#components-grid-demo-flex-alignment

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/91379532-8174c880-e855-11ea-9af6-93de360b78d3.png)
1.6.4 才增加的功能，请自行更新
