### ISSUE TITLE
GlobalFooter怎么去掉呢

### ISSUE THREAD

**Issue by caopengan** [vueComponent/ant-design-vue-pro#932]
**GlobalFooter如何去掉**
在`BasicLayout` 中把GlobalFooter的导入去掉，代码都注释掉了，还是会显示？有什么办法可以优雅的去掉吗？我不想把代码都注释掉

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by Fallsleep** [comment]
保留`BasicLayout`里的`GlobalFooter`，把`components/GlobalFooter/index.vue`里的`v-slot:links`和`v-slot:copyright`留空就可以了。

**Comment by caopengan** [comment]
> 保留`BasicLayout`里的`GlobalFooter`，把`components/GlobalFooter/index.vue`里的`v-slot:links`和`v-slot:copyright`留空就可以了。

这种方式我知道，我的意思是有没有什么更加优雅的方式可以达到这种效果

**Comment by Fallsleep** [comment]
仿照`:i18nRender=" (t) => t"`，使用`:footerRender=" (t) => t"`，好像能达到目的？不知道是不是正确的用法

**Comment by sendya** [comment]
这个我本来是打算处理的，增加一个 boolean 值类型用来关闭 footer，但是当时 pro 官方没提供这个 api 属性，所以没有继续跟进，后续更新，我会考虑处理这个问题

**Comment by caopengan** [comment]
> 这个我本来是打算处理的，增加一个 boolean 值类型用来关闭 footer，但是当时 pro 官方没提供这个 api 属性，所以没有继续跟进，后续更新，我会考虑处理这个问题

好的，那我就自己写一个吧，谢谢

**Comment by caopengan** [comment]
> 仿照`:i18nRender=" (t) => t"`，使用`:footerRender=" (t) => t"`，好像能达到目的？不知道是不是正确的用法

恩恩，那我试试

**Comment by caopengan** [comment]
> 这个我本来是打算处理的，增加一个 boolean 值类型用来关闭 footer，但是当时 pro 官方没提供这个 api 属性，所以没有继续跟进，后续更新，我会考虑处理这个问题

现在去掉GobalFoot的方案是什么，感觉试了几个都去不掉啊，求解答

**Comment by idefa** [comment]
找到layouts->BasicLayout.less添加下面代码
.ant-layout-footer{
    display: none;
}

**Comment by hushun1994** [comment]
> > 保留`BasicLayout`里的`GlobalFooter`，把`components/GlobalFooter/index.vue`里的`v-slot:links`和`v-slot:copyright`留空就可以了。
> 
> 这种方式我知道，我的意思是有没有什么更加优雅的方式可以达到这种效果

内容去掉很容易， slot不传值就行了，  这个footer 的 padding 还是一直在， 就很烦！

**Comment by sendya** [comment]
> 内容去掉很容易， slot不传值就行了， 这个footer 的 padding 还是一直在， 就很烦！

https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/BasicLayout.vue#L48

看更新，谢谢，不要烦！

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/commit/7609048d2ce96fad364c14487ea26ae6f503f68d
