### ISSUE TITLE
s-table 数据刷新时select数据缓存问题

### ISSUE THREAD

**Issue by meguoe** [vueComponent/ant-design-vue-pro#933]
**Question （问题描述）**
s-table 数据刷新时select数据缓存问题

**Describe the solution you'd like （你期待的是什么？）**
在请求数据刷新时清空select信息

**Additional context（附加信息）**
使用场景：比如选中一条数据删除后并重新请求数据列表，select的数据并没有清空，再选择一条数据删除时，其实select中存在两条记录信息。

**Comment by sendya** [comment]
select 数据是什么？

**Comment by meguoe** [comment]
表格第一列的checkbox  ^ ^

**Comment by sendya** [comment]
s-table 的 change 和 selectChange  事件会提供每次操作变化后的 select ，请自行清理或控制
