### ISSUE TITLE
子页面嵌套组件引入问题

### ISSUE THREAD

**Issue by caopengan** [vueComponent/ant-design-vue-pro#935]
**Question （问题描述）**
举个例子：A页面引用B页面，B页面上调用一些组件，比如：a-tree,或者a-transfer组件的时候，浏览器报错，无法找到组件，但是直接在A页面就可以找到，如果想在B页面使用的话我需要先引入ant-design-vue/es/……,下的index.js，再引入ant-design-vue原始组件，才可以使用该组件，具体的原理不太清楚

**Comment by sendya** [comment]
请提供复现，如无法提供，请整理语言表述得更清楚一点，一步一步说清楚

**Comment by Kimmyzhao** [comment]
<img width="1133" alt="图片" src="https://user-images.githubusercontent.com/11455494/92408993-bd6f2e00-f171-11ea-83d6-7ae63f104e20.png">
这样使用时，一直报a-carousel组件未注册，要怎么解决

**Comment by sendya** [comment]
那就注册 carousel 组件

**Comment by Kimmyzhao** [comment]
> 那就注册 carousel 组件

已解决，之前以为是全局引入的，看了下代码需要在core 目录下的 lazy_use.js中引入
