### ISSUE TITLE
请问如何将这些远程的js替换成本地js

### ISSUE THREAD

**Issue by teajoy** [vueComponent/ant-design-vue-pro#936]
描述 问题
内网环境下加载不了cdn下的js文件，因此想要将这些远程文件下载到本地引用，请问有修改建议嘛

重现步骤
步骤如下:
![image](https://user-images.githubusercontent.com/32169617/91708277-afd70880-ebb3-11ea-84f2-a1cdeec562fd.png)
期望结果r
能够在不联网的情况下加载本地js文件成功

实际结果
不连外网的情况下，一些cdn下的js文件没法加载。

系统环境:

操作系统: win10
浏览器 google chrome

**Comment by sendya** [comment]
你可以关闭 CDN 功能，参见上面 vue.config.js 的环境条件判断
