### ISSUE TITLE
ant-design-vue-pro官网组件demo打不开

### ISSUE THREAD

**Issue by qianjujie** [vueComponent/ant-design-vue-pro#937]
**Question （问题描述）**
ant-design-vue-pro官网组件demo打不开，显示
您的连接不是私密连接
攻击者可能会试图从 preview.pro.loacg.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
[https://preview.pro.loacg.com/test/home](url)

**Comment by sendya** [comment]
preview.pro.antdv.com

**Comment by qianjujie** [comment]
你的文档上链接的地址打不开啊，麻烦改改
