### ISSUE TITLE
打包后登陆页打不开

### ISSUE THREAD

**Issue by Axiang520** [vueComponent/ant-design-vue-pro#943]
**Describe the bug （描述 Bug）**
npm run build后本地登陆页无法打开

**To Reproduce （重现步骤）**

1. 执行npm run build
2. 进入dist文件夹
3. 打开index.html
4. 看到空白页面
5.控制台报错
6.修改webpack配置后依然报错

**Expected behavior（你期待的是什么?）**
打包后登陆页可以打开

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://pro.antdv.com/docs/faq#%E7%BC%96%E8%AF%91%E5%A5%BD%E7%9A%84%20dist%20%E6%80%8E%E4%B9%88%E8%BF%90%E8%A1%8C%EF%BC%9F

**Comment by zhangjiajia123** [comment]
本地不部署nginx就无法打开登录页面吗，请问你是如何解决的
