### ISSUE TITLE
请问页面刷新的时候，背景的PRO和ant design那个能去掉吗。

### ISSUE THREAD

**Issue by lb7767** [vueComponent/ant-design-vue-pro#944]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by skyhotqin** [comment]
@lb7767 lb 大佬，知道怎么换吗？

**Comment by 8090Lambert** [comment]
hi，这个问题你解决了吗
