### ISSUE TITLE
希望能指点怎么修改设置抽屉里的页面主题

### ISSUE THREAD

**Issue by NierWinter** [vueComponent/ant-design-vue-pro#946]
**Question （问题描述）**
How to use component `s-table` paging
有暗黑主题的需求，但不知道切换主题的代码在哪，是怎么切换的
**Describe the solution you'd like （你期待的是什么？）**
希望能指点一下是怎么在线切换主题的
**Additional context（附加信息）**

**Comment by sendya** [comment]
不支持黑暗主题，另外设置栏有回调，看 basic-layout 里怎么用的
