### ISSUE TITLE
Windows下yarn install报错

### ISSUE THREAD

**Issue by deepinsea** [vueComponent/ant-design-vue-pro#947]
**Describe the bug （描述 Bug）**
【错误区】
**********************************
[4/4] Building fresh packages...
[1/6] ⠄ core-js
[2/6] ⠄ core-js
[3/6] ⠄ yorkie
[4/6] ⠄ ejs
error E:\ideaProjects\ant-design-vue-pro\node_modules\babel-polyfill\node_modules\core-js, E:\ideaProjects\ant-design-vue-pro\node_modules\babel-runtime\node_modules\core-js: Command fa
iled.
Exit code: 1
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments:
*********************************

**To Reproduce （重现步骤）**
![image](https://user-images.githubusercontent.com/57308175/92311720-40ff1280-efec-11ea-931e-41a371d75906.png)

**Comment by deepinsea** [comment]
然后用npm install报错的包还是没用，关键下的还是官方包，是yarn的问题嘛？ 😥

**Comment by sendya** [comment]
安装依赖的问题请自己解决

**Comment by deepinsea** [comment]
把node_modules删了，清了cache，重新cnpm就OK了；只是最新版的yarn， install老是报依赖错误

**Comment by deepinsea** [comment]
搞定了呢🤪




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "言肆"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 上午10:37
收件人: "vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 
抄送: "风有云曦"<1360034559@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue-pro] Windows下yarn install报错 (#947)





 
安装依赖的问题请自己解决
