### ISSUE TITLE
请问，这个v3版本的菜单图标，要怎么把图标替换成iconfont图标

### ISSUE THREAD

**Issue by JaneyJso** [vueComponent/ant-design-vue-pro#949]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by JaneyJso** [comment]
有线上js，直接在icon改iconfont，识别不了。图标js要如何正确引入？defaultSettings里面引入js，icon不能识别；若使用图标选择器，菜单图标（ant）与图标选择器（element或iconfont）对应不上，。该如何解决

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/92427423-08636280-f1bf-11ea-9486-c597bf905c7d.png)

额外的均不支持，如有需要自行使用 menuRender 自定义渲染或改造源码
