### ISSUE TITLE
 如何直接更改页面的默认文字为中文呢，例如datepicker之类的，只能一个一个的改吗。我在local-index.js文件里面改了，并不生效。

### ISSUE THREAD

**Issue by lb7767** [vueComponent/ant-design-vue-pro#951]
请问一下  如何直接更改页面的默认文字为中文呢，例如datepicker之类的，只能一个一个的改吗。我在local-index.js文件里面改了，并不生效。

**Comment by sendya** [comment]
https://antdv.com/components/config-provider-cn/
