### ISSUE TITLE
how to use  the setting 'defaultExpandAllRows' in  s-table  

### ISSUE THREAD

**Issue by qayang** [vueComponent/ant-design-vue-pro#952]
请问如何在s-table中该如何实现a-table中默认展开所有查询选项的展开行。

**Comment by qayang** [comment]
I resolve it by using:
// 加载数据方法 必须为 Promise 对象
      loadData: parameter => {
        return getServiceToMenu(Object.assign({}, parameter, this.queryParam))
          .then(res => {
            // 展开首行
            this.expandedRowKeys.push(res.data.data[0].serviceId)
            return res.data
          })
      },
      expandedRowKeys: [],

**Comment by sendya** [comment]
pls use `a-table`
