### ISSUE TITLE
s-table可以导出成excel吗

### ISSUE THREAD

**Issue by five131415** [vueComponent/ant-design-vue-pro#953]
您好，抱歉打扰了，想问一下s-table现在本身具备对选中项导出成excel的功能吗？如果没有，是否有与其配套使用方便的三方推荐呢？本人初识web前端的东西，不甚了解。抱歉打扰。

**Comment by sendya** [comment]
table 只负责 table 要做的事情，其余请自行查找 excel 相关支持库，获取 table 的 dataSource 给 excel 来到处等方式来解决。

**Comment by five131415** [comment]
好的，谢谢
