### ISSUE TITLE
egg后台怎么拿到前台拿到的参数

### ISSUE THREAD

**Issue by baiwumm** [vueComponent/ant-design-vue-pro#955]
后端用的egg.js，请问怎么才能拿到前台传过来的参数
async getUserInfo(parameter) {
        const { app, ctx } = this;
        const Raw = app.mysql.get('home');
        console.log(parameter)
        console.log(ctx.query)
        console.log(ctx.request.body)
        try {
            let userList = await Raw.query(`select * from xmw_user`);
            this.ctx.body = {
                data: userList
            }
            return { state: 1, data: userList, msg: "请求成功!" }
        } catch (error) {
            app.CoreAPI.Log.info("getUserInfo:" + error);
            return { state: 0, msg: "请求失败!" };
        }

    }

这样都拿不到，为什么

作者大大，回复一下，很重要

**Comment by sendya** [comment]
没用过 不知道，建议去 egg 社区问
