### ISSUE TITLE
帮助说明文档能更新到和master保持一致吗？

### ISSUE THREAD

**Issue by wongqingbin** [vueComponent/ant-design-vue-pro#961]
**Question （问题描述）**
帮助文档-去除权限控制
https://pro.antdv.com/docs/remove-authority-management

**Describe the solution you'd like （你期待的是什么？）**
帮助文档的内容和master克隆下来的内容无法对应上，期望修改帮助文档和master分支保持一致

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/router/index.js#L3
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/BasicLayout.vue#L43
https://github.com/vueComponent/ant-design-vue-pro/blob/master/src/layouts/BasicLayout.vue#L92
