### ISSUE TITLE
pro-layout组件里，layout='topmenu'的时候，menuHeaderRender会失效

### ISSUE THREAD

**Issue by xinyu-s** [vueComponent/ant-design-vue-pro#962]
layout='sidemenu'时，
![image](https://user-images.githubusercontent.com/39296536/93320287-7bb24780-f843-11ea-9d84-ea259a60096f.png)
![image](https://user-images.githubusercontent.com/39296536/93320447-aef4d680-f843-11ea-99a0-f5abdd0d2f7e.png)

layout='topmenu'时，
![image](https://user-images.githubusercontent.com/39296536/93320518-c59b2d80-f843-11ea-990f-43f8b9f740c3.png)
![image](https://user-images.githubusercontent.com/39296536/93320566-d055c280-f843-11ea-8d3e-1a5f1e2569af.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/93429072-233a8300-f8f3-11ea-9f2e-3da36591557a.png)
![image](https://user-images.githubusercontent.com/5404542/93429084-29c8fa80-f8f3-11ea-87ef-d80ff89e7a3b.png)

无法复现，如果你的依赖没有升到最新，那么请升级到最新后再试

**Comment by sendya** [comment]
看你的代码，是不是 而外又设置了 logoRender

**Comment by xinyu-s** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/93429072-233a8300-f8f3-11ea-9f2e-3da36591557a.png)
> ![image](https://user-images.githubusercontent.com/5404542/93429084-29c8fa80-f8f3-11ea-87ef-d80ff89e7a3b.png)
> 
> 无法复现，如果你的依赖没有升到最新，那么请升级到最新后再试

升级到最新解决了，谢谢了
