### ISSUE TITLE
请问如何开启多标签（multiTab）？

### ISSUE THREAD

**Issue by zhangbo0921** [vueComponent/ant-design-vue-pro#967]
请问如何开启多标签（multiTab）？描述下详细步骤，或者在ant-design-vue-pro 文档中写出来，谢谢！！

**Comment by liyang1987jay** [comment]
好像这个版本去掉了

**Comment by gavinju** [comment]
为什么要去掉多标签功能？ 后续还会添加吗？ 这个功能还是很重要的。
