### ISSUE TITLE
请问下菜单怎么保持点击的菜单全部展开，看官方组件是支持的

### ISSUE THREAD

**Issue by zxuanhong** [vueComponent/ant-design-vue-pro#969]
**Question （问题描述）**
请求下怎么设置已经展开的菜单保持展开状态，官方组件是支持的如下图：
![image](https://user-images.githubusercontent.com/62740686/94100250-b168b900-fe5f-11ea-84df-e7cb43045403.png)

**Comment by sendya** [comment]
antd pro 不支持，如有需要 自行定义 Menu 的 render，或者自己写 layouts
