### ISSUE TITLE
左侧菜单栏切换刷新页面问题

### ISSUE THREAD

**Issue by wongqingbin** [vueComponent/ant-design-vue-pro#970]
**Question （问题描述）**
左侧菜单栏切换刷新页面问题

**Describe the solution you'd like （你期待的是什么？）**
前提：有多个菜单页面，其中a页面为A菜单名称，a页面有表单、输入框和选择框，b页面为B菜单名称。在a页面的表单输入内容，然后侧边栏点击B跳转到b页面中，再点击侧边栏A菜单名称回到a页面。

想要的结果：切换后a页面的内容不消失，保留表单、输入框和选择框的内容

目前实际结果：切换回a页面后a页面内容全部清空初始化了。。。。。

**Additional context（附加信息）**

**Comment by sendya** [comment]
keep-alive

**Comment by wongqingbin** [comment]
antd pro中，我在src/config/router.config.js文件中，把路由的配置项 meta: { keepAlive: true } 中的keepAlive设置为true后，点击左侧菜单切换的时候，还是会把form表单的内容清空。。。
