### ISSUE TITLE
s-tree组件使用titleclick触发多个handletitleclick问题

### ISSUE THREAD

**Issue by qayang** [vueComponent/ant-design-vue-pro#973]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44155912/94238636-3c6eaf80-ff43-11ea-921f-d3f8d7115b87.png">
我在s-tree的renderSubItem方法中增加了submenu控件调用titleclick的部分，但实际使用时发现点击一个title，会触发所有带children的title项，导致同时触发多个handletitleclick方法。请问这个怎么解决，或者是我使用错误了吗。

**Comment by sendya** [comment]
JSX 里面不能写 func() 会直接运行，要么 ()=> { func() } 解决

**Comment by qayang** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/44155912/94362590-0d953c80-00ef-11eb-85be-115801453239.png">
谢谢，经过你的提示已经实现了。
