### ISSUE TITLE
vuex保存的用户信息，一段时间不操作会清空

### ISSUE THREAD

**Issue by baiwumm** [vueComponent/ant-design-vue-pro#976]
![image](https://user-images.githubusercontent.com/40554571/94360866-12ec8a00-00e3-11eb-861c-9347dc0b9438.png)

**Comment by baiwumm** [comment]
请问一下，GetInfo方法保存用户信息到vux，是有时间缓存的吗，过一段时间就会自动清空

**Comment by baiwumm** [comment]
userInfo() {
            return this.$store.getters.userInfo
        },
这个信息是会有什么操作会清空vuex上的userinfo吗

**Comment by sendya** [comment]
请查阅 Vuex 文档 https://vuex.vuejs.org/  本项目开源，你可以在 src/store 中找到对 vuex 的全部操作
