### ISSUE TITLE
您好，ant vue 已经用在企业生产环境了，请问一下支持vue3的预计什么时候出呢

### ISSUE THREAD

**Issue by k713927** [vueComponent/ant-design-vue-pro#979]
感谢ant-design-vue-pro，很好用，想问一下Vue3有计划吗，什么时候出呢，

**Comment by sendya** [comment]
待定，预计是半年内吧。
现在 vue3 虽然 release 了，但是周边生态的库都还没几个兼容的，比如 裁剪图片都没 vue3 兼容，这种情况如何去升级呢？
