### ISSUE TITLE
后端接口报错

### ISSUE THREAD

**Issue by baiwumm** [vueComponent/ant-design-vue-pro#985]
![image](https://user-images.githubusercontent.com/40554571/95650257-12a5b300-0b15-11eb-8f55-d6569236646b.png)
请问一下，为什么会出现这种情况，main.js去掉mock.js也一样，是我后端的问题还是环境的原因，但又能从后端返回数据

**Comment by baiwumm** [comment]
![image](https://user-images.githubusercontent.com/40554571/95650309-75974a00-0b15-11eb-9e39-346e37435181.png)

**Comment by FollowTrend** [comment]
{state: 0, msg: "用户名或密码错误!"}
mock.js?411c:8404 POST http://127.0.0.1:7001/home/login 404 (Not Found)
send @ mock.js?411c:8404
dispatchXhrRequest @ xhr.js?b50d:178
xhrAdapter @ xhr.js?b50d:12
dispatchRequest @ dispatchRequest.js?5270:52
Promise.then (async)
request @ Axios.js?0a06:61
wrap @ bind.js?1d2b:9
login @ login.js?7ded:21
eval @ user.js?0f9a:38
Login @ user.js?0f9a:37
wrappedActionHandler @ vuex.esm.js?2f62:778
dispatch @ vuex.esm.js?2f62:457
boundDispatch @ vuex.esm.js?2f62:347
mappedAction @ vuex.esm.js?2f62:991
eval @ Login.vue?7463:84
callback @ createBaseForm.js?bcc9:583
eval @ createBaseForm.js?bcc9:564
complete @ index.js?2a95:1116
eval @ index.js?2a95:1302
next @ index.js?2a95:207
count @ index.js?2a95:129
cb @ index.js?2a95:1216
required$1 @ index.js?2a95:896
eval @ index.js?2a95:1281
eval @ index.js?2a95:134
asyncParallelArray @ index.js?2a95:133
eval @ index.js?2a95:226
eval @ index.js?2a95:220
asyncMap @ index.js?2a95:201
validate @ index.js?2a95:1177
validateFieldsInternal @ createBaseForm.js?bcc9:485
eval @ createBaseForm.js?bcc9:610
validateFields @ createBaseForm.js?bcc9:571
handleSubmit @ Login.vue?7463:80
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
onSubmit @ Form.js?d65b:217
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
Show 11 more frames
Login.vue?7463:103 Error: Request failed with status code 404
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:17)
    at MockXMLHttpRequest.handleLoad [as onreadystatechange] (xhr.js?b50d:61)
    at MockXMLHttpRequest.dispatchEvent (mock.js?411c:8517)
    at XMLHttpRequest.handle (mock.js?411c:8335)
