### ISSUE TITLE
关于webpack externals配置后不能剔除依赖问题

### ISSUE THREAD

**Issue by Neal-Wei** [vueComponent/ant-design-vue-pro#987]
你好，我配置了webpack externals,使用cdn, 查看打包后的index.html里面是成功使用lodash和moment的cdn引用，但是chunk-vendor.js里并没有剔除这两个依赖，希望大佬帮忙看看，图片地址：http://chuantu.xyz/t6/741/1602469358x1700340427.png

**Comment by sendya** [comment]
我不太清楚你这种写法是否为官方提供的。如果不是，请参照我写的那几个已存在的 externals 去写

**Comment by Neal-Wei** [comment]
> 我不太清楚你这种写法是否为官方提供的。如果不是，请参照我写的那几个已存在的 externals 去写

我换成官方提供的方法也不行，你可以试试把momen.js打包后换成cdn看看chunk-vendor.js里还有没有moment.js

**Comment by fengwenshan** [comment]
请问解决了吗，我也遇到了这个问题
