### ISSUE TITLE
src/permission.js中每次读取缓存都是空

### ISSUE THREAD

**Issue by BrettKang** [vueComponent/ant-design-vue-pro#988]
**Describe the bug （描述 Bug）**
src/permission.js中每次读取缓存都是空
console.log的结果：
****************store.getters.roles:[]  permission.js?223d:28 
这意味着每次刷新页面都请示了一次GetInfo()方法

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
刷新不获取才是 bug
