### ISSUE TITLE
ant-design-vue-pro 使用 electron 打包后运行时报错

### ISSUE THREAD

**Issue by nuochong** [vueComponent/ant-design-vue-pro#989]
**Question （问题描述）**

ant-design-vue-pro打包正常，没有问题。 打包后安装并运行报如下错误。

```
Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'
```

**具体错误信息有关片段**
```
...
//! moment.js
...
```
```
...
t.prototype.constructor=t,t.
...
```

![image](https://user-images.githubusercontent.com/28994748/95807589-292e5300-0d3d-11eb-932e-3ba33ccc1051.png)

**Describe the solution you'd like （你期待的是什么？）**

执行 `vue-cli-service electron:build` 打包安装后可以正常运行。

**Additional context（附加信息）**

执行 `vue-cli-service electron:build` 在使用 dev 环境的时候可以正常使用

**Comment by sendya** [comment]
去掉首屏 loading 动画

**Comment by nuochong** [comment]
> 去掉首屏 loading 动画

问题描述有修改，打包没有问题，只是打包后安装并运行会有问题，有关错误的详细代码片段有补充到问题。首屏动画有去除但是还是会报同样的错误。

感觉好像是打包后存在es6语法，但是有对node_modules报设置了转换，但还是会报同样的错误。不知道是否自己配置转换出了问题。

**Comment by Neal-Wei** [comment]
> > 去掉首屏 loading 动画
> 
> 问题描述有修改，打包没有问题，只是打包后安装并运行会有问题，有关错误的详细代码片段有补充到问题。首屏动画有去除但是还是会报同样的错误。
> 
> 感觉好像是打包后存在es6语法，但是有对node_modules报设置了转换，但还是会报同样的错误。不知道是否自己配置转换出了问题。

这个问题不是moment.js引起的，是antv引起的，把antv删除就不会有问题了，用webpack-bundle-analyzer查看打包后antv是否被移除
