### ISSUE TITLE
permission控制中，每次刷新页面都store.getters.roles.length === 0

### ISSUE THREAD

**Issue by BrettKang** [vueComponent/ant-design-vue-pro#994]
**Describe the bug （描述 Bug）**

\src\permission.js
这个权限路由页面，每次判断roles集合都为空。这就意味着每次刷新页面都需要会重新加载UserInfo数据

if (store.getters.roles.length === 0) {
console.log('store.getters.roles:' + JSON.stringify(store.getters.roles))
//**************这里每次都会打印出空array[]
store
.dispatch('GetInfo')
.then(res => {

**To Reproduce （重现步骤）**

**Expected behavior（你期待的是什么?）**

**Screenshots（截图）**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context（附加信息）**

**Comment by sendya** [comment]
刷新是一定会重新获取的，不然如何保障权限安全性

**Comment by BrettKang** [comment]
> 刷新是一定会重新获取的，不然如何保障权限安全性

我看有个commit保存，那还是我自己storage一下吧

**Comment by sendya** [comment]
储存里保存权限？坐等别人修改伪造吗

**Comment by BrettKang** [comment]
> 储存里保存权限？坐等别人修改伪造吗

token都保存了，不是一样吗？有了token数据也是一样取出来。存储在本机，token可以取到，其他的都一样

**Comment by sendya** [comment]
token 无法修改，也是权限只读，从一开始就被限制了的。
另外 我不参与这个问题的讨论，你怎么做都好。
