### ISSUE TITLE
如何发布 Ant Design Pro for Vue 到子目录

### ISSUE THREAD

**Issue by BrettKang** [vueComponent/ant-design-vue-pro#995]
**Question （问题描述）**
我看到ant design pro有发布到非根目录的指引，但是ant design pro for vue怎么没有找到配置方案?

请问有发布到子目录的方法吗？

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://cli.vuejs.org/config/#publicpath
